### ISSUE TITLE
vaccipy hört einfach mit dem Suchen auf (keine Fehlermeldung)

### ISSUE THREAD

**Issue by devsbr** [iamnotturner/vaccipy#100]
<img width="648" alt="scripthörtauf" src="https://user-images.githubusercontent.com/40228042/119260881-22ba6080-bbd5-11eb-966e-fec10414a465.PNG">

Hi!
Manchmal hört bei mir das Script einfach auf, ohne eine Fehlermeldung o.ä. zu spucken
Seit 3 Minuten lief nichts mehr. Ein Neustart konnte das Problem lösen.

Woran könnte das liegen?

**Comment by haslersn** [comment]
Welchen Branch/Commit benutzt du?

**Comment by Sars-Cov-2-Antigen** [comment]
hatte das Problem auf. Woran es liegt, weiß ich nicht, aber es reicht einfach Enter zu drücken, um die Suche fortzusetzen.

**Comment by pancakeDevelopment** [comment]
> Welchen Branch/Commit benutzt du?

Ich habe die aktuellste Beta Branch.



> hatte das Problem auch. Woran es liegt, weiß ich nicht, aber es reicht einfach Enter zu drücken, um die Suche fortzusetzen (alpha branch)

Ja das habe ich auch festgestellt

**Comment by haslersn** [comment]
Tritt das nur auf Windows auf?

**Comment by pancakeDevelopment** [comment]
> Tritt das nur auf Windows auf?

Ich nutze zumindest Windows, ja

**Comment by sinun98** [comment]
Durch einen Klick in das Konsolenfenster stoppt das Programm. Durch Enter wird der Programmablauf fortgesetzt. Das ist Standardmäßig bei Python so.
