### ISSUE TITLE
Manuelle Cookieeingabe funktioniert nicht (Eingabe auf 1024 Zeichen begrenzt)

### ISSUE THREAD

**Issue by wielandbrendel** [iamnotturner/vaccipy#102]
Zuvorderst: vielen Dank für die Entwicklung, macht einen tollen Eindruck, deutlich professioneller als mein eigene Automatisierung mit Selenium :).

Bei der Code-Generierung mit der neuen Beta stoße ich aber auf ein Problem mit der manuellen Cookie-Eingabe: nach genau 1024 Zeichen kann ich nichts mehr eingeben. Mein Cookie Wert ist aber 1277 Zeichen lang, daher komme ich an der Stelle nicht weiter.

**Comment by sinun98** [comment]
Hi, vielen Dank. 
Wie gibst du den den Wert ein und hast du eventuell einen Screenshot wie sich das auswirkt und der Error zu sehen ist? Meine Werte sind teilweise >1500 und ich habe eigentlich keine Probleme diese per Paste einzufügen.  Hier waren es 1650 Zeichen:
![image](https://user-images.githubusercontent.com/48892674/119275481-b0b63b80-bc15-11eb-9bb0-b86d13294d22.png)

**Comment by wielandbrendel** [comment]
Hi @sinun98 , ich habe (nach einigen Versuchen) die ersten 1020 Zeichen in das (Mac) Terminal kopiert, und dann die nächsten Zeichen manuell eingetippt. Die ersten 4 Zeichen werden genommen, danach ertönt nur das ein akustisches Warnsignal und es werden keine weiteren Zeichen genommen.

**Comment by sinun98** [comment]
Das scheint ein Mac Limit zu sein. Die Limitieren die Terminaleingaben auf maximal 1024 Zeichen. Hast du schon versucht direkt in der IDLE auszuführen? Main.py öffnen und dann unter Run>Run Module ausführen?

**Comment by wielandbrendel** [comment]
Ich konnte das Problem jetzt durch import von readline lösen (https://stackoverflow.com/questions/7357007/python-raw-input-limit-with-mac-os-x-terminal).

Leider passiert jetzt etwas merkwürdiges: es wird jetzt ein Chrome Fenster geöffnet, dann auf "Vermittlungscode vorhanden" und mein Code (für ein anderes Impfzentrum) eingegeben. Im Terminal sieht das so aus:

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/6177693/119276431-8024d080-bc1a-11eb-849f-14e1b5136ff3.png">

**Comment by sinun98** [comment]
Der eingegebene Code ist: Platzhalter1. Der Dummy Wert dient dazu die Cookies zu generieren und spielt keine Rolle. Kannst du es mal mit einer anderen Email und Nummer versuchen? Der Timeout ist nicht normal.

**Comment by wielandbrendel** [comment]
@sinun98 Ah, mit einer anderen Email + Telefonnummer funktioniert es - super! Ist das eine Art "shadow-banning" in die ich da reingelaufen bin? Oder liegt das daran, dass ich schon einen Code für ein anderes Impfzentrum unter der Telefonnummer + Email habe?

**Comment by sinun98** [comment]
Ist ein temporärer Bann. Grundsätzlich kann man ca. 3 Anfragen pro Gruppe (https://github.com/iamnotturner/vaccipy/blob/master/impfzentren_gruppiert.md) machen innerhalb einiger Minuten, unabhängig ob erfolgreich oder nicht. Danach dauert es einige Stunden bis man erneut in der Gruppe einen Code generieren kann.

**Comment by wielandbrendel** [comment]
Danke für die Info! Und danke nochmals für euren tollen Einsatz!

**Comment by wielandbrendel** [comment]
@sinun98 Spricht etwas dagegen, einfach ein "import readline" statement am Anfang der main.py einzubauen anstatt Mac Nutzer auf IDLE zu verweisen? Ersteres wäre m.E. die elegantere Lösung.

**Comment by sinun98** [comment]
@wielandbrendel Da hast du recht. Danke für den Hinweis, fügen wir hinzu.
