### ISSUE TITLE
Development communication

### ISSUE THREAD

**Issue by haslersn** [iamnotturner/vaccipy#111]
Is there a matrix channel for communication between developers?

**Comment by iamnotturner** [comment]
we are thinking about a discord server - what's your opinion on that? any suggestions for a easy-to-access communication tool? best practices?

**Comment by haslersn** [comment]
I think there's no tool that's easy-to-access for everybody. No matter which tool you use, some people don't have it (or not yet).

For instance, I will not use Discord, because it collects lots of user data.

**Comment by 4kills** [comment]
I think setting up a github project with the integrated **Kanban Board** would already greatly help and make it easier to assign tasks.

**Comment by iamnotturner** [comment]
Gute Idee, ich habe mal ein Kanban angelegt. Könnt ihr darauf zugreifen und es bearbeiten? 

https://github.com/iamnotturner/vaccipy/projects/2

**Comment by 4kills** [comment]
Nein, ich glaube das können nur Collaborator, aber das ist schon mal gut, damit man gleich sieht welche issues noch im backlog / frei sind. Es wäre dann halt gut unter dem issue eventuell einen comment da zu lassen, wenn man anfängt daran zu arbeiten.  
Optimal ist das zwar noch nicht aber schon mal ein anfang 👍

**Comment by 4kills** [comment]
> we are thinking about a discord server - what's your opinion on that? any suggestions for a easy-to-access communication tool? best practices?

Ich denk ein Discord-Server wäre aber trotzdem sehr praktisch. Das machen viele Communities so. Ist ja auch nicht die Welt das schnell aufzusetzen. Das haben auch viele Developer im Gegensatz zu anderen Diensten.

**Comment by BamButz** [comment]
Man könnte alternativ auch [Gitter.im](https://gitter.im/) verwenden, dass wird m.W. gerade in Zusammenspiel mit GitHub/Gitlab viel genutzt und unterstützt SSO.

**Comment by haslersn** [comment]
Im allerersten Post hatte ich ja Matrix vorgeschlagen, aber darauf ist offenbar noch keiner eingegangen.

https://doc.matrix.tu-dresden.de/why/

Accounts lassen sich direkt im Client erstellen. Den Server kann sich jeder selber raussuchen. Man kann z. B. matrix.org nehmen, oder das von uns (stuvus) gehostete studichat.de .

**Comment by iamnotturner** [comment]
Wir haben uns nun für Slack entschieden - das kennen viele bereits.
Hier die Einladung:

https://join.slack.com/t/vaccipy/shared_invite/zt-qt5ympiu-j7P86E2U0yM3shqoNSoqyg

**Comment by iamnotturner** [comment]
> https://join.slack.com/t/vaccipy/shared_invite/zt-qt5ympiu-j7P86E2U0yM3shqoNSoqyg

@Floskinner komm mal in Slack
