### ISSUE TITLE
Loglevel erhöhen

### ISSUE THREAD

**Issue by Steffeeeen1234** [iamnotturner/vaccipy#113]
Hallo zusammen, gibt es die Möglichkeit das Loglevel zu erhöhen, so dass auch alle Info [INF] logs geloggt werden? Aktuell werden bei mir nur [SUC] und [err] in der .log Datei und \tools\log geloggt.

Ich würde das einfach gern mal bei mir lokal ausprobieren wollen. Habe aber nichts auf Anhieb gefunden, wo und wie ich das ändern könnte.

Vielen Danke

**Comment by iamnotturner** [comment]
Hi,

in `tools/its.py` Zeile 38 wird der Logger instanziiert und da kannst du das `file_log_level` setzen. Probier es mal mit:

`self.log = CLogger("impfterminservice", file_log_level=10)`

**Comment by Steffeeeen1234** [comment]
Ich hätte vielleicht dazu sagen sollen, dass ich nur die Windows Distribution runtergeladen hatte. Dort war unter `tools` keine `its.py` Datei vorhanden.

Ich habe gerade nochmal den kompletten Master runtergalden und jetzt ist unter `tools` die `its.py` Datei vorhanden (aber nicht im Dist Ordner). Nachdem ändern der Codezeile und dem starten der Windows Exe aus `vaccipy-master\dist\windows-terminservice` wird aber weiterhin nicht alles geloggt was auch in der Kommandozeile ausgegeben wird, sondern wohl nur die errors und warnings.

muss ich in dem Fall die Distribution dann selber manuell erzeugen?

**Comment by iamnotturner** [comment]
Ja genau, die müsstest du dann manuell erzeugen oder das Programm einfach direkt mit Python ausführen 👍
