### ISSUE TITLE
Umlaute?

### ISSUE THREAD

**Issue by pancakeDevelopment** [iamnotturner/vaccipy#114]
Hi,
in der Beta Branch die ich derzeit habe, macht es andauernd die Umlaute in der kontakt Datei kaputt.

Aus Ä wird z.B. Ã¤. Ist das nur in der Datei & CMD so, oder wird das dann auch so in das Formular auf Impfterminservice.de gesendet?

**Comment by bonxz** [comment]
> Aus Ä wird z.B. Ã¤. Ist das nur in der Datei & CMD so, oder wird das dann auch so in das Formular auf Impfterminservice.de gesendet?

Gerade festgestellt wenn die Botprotection greift und das Programm es eintippt wird es auch so eingetippt mit den Zeichen "Ã¤". Hat dern Termin zum Glück nicht gebucht weil das Formular keine Umlaute annimmt :D

**Comment by sinun98** [comment]
Wird gefixt danke für den Hinweis.

**Comment by JuliusJacobitz** [comment]
@sinun98 das JSON Modul nimmt manchmal Standardmäßig ascii beim Speichern. Daran liegts

**Comment by haslersn** [comment]
https://github.com/iamnotturner/vaccipy/commit/c6a99378b3b81ef3c1b61819a2eec5cac77c84ef#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R65

Wieso diese Änderung? Es ist vollkommen erlaubt, Umlaute im Formular einzugeben. Ich denke eher, dass hier ein Problem mit dem Encoding der `kontaktdaten.json` vorliegt. Das hat ja auch @JuliusJacobitz schon angedeutet.

Außerdem wäre es sehr hilfreich, wenn ihr aufhört, direkt auf beta zu pushen, und anstattdessen einen PR erstellt und diesen merged. Dann kann man solche Kommentare direkt beim PR verfassen.

**Comment by iamnotturner** [comment]
> c6a9937#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R65
> 
> Wieso diese Änderung? Es ist vollkommen erlaubt, Umlaute im Formular einzugeben. Ich denke eher, dass hier ein Problem mit dem Encoding der kontaktdaten.json vorliegt. Das hat ja auch @JuliusJacobitz schon angedeutet.

Die Änderung ist nicht korrekt so, das stimmt. Ich wundere mich, warum überhaupt das Problem auftritt. Soweit ich weiß hat sich an der Schreibmethode von `kontaktdaten.json` nichts geändert - und bei mir macht es nach wie vor keine Probleme. Kann das auch Systemabhängig sein? 

> Außerdem wäre es sehr hilfreich, wenn ihr aufhört, direkt auf beta zu pushen, und anstattdessen einen PR erstellt und diesen merged. Dann kann man solche Kommentare direkt beim PR verfassen.

stimme ich dir zu, passiert in Zukunft nicht mehr

**Comment by haslersn** [comment]
@pancakeDevelopment Hast du vielleicht `python` (was auf vielen Systemem gleich Python 2 ist) statt `python3` verwendet?

**Comment by haslersn** [comment]
Potentieller Fix: #119 – wir müssen aber erst @pancakeDevelopment fragen, ob es damit funktioniert.

**Comment by bonxz** [comment]
Meine Kontaktdaten sahen nach dem Fehler so aus wie im Anhang.
![straße](https://user-images.githubusercontent.com/61289944/119371324-97b19700-bcb6-11eb-9c91-ebb3eb28325c.png)

Der Log ergab folgendes:

`2021-05-24 10:38:47.948   impfterminservice   [suc] [*CPCF | -----]   Terminpaar gefunden!
2021-05-24 10:38:47.948   impfterminservice   [suc] [*CPCF | -----]   '---------------' in ----- 
2021-05-24 10:38:47.948   impfterminservice   [suc] [*CPCF | -----]   1. Termin: ------ um ----- Uhr
2021-05-24 10:38:47.948   impfterminservice   [suc] [*CPCF | -----]   2. Termin:------- um ----- Uhr
2021-05-24 10:38:48.027   impfterminservice   [err] [*CPCF | -----]   Anfrage wurde von der Botprotection geblockt.
2021-05-24 10:38:58.891   impfterminservice   [err] [*CPCF | -----]   Button ÜBERNEHMEN kann nicht gedrückt werden
2021-05-24 10:38:59.923   impfterminservice   [err] [*CPCF | -----]   Button Termin buchen kann nicht gedrückt werden
2021-05-24 10:39:02.928   impfterminservice   [err] [*CPCF | -----]   Automatisierte Terminbuchung fehlgeschlagen. Termin manuell im Fenster oder im Browser buchen.
`

**Comment by sinun98** [comment]
> [c6a9937#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R65](https://github.com/iamnotturner/vaccipy/commit/c6a99378b3b81ef3c1b61819a2eec5cac77c84ef#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R65)
> 
> Wieso diese Änderung? Es ist vollkommen erlaubt, Umlaute im Formular einzugeben. Ich denke eher, dass hier ein Problem mit dem Encoding der `kontaktdaten.json` vorliegt. Das hat ja auch @JuliusJacobitz schon angedeutet.
> 
> Außerdem wäre es sehr hilfreich, wenn ihr aufhört, direkt auf beta zu pushen, und anstattdessen einen PR erstellt und diesen merged. Dann kann man solche Kommentare direkt beim PR verfassen.

War ein Hotfix der in der Schnelle einfach zu testen war und 100% funktioniert. Natürlich nicht die schönste Lösung.

**Comment by JuliusJacobitz** [comment]
@haslersn @alle. Vielen Dank für das Feedback, es ist natürlich vollkommen richtig. Ich möchte hier einmal drauf hinweisen, dass wir alle sehr viel neues dazu lernen und unterschiedliche stärken und schwächen haben. Deshalb freuen wir uns weiterhin über konstruktives und freundlich formuliertes Feedback. So kommen wir gemeinsam zum best möglichen Ergebnis ! :) ✌️
