### ISSUE TITLE
Fehler bei Auswahl von Impfzentrum 'Nordrhein'?

### ISSUE THREAD

**Issue by TimB83** [iamnotturner/vaccipy#115]
Hallo,

ich habe eine Frage: bei mir gibt es bei Benutzung des Tools immer eine Fehlermeldung (siehe unten). Dann geht es nicht weiter. Was mache ich falsch? Bin für jede Hilfe dankbar!

2021-05-24 13:36:28.140   impfterminservice   [inf] [*TER1 | ]   102 Impfzentren verfügbar
2021-05-24 13:36:28.140   impfterminservice   [inf] [*TER1 | ]   'Nordrhein' in  Weitere Impfzentren in NRW ausgewählt
2021-05-24 13:36:28.266   impfterminservice   [err] [impfstoffe_laden]   JSON parsing exception | IP gebannt oder Website down, erneuter Versuch in 30 Sekunden

**Comment by sinun98** [comment]
Hi, welche PLZ gibst du ein?

**Comment by TimB83** [comment]
Hi :) Ich würde gerne 52070 für Aachen eingeben. Die kennt er aber nicht. Also gebe ich gar nichts ein, drücke einfach Enter und dachte, dadurch würde er automatisch "Nordrhein" und "Weitere Impfzentren in NRW" auswählen. Vielleicht liegt aber gerade hier mein Fehler und ich verstehe etwas falsch!?

**Comment by haslersn** [comment]
Gar nichts eingeben ist soweit ich weiß zur Zeit nur möglich, wenn man manuell die `kontaktdaten.json` editiert. Editieren ist prinzipiell erlaubt, aber eine PLZ muss **immer** aus 5 Ziffern bestehen.

Die Impfzentren aus Gruppe 10 und Gruppe 16 werden vom Bot nicht unterstützt, da diese Buchungen über andere Plattformen laufen.

**Comment by TimB83** [comment]
> Die Impfzentren aus Gruppe 10 und Gruppe 16 werden vom Bot nicht unterstützt, da diese Buchungen über andere Plattformen laufen.

Das ist natürlich sehr schade :( Aber Danke für die Aufklärung, dann kann ich aufhören, weiter herumzuprobieren.

**Comment by Hastalavistahastalavista** [comment]
Hi, cooles Tool. Ich gehöre zur Impfgruppe 3 und versuche seit 2 Wochen vergeblich einen Termin zu bekommen. Verstehe ich das richtig, dass die Bereiche der Kassenärztlichen Vereinigung Nordrhein alle nicht vom Bot unterstütz werden? Mit PLZ 46485 oder 47441 gibt es diese Meldung: "Kein Impfzentrum zu eingetragenen PLZ's verfügbar"

**Comment by haslersn** [comment]
Ja, richtig. Es sind nur die Impfzentren unterstützt, die **mit Postleitzahl** [hier](https://github.com/iamnotturner/vaccipy/blob/master/impfzentren_gruppiert.md) gelistet sind.

**Comment by JuliusJacobitz** [comment]
Die Aufgabe von vaccipy ist die Nutzung der Website [impfterminservice.de](https://www.impfterminservice.de/impftermine)zu vereinfachen. Es werden von uns daher auch nur die dort unterstützen Impfzentren unterstützt.

**Comment by haslersn** [comment]
@JuliusJacobitz schon klar, aber sowohl auf impfterminservice.de, als auch in der API, als auch in unserer impfzentren_gruppiert.md findet sich Nordrhein. impfterminservice.de leitet aber nach der Auswahl weiter. D. h. wir haben hier ein Dokumentations-Problem.
