### ISSUE TITLE
Alle Plz nicht verfügbar?

### ISSUE THREAD

**Issue by Ralf-15** [iamnotturner/vaccipy#121]
Bei mir wird angezeigt, dass keine der von mir ausgesuchten Plz verfügbar sind!
![grafik](https://user-images.githubusercontent.com/84732956/119379579-f3345280-bcbf-11eb-8872-43e84d5ee667.png)

Kann das denn sein?
Ich habe die alle aus der offiziellen Quelle entnommen.

**Comment by haslersn** [comment]
https://355-iz.impfterminservice.de/impftermine/service?plz=32130

**Comment by Ralf-15** [comment]
Das hatte ich gesehen.
Aber, wie soll ich den Service denn aktivieren, wenn alle Plz´en abgelehnt werden und ich daher keinen Code für mehrere Impfzentren erstellen kann?

**Comment by haslersn** [comment]
Ich bin mir nicht sicher, ob man zur Zeit über die API Vermittlungscodes anfordern kann, während Onlinebuchungen deaktiviert sind.

**Comment by JuliusJacobitz** [comment]
Das sollte ein tempöräres Problem mit impfterminservice.de sein. Einfach später oder morgen wieder probieren.
