### ISSUE TITLE
Download Link funktioniert nicht

### ISSUE THREAD

**Issue by Steffeeeen1234** [iamnotturner/vaccipy#122]
mir ist gerade aufgefallen, dass der Download-Link nicht funktioniert .

![image](https://user-images.githubusercontent.com/34890799/119388888-2cbe8b00-bccb-11eb-99ea-d3cd76236f66.png)

Jeden Falls pssiert nichts, wenn man auf den Downloadlink klickt.
Wahrscheinlich sollte in der README.md der gleiche Link wie hier hinterlegt sein: https://github.com/iamnotturner/vaccipy/blob/master/docs/distribution.md

oder?

**Comment by Floskinner** [comment]
Also der Link Funktioniert nicht, da `https://github.com/iamnotturner/vaccipy##Downloads` hinterlegt ist -> 2mal #
Was einem direkt nach oben zu den Downloads bringen sollte. 

Alternativ könnte man auch direkt [https://cntr.click/9ypzBLb](https://cntr.click/9ypzBLb) einfügen, würde das aber so lassen, da man in der Readme dadurch nur ein download link verwalten muss, falls der sich ändern sollte

Und im Beta Branch steht der Text so auch gar nicht mehr drin

Siehe Quick-Fix #124

**Comment by JuliusJacobitz** [comment]
Danke an @Floskinner !

**Comment by Steffeeeen1234** [comment]
Danke @Floskinner fürs schnelle beheben.
