### ISSUE TITLE
J&J XPATH von Terminauswahl Button

### ISSUE THREAD

**Issue by sinun98** [iamnotturner/vaccipy#126]
Aktuell wird die automatisierte Terminbuchung von J&J Terminen nicht unterstützt. Um dies zu implementieren wird der HTML Code beim letzten Schritt der Terminbuchung benötigt. Genauer geht es um den XPATH des runden Buttons von J&J, der zur Terminauswahl dient.
![image](https://user-images.githubusercontent.com/48892674/119403018-0bb36580-bcde-11eb-9f18-d2e8fb86a92f.png)

**Comment by zoomzoom2408** [comment]
Das bedeutet also das man derzeit überhaupt keine Termine mit dem Tool buchen kann? Habe ich das richtig verstanden?

Weil ich habe seit heute morgen das Script für einen Termin für meine Frau laufen mit dem J&J Impfstoff.
Ich möchte ungern Termine erstellen die die Impfzentren dann belasten.
Vielen Dank

**Comment by sinun98** [comment]
Es wird vermutlich ein manueller Eingriff notwendig sein. Es öffnet sich ein Chrome Fenster indem der Termin manuell ausgewählt werden muss.

**Comment by Floskinner** [comment]
Könnte man nicht alternativ zum absoluten XPATH einen nehmen wie `//input[@type='radio']` der einem einfach alle Radio-Buttons auf der Seite zurück gibt und man dann einfach den 1. Radio-Button nimmt und "klickt"?
Dann wäre das auch unabhängig, welcher Impfstoff verwendet wird.

(Vorausgesetzt die Seite verwendet `<input type="radio" ...>`)

**Comment by sinun98** [comment]
> Könnte man nicht alternativ zum absoluten XPATH einen nehmen wie `//input[@type='radio']` der einem einfach alle Radio-Buttons auf der Seite zurück gibt und man dann einfach den 1. Radio-Button nimmt und "klickt"?
> Dann wäre das auch unabhängig, welcher Impfstoff verwendet wird.
> 
> (Vorausgesetzt die Seite verwendet `<input type="radio" ...>`)
 Ist leider nur ein div. Ich vermute bei J&J ist die class auch eine andere. 
<div _ngcontent-nfa-c125="" class="its-slot-pair-search-radio-btn"></div>

**Comment by sinun98** [comment]
Wurde gefixt
