### ISSUE TITLE
FM "[err] [impfstoffe_laden]   JSON parsing exception | IP gebannt oder Website down, erneuter Versuch in 30 Sekunden"

### ISSUE THREAD

**Issue by Rennhamster** [iamnotturner/vaccipy#129]
Hi, ich versuche vaccipy unter Mint Linux zu nutzen. Die Installationhat soweit funktioniert. Wenn ich jetzt einen Termin im Rheinland suche, erhalte ich die FM "[err] [impfstoffe_laden]   JSON parsing exception | IP gebannt oder Website down, erneuter Versuch in 30 Sekunden". Ist die FM woanders auch schon aufgetreten?
Ich lkann mir als Fehlerquelle vorstellen:
- meine IP ist aus irgendwelchen Gründen tatsächlich gebannt. Kann ich mir nicht richtig vorstellen, weil ich mich vom selben Rechnuer problemlos auf https://termin.corona-impfung.nrw/ einloggen kann.
- Der Server mag das Skript nicht oder das Script spricht eine andere Webseite an
- Das Script mag die PLZ des Impfzentrums nicht - hier im Rgheinland wird die PLZ des Impfzentrums (40474) nicht akzeptiert, stattdessen muss ich die PLZ leer lassen. Kann es sein, dass es daran scheitert?

Viele Grüße
Holger (aka Rennhamster)

P.S.: die komplette Bildschirmausgabe bei mir ist:
2021-05-24 22:32:14.094   impfterminservice   [inf] [*TER1 | ]   102 Impfzentren verfügbar
2021-05-24 22:32:14.094   impfterminservice   [inf] [*TER1 | ]   'Nordrhein' in  Weitere Impfzentren in NRW ausgewählt
2021-05-24 22:32:14.332   impfterminservice   [err] [impfstoffe_laden]   JSON parsing exception | IP gebannt oder Website down, erneuter Versuch in 30 Sekunden
Die letzte Zeile wiederholt sich dann beliebig oft....

**Comment by sinun98** [comment]
Hi, vaccipy unterstützt die Nutzung der Website impfterminservice.de. Es werden von uns daher auch nur die dort gelisteten Impfzentren unterstützt.

**Comment by TimB83** [comment]
Hey. Ich hatte heute genau die gleiche Frage ;) Siehe Diskussion unter https://github.com/iamnotturner/vaccipy/issues/115. Fazit: wir werden das Tool wohl leider nicht nutzen können :(
