### ISSUE TITLE
Terminpaare

### ISSUE THREAD

**Issue by rbin77** [iamnotturner/vaccipy#130]
Guten Tag,
ich hätte da nur eine kurze Frage, hab vaccipy gestartet und da kommt immer wieder diese Fehlermeldung: 

![vaccipy-Fehler](https://user-images.githubusercontent.com/84762827/119444983-62479080-bd2c-11eb-98c1-a2a9c0d17b48.PNG)

Meine Frage wäre, ob das weiter schlimm ist oder ob ich das ignorieren kann.

MfG Robin

**Comment by sinun98** [comment]
Hi, das bedeutet ungültiger Vermittlungscode. Hast dich wohl bei der Eingabe vertippt.
