### ISSUE TITLE
Automatische Dateneingabe bei Terminbuchung hat nicht funktioniert

### ISSUE THREAD

**Issue by ninjasan420** [iamnotturner/vaccipy#132]
Moin,

erstmal vielen Dank für diese App. Ich hab vor wenigen Minuten meinen Impftermin, den ich durch vaccipy ergattern konnte, bestätigt bekommen.

Allerdings ist beim Prozess folgender Fehler aufgetreten:
[Bild zum CMD Fehler](https://i.imgur.com/nb9ocGw.jpg)

Die automatische Dateneingabe meiner persönlichen Daten hat nicht funktioniert. 
Ich vermute es lag daran, dass ich (in dem Fall) Moderna als Impfstoff angeboten bekam und bei der Terminsuche 2x2 Blöcke (Moderna muss 2 mal geimpft werden) vorgeschlagen bekam. Vermutlich ist es so gedacht, dass man nur einen Termin vorgeschlagen bekommt.
es hat sich darauf ein Chrome Fenster geöffnet, wo ich dann die manuelle Terminbuchung und Dateneingabe vornehmen konnte - was dann zu einer erfolgreichen Buchung führte. 
Wenn ich allerdings nicht am PC gewesen wäre, hätte ich das nicht mitbekommen und keinen Termin abbekommen, da man für die Eingabe der Daten auch nur 10 Minuten Zeit gewährt bekommt.

Bin mir nicht sicher ob es "wichtig" ist - ich finde nur man sollte jeden Error melden :)

Beste Grüße!

**Comment by sinun98** [comment]
Hi, 

danke für das Feedback, ist immer hilfreich.  Schauen wir uns definitiv an. Der Fehler wurde bei der Terminauswahl ausgelöst, mit deiner Vermutung könntest du richtig liegen.

**Comment by bonxz** [comment]
Es sind doch immer zwei Termine außer bei J&J?

**Comment by sinun98** [comment]
Ja Moderna ist nicht der Grund. Bei mir hat es heute funktioniert.

**Comment by Sars-Cov-2-Antigen** [comment]
Manchmal erhält man mehr als nur ein Terminpaar. Habe mir noch nicht angeschaut, wie Vaccipy sich da verhält. Ich vermute, es wählt automatisch das erste. Hier wäre es sinnvoll, wenn man eine Präferenz einstellen könnte (z.B. lieber Samstagtermine oder lieber Termine in einem bestimmten Zeitraum...).
So wie ich das Problem hier verstehe, fragt sich ninjasan eher, ob Vaccipy mit der Mehrauswahl nicht klar kommt.

**Comment by ninjasan420** [comment]
wie @Sars-Cov-2-Antigen schreibt, ist es richtig.
Es hat sich effektiv ein neues Fenster geöffnet mit den 2 Terminvorschlägen.
Es waren 2 Blöcke mit Terminen, von denen ich einen Termin mit jeweils 2 Tagen auswählen konnte. 
Weil ich manuell eingreifen musste, hat autofill der Daten natürlich nicht funktioniert.
Ich gehe eben davon aus, dass man eigentlich nicht selbst den Termin der Impfung wählt (wählen sollte), sondern vaccipy selbst bestimmt (bestimmen sollte), damit man einen Termin nicht verpasst, sollte man gerade nicht am PC sitzen.

**Comment by Steffeeeen1234** [comment]
Gleiches Verhalten konnte ich heute bei meiner Impfbuchung für Biontech feststellen.
Es wurde dort allerdings nur ein Terminpaar angezeigt. Ich musste den Termin manuel bestätigten, weil es nicht mehr weiterging (ich glaube es gab auch einen Hinweis in der Console). Danach musste ich die Daten ebenfalls manuel eingeben.

Am Ende hat aber alles geklappt. 
Danke euch :)

**Comment by bluefor2** [comment]
Bei mir kam der gleiche Fehler. War zu der Zeit leider nicht am PC und konnte den Termin somit nicht buchen.
Wurde die Seite www.impfterminservice.de evtl. angepasst, sodass sie auf den Bot reagiert und der Bot daher gar keine Termine mehr buchen kann?
[Link zum Fehler](https://imgur.com/a/FoDEkEy)

Ich werden ihn jedenfalls erstmal weiter laufen lassen und hoffe, dass es beim nächsten versuch klappt.

**Comment by Floskinner** [comment]
Hey @Sars-Cov-2-Antigen

> Hier wäre es sinnvoll, wenn man eine Präferenz einstellen könnte (z.B. lieber Samstagtermine oder lieber Termine in einem bestimmten Zeitraum...).

Bei dem Thema bin ich dran -> #74
Es würde theoretisch eine Lauffähige Testversion in meinem [Fork ](https://github.com/Floskinner/vaccipy/tree/zeitbegrenzung_beta) geben, aber wie in #74 dargestellt, erstelle ich nun eine komplette GUI Anwendung, welches dieses Feature beinhaltet :)
