### ISSUE TITLE
Support mehrerer Codes und dadurch verschiedene Impfzentren

### ISSUE THREAD

**Issue by westside2626** [iamnotturner/vaccipy#133]
Hi zusammen, 

dies ist mehr ein Feature Request. 
Aktuell suche ich in verschiedenen Impfzentren mit verschiedenen Codes. Daher kopiere ich das aktuelle Projekt mehrmals und erstelle verschiedene "kontaktdaten.json" 
Wäre eine Erweiterung um mehrere Codes möglich, leider komme ich gerade nicht dazu. Schau mir aber gerne das Codereview an + testen. 

THX

**Comment by JuliusJacobitz** [comment]
Hi @westside2626. Es gibt dieses Feature absichtlich nicht, um zu vermeiden, dass du mehrere Termine buchst und um die Nutzung zumindest etwas zu beschränken.

**Comment by westside2626** [comment]
Passt! Völlig in Ordnung!
Grüße
