### ISSUE TITLE
"Die Code-Generierung war leider nicht erfolgreich"

### ISSUE THREAD

**Issue by jsmuehl** [iamnotturner/vaccipy#137]
(_Sorry vorab, falls das hier zu einer Dopplung wird - eine Antwort habe ich in den alten Issues jedoch nicht gefunden_)

Bei der Impf-Code-Generierung scheint die manuelle Einrichtung der Cookies zu klappen (zumindest scheitert es nicht an der botprotection) aber ich werde dann stets mit der Meldung **"Die Code-Generierung war leider nicht erfolgreich"** konfrontiert. 

![vacippy](https://user-images.githubusercontent.com/84790837/119522622-6ac7b780-bd7c-11eb-9bdf-2a55deaeea96.jpg)

Weiß jemand, woran das liegt oder wie ich daran vorbeikomme? Ich hatte in mehrmaligen Versuchen, auch mit (kleinerem) zeitlichem Abstand, keinen Erfolg.

**Comment by sinun98** [comment]
Hast du schon eine andere Telefonnummer und Mail versucht?

**Comment by chhantyal** [comment]
Ja, ich bekomme den gleichen Fehler

**Comment by sinun98** [comment]
Ist ein Fehler der auftritt, wenn der Request in die Warteschlange läuft. Wird gefixt. Einfach nochmal später versuchen wenn die Seite nicht so sehr überlastet ist.

**Comment by adargu** [comment]
> Ja, ich bekomme den gleichen Fehler
Ich muss jedesmal manuell die Cookies einfügen, manchmal wird der auch angenommen und bisher bin ich dann auch jedesmal bei "Die Code-Generierung war leider nicht erfolgreich" geendet. Habe Telefonnummer und E-Mail auch mal gewechselt und hat nichts gebracht.
