### ISSUE TITLE
Fehler: Impfzentren laden fehlgeschalgen

### ISSUE THREAD

**Issue by kaikl72** [iamnotturner/vaccipy#139]
![Screenshot 2021-05-25 194413](https://user-images.githubusercontent.com/84735353/119544728-48d92f80-bd92-11eb-868b-4434d3467dfb.png)

Hallo, komme beim Generieren des Impf-Codes nicht weiter. Ich habe 6 PLZ eingegeben, aber es kommt immer die Meldung, dass das Impfzentrum nicht gefunden wird und dass das Laden der Impfzentren fehlgeschlagen ist. Das gleiche passiere auch, wenn ich nur einen PLZ eingebe.

Danke für Tipps !

**Comment by Sars-Cov-2-Antigen** [comment]
1. Du solltest das Bild nochmal editieren. Ich kann hier problemlos deine Handynummer und deine E-Mailadresse lesen.
2. Du hast hier wahllos PLZ aufgelistet, die nicht der gleichen "Code-Gruppe" gehören. Ein Vermittlungscode ist zwar bei verschiedenen Zentren anwendbar, aber nicht bei allen. Schau Dir [hier](https://github.com/iamnotturner/vaccipy/wiki/Ein-Code-fuer-mehrere-Impfzentren) an, wie diese gruppiert sind.
3. Du kannst generell nur bei solchen Impfzentren anfragen, die auch über impfterminservice.de erreichbar sind. Aktuell funktioniert das also nicht für NRW. Dafür wird man auf [diese Seite](https://termin.corona-impfung.nrw/home) weitergeleitet (wo ich allerdings in meinem Browser nichts anklicken kann (Firefox).

**Comment by iamnotturner** [comment]
danke @Sars-Cov-2-Antigen für deine ausführliche Antwort, das ist korrekt. @kaikl72 melde dich kurz, wenn es nicht geklappt hat.
