### ISSUE TITLE
Fehler: Terminpaare können nicht geladen werden: 401 Unauthorized

### ISSUE THREAD

**Issue by eguido3333** [iamnotturner/vaccipy#140]
Guten Abend,

vielen Dank für Eure Unterstützung bei der Terminsuche!

Ich hab heute mal vaccipy ausprobiert und bin jetzt an einem Punkt angekommt, an dem es vermutlich läuft. Aber ich bekomme im Protokoll immer wieder den Fehler "Terminpaare können nicht geladen werden: 401 Unauthorized".
![cmd](https://user-images.githubusercontent.com/17071524/119555048-b2ab0680-bd9d-11eb-82f6-efa2bc09fa4c.png)

Ist das normal? Was bedeutet das und wie behebe ich dieses Problem? Danke im Voraus!

**Comment by eguido3333** [comment]
Hab noch etwas herumprobiert... liegt wohl an den ausgewählten Impfzentren. Ich habe mehrere angegeben, aber wohl aus unterschiedlichen Gruppen. Der erfolgreich generierte Code ist nur für eine (?) PLZ aus der eingegebenen Liste gültig.

Falls jemand dasselbe Problem hat, dann hier nachschauen, ob die ausgewählten PLZs in einer Gruppe sind:
[Ein-Code-fuer-mehrere-Impfzentren](https://github.com/iamnotturner/vaccipy/wiki/Ein-Code-fuer-mehrere-Impfzentren)

Kann jemand die "Lösung" bestätigen?

**Comment by iamnotturner** [comment]
Ja das ist richtig!
