### ISSUE TITLE
Error:"Anfrage wurde geblockt"

### ISSUE THREAD

**Issue by AliasHH20357** [iamnotturner/vaccipy#141]
Hi,
habe bereits ein paar Codes generiert. Nun kommt immer folgende Fehlermeldung. 
Mache ich was falsch? Bin kein IT´ler :)

![image](https://user-images.githubusercontent.com/84808576/119555869-a2dff200-bd9e-11eb-9a18-5652ecf4084d.png)

**Comment by devsbr** [comment]
Vielleicht bist du gerade geblockt (E-Mail, IP oder Handynummer).
Versuch es mal mit anderen Daten / später erneut

**Comment by sinun98** [comment]
Du verwendest eine alte Version.
