### ISSUE TITLE
Warum bekomme ich nur 1 Code?

### ISSUE THREAD

**Issue by Sylwuscha** [iamnotturner/vaccipy#146]
Was ich auch probiere, ich kann keinen 2. Code generieren. Habe auch schon 2x entzippt. Weiß nicht weiter. Hat jemand Tipps?

**Comment by iamnotturner** [comment]
Hi, schau mal ob dir dieser Beitrag (und der darunter) hilft : https://github.com/iamnotturner/vaccipy/issues/116#issuecomment-847024245

**Comment by Sylwuscha** [comment]
Habe es schon mit versch. Email und Handynummer probiert-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 26.05.21, 12:43, Tim Reibe ***@***.***> schrieb:

Closed #146.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/iamnotturner/vaccipy/issues/146#event-4798469817",
"url": "https://github.com/iamnotturner/vaccipy/issues/146#event-4798469817",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by iamnotturner** [comment]
wie sieht deine Fehlermeldung aus? Kannst du davon einen Screenshot posten?

**Comment by Sylwuscha** [comment]
2. Antwort Ich probiere schon seit fast 1 Woche, noch einen Code zu bekommen Erst für Tante, jetzt für Schwester und SchwagerEmail und Nummer schon getauscht-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 26.05.21, 12:43, Tim Reibe ***@***.***> schrieb:

Closed #146.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/iamnotturner/vaccipy/issues/146#event-4798469817",
"url": "https://github.com/iamnotturner/vaccipy/issues/146#event-4798469817",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
