### ISSUE TITLE
Terminpaare konnten nicht geladen werden

### ISSUE THREAD

**Issue by frank196612** [iamnotturner/vaccipy#147]
Hallo, 
ich habe folgendes Problem, habt ihr einen Tip`?

![image](https://user-images.githubusercontent.com/84847991/119651204-0b71b200-be25-11eb-9e6d-d3a1e6bcc908.png)

**Comment by iamnotturner** [comment]
Hey, eine Antwort dazu findest du hier.

https://github.com/iamnotturner/vaccipy/issues/116#issuecomment-848690301

**Comment by frank196612** [comment]
Danke Dir!
