### ISSUE TITLE
Anfrage durch Botprotection blockiert

### ISSUE THREAD

**Issue by Klobbinger** [iamnotturner/vaccipy#148]
Trotz des hier https://github.com/iamnotturner/vaccipy/blob/master/FAQ.md#faq beschriebenen Vorgehens für manuelle Cookies taucht wiederholt der folgende Fehler bei der Impf-Code Generierung auf:

```
[err] [*TER1 | 71065]   Anfrage wurde von der Botprotection geblockt.
Es werden manuelle Cookies aus dem Browser benötigt.
Bitte Anleitung im FAQ in GitHub beachten.
Link: https://229-iz.impfterminservice.de/impftermine/service?plz=71065
```

**Comment by iamnotturner** [comment]
Wie in den FAQ's beschrieben ist ein "normales" Nutzerverhalten im Browser nachzustellen, also Seite muss lang geöffnet sein und man muss mal hier und da rumklicken. Ansonsten hilft es auch die Mail/Telefonnummer zu ändern oder 24 Stunden zu warten.
