### ISSUE TITLE
Anfrage wurde von der botprotection geblockt

### ISSUE THREAD

**Issue by Justin9720** [iamnotturner/vaccipy#150]
![image](https://user-images.githubusercontent.com/84766002/119660264-5690c280-be2f-11eb-982a-075364f3f604.jpeg)
Was kann ich dagegen tun?? Bitte um Hilfe ...

**Comment by iamnotturner** [comment]
Du musst Chrome installieren, wie in der README.md über den Download-Symbolen beschrieben

**Comment by iamnotturner** [comment]
Zu deiner Frage

> Bei mir kam Fehlermeldung Terminpaare nicht gefunden Postleitzahl ungültig weshalb???

hat sich das erledigt?

**Comment by Justin9720** [comment]
Ja das mit ungültiger plz hat sich erledigt danke dir ! 😀

**Comment by Justin9720** [comment]
Und sobald ich den chrome Browser installiert habe funkt es mit der Buchung?? Sorry das ich frage aber ich fuchs mich da erst noch ein 😁
