### ISSUE TITLE
Manuelle Cookies - Egal was man macht

### ISSUE THREAD

**Issue by csenk** [iamnotturner/vaccipy#153]
Hallo zusammen,

ich verzweifel gerade an der Generierung eines Imp-Codes. Ich befolge die Hinweise in der FAQ, habe jetzt auch schon weit über eine halbe Stunde ein Browser-Fenster auf in dem ich auch immer mal wieder eine Interaktion durchführe um einen gültigen Cookie zu bekommen.

Führe das Programm auch direkt in IDLE aus. Führt bei mir alles nicht zum Erfolg :/
Würde mich freuen über den ein oder anderen Hinweiß.

Schöne Grüße

**Comment by devsbr** [comment]
Hi!
Wichtig ist, dass du den Wert des ### bm_sz Cookies (wie aus der Anleitung des FAQs) des request headers kopierst und dann vollständig einfügst.

**Comment by typu3yy9** [comment]
@devsbr 
Ich kann das Problem von @csenk so bestätigen.
Gebe die bm_sz Cookies ein, aber es kommt immer wieder die selbe Meldung:

`2021-05-26 15:53:24.572   impfterminservice   [err] [*TER1 | 76137]   Anfrage wurde von der Botprotection geblockt.
Es werden manuelle Cookies aus dem Browser benötigt.
Bitte Anleitung im FAQ in GitHub beachten.
Link: https://005-iz.impfterminservice.de/impftermine/service?plz=76137`

Auch ich führe direkt in IDLE aus, nachdem es vorher schon in der Konsole nicht geklappt hat.

**Comment by sebastianpfau** [comment]
Das gleiche Problem hatte ich gestern. Gerade habe ich es mit einer anderen PLZ probiert - direkt bei der ersten manuellen Eingabe hat es funktioniert.
Möglicherweise aber auch nur ein Zufall und es braucht nur etwas Geduld.

**Comment by trfr3ak** [comment]
war bei mir auch gestern, habs das Cookie aus nem anderen Gerät geholt, dann gings

**Comment by NilsB26** [comment]
![grafik](https://user-images.githubusercontent.com/71553507/119690314-db88d580-be49-11eb-9818-c7b729da1dde.png)

Nehmt ihr den Cookie von der impterminservice.de/imptermine Seite oder den Cookie von dem ausgewählten Impfzentrum -> 
![grafik](https://user-images.githubusercontent.com/71553507/119690468-02dfa280-be4a-11eb-80b1-37f791383df5.png)

Weil nur dieser beginnt direkit mit einem bm_sz

**Comment by sinun98** [comment]
> ![grafik](https://user-images.githubusercontent.com/71553507/119690314-db88d580-be49-11eb-9818-c7b729da1dde.png)
> 
> Nehmt ihr den Cookie von der impterminservice.de/imptermine Startseite (das obere Bild) oder den Cookie von dem ausgewählten Impfzentrum (das untere Bild) ?
> ![grafik](https://user-images.githubusercontent.com/71553507/119690468-02dfa280-be4a-11eb-80b1-37f791383df5.png)
> 
> Weil nur dieser beginnt direkt mit einem bm_sz

unten

**Comment by sinun98** [comment]
Die Cookies aus dem laufenden Browser müssen manuell eingefügt werden. Sind diese nicht gültig muss weiter versucht werden, mittels Eingaben und normalem Nutzerverhalten, diese gültig werden zu lassen. Es gibt aber auch Browser/Geräte da werden diese nie gültig. Es gibt hier auch kein Muster. Manche User bekommen ohne Probleme valide Cookies andere wiederum nur nach langem warten oder gar nicht.

**Comment by JuliusJacobitz** [comment]
@sinun98 Könnte es am headless mode liegen ?

**Comment by sinun98** [comment]
> @sinun98 Könnte es am headless mode liegen ?

Meinte damit den "echten" Chrome Browser mit längerer Historie und individuellem Nutzerverhalten.

**Comment by NilsB26** [comment]
Sieht man irgendwo wann genau das Cookie valide ist? und Warum beginnt mein Cookie aus der Datei "Impftermine" mit akaalb_www...
Ist das bei euch auch so?

**Comment by typu3yy9** [comment]
Ich habe das Problem für mich gelöst. 
Im Screenshot im FAQ ist alles nach dem Cookie markiert. Ihr dürft allerdings nur den Part bis zum ersten Semikolon kopieren. Hat bei mir dann sofort geklappt, nachdem ich es zig mal mit dem kompletten Ding probiert habe.

**Comment by Sylwuscha** [comment]
Wo finde ich, was ich manuell für Cookies eingeben muss?

**Comment by typu3yy9** [comment]
@Sylwuscha In Chrome 
Rechtsklick -> Untersuchen -> Network -> cmd + r -> oberstes Element anklicken (document, other) -> dann runterscrollen zu request headers.

**Comment by sinun98** [comment]
> Sieht man irgendwo wann genau das Cookie valide ist? und Warum beginnt mein Cookie aus der Datei "Impftermine" mit akaalb_[www](http://www)...
> Ist das bei euch auch so?

Leider nur durch probieren. Entweder es klappt oder es wird geblockt.

**Comment by sinun98** [comment]
> Ich habe das Problem für mich gelöst.
> Im Screenshot im FAQ ist alles nach dem Cookie markiert. Ihr dürft allerdings nur den Part bis zum ersten Semikolon kopieren. Hat bei mir dann sofort geklappt, nachdem ich es zig mal mit dem kompletten Ding probiert habe.
> 
> ![image](https://user-images.githubusercontent.com/84856597/119696982-0b3adc00-be50-11eb-9972-87ff5b397bab.png)
> 
> Solltet ihr vielleicht im FAQ anpassen, so erspart ihr euch wahrscheinlich einiges an Support-Arbeit.

Wäre interessant ob das andere hier bestätigen können.

**Comment by Sylwuscha** [comment]
Kenne mich leider 0 aus. Wo finde ich die Chrome Einstellungen am PC?

**Comment by sinun98** [comment]
@Sylwuscha #116 ist die Anleitung 
Alternativ zu Schritt 3 kannst du auch in Chrome oben Rechts auf die 3 Punkte -> Weiter Tools -> Entwicklertools

**Comment by csenk** [comment]
Ich konnte das Problem für mich jetzt lösen, nachdem ich das fragliche Impfzentrum nicht mehr nehme.

**Comment by NilsB26** [comment]
> 
> 
> > Ich habe das Problem für mich gelöst.
> > Im Screenshot im FAQ ist alles nach dem Cookie markiert. Ihr dürft allerdings nur den Part bis zum ersten Semikolon kopieren. Hat bei mir dann sofort geklappt, nachdem ich es zig mal mit dem kompletten Ding probiert habe.
> > ![image](https://user-images.githubusercontent.com/84856597/119696982-0b3adc00-be50-11eb-9972-87ff5b397bab.png)
> > Solltet ihr vielleicht im FAQ anpassen, so erspart ihr euch wahrscheinlich einiges an Support-Arbeit.
> 
> Wäre interessant ob das andere hier bestätigen können.

Kannst du mal kurz erzklären welche Cookie du genau genommen hast, das aus "Impftermine" unter Request Headers?
Bei mir will es einfach nicht suchen (Impfzentrum Mannheim)

**Comment by csenk** [comment]
Eine Mischung aus Skript neustarten und @typu3yy9 Hinweiß nur das eine Cookie zu kopieren hat am Ende geholfen. Ein Code konnte generiert werden.

Danach bin ich öfter in den 401 Fehler gelaufen, weil ich noch Impfzentren in der Liste hatte die nicht in der Gruppe waren auf die sich der Code bezog. Auch hier hat neustarten des Skripts inkl. Anpassung von kontaktdaten.json geholfen.

Jetzt scheint die Suche nach Terminen stabil zu laufen.
Danke für die die hilfreichen Hinweiße und natürlich überhaupt erst für das entwickeln dieses Skripts.

**Comment by typu3yy9** [comment]
> > > Ich habe das Problem für mich gelöst.
> > > Im Screenshot im FAQ ist alles nach dem Cookie markiert. Ihr dürft allerdings nur den Part bis zum ersten Semikolon kopieren. Hat bei mir dann sofort geklappt, nachdem ich es zig mal mit dem kompletten Ding probiert habe.
> > > ![image](https://user-images.githubusercontent.com/84856597/119696982-0b3adc00-be50-11eb-9972-87ff5b397bab.png)
> > > Solltet ihr vielleicht im FAQ anpassen, so erspart ihr euch wahrscheinlich einiges an Support-Arbeit.
> > 
> > 
> > Wäre interessant ob das andere hier bestätigen können.
> 
> Kannst du mal kurz erzklären welche Cookie du genau genommen hast, das aus "Impftermine" unter Request Headers?
> Bei mir will es einfach nicht suchen (Impfzentrum Mannheim)

Bei mir wurde in der "Fehlermeldung" auch immer ein Link angegeben, der auch die PLZ meines Impfzentrums enthielt. 
An oberster Stelle war bei mir dann meist einfach die PLZ als Titel, anstelle von "Impfzentren" wie im FAQ. Nebendran sollte in der Table (document, other) stehen.

**Comment by NilsB26** [comment]
![grafik](https://user-images.githubusercontent.com/71553507/119711646-0e3dc880-be60-11eb-91cc-d5a1cd2d7708.png)
Kommt bei euch auch diese Fehlermeldung?

**Comment by gv-rgb** [comment]
> Ich habe das Problem für mich gelöst.
> Im Screenshot im FAQ ist alles nach dem Cookie markiert. Ihr dürft allerdings nur den Part bis zum ersten Semikolon kopieren. Hat bei mir dann sofort geklappt, nachdem ich es zig mal mit dem kompletten Ding probiert habe.
> 
> ![image](https://user-images.githubusercontent.com/84856597/119696982-0b3adc00-be50-11eb-9972-87ff5b397bab.png)
> 
> Solltet ihr vielleicht im FAQ anpassen, so erspart ihr euch wahrscheinlich einiges an Support-Arbeit.

Hat bei mir auch funktioniert

**Comment by ralfescher** [comment]
Anmerkung: bei mir hat das Ganze (Thema manuelle Cookies) unter Windows 10 **nicht** funktioniert.
Ich lasse es jetzt auf meinem Raspberry Pi laufen (`python3 main.py`).
Dort habe ich sofort einen Vermittlungscode erhalten 😄 
und lasse aktuell die Terminsuche laufen (ohne jegliche Fehlermeldungen bisher)

**Comment by NilsB26** [comment]
> 
> 
> Anmerkung: bei mir hat das Ganze (Thema manuelle Cookies) unter Windows 10 **nicht** funktioniert.
> Ich lasse es jetzt auf meinem Raspberry Pi laufen (`python3 main.py`).
> Dort habe ich sofort einen Vermittlungscode erhalten 😄
> und lasse aktuell die Terminsuche laufen (ohne jegliche Fehlermeldungen bisher)

Bei welchem Impfzentrum?

**Comment by NilsB26** [comment]
![grafik](https://user-images.githubusercontent.com/71553507/119784552-9eb2f200-bece-11eb-9311-ac628200910a.png)

Ich lass es gerade unter WIN10 laufen, sieht so aus als würde alles laufen nur keine Vermittlungscodes zu Verfügung stehen =/

**Comment by NilsB26** [comment]
> 
> 
> Anmerkung: bei mir hat das Ganze (Thema manuelle Cookies) unter Windows 10 **nicht** funktioniert.
> Ich lasse es jetzt auf meinem Raspberry Pi laufen (`python3 main.py`).
> Dort habe ich sofort einen Vermittlungscode erhalten 😄
> und lasse aktuell die Terminsuche laufen (ohne jegliche Fehlermeldungen bisher)

Vielleicht wärst du ja so lieb und würdest schnell für mich auch einen erstellen ? =)

**Comment by iamnotturner** [comment]
@NilsB26 hast du Chrome installiert

**Comment by NilsB26** [comment]
@iamnotturner klar ist Chrome installiert

**Comment by ralfescher** [comment]
> > Anmerkung: bei mir hat das Ganze (Thema manuelle Cookies) unter Windows 10 **nicht** funktioniert.
> > Ich lasse es jetzt auf meinem Raspberry Pi laufen (`python3 main.py`).
> > Dort habe ich sofort einen Vermittlungscode erhalten 😄
> > und lasse aktuell die Terminsuche laufen (ohne jegliche Fehlermeldungen bisher)
> 
> Bei welchem Impfzentrum?

@NilsB26: Waiblingen (71334), konnte gerade auch einen weiteren Vermittlungscode erstellen.
bitte PM per Twitter (@ralfescher), da dies hier wohl nicht geht

**Comment by Sylwuscha** [comment]
Ich schaffe es einfach nicht, den richtigen manuellen Code zu finden. Für mich als Laie ist alles unverständlich, was hier geschrieben wird :-( Ich klicke F12, aber trotzdem sieht es bei mir nicht ganz gleich aus wie im FAQ beschrieben. Einen langen Code mit bm_sz finde ich einfach nicht. Wer kann mir alles von Anfang an leichter erklären? (ich weiß auch nicht, was Chrome ist und ob ich es auf dem PC habe)

**Comment by NilsB26** [comment]
@ralfescher ich hab dir eine Anfrage auf Twitter geschickt

**Comment by Sylwuscha** [comment]
Hab kein Twitter :-(

**Comment by sinun98** [comment]
> Ich schaffe es einfach nicht, den richtigen manuellen Code zu finden. Für mich als Laie ist alles unverständlich, was hier geschrieben wird :-( Ich klicke F12, aber trotzdem sieht es bei mir nicht ganz gleich aus wie im FAQ beschrieben. Einen langen Code mit bm_sz finde ich einfach nicht. Wer kann mir alles von Anfang an leichter erklären? (ich weiß auch nicht, was Chrome ist und ob ich es auf dem PC habe)

bm_sv=C42684755698BF14F7711ED2CCBD5C59~ZUevIxbGt5h47GuqIHd1oPUsbVLhBm1Azoo1LTsQ7/YGaMeXa3cOrLvvrs6vJ2BZy5SqLYWO1vEkYZNnj0Aei17HBqBFlLH9TLvaBOVjwUGVivGyKkkUB50kw4WleoUAtz0npXpeGisWlm1gBtI1SBc472/00oyocxjHa6I377Y=; akavpau_User_allowed=1622104037~id=942cf302d679e9c20dec2b58a079a6c7;

Probiers mal mit diesem Wert.

**Comment by Sylwuscha** [comment]
bm_sv=C42684755698BF14F7711ED2CCBD5C59~ZUevIxbGt5h47GuqIHd1oPUsbVLhBm1Azoo1LTsQ7/YGaMeXa3cOrLvvrs6vJ2BZy5SqLYWO1vEkYZNnj0Aei17HBqBFlLH9TLvaBOVjwUGVivGyKkkUB50kw4WleoUAtz0npXpeGisWlm1gBtI1SBc472/00oyocxjHa6I377Y=;

Diesen Code kopiert und eingefügt, hat nicht geklappt

**Comment by sinun98** [comment]
`ak_bmsc=2894C9D1F9A09FC5767510359FA0B9C602148F3DAB7C00007155AF60D0FEB851~pl32OFVSUrKlhk0BHBsAYwHYqzgcuMaN4lLfdRwDWF/15zoA/dOgOPT/aM2txv+VrWv2kH4pudosxviHcUW2HBQayYFkO5p+zVpdW4CkyxvmtgEgsN5TosqMbsghUI/a8Oh/yyGIjATDyUEn8c5aI3URDoJrYuBWdwH7YxWX5oSiPDqAiXwAnge9EoyTZH1bd1KFbrpnmtjViGEx+zdpstx+sAjnZ1tTDeVCr5tLghWa8C+G+e2JnDv/hFl58Ej0bl; bm_sz=EAB2E04CEB4CCA44C50D3F510E6F79D0~YAAQPY8UAkfOlD95AQAAEMPlrAsEDeeBeXCnp7NKHXsu+12NjpEq93GGoJTtO9xnQKlh4bG/XBqTjPn6n0zIUe/wW9RgHOTAk9EwHBeOQmsF1dYJ4YjJaXzOHo3rPjw4zayAdbqYMdrJwF2x2aKCbrRYtGzxCky5fCMRjDmrAsDDK/HEudU6iDr675dkTvzW5xYTQQ6/n5EaDQ==; bm_mi=CF7217D546DDBA4EC0B2FB4CA0F9F9F4~cm+N1duhJI4RJ38lyzVw2SN9o2PR0t/e2cOytCcfi7NnvaagFKoKhoP3kXGRhnpgT7FZ/de4MA4WA2F6M+/M3mdsOUeIrHpPSK6pepDMWFP205Ip11lBpBX1fOZWDpPViL0+vQisYKs0+0k54jHtqr6wdXiIQSveqQZx68B0B7yJrQQE4TSRFlcuNv5umhmQ+6CEhEHZ1rZ8wnOgs+rcOw7P/1eMmo0bKdXtJ5YaI0yajNkPE5yBPTYiab9Ggtn5NDOJmgQZdXewoYS6IfzHCIaT1Nx0MmE9kuDrGH5uDEk=; bm_sv=C42684755698BF14F7711ED2CCBD5C59~ZUevIxbGt5h47GuqIHd1oPUsbVLhBm1Azoo1LTsQ7/YGaMeXa3cOrLvvrs6vJ2BZy5SqLYWO1vEkYZNnj0Aei17HBqBFlLH9TLvaBOVjwUGVivGyKkkUB50kw4WleoUAaEL0PjO91S0odApIyl0E+/Ylwh8P5PVgUs6blbBs6SI=; akavpau_User_allowed=1622104918~id=ff8edfc62763eaaeab52dfb7f81385ef; _abck=CCDDF4A26B8D09406018AC71F7ECD30C~-1~YAAQLI8UAlYpBpx5AQAA7qDzrAV3lsSkFwdhWzh6tx/2N3XiZ8yK8FmwiNCWYa0nzB9X/+NVH+FTZwKHBnETkxSvx5ODiY3RDr7BL2Ojo0CIDi3+hPtYVgx+lLo09ZU34zUwbSEZKaRt/licVD6gdFw9U8HFEE4x4X1eXGrJiQzm1Md5pCAEtlId+siF9eghdAQgnHUmg+5J8+ewB036mpVeTs4miB5yNHddHNE2jVwvxu0ddzPFVPz43jK9vuiYnyQV+BCIX7eoNxB3PfLvs+fvhEOWyaHngMX3pf94fy+Y07FU64D8NKEqSRId3cZYp34UsgDR9b4uMkF2AvF112lw+fMJ45ift1kN1it6kCe32V0MGz+TttHvOVBeAOxQyaKv7YpYuxYw00fUUbKQi0R8qip1g0FfayU6whyrFH8SOg==~0~-1~-1`

Dann kannst du es damit nochmal probieren

**Comment by typu3yy9** [comment]
Ihr müsst den bm_sz nehmen, nicht den bm_sv. Und nur bis zum ersten Semikolon.

**Comment by typu3yy9** [comment]
> Ich schaffe es einfach nicht, den richtigen manuellen Code zu finden. Für mich als Laie ist alles unverständlich, was hier geschrieben wird :-( Ich klicke F12, aber trotzdem sieht es bei mir nicht ganz gleich aus wie im FAQ beschrieben. Einen langen Code mit bm_sz finde ich einfach nicht. Wer kann mir alles von Anfang an leichter erklären? (ich weiß auch nicht, was Chrome ist und ob ich es auf dem PC habe)

Du bekommst Python zum Laufen, aber weißt nicht was Chrome ist?

Chrome ist der Browser, der bei dir in etwa so aussehen sollte 
![image](https://user-images.githubusercontent.com/84856597/119795209-8d6ee300-bed8-11eb-8af2-044f935d7555.png)

Auf der verlinkten Seite machst du dann folgendes:
Rechtsklick irgendwo im weißen Bereich -> Untersuchen -> Network -> cmd + r -> oberstes Element anklicken (document, other) -> dann runterscrollen zu request headers.

**Comment by LenzGr** [comment]
Danke für diesen Hinweis, an dieser Hürde bin ich auch fast verzweifelt. Es ging bei mir (Impfzentrum Hamburg), nachdem ich nur den `bz_sz=[...];`-Teil kopiert habe und nicht die kompletten Cookie-Daten.

**Comment by Klobbinger** [comment]
> Danke für diesen Hinweis, an dieser Hürde bin ich auch fast verzweifelt. Es ging bei mir (Impfzentrum Hamburg), nachdem ich nur den bm_sz=[...];-Teil kopiert habe und nicht die kompletten Cookie-Daten.

Funktioniert bei mir leider nicht, auch an 2. Rechner ausprobiert. Kann es sein das die IP eine Rolle spielt, da die exakt gleiche Vorgehensweise bei einem Kollegen bei sich zu Hause geklappt hat?

**Comment by l-e-e-o** [comment]
Kann auch bestätigen, dass es nur mit dem `bm_sz` Cookie bei auch funktioniert hat, während ich vorher immer in die Bot Protection gelaufen bin.

**Comment by l-e-e-o** [comment]
@Klobbinger oder dein Mail-Telefonnummer-Paar ist schon für 24h geblockt worden.

**Comment by Klobbinger** [comment]
Nummer und Mailadresse habe ich bereits geändert. Habe mir augu schon den
Cookie schicken lassen, hatte da allerdings noch nicht den Trick probiert
nur den Teil bis zum ersten Semikolon zu nehmen, allerdings sollte es ja
eigentlich auch mit dem gesamten gehen.

Leonard Frank ***@***.***> schrieb am Do., 27. Mai 2021,
14:09:

**Comment by sinun98** [comment]
> Mit dem Tipp von sinun98, den unten stehenden Link zu probieren, hat es leider auch nicht geklappt
> im Gegenteil - jetzt erscheint:
> 
> ![grafik](https://user-images.githubusercontent.com/84845174/119825270-11d05e80-bef7-11eb-8289-6cf38cd72767.png)
> 
> "ak_bmsc=2894C9D1F9A09FC5767510359FA0B9C602148F3DAB7C00007155AF60D0FEB851~pl32OFVSUrKlhk0BHBsAYwHYqzgcuMaN4lLfdRwDWF/15zoA/dOgOPT/aM2txv+VrWv2kH4pudosxviHcUW2HBQayYFkO5p+zVpdW4CkyxvmtgEgsN5TosqMbsghUI/a8Oh/yyGIjATDyUEn8c5aI3URDoJrYuBWdwH7YxWX5oSiPDqAiXwAnge9EoyTZH1bd1KFbrpnmtjViGEx+zdpstx+sAjnZ1tTDeVCr5tLghWa8C+G+e2JnDv/hFl58Ej0bl; bm_sz=EAB2E04CEB4CCA44C50D3F510E6F79D0~YAAQPY8UAkfOlD95AQAAEMPlrAsEDeeBeXCnp7NKHXsu+12NjpEq93GGoJTtO9xnQKlh4bG/XBqTjPn6n0zIUe/wW9RgHOTAk9EwHBeOQmsF1dYJ4YjJaXzOHo3rPjw4zayAdbqYMdrJwF2x2aKCbrRYtGzxCky5fCMRjDmrAsDDK/HEudU6iDr675dkTvzW5xYTQQ6/n5EaDQ==; bm_mi=CF7217D546DDBA4EC0B2FB4CA0F9F9F4~cm+N1duhJI4RJ38lyzVw2SN9o2PR0t/e2cOytCcfi7NnvaagFKoKhoP3kXGRhnpgT7FZ/de4MA4WA2F6M+/M3mdsOUeIrHpPSK6pepDMWFP205Ip11lBpBX1fOZWDpPViL0+vQisYKs0+0k54jHtqr6wdXiIQSveqQZx68B0B7yJrQQE4TSRFlcuNv5umhmQ+6CEhEHZ1rZ8wnOgs+rcOw7P/1eMmo0bKdXtJ5YaI0yajNkPE5yBPTYiab9Ggtn5NDOJmgQZdXewoYS6IfzHCIaT1Nx0MmE9kuDrGH5uDEk=; bm_sv=C42684755698BF14F7711ED2CCBD5C59~ZUevIxbGt5h47GuqIHd1oPUsbVLhBm1Azoo1LTsQ7/YGaMeXa3cOrLvvrs6vJ2BZy5SqLYWO1vEkYZNnj0Aei17HBqBFlLH9TLvaBOVjwUGVivGyKkkUB50kw4WleoUAaEL0PjO91S0odApIyl0E+/Ylwh8P5PVgUs6blbBs6SI=; akavpau_User_allowed=1622104918~id=ff8edfc62763eaaeab52dfb7f81385ef; _abck=CCDDF4A26B8D09406018AC71F7ECD30C~-1~YAAQLI8UAlYpBpx5AQAA7qDzrAV3lsSkFwdhWzh6tx/2N3XiZ8yK8FmwiNCWYa0nzB9X/+NVH+FTZwKHBnETkxSvx5ODiY3RDr7BL2Ojo0CIDi3+hPtYVgx+lLo09ZU34zUwbSEZKaRt/licVD6gdFw9U8HFEE4x4X1eXGrJiQzm1Md5pCAEtlId+siF9eghdAQgnHUmg+5J8+ewB036mpVeTs4miB5yNHddHNE2jVwvxu0ddzPFVPz43jK9vuiYnyQV+BCIX7eoNxB3PfLvs+fvhEOWyaHngMX3pf94fy+Y07FU64D8NKEqSRId3cZYp34UsgDR9b4uMkF2AvF112lw+fMJ45ift1kN1it6kCe32V0MGz+TttHvOVBeAOxQyaKv7YpYuxYw00fUUbKQi0R8qip1g0FfayU6whyrFH8SOg==~0~-1~-1"

Update dazu ist in Arbeit

**Comment by FlauschR** [comment]
Hello,

bei der Codegenerierung habe ich nachdem ich den cookie eingesetzt habe sofort die meldung "Die Code-Generierung war leider nicht erfolgreich." bekommen.
Muss man das ganze einfach öfter machen? 
Oder hat jemand eine Idee, was da Falsch läuft? Virusprogramm/ Chrome verhindert evtl die Ausführung? I dont know..

Generell wäre es eigentlich ganz cool mal zu sehen, wie so ein skriptverlauf aussieht wenn alles funktioniert... Ich vermute bei den wenigsten funktioniert es sofort, oder?

Gruß

**Comment by sinun98** [comment]
> Hello,
> 
> bei der Codegenerierung habe ich nachdem ich den cookie eingesetzt habe sofort die meldung "Die Code-Generierung war leider nicht erfolgreich." bekommen.
> Muss man das ganze einfach öfter machen?
> Oder hat jemand eine Idee, was da Falsch läuft? Virusprogramm/ Chrome verhindert evtl die Ausführung? I dont know..
> 
> Generell wäre es eigentlich ganz cool mal zu sehen, wie so ein skriptverlauf aussieht wenn alles funktioniert... Ich vermute bei den wenigsten funktioniert es sofort, oder?
> 
> Gruß

Dann war zumindest der Cookie valide. Entweder du probierst es jetzt einige Male bis es klappt oder du wartest etwas. Wenn die Server eine Warteschlange haben funktioniert es nur mit Glück.

**Comment by iamnotturner** [comment]
> Update dazu ist in Arbeit

wir geben Bescheid, wenn das neue Update da ist

**Comment by iamnotturner** [comment]
Update ist nun da, bitte [neuen Release hier downloaden](https://github.com/iamnotturner/vaccipy#downloads)

**Comment by JuliusJacobitz** [comment]
[neuer Release](https://github.com/iamnotturner/vaccipy/releases/tag/v1.0.2) jetzt da !
