### ISSUE TITLE
Wartezeit zwischen Prüfung von mehreren Impfzentren

### ISSUE THREAD

**Issue by sebastianpfau** [iamnotturner/vaccipy#158]
Hi,

Richtig tolles Projekt! Vielen Dank für eure ganze Mühe!

Habe gerade die Terminsuche für mehrere Impfzentren einer Gruppe gestartet und gemerkt, dass die 1min Wartezeit auch zwischen den einzelnen PLZ eingehalten wird.

Wäre es vielleicht sinnvoll die Wartezeit nur einzustellen zwischen der Abfrage von allen eingegebenen Impfzentren?
Also Batchabfrage und dann 1min Pause.

Könnte alternativ die Wartezeit reduziert werden?
Sonst wird bei fünf Impzentren effektiv aus 1min Abstand direkt 5min.

Gruß, Sebastian

**Comment by sinun98** [comment]
Hi, 
die Wartezeit lässt sich über erweiterte Einstellungen einstellen.
