### ISSUE TITLE
Ein Code für mehrere Impfzentren

### ISSUE THREAD

**Issue by iamnotturner** [iamnotturner/vaccipy#16]
### Du kannst deinen Code für die Terminsuche bei mehreren Impfzentren verwenden!
[Hier findest du eine Übersicht über die gruppierten Impfzentren. 
](https://github.com/iamnotturner/vaccipy/blob/master/impfzentren_gruppiert.md)

**Comment by Justin9720** [comment]
Bei mir kam Fehlermeldung Terminpaare nicht gefunden Postleitzahl ungültig weshalb???
