### ISSUE TITLE
Code anfordern

### ISSUE THREAD

**Issue by NilsB26** [iamnotturner/vaccipy#162]
Läuft jetzt alles richtig?

![grafik](https://user-images.githubusercontent.com/71553507/119706561-6bcf1680-be5a-11eb-8180-053857999b79.png)

**Comment by NilsB26** [comment]
Ich denke einfach, das sich gerade keiner erzeugen lässt, er es aber die ganze Zeit weiter versucht. Manuell kann man ja gerade auch keinen erstellen. Hat es bei dir funktioniert, wenn ja in welchem Impfzentrum?

**Comment by sinun98** [comment]
73730 funktioniert bei mir problemlos

**Comment by NilsB26** [comment]
@iamnotturner Kannst du mir vielleicht meine Frage beantworten?? Oder jemand anderes der Devs? Danke

**Comment by iamnotturner** [comment]
Ich bitte um etwas mehr Geduld. Wir geben unser bestes, jedem in kurzer Zeit zu antworten, aber es handelt sich hier um ein freiwilliges Projekt und wir haben alle noch andere Verpflichtungen, denen wir zuerst nachkommen müssen.

Welches Betriebssystem nutzt du?
Der Screenshot von dir ist leider nicht wirklich aussagekräftig. Erscheint noch eine andere Fehlermeldung beim Programmstart?

**Comment by NilsB26** [comment]
Nein, zu Beginn will er das ich den manuellen validen Cookie eingebe, das mach ich dann auch. Danach dauert es ca. 5 Sekuden bist er anfängt, es kommt aber immer die Fehlermeldung "Timeout exception raised" , kannst du damit was anfangen?

Danke für deine Hilfe.

**Comment by NilsB26** [comment]
![grafik](https://user-images.githubusercontent.com/71553507/119821494-ecd9ec80-bef2-11eb-8705-0b27401b32e9.png)

**Comment by iamnotturner** [comment]
Dazu kommt bald ein Update; bitte bis dahin warten.

**Comment by sinun98** [comment]
Probier mal eine andere Mail + Telefonnummer. Und maximal eine Instanz es ist nicht notwendig alles 4fach auszuführen, damit bannst du deine IP, Mail und Telefonnummer und brauchst dich nicht wundern wenn nichts mehr funktioniert.

**Comment by NilsB26** [comment]
@sinun98 das war eben nur ein Versuch, aber bitte erzähl mir keine Unwahrheiten und Dinge die du nicht zu 100% bestätigen kannst. Danke!

**Comment by sinun98** [comment]
https://github.com/iamnotturner/vaccipy/issues/153#issuecomment-849407813 Siehe hier....

**Comment by iamnotturner** [comment]
@NilsB26 bitte versuch es mit den vorgeschlagenen Lösungsansätzen oder zu einem späteren Zeitpunkt nochmal. 

Wenn das nicht hilft bitte den Code über den normalen Weg beim Impfterminservice generieren.
