### ISSUE TITLE
Niedersachsen hinzufügen

### ISSUE THREAD

**Issue by Runortyx** [iamnotturner/vaccipy#163]
Bitte Niedersachsen hinzufügen.

**Comment by sinun98** [comment]
Dafür ist vaccipy nicht gedacht.

**Comment by Runortyx** [comment]
Wenn ist nicht dafür gedacht ist Impftermine zu machen wofür denn dann?
Meine Bitte war halt Niedersachen bzw 26160 / 26188 hinzu zufügen damit dort auch nach Terminen gesucht werden kann.

**Comment by iamnotturner** [comment]
vaccipy unterstützt nur die Terminsuche auf https://www.impfterminservice.de/impftermine

Bitte informieren, welche Bundesländer die Buchung über den Impfterminservice anbieten.
