### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by notcimon** [iamnotturner/vaccipy#171]
Bekomme beim Ausführen der .exe folgende Fehlermeldung:
`[err] [renew_cookies]   SessionNotCreatedException exception raised - retry 2`
Diese Meldung kommt dann mehrfach wieder, jeweils mit einer nachfolgenden Ziffer am Ende. Woran kann das liegen?

**Comment by berschel** [comment]
Ich habe den Fehler auch...
```
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: 
This version of ChromeDriver only supports Chrome version 89
Current browser version is 91.0.4472.77 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
```

**Comment by NilsB26** [comment]
Eure chrome Version ist zu aktuell, ihr müsst auf 89 downgraden.

**Comment by NilsB26** [comment]
https://chrome.softwaredownload.co.in/chrome-89-0-4389

**Comment by notcimon** [comment]
Stimmt, vielen Dank!

**Comment by mpallman** [comment]
kann man stattdessen auch einfach einen aktuelleren chromedriver benutzen? also die .exe im Ordner tools austauschen? das Downgrade hat bei mir nicht richtig funktioniert, weil ich die automatischen updates einfach nicht ausgeschaltet bekommen habe...

**Comment by iamnotturner** [comment]
@mpallman ja das geht - in der Beta ist der neue Chromedriver schon drin

**Comment by FlauschR** [comment]
@NilsB26 ist dieser Link sicher? bzw. die exe datei? kenne diese homepage nicht.

**Comment by cent92** [comment]
> Bekomme beim Ausführen der .exe folgende Fehlermeldung:
> `[err] [renew_cookies] SessionNotCreatedException exception raised - retry 2`
> Diese Meldung kommt dann mehrfach wieder, jeweils mit einer nachfolgenden Ziffer am Ende. Woran kann das liegen?

das ist doch ein anderer Fehler als der von "berschel" ? 
Hier hilft weder die BETA noch das Downgrade.
Was ist hier die Lösung?

**Comment by FlauschR** [comment]
@iamnotturner was hälst du von dem link von @NilsB26  ?

**Comment by cent92** [comment]
> @mpallman ja das geht - in der Beta ist der neue Chromedriver schon drin

d.h. doch, dass es mit der BETA funktionieren müsste? Aber auch wenn ich die Beta nutze kommt dieser Fehler? Gestern hat alles noch reibungslos funktioniert.. ?

**Comment by NilsB26** [comment]
> 
> 
> @iamnotturner was hälst du von dem link von @NilsB26 ?

![grafik](https://user-images.githubusercontent.com/71553507/119821337-bbf9b780-bef2-11eb-8db1-8c4c7e4814fd.png)
Ich hab Chrome 89 dort selbst heruntergeladen.

VG
Nils

**Comment by MrMxDzn** [comment]
Habe eine fix gefunden. Auf https://chromedriver.storage.googleapis.com/index.html findet man den Chromedriver auch für die 91er Version von Chrome. Wenn man den Driver für sein System herunterlädt, und in /tools/chromedriver den vorhandenen durch den heruntergeladenen ersetzt und den neuen dementsprechend umbenennt, läuft alles auch auf Chrome 91

 #183

**Comment by iamnotturner** [comment]
Die Chromedriver-Dateien sind auch in der Beta und werden bald in den Master eingepflegt. Wir geben Bescheid wenn das Update da ist.

**Comment by iamnotturner** [comment]
Update ist nun da, bitte [neuen Release hier downloaden](https://github.com/iamnotturner/vaccipy#downloads).
Gebt uns bitte eine kurze Rückmeldung wies läuft.

**Comment by JuliusJacobitz** [comment]
[neuer release](https://github.com/iamnotturner/vaccipy/releases/tag/v1.0.2) jetzt da !
