### ISSUE TITLE
keine Mail trotz erfolgreicher Impfcode-Anfrage

### ISSUE THREAD

**Issue by gv-rgb** [iamnotturner/vaccipy#174]
![image](https://user-images.githubusercontent.com/84865605/119811382-5227e080-bee7-11eb-8da3-6116944e9a4b.png)

Ich erhalte keine Mail trotz erfolgreicher Impfcode-Anfrage? Woran könnte das liegen?
(Mail-Adresse habe ich mehrfach überprüft)

**Comment by iamnotturner** [comment]
spam? Kommt vielleicht noch

**Comment by gv-rgb** [comment]
Im Spam ist auch nichts. Alles klar, dann mal abwarten. Ich gebe Rückmeldung

**Comment by halcyon44** [comment]
Ich entschuldige mich schon mal für die blöde Frage, aber welche Version ist eigentlich die Beta Version?
Wenn ich auf die Seite mit dem neuesten Release gehe, finde ich dort Version v1.0.0. und dann v0.1.1-lw.

Und momentan benutze ich die Version, die ich vor rund einer Woche gedownloadet habe. Die aktuelle Version sieht etwas anders aus. Ist das egal, ob ich die ältere Version benutze oder die aktuelle Version? Die neue chromedriver Datei habe ich selbst in den Ordner kopiert. Daher scheinen beide zu funktionieren.

**Comment by sinun98** [comment]
> ![image](https://user-images.githubusercontent.com/84865605/119811382-5227e080-bee7-11eb-8da3-6116944e9a4b.png)
> 
> Ich erhalte keine Mail trotz erfolgreicher Impfcode-Anfrage? Woran könnte das liegen?
> (Mail-Adresse habe ich mehrfach überprüft)

Probier am besten mal eine andere Mail. Darauf achten das alles in Kleinbuchstaben eingegeben ist und eine neue Handynummer.
