### ISSUE TITLE
Kein Impfzentrum gefunden bei Eingabe mehrerer PLZs

### ISSUE THREAD

**Issue by SaschaH1** [iamnotturner/vaccipy#176]
Hallo. Tolle Idee, diese App.
Gebe ich mehrere PLZs ein, wird kein Impfzentrum gefunden. Gebe ich die PLZs einzeln ein, wird das jeweilige Impfzentrum gefunden.
Möglicherweise wird die PLZ-Zeichenkette nicht richtig aufgesplittet. (?)
Schade, dass in NRW alle Impfzentren "down" sind....
VG Sascha

**Comment by iamnotturner** [comment]
Hallo Sascha, wie gibst du welche PLZs ein?

**Comment by Danko1972** [comment]
Hallo Ihr beiden, 

Bei mir ging es auch nicht. (Eingabe wie im Beispiel von vaccipy) Aber auch eine einzelne Plz hat nicht funktioniert. (err) (*TeER1) Kein Impfzentrum zu eingetragener PLZ verfügbar. 

VG
Daniel

**Comment by iamnotturner** [comment]
Welche PLZ's waren das konkret?

**Comment by Danko1972** [comment]
Die Einzelne war 40474 (Düsseldorfer Impfzentrum)... Die anderen die PLZ kamen von dieser Liste: https://www.mags.nrw/coronavirus-impfzentren-nrw

**Comment by sinun98** [comment]
Unter #116 wird beschrieben welche Impfzentren unterstützt werden. Düsseldorf ist nicht dabei.

**Comment by Danko1972** [comment]
Sorry, das hatte ich übersehen. Vielen Dank für die Info! ...und Eure Arbeit! :)

**Comment by SaschaH1** [comment]
Ich hatte die PLZs dann doch falsch getrennt.  Sorry, dass hatte ich erste jetzt bemerkt, als ich einen Screenshot hochladen wollte.
VG.Sascha
