### ISSUE TITLE
SessionNotCreatedExeption

### ISSUE THREAD

**Issue by BoxFoxGames** [iamnotturner/vaccipy#177]
Folgendes Problem:
![vaccipy_error](https://user-images.githubusercontent.com/48164012/119815604-04fa3d80-beec-11eb-9f9b-bee1890bbb87.png)

Augenscheinlich scheinen am Ende sogar Anfragen gesendet zu werden, allerdings tritt dieses Verhalten auch auf wenn Chrome gar nicht installiert ist.

Ich konnte leider noch nicht testen wie es mit Chrome 89 aussehen würde da man sehr schlecht an legacy Chrome-Versionen rankommt.

**Comment by TheN0x21** [comment]
Hatte diesen Fehler heute auch, nachdem ich chrome deinstalliert und die Version 89 installiert habe, wurde das Problem gefixt bzw. kam die Meldung nicht mehr.

**Comment by BoxFoxGames** [comment]
Super danke! Auch für den Link :)
