### ISSUE TITLE
Fehlermeldung bei Impf-Code Generierung

### ISSUE THREAD

**Issue by Danko1972** [iamnotturner/vaccipy#178]
Nach Eingabe meiner Daten (Email, Telefon), Impfzentren freigelassen (Vaccipy hat hier Nordrhein ausgewählt) erhalte ich die Fehlermeldung: (err)(Impfstoffe_laden) JSON parsing exception IP gebannt oder Webseite down. 

VG
Daniel

**Comment by iamnotturner** [comment]
Nordrhein wird nicht unterstützt vom Impfterminservice
