### ISSUE TITLE
Fehlermeldung beim Installieren Code 5/Code 2

### ISSUE THREAD

**Issue by LaurenzMar** [iamnotturner/vaccipy#180]
Hallo zusammen,

Nach download des installers gibt es den Fehlercode 5 beim installieren: 'Fehler beim Umbenennen einer Datei im Ziel-Ordner MoveFile schlug fehl; Code5. Zugriff verweigert'.
Hat jemand eine Idee, warum der Installer nicht durchläuft?
Vor den Versuchen zu Installieren habe ich sichergestellt, dass alte Dateien gelöst wurden. 

Liebe Grüße,

**Comment by iamnotturner** [comment]
Probiers mal als Administrator auszuführen

**Comment by LaurenzMar** [comment]
Das habe ich auch ausprobiert, hat leider nicht geklappt. Ich habe das zip nun über releases->assets herunter geladen, was anschließend einwandfrei funktioniert hat. Die Datei die hinter dem Windows Icon in der Rubrik Download hinterlegt ist vielleicht nicht identisch zu der Version unter releases -> assets

**Comment by LaurenzMar** [comment]
Ja unter diesem Link funktioniert der Download. 
Via https://github.com/iamnotturner/vaccipy#downloads führte es bei mir zu Fehlermeldungen.

**Comment by iamnotturner** [comment]
sollte jetzt gehen, kannst dus nochmal testen?

**Comment by LaurenzMar** [comment]
ich bekomme die Fehlermeldung leider immer noch, selbst wenn ich Administratorenrechte verwende. 
Ich kann es mir nur dadurch erklären, dass ich über den release die .zip runtergeladen habe, über den link jedoch nur die .exe.

**Comment by Floskinner** [comment]
@LaurenzMar kann es sein das du den Link vom Beta-Branch verwendet hast?
Also jetzt beim 2. Versuch

Weil dort wurden die Links bei den Windows / Unix Symbolen noch nicht angepasst

**Comment by iamnotturner** [comment]
Download-URL für Windows-Zip mit #194 zu README hinzugefügt
