### ISSUE TITLE
Frage: Codegenerierung hier, aber online keine!!

### ISSUE THREAD

**Issue by erwillnicht** [iamnotturner/vaccipy#181]
Hi hab da kurz ne Frage:

Online wird gesagt das keine Termine verfügbar sind (kein Vermittlungscode in der Altersgruppe). Das Programm generiert einen. Wie ist das möglich? Und gibt's da keine Probleme vor Ort im impfzentrum?

**Comment by iamnotturner** [comment]
Ja das ist richtig. Wir überspringen die Website und fragen den Code direkt an. Der Code ist 100 % valide. VG
