### ISSUE TITLE
Englische Windows-Version führt zu admin-Problemen

### ISSUE THREAD

**Issue by Phil-Schwarz** [iamnotturner/vaccipy#184]
Habe Windows auf Englisch installiert und nach Installation kann der Ordner nicht verändert werden, da Zugriff durch VORDEFINIERT\Administratoren gebraucht wird, was es auf dem Rechner nicht gibt. Daher kann auch nicht deinstalliert werden.
Issue ist aufgefallen weil ich die Dateien, die durch mein anti-virus geblockt waren, wieder herstellen wollte.

**Comment by iamnotturner** [comment]
Ich nehme an, dass davon nicht so viele betroffen sind und schließe das Issue erstmal. Kannst du es direkt über Python ausführen?

**Comment by Phil-Schwarz** [comment]
Über die installer exe nicht möglich, main.py kann ich zwar ausführen, führt aber zu ModuleNotFoundError: No module named 'plyer'.
Hab ne neue Installation von 3.9 dafür installiert aber scheint nicht zu funktionieren.

**Comment by Phil-Schwarz** [comment]
Sollte vielleicht anmerken dass ich den Code als Zip gedownloaded hab und der wahrscheinlich versucht fehlende directories zu erstellen.

**Comment by iamnotturner** [comment]
Vor der Ausführung müsstest du noch mit Pip die notwendigen Module installieren

https://github.com/iamnotturner/vaccipy#requirements
