### ISSUE TITLE
Zweiter Release für Beta

### ISSUE THREAD

**Issue by bonxz** [iamnotturner/vaccipy#191]
Nur als Tipp. Ihr solltet auch regelmäßig releases pushen jetzt wo ihr es mit implentiert habt auf Github und nicht nur die master branch updaten, sonst hat das ja keinen Zweck. Viele User die neu Aufmerksam werden auf dieses Projekt laden auch nur die Version vom Release direkt.  Und evenutell sogar ein Zweit Release für die Beta Branch mit einbauen?

**Comment by iamnotturner** [comment]
Hi! Danke für den Tipp, in den Master werden nur README-Änderungen gepusht. Ansonsten landet alles erstmal in der Beta und wenn die erfolgreich getestet wurde wird ein neuer Release erstellt. 

Über einen zweiten Release für die Beta nachzudenken wäre eine Option, damit könnten wir auch schneller Tests durchführen. Bin da auf die schnelle überfragt, hast du mit 2 Releases in einem Projekt bereits Erfahrung?

**Comment by Sylwuscha** [comment]
![grafik](https://user-images.githubusercontent.com/84845174/119984960-57a62900-bfc2-11eb-83d5-add9ffa2c6f2.png)

Code ließ sich jetzt ohne Probleme und ohne manuelle Cookies generieren. 

Aber jetzt können keine Terminpaare geladen werden - Fehler

**Comment by iamnotturner** [comment]
@Sylwuscha siehe hier https://github.com/iamnotturner/vaccipy/issues/116#issuecomment-848690301 

Bitte nicht einfach in anderen Beiträgen kommentieren und zuerst in den FAQ's und geschlossenen Issues schauen, ob die Frage bereits beantwortet wurde. Danke :-)

**Comment by Sylwuscha** [comment]
Als Laie ist es sooo schwierig, hier überhaupt durchzublicken. Deshalb schreibe ich wieder hier, weil ich nichts Passenderes finde. Dieses, was bei euch "Release" heißt und für mich "Update" bedeutet, hat zumindest geholfen, Codes zu generieren. Mit den Codes kann ich aber leider keine Terminpaare buchen (Fehler 401). Wenn ich nachlese, was der Fehler 401 bedeutet - und zwar, dass Impfzentrum und Code nicht zusammenpassen - dann hat mich das Release doch nicht weitergebracht, denn die Codes funktionieren ja nicht für mein Impfzentrum :-(

Verschiebt den Kommentar gern dorthin, wo er nach eurem Wissen hingehört. Die Themen überschneiden sich ja

**Comment by JuliusJacobitz** [comment]
Wird im Moment über Prereleases geregelt
