### ISSUE TITLE
Start der Suche ohne Interaktion nicht möglich

### ISSUE THREAD

**Issue by sleeksorrow** [iamnotturner/vaccipy#196]
Es scheint keinen Weg zu geben, mit gespeicherten Kontaktdaten die Suche zu starten, ohne wenigstens mit einmal "y" zu bestätigen, die Kontaktdaten zu laden. Mein Wunsch wäre es aber, ohne persönliche Interaktion einfach loszulegen mit der Suche.

Vorschläge:
- Extra Option wie etwa "--non-interactive"
- Bei Benutzung von "-f" diese Abfrage überspringen, denn diese Option sagt ja schon explizit aus, dass hier Kontaktdaten benutzt werden sollen, also will der User sicher auch, dass sie geladen werden.

**Comment by mmhh1910** [comment]
python3 main.py search -r

**Comment by sinun98** [comment]
Du kannst unter erweiterte Einstellungen read-only aktiveren.
