### ISSUE TITLE
[Frage] Impfterminvergabe ab 7. Juni

### ISSUE THREAD

**Issue by ralfescher** [iamnotturner/vaccipy#197]
Hallo!

Weiß bereits jemand, wie die elektronische Impfterminvergabe für Impfzentren ab dem 7. Juni ablaufen wird?

Eine Prüfung auf den Anspruch auf eine Corona-Schutzimpfung wäre dann ja hinfällig,
andererseits spielt die Altersprüfung eine Rolle für die Vergabe des Impfmittels.

**Comment by JuliusJacobitz** [comment]
Hi @ralfescher. Ich kann mir gut vorstellen, dass der Ablauf gleich bleibt. Aktuell muss jeder Nutzer von [impfterminservice.de](impfterminservice.de) im Voraus prüfen, ob er/sie impfberechtigt ist. Da der Vermittlungscode im Moment nur abhängig vom Alter ist denke ich, dass diese Abfrage bestehen bleibt und sich nicht all zu viel ändern wird. Hoffe ich konnte dir helfen :)
