### ISSUE TITLE
Login und cookie Probleme

### ISSUE THREAD

**Issue by yigitdev** [iamnotturner/vaccipy#2]
Hallo,

leider funktioniert das Login nicht. Ich bekomme hier eine "401 Unauthorized" Meldung.
Außerdem scheint dass setzten der cookies ebenfalls nicht zu funktioniern, hier bekomme ich eine 429.

lg

**Comment by iamnotturner** [comment]
Hi, ich habe das Script eben bei mir ausgeführt und es funktioniert, also liegt die Fehlerquelle wahrscheinlich irgendwo auf deiner Seite.

Ich nehme an du bist temporär gebannt, wahrscheinlich durch zu viele Versuche, aber dennoch die Nachfrage:
Ist der Impf-Code für das entsprechende Impf-Zentrum ausgestellt worden? Die Codes sind meistens (oder immer?) nur für das Impfzentrum gültig, für das sie generiert wurden. Melde dich mal im Browser an und schaue, ob du dich beim entsprechenden IZ einloggen kannst.

Zurück zum 429 bei der Cookie-Erstellung: Kannst du mir sagen, an welcher Stelle du den Status-Code erhälst?
Meine Vermutung ist, dass du temporär von Akamai gebannt wurdest. Das kommt vor, wenn man sich in zu kurzen abständen versucht einzuloggen, oder nach Terminen sucht (deshalb ist der Default-Delay auch bei 60 Sekunden). Du wirst in der Regel nach 10-20 Minuten wieder entbant. Warte einfach kurz, probiere ob du dich in der Konstellation im Browser anmelden kannst und probiere es anschließend nochmal mit dem Script.

VG

**Comment by yigitdev** [comment]
Mit dem Impf-Code kann ich im Browser anmelden, da gibt es kein problem.
Wenn ich vaccipy starte erhalte ich nach der Generierung des Cookie die Meldung "Einlogen mit Code nicht möglich!".
Anschließend öffnet er den Browser neu und versucht nochmal ein Cookie zu holen und dass wiederholt sich dauernt.

**Comment by yigitdev** [comment]
Habe es jetzt unter Windows 10 probiert, hier hat es funktioniert. Scheint ein problem unter Linux (Debian) zu sein.

**Comment by iamnotturner** [comment]
vaccipy unterstützt nur Desktop-OS, läuft dein Linux als Desktop oder CLI?

**Comment by yigitdev** [comment]
Ja, habe ein Debian Buster xfce desktop auf einen OrangePi Lite aufgesetzt.

**Comment by iamnotturner** [comment]
Ich kenne mich mit Debian Buster nicht aus, aber du könntest mal probieren einen anderen Chromedriver zu verwenden:
https://packages.debian.org/buster/chromium-driver

**Comment by yigitdev** [comment]
Ich habe bereits diesen chromium-driver installiert. Da meine Hardware auf ARM basiert, habe ich die mit vaccipy mitgelieferten Treiber nicht benutzen. Habe jetzt noch weitere Tests durchgeführt und ich konnte es durch klicken auf cookies akzeptieren einmal laufen lassen. 
Seit heute Mittag ist es jetzt aber so, dass ich auch unter Windows10 den code 429 bekomme. Aber manuell über den Browser gibt es keine Probleme. Wurde da was verändert?

**Comment by iamnotturner** [comment]
Nein, da hat sich nichts geändert, das ist die Protection. 

Die Cookie-Generierung wurde im letzten Commit um ein paar Klicks und das Eintragen des Codes erweitert. Damit haben wir in den letzten Tagen langfristig gute Erfahrungen gemacht und es sollte länger halten. Bei mir läuft es ohne Probleme für mehrere Stunden.

**Comment by yigitdev** [comment]
OK hast recht wurde Anscheinnend gebannt, heute hat es wieder funktioniert. Obwohl ich nach dem Problem über 30min gewartet hatte, ging es gestern nicht. Scheint so als würde die auch für längere Zeit bannen.

Vielen Dank für die Mühe.

VG
