### ISSUE TITLE
Webdriverexception Error

### ISSUE THREAD

**Issue by bonxz** [iamnotturner/vaccipy#20]
![fehler](https://user-images.githubusercontent.com/61289944/117042419-3ed08d80-ad0c-11eb-9eaf-22547bf2b1dd.png)

Was soll ich tun? Finde den fehler nicht.

**Comment by iamnotturner** [comment]
Hi, führst das Script mit Python aus? Ansonsten mal die .exe probieren, oder umgekehrt es mit python ausführen.

**Comment by bonxz** [comment]
Problem gelöst. Hatte kein Chrome installiert. 👍🏼 

Aber noch was anderes. Habe beides getestet. Die exe und das Script. Exe läuft einwandfrei. Beim python Script werde ich immer wieder aufgefordert alle Daten einzutippen obwohl die kontaktdaten Datei existiert.

**Comment by iamnotturner** [comment]
Gute Info, ich wusste nicht, dass Chrome installiert sein muss. Dachte, dass die Chromedriver ausreichen.

Liegt die `kontaktdaten.json` im selben Ordner wie die `main.py`?

**Comment by bonxz** [comment]
> Liegt die `kontaktdaten.json` im selben Ordner wie die `main.py`?

Ja liegt sie. Wurde ja automatisch erstellt mit der main,py. Aber wenn ichs zu mache und wieder main.py öffne kommt nicht die Abfrage o ich die Datei laden will sondern will sie neu anlegen. Also fragt wieder alles ab.

**Comment by iamnotturner** [comment]
Wie führst du die `main.py` aus? Damit die Pfade funktionieren, musst du dich, bspw mit der Powershell, im vaccipy-Ordner befinden und dann ausführen.

**Comment by JuliusJacobitz** [comment]
@bonxz
Ich konnte das Problem nicht reproduzieren. Bitte teste ob du den aktuellen master-branch gepulled hast und dich im vaccipy ordner befindest. Dort musst du die ```main.py``` ausführen. Versuche vlt noch die ```kontaktdaten.json``` zu löschen.
```shell
python main.py
```
Ich schließe dieses Issue mit dem Comment. Wenn es weiterhin auftritt, bitte ein neues öffnen :)

**Comment by bonxz** [comment]
Ja hat sich auch erledigt. Man muss Python mit Adminrechte starten sonst "sieht" er die Datei nicht.

**Comment by iamnotturner** [comment]
> Ja hat sich auch erledigt. Man muss Python mit Adminrechte starten sonst "sieht" er die Datei nicht.

😵‍💫
