### ISSUE TITLE
WebDriverException beim Terminbuchen, obwohl Cookie erneuern funktioniert.

### ISSUE THREAD

**Issue by ilteen** [iamnotturner/vaccipy#200]
Ich habe vaccipy auf einem Raspberry Pi 4 laufen, chromedriver scheint zu funktionieren, weil die Cookies erfolgreich neu geladen werden. 
Aber wenn Termine gefunden werden, und die Bot protection greift, dann funktioniert das Buchen per webdriver nicht (siehe screenshots). 
VACCIPY_CHROMEDRIVER = "/usr/bin/chromedriver" als Umgebungsvariable ist definiert, aber sollte ja nicht daran liegen, wenn es bei den Cookies klappt. 
Hat jemand eine Idee, was das Problem sein könnte?

(chromedriver installiert über https://ivanderevianko.com/2020/01/selenium-chromedriver-for-raspberrypi)

<img width="604" alt="Bildschirmfoto 2021-05-28 um 11 05 03" src="https://user-images.githubusercontent.com/35779536/119959754-97f6ae80-bfa4-11eb-9826-1a3b8b557e90.png">
<img width="281" alt="Bildschirmfoto 2021-05-28 um 11 05 14" src="https://user-images.githubusercontent.com/35779536/119959766-9af19f00-bfa4-11eb-8a15-a55fa0feefca.png">

**Comment by iamnotturner** [comment]
ich nehme an deine Raspi läuft ohne Desktop, oder?

**Comment by ilteen** [comment]
Ja. stimmt, das könnte natürlich daran liegen, wenn chromium nicht headless ausgeführt wird. Gibt es denn eine Möglichkeit, das zu beheben, zB. VNC virtual desktop?

**Comment by sinun98** [comment]
Speziell in der neusten Version wird headless aktuell nicht mehr unterstützt, da die Cookies nicht valide sind. Mit der neusten Version sollte es nun kaum mehr zu Selenium Buchungen kommen. Allerdings werden auch hierfür die Cookies mit dem Browser und nicht headless erzeugt. Am besten du speicherst dir den Link schon ab das du ihn sofort bereit hast sollte ein Termin gefunden werden. Format ist https://**Gruppennummer**-iz.impfterminservice.de/impftermine/suche/**XXXX-XXXX-XXXX**/**PLZ**

**Comment by ralfescher** [comment]
Bei mir hat die automatische Buchung geklappt (Raspberry Pi, Headless).

**Comment by ilteen** [comment]
@sinun98 wenn in der neuesten Version headless sowieso nicht mehr unterstützt wird, kann man den issue schließen. Aber was ist gemeint mit "da die Cookies nicht valide sind" (bei headless). 
Ich verwende die version 1.0.0 headless und bei mir funktioniert das mit den Cookies einwandfrei. 

"Mit der neusten Version sollte es nun kaum mehr zu Selenium Buchungen kommen" - also sollte ich einfach mal die Version aktualisieren, dann erhöht sich die Wahrscheinlichkeit, dass Selenium gar nicht gebraucht wird für's Buchen?

@ralfescher Ich habe auch einen Termin mit headless bekommen, danach habe ich das Skript aber noch für einen Verwandten laufen lassen, und hat die bot detection immer eine Buchung verhindert.

**Comment by sinun98** [comment]
> @sinun98 wenn in der neuesten Version headless sowieso nicht mehr unterstützt wird, kann man den issue schließen. Aber was ist gemeint mit "da die Cookies nicht valide sind" (bei headless)?
> Ich verwende die version 1.0.0 headless und bei mir funktioniert das mit den Cookies einwandfrei.
> 
> "Mit der neusten Version sollte es nun kaum mehr zu Selenium Buchungen kommen" - also sollte ich einfach mal die Version aktualisieren, dann erhöht sich die Wahrscheinlichkeit, dass Selenium gar nicht gebraucht wird für's Buchen?
> 
> @ralfescher Ich habe auch einen Termin mit headless bekommen, danach habe ich das Skript aber noch für einen Verwandten laufen lassen, und hat die bot detection immer eine Buchung verhindert.

Mit valide Cookies meine ich das die Anfrage nicht von der Botprotection geblockt wird.

"Mit der neusten Version sollte es nun kaum mehr zu Selenium Buchungen kommen" Funktioniert aber nur wenn du auch den Browser ausführen kannst. Mit dem Browser (nicht headless) werden valide Cookies erzeugt um nicht geblockt zu werden.

**Comment by ilteen** [comment]
@sinun98 Alles klar, vielen Dank! Dann schließe ich den den issue als "headless nicht vollständig unterstützt".

**Comment by ralfescher** [comment]
Nachtrag: Terminsuche funktioniert noch, bei der Suche nach einem Vermittlungscode bekomme ich ebenfalls die obigen Fehlermeldungen.

**Comment by sinun98** [comment]
Die Terminsuche ist noch im ersten Schritt headless, daher funktioniert es. Schlägt dann die Terminbuchung durch einen Block fehl werden Cookies mit dem Browser generiert.
