### ISSUE TITLE
Botprotection - manuelle Cookies werden nicht akzeptiert

### ISSUE THREAD

**Issue by hardy2206** [iamnotturner/vaccipy#203]
Ersteinmal danke für eure Arbeit!

Ich lasse vaccipy auf einer VM mit Ubuntu laufen. Beim Code erstellen kommt immer die Meldung Botprotection. Das manuelle hinzufügen der Cookies, lt. FAQ, funktioniert auch nicht. Gleiche Fehlermeldung, egal wie viel ich von dem Cookieeintrag kopiere. Browser ist schon mehrere Stunden mit der Seite geöffnet.

**Comment by hardy2206** [comment]
Leider auch nicht erfolgreich. Es öffnet sich der Chrome und die Meldung, dass ich Elemente anklicken soll. Dann wieder alles von vorn in einer anscheinenden Endlosschleife.

**Comment by iamnotturner** [comment]
Es kann sein, dass deine IP geflaggt ist. Am besten mal auf einem anderen Gerät und in einem anderen Netzwerk probieren.

**Comment by hardy2206** [comment]
Jetzt funktioniert es. Warum - keine Ahnung.
