### ISSUE TITLE
ChromeDriver executable may have wrong permissions

### ISSUE THREAD

**Issue by JasonPy** [iamnotturner/vaccipy#204]
![Screenshot from 2021-05-28 12-41-25](https://user-images.githubusercontent.com/26459555/119972067-0ee67400-bfb2-11eb-9a73-f26f489942a6.png)

Hallo zusammen!

Bei mir funktioniert seit heute Vormittag das Cookie-Generieren bei der Terminsuche nicht mehr. Zuvor hatte die Suche funkioniert. Einen Screenshot der Fehlermeldung habe ich angehängt. 

Danke für eure Hilfe

**Comment by iamnotturner** [comment]
hey, dazu ist ein PR schon offen, der noch gemerged werden muss.
#201 du kannst dir hier den Chromedriver schonmal laden

**Comment by iamnotturner** [comment]
Ist nun auch im neusten Release
