### ISSUE TITLE
Automatisierte Terminbuchung fehlgeschlagen

### ISSUE THREAD

**Issue by Justin9720** [iamnotturner/vaccipy#207]

**Comment by Justin9720** [comment]
![image](https://user-images.githubusercontent.com/84766002/119980481-9e912000-bfbc-11eb-8afd-c9c70e7c59db.jpeg)

Zuvor hat es bei einem Termin geklappt aber jetzt nicht woran kann das liegen??

**Comment by sinun98** [comment]
Bitte neuste Version downloaden

**Comment by Justin9720** [comment]
X86 die aktuellste??

**Comment by sinun98** [comment]
https://github.com/iamnotturner/vaccipy/releases v.1.0.3
