### ISSUE TITLE
Requirments.txt outdated

### ISSUE THREAD

**Issue by TRojaner2013** [iamnotturner/vaccipy#209]
Ich habe versucht im beta-branch die requirments wie folgt in meiner venv zu installieren:

- pip3 install -r requirments.txt

Dabei tritt folgender Fehler auf:

- requests 2.25.1 requires idna<3,>=2.5, but you'll have idna 3.1 which is incompatible.

Quick fix durch Anpassen der requirments.txt:

- idna>=2.5,<3

Ich erstelle gleich noch ein Pull-request, so dass der Fehler direkt gefixt werden kann, wenn ihr ihn nachstellen könnt.

**Comment by iamnotturner** [comment]
Das wäre super, danke
