### ISSUE TITLE
Wartezeit-Einstellung retry-sec wird nicht übernommen

### ISSUE THREAD

**Issue by hardy2206** [iamnotturner/vaccipy#211]
Ich habe in den erweiterten Einstellungen den Wert retry-sec mal auf 10 und mal auf 1 gesetzt. Wartezeit bleibt anschließend bei default-Wert.
Abfrage mit ... search -f name.json
Die Datei name.json wurde vorher erstellt.

**Comment by Sars-Cov-2-Antigen** [comment]
Womöglich gibt es hier eine Mindestzeit, die man nicht unterschreiten darf. Warum willst Du denn überhaupt jede Sekunde abfragen? So wird der Bot doch umso schneller erkannt. 
Ich würde nichts unter 30 Sekunden einstellen.

**Comment by hardy2206** [comment]
Bei Abfragen mit mehreren Impfzentren wird die Wartezeit auch zwischen den einzelnen Impfzentren angesetzt. So verlängert sich die Wartezeit für jedes Impfzentrum deutlich. Hierfür wollte ich die Zeit verkürzen, so dass die Wartezeit je Impfzentrum nicht z.b. 5 Minuten beträgt. 
Die Einstellung mit einer Sekunde habe ich nur kurz zum Testen gesetzt, um zu sehen, ob es funktioniert.

**Comment by Sars-Cov-2-Antigen** [comment]
Ist nur ein Tipp, aber ich würde gar nicht bei so vielen Zentren gleichzeitig abfragen. Habe in der Regel nur ein einziges, in einem Fall 3 eingestellt, das reicht völlig aus. Und bei der Abfrage an 3 Zentren habe ich einen 30 Sekunden-Abstand eingestellt, also 1 1/2 Minuten zwischen den Abfragen beim gleichen Zentrum.
