### ISSUE TITLE
WebDriverException

### ISSUE THREAD

**Issue by RedStylzZ** [iamnotturner/vaccipy#212]
Auf Windows funktioniert das Programm einwandfrei, jedoch auf Ubuntu und ParrotOS kommt jedes Mal diese Fehlermeldung:

![image](https://user-images.githubusercontent.com/19490975/120028358-e03dbd00-bff4-11eb-9c70-1d52d29bf107.png)

**Comment by RedStylzZ** [comment]
Nach dem Installieren dieser Pakete kam eine neue Fehlermeldung:
libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev

![image](https://user-images.githubusercontent.com/19490975/120029965-23992b00-bff7-11eb-8982-86f8eaca7e20.png)

**Comment by iamnotturner** [comment]
Hi, hast du Chrome installiert?

**Comment by RedStylzZ** [comment]
Hey, ja Chromium ist installiert

**Comment by RedStylzZ** [comment]
Es war wohl trotz den Fehlermeldungen möglich einen Termin zu bekommen, auch wenn im Terminal keine Bestätigung kam.

**Comment by iamnotturner** [comment]
Also hat es trotzdem funktioniert?

**Comment by RedStylzZ** [comment]
Ja, zumindest wurde eine Bestätigungsmail gesendet. Vielen Dank für die Bereitstellung des Programmes!

**Comment by iamnotturner** [comment]
Wir helfen wo wir können 😁
