### ISSUE TITLE
Codes für verschiedene Gruppen automatisch anfragen

### ISSUE THREAD

**Issue by Klobbinger** [iamnotturner/vaccipy#213]
Erst mal Danke für das letzte Update, das Cookie Problem ist gelöst! Wo kann man dir nen Kaffee spendieren?

Nun zu meinem Feature Request: Wenn man in Impfzentren mehrerer Gruppen suchen möchte muss man sich für jede Gruppe einen Code abrufen und dann umständlich die kontaktdate.json umbenennen und mehrere Instanzen des Skripts laufen lassen. Es wäre cool wenn das Skript erkennen würde, wenn PLZs aus verschiedenen Gruppen dabei sind und für diese dann entsprechend separat die Codes anfragen würde.

**Comment by derBobby** [comment]
My 5 Cent: Haltet das Tool einfach. Ich als IT'ler komme mit mehr Komplexität klar, andere nicht.

**Comment by Klobbinger** [comment]
Darum ja mein Voraschlag. Aktuell ist es nicht ganz eindeutig, wenn man nicht genau liest trägt man einfach alle PLZ ein die einem passen. Der abgerufene Code passt aber nur zu einer dieser Gruppen und man weiß auch nicht zu welcher. (Was soll das überhaupt mit dem Code, der Sinn erschlißt sich mir nicht). 

Stimme Dir aber in so weit zu, dass es ein "nice to have" wäre.

**Comment by iamnotturner** [comment]
> Erst mal Danke für das letzte Update, das Cookie Problem ist gelöst! Wo kann man dir nen Kaffee spendieren?

Wenn du spenden willst, findest du in der README unten einen Link zu unserer Sammelaktion bei Ärzte ohne Grenzen 😊

> Nun zu meinem Feature Request: Wenn man in Impfzentren mehrerer Gruppen suchen möchte muss man sich für jede Gruppe einen Code abrufen und dann umständlich die kontaktdate.json umbenennen und mehrere Instanzen des Skripts laufen lassen. Es wäre cool wenn das Skript erkennen würde, wenn PLZs aus verschiedenen Gruppen dabei sind und für diese dann entsprechend separat die Codes anfragen würde.

Danke für den Vorschlag, aber solche Features lassen wir bewusst aus. Wenn man parallel in X Zentren suchen will, sollte das mit einem gewissen Aufwand verbunden sein.

**Comment by Klobbinger** [comment]
> Wenn du spenden willst, findest du in der README unten einen Link zu unserer Sammelaktion bei Ärzte ohne Grenzen 
Das ist noch besser als ein Kaffee ;)

> Danke für den Vorschlag, aber solche Features lassen wir bewusst aus. Wenn man parallel in X Zentren suchen will, sollte das mit einem gewissen Aufwand verbunden sein.
Gut, kann ich auch verstehen. Danke für die Rückmeldung!

**Comment by theonlybebu** [comment]
Hey, gibt es denn die Möglichkeit innerhalb einer Gruppe mehrere Zentren anzugeben? Wenn ja wie sieht hier die korrekte Syntax aus? Bei dem Versuch mehrere PLZs anzugeben erhalte ich die folgende Fehlermeldung
2021-05-28 23:06:13.393   impfterminservice   [inf] [*M9MF | 73730,70629]   102 Impfzentren verfügbar
2021-05-28 23:06:13.393   impfterminservice   [err] [*M9MF | 73730,70629]   Kein Impfzentrum zu eingetragenen PLZ's verfügbar 
Vielen Dank

**Comment by Klobbinger** [comment]
@theonlybebu nach dem Komma ein Leerzeichen, dann sollte es gehen. Alternativ kannst du auch die kontakdaten.json Datei mit dem Notepad manuell bearbeiten. Du findest die datei in Programme\vaccipy\data

So sieht das Format in der .json aus:

```
{
    "plz_impfzentren": [
        "71065",
        "71636",
        "74081",
        "70629",
        "70376",
        "71334",
        "70174"
    ],
    "kontakt": {
        "anrede": "Herr",
        "vorname": "",
        "nachname": "",
        "strasse": "",
        "hausnummer": "",
        "plz": "",
        "ort": "",
        "phone": "",
        "notificationChannel": "email",
        "notificationReceiver": ""
    }
}
```

**Comment by theonlybebu** [comment]
@Klobbinger  vielen Dank. Das mit dem Leerzeichen nach dem Komma hatte ich schon getestet. 
Da bekomme ich eine ähnliche Fehlermeldung 
 021-05-28 23:26:06.615   impfterminservice   [err] [*M9MF | 73730, 70629]   Kein Impfzentrum zu eingetragenen PLZ's verfügbar.

Aber das von dir vorgeschlagene Format mit:
"XXX", 
"XXX" 
funktioniert
