### ISSUE TITLE
Info zu langen Timeouts

### ISSUE THREAD

**Issue by TRojaner2013** [iamnotturner/vaccipy#218]
Bei der Terminbuchung ist mir aufgefallen, dass manche Timeouts sehr hoch angesetzt sind.
So ist beim Warteraum in der its.py l.217ff ein Timeout von einer Stunde vorgesehen:

```
        # Warteraum-Support: Timeout auf 1 Stunde
        button_xpath = ".//html/body/app-root/div/div/div/div[2]/div[2]/div/div[1]/a"
        button = WebDriverWait(driver, 60 * 60).until(EC.element_to_be_clickable((By.XPATH, button_xpath)))
```

Bei mir ist es tatsächlich schon öfters vorgekommen, dass der Timeout auch abgewartet wird, wie in diesem Screenshot:

![timeout_warteraum](https://user-images.githubusercontent.com/10894083/120066870-e07f9c00-c078-11eb-882e-660ff15c85c1.PNG)

Bevor ich in den Code geschaut habe, dacht ich immer, dass sich vaccipy aufgehangen hat.
Aus Rücksicht auf die Benutzerfreundlichkeit würde ich daher vorschlagen, dass eine Ausgabe über die Timeous an den Benutzer erfolgt. Also z. B. eine kurze Info wie "Im Warteraum, max. Wartezeit: 1h...", sofern die Timeouts im Bereich von mehreren Minuten liegen. So hat der Benutzer eine Chance zu erkennen, das das Verhalten gewollt ist und es sich nicht um einen Fehler handelt.

Ich kann bei Interesse gerne die entsprechenden Stellen überarbeiten und eine kurze Info ausgeben.
Alternativ kann natürlich auch der Timeout überarbeitet werden.

**Comment by iamnotturner** [comment]
sollte gefixt sein mit #278
