### ISSUE TITLE
New Feature: Klarname zusätzlich zu PLZ

### ISSUE THREAD

**Issue by andoorius** [iamnotturner/vaccipy#222]
Ich könnte mir vorstellen, statt der PLZ der Impfzentren eine Tabelle mit Checkboxes und den Klarnamen zu haben. Sind natürlich nicht unendlich viele verschiedene aber an langen Tagen sind die PLZs doch etwas sperrig.

**Comment by iamnotturner** [comment]
Hey, kannst du mal ein Beispiel machen?

**Comment by andoorius** [comment]
Sorry war etwas knapp ausgedrückt.
Also wenn ich einen Code oder Termin in Stuttgart suche, muss ich irgendwo eine Liste oder den Terminservice aufmachen um die richtige PLZ 70174 zu finden.
Stattdessen könnte man ja im GUI eine Auswahlliste haben. Dort klicke ich die Impfzentren an und die PLZ wird übernommen.
Bei der Terminsuche könnte man so auch die Gruppen Zusammenhänge abbilden.

**Comment by Floskinner** [comment]
Wenn ich das richtig verstehe meinst du sowas in der Art hier?

![vorschlag-Qt Designer](https://user-images.githubusercontent.com/58706771/120084637-0a18e180-c0d2-11eb-90c0-6667291d419f.png)

**Comment by andoorius** [comment]
Ja - genau so!

**Comment by iamnotturner** [comment]
> Wenn ich das richtig verstehe meinst du sowas in der Art hier?
> 
> 
> 
> ![vorschlag-Qt Designer](https://user-images.githubusercontent.com/58706771/120084637-0a18e180-c0d2-11eb-90c0-6667291d419f.png)
> 
> 

wird das dynamisch geladen?

**Comment by Floskinner** [comment]
Wurde in #265 hinzugefügt und in #288 (hoffentlich) gefixed :D

kann man also schließen
Danke nochmal für die Idee @andoorius

**Comment by andoorius** [comment]
Vielen Dank für die Implementierung! Das ist der komplexere Teil :-) @Floskinner
