### ISSUE TITLE
E-Mail kommt nicht

### ISSUE THREAD

**Issue by Gudwud** [iamnotturner/vaccipy#223]
Habe das Programm benutzt um einen Vermitlungscode zu generieren. Hat mich dann gefragt meinen SmS Code einzugeben. Aber habe letzendlich keine e-mail bekommen. ISt das ein bekanntes Problem? Soll ich es einfach nochmal versuchen oder macht das nur weitere Probleme ?

**Comment by iamnotturner** [comment]
hey, kannst du es mal erneut probieren, aber davor deine email kleingeschrieben eintragen?

**Comment by Gudwud** [comment]
Ok mache ich.

**Comment by Gudwud** [comment]
Hat funktioniert Danke <3

**Comment by derBobby** [comment]
Habe den Code für zwei Personen angefordert. Laut Vaccipy-Output erfolgreich. Mail kam allerdings keine. Version 1.0.4.

**Comment by iamnotturner** [comment]
fix mit #224 in der Beta-Version

**Comment by iamnotturner** [comment]
ich nehme an das hat sich erledigt

**Comment by janquisgran** [comment]
wenn der Fehler "Anfragelimit erreicht" kommt (und damit auch keine SMS bzw. Mail) - hat jemand Erfahrung, ob das nach einer gewissen Zeit zurückgesetzt wird?

**Comment by iamnotturner** [comment]
@janquisgran ja wirds, es gilt: 3 Codes pro Altersgruppe pro Tag pro Handynr./Mail
