### ISSUE TITLE
Mehrere Codes für verschiedene Impfzentrengruppen

### ISSUE THREAD

**Issue by Thorongil80** [iamnotturner/vaccipy#226]
Hi, erstmal: sehr schönes Tool, Nutzung problemlos und mit einem Klick installiert auf Windows...

Hier jetzt aber meine Frage: Ich habe aktuell drei Vermittlungscodes für die Servergruppen 001, 002 und 005.

Allerdings lässt ein Suchlauf nur die Nutzung eines Codes zu, d.h. wenn ich auf allen drei Servergruppen suchen will (z.B. Karlsruhe Schwarzwaldhalle (KIZ SK Karlsruhe) ist seltsamerweise 005, Messe Karlsruhe (ZIZ RP KA) ist 002 und Bruchsal und Sulzfeld (KIZ Landkreis KA) sind 001.

Eine Suche über diese vier Impfzentren würde also drei separate Instanzen (zwei davon "irgendwohin anders installiert" oder gar auf anderen Rechnern) von vaccipy benötigen. Auch das Kontaktdaten.json müsste ja PLZs und einen Code jeweils zu Gruppen zusammenziehen, aktuell ist nur ein Code hinterlegt und eine Liste von PLZ.

Habt ihr das schon auf dem Schirm?

**Comment by SkyPlayerTV** [comment]
Nein, ist nicht so. Einfach verschiedene kontaktdaten.json anlegen und mit Hilfe des Kommandozeilen Parameters -f die genutzte Datei wählen. Ist wohl absichtlich so, um das Tool sicherer gegenüber Missbrauch zu machen.

**Comment by Thorongil80** [comment]
Achso! Also man kann mehrere Instanzen laufen lassen aus einem Installationsort jeweils mit -f Blabla.json? Hatte ich überlesen ;-)

**Comment by iamnotturner** [comment]
Hey! Erstmal danke für das nette Feedback. Es freut uns, dass es so problemlos klappt.

Die Verteilung der Impfzentren ist willkürlich, wir verstehen dein Problem und haben es auch auf dem Schirm, lehnen das aber aus Gründen der Fairness und zum Schutz vor Missbrauch bisher bewusst ab. Wenn man parallel in X Zentren suchen will, sollte das mit einem gewissen Aufwand verbunden sein. 

Ich hoffe, dass du unsere Entscheidung nachvollziehen kannst.
