### ISSUE TITLE
Vaccination dates from the age of 12

### ISSUE THREAD

**Issue by Gr33ndev** [iamnotturner/vaccipy#233]
As of June 7, BioNTech's vaccine will also be approved for children 12 and older. It would therefore be very good if a selection for this age group is added (possibly modify 16+). In addition, it would be very useful if the program would allow to book an appointment for this group already today, but then in any case the date is after 07.06.

**Comment by pancakeDevelopment** [comment]
As far as I know, the specification for 12+ is not yet activated on the 'impfterminservice.de'
=> https://www.impfterminservice.de/assets/static/its/vaccination-list.json

**Comment by andoorius** [comment]
My proposal is you use L920 (today 16+) than you get 100% BioNTech. This is what you get for 12+ later.
Your idea with the Date is already implemented since Beta 1.0.5.

**Comment by Gr33ndev** [comment]
Oh ok I did not know that.
As far as I know it should be vaccinated from 7.6. also to 12 year olds: https://www.swr.de/swraktuell/rheinland-pfalz/mainz/ema-entscheidet-ueber-biontech-fuer-kinder-100.html

**Comment by Gr33ndev** [comment]
I will try the Beta, thank you :D

**Comment by Floskinner** [comment]
> Your idea with the Date is already implemented since Beta 1.0.5.

As a small addition
This is only implemented in the beta **GUI** version :)
GUI installer -> https://github.com/iamnotturner/vaccipy/releases/download/v1.0.6/vaccipy_gui_installer.exe
GUI zip -> https://github.com/iamnotturner/vaccipy/releases/download/v1.0.6/vaccipy-windows-gui.zip

**Comment by iamnotturner** [comment]
@Gr33ndev since the vaccination distribution depends on the code and we're dynamically checking the age groups before every code creation we will support appointment bookings for 12 years + old.
