### ISSUE TITLE
[BUG] retry-sec setzen wird in GUI nicht übernommen

### ISSUE THREAD

**Issue by andoorius** [iamnotturner/vaccipy#234]
Die GUI fragt immer exact nach 30sec. einen neuen Termin ab.
Die Einstellungen aus der Konsolenanwendung werden nicht übernommen.

**Comment by Floskinner** [comment]
Hey @andoorius,
dieses Feature bietet die GUI leider noch nicht ( ist aber notiert und in Planung :) )

Kleiner Background:
Die Einstellungen einfach "übernehmen" kann es aus der Konsolenanwendung gar nicht, da die Einstellung in keiner Datei gespeichert wird. Die `--retry-sec` Einstellung "lebt" pro Start der Konsolenanwendung nur in diesem einem Prozess, daher musst du auch die Konfiguration jedes mal neu übergeben, sobald die Anwendung einmal gestoppt wurde.

**Comment by andoorius** [comment]
Ohh und ich dachte das wird auch in einer Datei abgelegt - so wäre es tatsächlich verwunderlich, wenn es übernommen worden wäre 😜

Frage zu den 30s - ist das eine "zufälliger" Wert oder wird man bei schnelleren Abfragen geblockt? 

Noch eine Idee für ein Feature: vielleicht könntet Ihr noch eine Art "zufällige Unschärfe" reinbringen. In der Art User gibt eine Zeit in Sekunden (z.B. 10s) an und es wird jedesmal beim Abfragen die nominale Wartezeit um bis zu 10s verlängert/verkürzt. Das würde einer natürlicheren Abfrage entsprechen und die Terminsuche ist ja eh Glücksache....

**Comment by pancakeDevelopment** [comment]
> Ohh und ich dachte das wird auch in einer Datei abgelegt - so wäre es tatsächlich verwunderlich, wenn es übernommen worden wäre 😜
> 
> Frage zu den 30s - ist das eine "zufälliger" Wert oder wird man bei schnelleren Abfragen geblockt?
> 
> Noch eine Idee für ein Feature: vielleicht könntet Ihr noch eine Art "zufällige Unschärfe" reinbringen. In der Art User gibt eine Zeit in Sekunden (z.B. 10s) an und es wird jedesmal beim Abfragen die nominale Wartezeit um bis zu 10s verlängert/verkürzt. Das würde einer natürlicheren Abfrage entsprechen und die Terminsuche ist ja eh Glücksache....

Ich habe bisher noch keine Sperre erfahren. Aber ich finde, dass 30 Sekunden mehr als genug sind. Meiner Meinung machen weniger Sekunden wenig Sinn und würden die Server des Impfterminservices nur unnötig belasten, was im Umkehrschluss zu Maßnahmen führen könnte.

**Comment by andoorius** [comment]
Ja, wenn das zu keiner Sperre führt sind 30s völlig ok - ich wäre es sogar etwas langsamer angegangen.
