### ISSUE TITLE
Define Code per https://XXX-iz.impfterminservice.de

### ISSUE THREAD

**Issue by alexanderrock** [iamnotturner/vaccipy#239]
Each Server with different Locations identified by https://XXX-iz.impfterminservice.de has the same code.
Make it configurable which centers have which code.

Example:

{
            "url": "https://229-iz.impfterminservice.de/impftermine/service?plz=88212",
            "code": "XXXX-XXXX-XXXX",
            "name": "Ravensburg"
        },
        {
            "url": "https://001-iz.impfterminservice.de/impftermine/service?plz=89073",
            "code": "YYYY-YYYY-YYYY",
            "name": "Ulm"
        },
        {
            "url": "https://003-iz.impfterminservice.de/impftermine/service?plz=88045",
            "code": "ZZZZ-ZZZZ-ZZZZ",
            "name": "Friedrichshafen"
        },
        {
            "url": "https://003-iz.impfterminservice.de/impftermine/service?plz=88444",
            "code": "ZZZZ-ZZZZ-ZZZZ",
            "name": "Ummendorf"
        }

**Comment by iamnotturner** [comment]
we won't support searching in multiple groups at once as explained in #226
