### ISSUE TITLE
Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by D1yt** [iamnotturner/vaccipy#247]
Hey, is the installer malicious?

**Comment by D1yt** [comment]
windows-terminservice.exe v1.02 after installation via installer:
https://www.virustotal.com/gui/file/997c04d502b6d28ea9fbd28c26dd7f0dfd3be9844e68050dd5029b378f437212/detection

vaccipy_installer.exe v1.0.2
https://www.virustotal.com/gui/file/ef20b54d311705611c207ad88d3c887de1b503d3dcddcaf50a16c86f765e76c7/detection

vaccipy_installer.exe v1.0.4
https://www.virustotal.com/gui/file/352e61d5d2ed2154c7b8af73a274f33dd9c7aa4f92d8879bc5e965da9b8a3517/detection

**Comment by Floskinner** [comment]
Hey @D1yt, we already know about the problem - see #128
No don't worry, the installer is not malicious. Otherwise, here is an alternative: https://github.com/iamnotturner/vaccipy/issues/128#issuecomment-850964801

**Comment by D1yt** [comment]
Only windows defender on background check
