### ISSUE TITLE
Mehrere Kontaktdaten.json Einträge

### ISSUE THREAD

**Issue by janquisgran** [iamnotturner/vaccipy#249]
Feature Request: vaccipy sollte auch mehrere Toplevel-Einträge in der json, z. B. beide Impfzentren in Stuttgart, für die man unterschiedliche Codes braucht abgrasen können.

Aktuell starte ich mehrere Kernels mit anderen Kontaktdaten-Pfaden, um gleichzeitig in mehreren Gebieten zu suchen.

**Comment by iamnotturner** [comment]
Hey, wie in #226 beschrieben lassen wir das Feature direkt aus.

**Comment by janquisgran** [comment]
Ok, danke - ich hatte es gerade auch in den geschlossenen Issues gesehen.
