### ISSUE TITLE
[FEATURE] Update check

### ISSUE THREAD

**Issue by derBobby** [iamnotturner/vaccipy#255]
Es gibt Benutzer, die wenig von Entwicklung und Releases verstehen und daher nicht unbedingt verstehen, dass man das Tool regelmäßig aktualisieren sollte. Daher schlage ich einen Update-Check beim Start vor.

Meinung?

**Comment by iamnotturner** [comment]
Gern! Hast du Erfahrung wie man einen Update-Check mit Github Releases implementiert?

**Comment by derBobby** [comment]
Ich kann leider nur den Vorschlag liefern, bin nur in der Java Welt unterwegs. Und das nur hobbymäßig.

Ich weiß nicht, wie Python tickt. Lässt sich das direkt einbinden?: https://github.com/lilydjwg/nvchecker

Grundsätzliche Idee: Hat die aktuelle Version die Nummer x.y.z, dann ist ein Update zu machen, wenn ein Release x+1, y+1 oder z+1 existiert. Man sollte dann aber durch einen Test sicherstellen, dass eine neue Version auch tatsächlich erkannt wird.

**Comment by sinun98** [comment]
[v1.1.8](https://github.com/iamnotturner/vaccipy/releases/latest)
