### ISSUE TITLE
Anfrag wurde von der Botprotection geblockt.

### ISSUE THREAD

**Issue by NilsB26** [iamnotturner/vaccipy#260]
![grafik](https://user-images.githubusercontent.com/71553507/120303057-c3440b00-c2ce-11eb-85aa-4905b863e4b7.png)

Ist das Problem bekannt?

**Comment by iamnotturner** [comment]
jap, Workaround ist den Termin manuell selbst zu buchen mit der URL aus der Ausgabe.

**Comment by NilsB26** [comment]
Das Problem war nur das ich in diesem Moment nicht am PC war, als ich wieder kam war der Termin bereits nicht mehr verfügbar =/

**Comment by NilsB26** [comment]
Naja vielleicht klappt es ja beim nächsten mal
