### ISSUE TITLE
Release 1.1.0 -> GUI -> Kontaktdaten error, Impfzentren auswählen beendet

### ISSUE THREAD

**Issue by alexanderrock** [iamnotturner/vaccipy#268]
Hi Zusammen,
gerade die Release 1.1.0 GUI getestet.
Zeitspanne kann eingestellt werden, Kontaktdaten alle ausgefüllt ergibt ein Error Fenster -> 
![image](https://user-images.githubusercontent.com/13395039/120400167-ab57a000-c33d-11eb-800d-9a53788dcddc.png)

Ein Klick auf Impfzentren wählen, lässt das Programm kurz einfrieren und wird danach beendet

**Comment by iamnotturner** [comment]
Hey Alex, danke für die Info. Die Version war aus Versehen schon im Master, muss aber erst noch im Beta getestet werden. 
@Floskinner ich markiere dich mal

**Comment by iamnotturner** [comment]
Fehler sollten mit [v1.1.1](https://github.com/iamnotturner/vaccipy/releases/tag/v1.1.1) behoben sein, bitte kurz Rückmeldung geben obs klappt.

**Comment by alexanderrock** [comment]
Kontaktdaten können nun gespeichert werden
Impfzentren auswählen beendet das Programm weiterhin

**Comment by Floskinner** [comment]
ja das mit den Impfzentren ist noch vorhanden. 
Ich öffne dafür mal ein eigenes Issue damit man sieht dass wir bescheid wissen :)
