### ISSUE TITLE
[BUG] GUI v1.1.0 Fenster schließen sich (Windows)

### ISSUE THREAD

**Issue by andoorius** [iamnotturner/vaccipy#273]
Guten Morgen,
beim Versuch in Kontaktdaten ein Impfzentrum über den neuen Button zu wählen, schließt sich die GUI sofort.
Gleiches Verhalten beim Button Termin suchen.

**Comment by alexanderrock** [comment]
Duplikate #268 
Ist bekannt, versuch mal Release 1.0.4 damit geht es,, hat allerdings weniger Features
1.1.0 ist beta

**Comment by iamnotturner** [comment]
Wann hast du 1.1.0 gedownloaded? Um 2 Uhr gabs da nochmal Änderungen

**Comment by andoorius** [comment]
Download war heute morgen gegen 7Uhr

Am 02.06.2021 um 08:39 schrieb Tim Reibe ***@***.***>:

﻿
Wann hast du 1.1.0 gedownloaded? Um 2 Uhr gabs da nochmal Änderungen

**Comment by iamnotturner** [comment]
Fehler sollten mit [v1.1.1](https://github.com/iamnotturner/vaccipy/releases/tag/v1.1.1) behoben sein, bitte kurz Rückmeldung geben obs klappt.

**Comment by andoorius** [comment]
Leider nein - identisches Verhalten.
