### ISSUE TITLE
Error: Release 1.1.1 -> GUI -> Impfzentren Wählen fürt zu Programmabsturz

### ISSUE THREAD

**Issue by Floskinner** [iamnotturner/vaccipy#277]
Problem:
-
Aktuell gibt es das Problem in der GUI, dass die "Impfzentren auswählen" zu einem Programmabsturz führt:
![image](https://user-images.githubusercontent.com/58706771/120470845-513df580-c3a4-11eb-9092-d1df5a68a80f.png)

Workaround:
-
Alternativ kann man die PLZs der Impfzentren einfach manuell eingeben.
Wir arbeiten jedoch an einer Lösung

**Comment by iamnotturner** [comment]
fixed mit release v1.1.2
