### ISSUE TITLE
Abgelaufener SMS-Code wird angenommen

### ISSUE THREAD

**Issue by mapelpapel** [iamnotturner/vaccipy#279]
Hallöchen, ich hatte gerade das Phänomen, dass ein SMS-Code erfolgreich angenommen wurde, der eigentlich fast eine Stunde abgelaufen war. Eine Mail habe ich jedoch (richtigerweise) nicht erhalten. Ich weiß, dass das eigentlich in der code_besteatigen() abgeprüft wird, aber irgendwie ist es ja trotzdem durchgerutscht. Kann ja auch sein, dass der Server da Mist zurückschickt. 
Vielleicht will es sich ja mal jemand anschauen, ist aber eigentlich unwichtig :D

**Comment by pancakeDevelopment** [comment]
Musst mal schauen ob der Code später noch kam.
Hatte vor 2 Stunden auch 2 Codes erstellt, welche jedoch erst vor wenigen Minuten im E-Mail Postfach angekommen sind.

**Comment by iamnotturner** [comment]
Glaube dagegen können wir nix tun, danke für den Hinweis aber 🙃
