### ISSUE TITLE
Chrome wird nicht geschlossen

### ISSUE THREAD

**Issue by pancakeDevelopment** [iamnotturner/vaccipy#282]
Getestet mit der GUI:

Sollte man die Terminsuche (warum auch immer) während diesem Prozess:

`2021-06-02 16:48:26.514 impfterminservice [inf] [*Q9BU | *] Code eintragen und Mausbewegung / Klicks simulieren. Dieser Vorgang kann einige Sekunden dauern. `

beenden, dann wird der Chrome Prozess nicht beendet. Beim erneuten Start einer Suche führt es zu folgendem Fehler:

`2021-06-01 22:25:30.972 impfterminservice [err] [renew_cookies] SessionNotCreatedException exception raised - retry 1 `

Nach 9. retry dann:

`2021-06-01 22:25:54.568 impfterminservice [err] [*K6BS | *] from disconnected: unable to connect to renderer (Session info: headless chrome=91.0.4472.77) `

Vielleicht möchte sich jemand das mal anschauen. Sobald man die Chrome Prozesse über den TM manuell beendet hat läuft die Terminsuche wieder ohne Probleme.

**Comment by funnym0nk3y** [comment]
Bei mir lassen sich die Chrome Instanzen nicht mal mit dem Taskmanager beenden.

**Comment by iamnotturner** [comment]
[bitte mal v1.1.5 testen](https://github.com/iamnotturner/vaccipy/releases/tag/v1.1.5) und kurz Rückmeldung geben, obs hilft
