### ISSUE TITLE
dist/windows-terminservice existiert nicht bei dem hauptverzeichnis

### ISSUE THREAD

**Issue by Kimo1989-1** [iamnotturner/vaccipy#285]
hallo Leute, 
ich will gerade einen Impftermin vereinbaren..
Dazu habe ich gerade vaccipy-master heruntergeladen und will, so wie  auf dasding.de steht den Ordner dist/windows-terminservice finden. ich befolge die Anleitung, die auf der Webseite stehet. (https://www.dasding.de/update/wie-impftermin-einfacher-bekommen-100.html) 

Was mache ich genau da falsch? Hat jemand eine Idee!
grüße

Kimo

**Comment by iamnotturner** [comment]
Hey Kimo, das ist richtig, wir haben den Ablauf etwas angepasst.
Du kannst den Installer für Windows direkt hiet downloaden und ausführen: https://github.com/iamnotturner/vaccipy/releases/latest/download/vaccipy_installer.exe

Gib gerne eine Rückmeldung obs klappt. Denk dran, dass Chrome (Version 91) installiert sein muss. 

Liebe Grüße

**Comment by Sylwuscha** [comment]
Bei mir klappt es gerade nicht mit dem alten und auch nicht mit dem neuen (Chrome blockiert) Weg zum Download

**Comment by Sylwuscha** [comment]
Kann mir bitte jemand helfen? Leider habe ich das Programm gelöscht und nun lässt es sich nicht mehr installieren.

@iamnotturner - https://github.com/iamnotturner/vaccipy/releases/latest/download/vaccipy_installer.exe - funktioniert leider nicht. Ich habe die aktuelle Chrome Version mit 91 vorne.

Problem beim Download: "vaccipy_installer.exe ist schädlich und wurde daher von Chrome blockiert"

Ich habe nichts gefunden, wie ich die Blockierung aufheben / umgehen kann (als Laie!).

**Comment by BlackScreen** [comment]
> Ich habe nichts gefunden, wie ich die Blockierung aufheben / umgehen kann (als Laie!).

Variante 1: Den Ordner wo der Download entpackt wird, als Ausnahme in den Windows-Sicherheiteinstellungen hinzufügen. Hier steht wie das geht: https://support.microsoft.com/de-de/windows/hinzuf%C3%BCgen-eines-ausschlusses-zu-windows-sicherheit-811816c0-4dfd-af4a-47e4-c301afe13b26

Variante 2: Komplett isoliert und sicher in der Windows Sandbox laufen lassen, da macht man nix kaputt.
Wie das geht steht hier: https://docs.microsoft.com/de-de/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview

**Comment by Sylwuscha** [comment]
klappt beides nicht :-(

**Comment by BlackScreen** [comment]
> klappt beides nicht :-(

Sicher? Bei mir haben beide Methoden wunderbar funktioniert. Wir sprechen über einen Windows-PC?
Ansonsten geht noch Variante 3: das Skript direkt via Python ausführen. Ist aber vermutlich nichts für den Laien.
