### ISSUE TITLE
Frage: Beschränkung auf gewisse Impfstoffe

### ISSUE THREAD

**Issue by Tomagori** [iamnotturner/vaccipy#290]
Erstmal: Richtig nices tool, vielen Dank an die Entwickler.

Ich versuche, vaccipy für eine Bekannte einzurichten, die bereits gewisse Vorerkrankungen hatte und deshalb nicht AstraZeneca verwenden sollte. Da vaccipy auch die vorhandenen Impfstoffe abruft, ist es möglich, hier AZ auszuschliessen? Verstehe natürlich auch, warum man vaccipy keine solche Impfstoffpriorisierung erlauben wollen würde, aber ich dachte eine Frage wärs mal wert.

**Comment by iamnotturner** [comment]
Hi, den Impfstoff kann man sich nicht explizit auswählen. Die Verteilung passiert anhand des Alters, AZ wird nur an Ü60 vergeben. Es gibt 2 Möglichkeiten: 

A) entweder du versuchst es trotzdem ihr einen Termin auszumachen und stornierst ihn, wenn es AZ wird

oder B) es beim Hausarzt probieren, die haben freie Entscheidungsmacht

**Comment by Tomagori** [comment]
Ok, vielen Dank :)
