### ISSUE TITLE
Feature: Extra eMail Benachrichtigung bei Buchung

### ISSUE THREAD

**Issue by andoorius** [iamnotturner/vaccipy#291]
Ich habe für ein paar Freunde die nicht soo IT affine sind und bei Beta Version eher an ne Virus Variante denken erfolgreich Termine gebucht :-) Zum Glück auch sehr kurzfristig. Da ich nicht immer am "Such PC" bin und die eMails nicht sehr regelmäßig angerufen werden, könnte ich mir folgendes Feature vorstellen:
Bei erfolgreicher Buchung generiert Vaccipy eine eigene eMail mit Name, Code, Impfzentrum, Terminen, Lini direkt zum Termin und vielleicht Suchzeit und verschickt diese über einen vom User voreingestellten SMTP Server. Da könnte man sogar über Pushsafer Pushnachrichten generieren.

**Comment by pancakeDevelopment** [comment]
Verstehe ich das richtig: Die Mails werden nicht regelmäßig aufgerufen, aber du möchtest eine E-Mail Benachrichtigung?
Derzeit hat jemand bereits ein PR zu Telegram Benachrichtigungen erstellt. Ich denke das sollte völlig ausreichen:

https://github.com/iamnotturner/vaccipy/pull/287

Sobald der Termin erfolgreich gebucht wurde kommt sowieso eine E-Mail, weswegen eine weitere Mail sowieso überflüssig wäre.

**Comment by bonxz** [comment]
Find ich jetzt nicht so nötig. Stell doch einfach die Email die du für die Termine eingibst in dein Handy ein und check da die Emails?
Oder wie der User vor mir schon gesagt hat gibts ja ein PR für Telegram.

**Comment by pancakeDevelopment** [comment]
> Find ich jetzt nicht so nötig. Stell doch einfach die Email die du für die Termine eingibst in dein Handy ein und check da die Emails?
> Oder wie der User vor mir schon gesagt hat gibts ja ein PR für Telegram.

Genau. Bei den üblichen E-Mail Anbietern hat man sowieso die Möglichkeit zu push-Benachrichtigungen

**Comment by andoorius** [comment]
Naja leider ein bisschen anderer Usecase. Bestätigung geht an den Impfling und Info wäre an jemand anderen gegangen. Deshalb geht das mit Handyeinrichten und die anderen Vorschläge nicht. Telegram ist auch ne Option...
