### ISSUE TITLE
[FEATURE] Öffne Browser und zeige Buchung wenn erfolgreich

### ISSUE THREAD

**Issue by alexanderrock** [iamnotturner/vaccipy#292]
Hey Zusammen,
wenn eine Buchung erfolgreich war, schließst sich das Tool ja und wenn man zu dem Zeitpunkt grade nicht am Rechner ist und die Windows Notification nicht mitbekommt hat man kein Indiz für die Buchung, außer der von Impftermnservice generierten Mail und wunder sich, ob es eine erfolgreiche Buchung gab oder das Programm so abgestürtzt ist.

Könnte man nach einer erfolgreichen Buchung die Prüfung nochmal für den Code die Prüfung durchführen, wenn erfolgreich war, dann werden die beiden Termine angezeigt -> so könnte man auch Prüfen, ob ein Code bereits erfolgreich war "Termine absagen" auf der Seite -> code nicht mehr prüfen

**Comment by pancakeDevelopment** [comment]
Also als ich meinen letzten Termin gebucht hatte blieb vaccipy offen. Dort sah ich dann sie [suc] Meldung mit dem entsprechenden Termin. Ist das nicht mehr so?

**Comment by alexanderrock** [comment]
Hatte heute das Glück für einen Kollegen einen Termin zu bekommen, war zu der Zeit in der Dusche und konnte nur sehen, dass vaccipy nicht mehr da war, dann habe ich manuell den Code geprüft und gesehen, dass ein Termin vorlag, danach habe ich dann in der Windows Info Leiste gesehen, dass da auch die Benachrichtigung war

**Comment by bonxz** [comment]
Also bei mir bleibt das Fenster auch offen und habe schon 6 Termine ausgemacht mit dem Programm. Falls es bei dir aber zugehen sollte könntest du aber auch im Log nachschauen. Da steht alles drin dann.

**Comment by BlackScreen** [comment]
Bei mir blieb es mit Version 1.0.4 offen bei beiden Buchungen für Kollegen.
Zuvor war das anders, also danke dafür. :)

**Comment by alexanderrock** [comment]
Hi,
hab heute Version 1.1.5 CLI getestet und einen Termin gefunden, der erfolgreich gebuchte Termin war wieder nicht offen geblieben, sondern CLI und Browser geschlossen. Nur die Benachrichtigung war da, wäre toll wenn die Buchungsseite mit den Terminen angezeigt wird.
