### ISSUE TITLE
TimeoutException 

### ISSUE THREAD

**Issue by bonxz** [iamnotturner/vaccipy#296]
Vor einer halben Stunde wurden Wartungsarbeiten an der Webseite durchgeführt. Habe das Programm seit 4 Tagen ohne Probleme durchlaufen lassen. Seit den Wartungsarbeiten eben kommt jetzt folgendes. 

![impferror](https://user-images.githubusercontent.com/61289944/120698943-05787280-c4b0-11eb-9ff2-1d6d420014bd.png)

Sucht danach aber trotzdem nach Terminen weiter. Ob es dann aber auch die Termine macht wenn das Tool einen findet, weiß ich natürlich nicht

**Comment by bonxz** [comment]
Nach einem Neustart nochmal ein anderer Fehler jetzt. 
![straße](https://user-images.githubusercontent.com/61289944/120699460-b1ba5900-c4b0-11eb-942f-0f944cd0a32f.png)

**Comment by Xography** [comment]
Selbes Problem, bei mir hängts beim Cookie generieren.
![image](https://user-images.githubusercontent.com/264484/120699564-d31b4500-c4b0-11eb-86d6-dedb1fd79108.png)

Ich gehe davon aus, dass im Wartungsfenster das Layout / Code der Webseite geändert wurde was erstmal wieder in its.py integriert werden muss...

**Comment by iamnotturner** [comment]
Danke für den Hinweis

**Comment by Fabian25180** [comment]
![Screenshot 2021-06-03 213140](https://user-images.githubusercontent.com/72571873/120701434-1e365780-c4b3-11eb-96bc-8420fef531f8.png)

Ebenfalls gleiches Problem wie @Xography, vermute auch, dass es mit den Wartungsarbeiten zusammenhängt ://

**Comment by IsmAbd** [comment]
Beim Cookiebanner hat sich der xPath geändert, aber ich habe gesehen, dass da gerade noch ne PR gemacht wurde

**Comment by Daniel80769** [comment]
Bei mir hängt es auch nach dem Update der Impftermine Seite bei Browser-Cookies generieren.

**Comment by IAmWebSA** [comment]
Im Beta Branch gefixt

**Comment by Daniel80769** [comment]
Wie kann ich das einfügen ?

**Comment by IAmWebSA** [comment]
in der its.py den xpath durch folgendes ersetzen wie im PR:
[]( https://github.com/iamnotturner/vaccipy/pull/297)

`# Klick auf "Auswahl bestätigen" im Cookies-Banner
  button_xpath = "//*/a[@class=\"cookies-info-close btn kv-btn btn-magenta\"]"`

**Comment by Daniel80769** [comment]
OK danke werde ich mal
Suchen

**Comment by Daniel80769** [comment]
Wo finde ich die ITS.PY ?
