### ISSUE TITLE
{"error":"Geburtsdatum ungueltig oder in der Zukunft"}

### ISSUE THREAD

**Issue by smartschat** [iamnotturner/vaccipy#303]
Mit dem aktuellen Release 1.1.3 bekomme ich bei der automatischen Codegenerierung den Fehler (bei Altersgruppe 18+)

```
2021-06-03 22:18:12.325   impfterminservice   [err] [*V894 | 70174]   Code kann nicht angefragt werden: {"error":"Geburtsdatum ungueltig oder in der Zukunft"}
```

Ich benutze vaccipy per Kommandozeile unter Linux.

**Comment by alexanderrock** [comment]
Das Feld für die Altersabfrage beim Anspruch prüfen wurde geändert:

![image](https://user-images.githubusercontent.com/13395039/120707145-42e1fd80-c4ba-11eb-8819-face29879aec.png)

**Comment by funnym0nk3y** [comment]
Hab das selbe Problem.

**Comment by sinun98** [comment]
Wird aktuell gefixt.

**Comment by funnym0nk3y** [comment]
Mega, danke!

**Comment by iamnotturner** [comment]
#306 damit fixed
