### ISSUE TITLE
[BUG] Impf Code Generierung mit falsche Daten

### ISSUE THREAD

**Issue by ndp1410** [iamnotturner/vaccipy#304]
Hallo zusammen,

beim Ausführen der Impf Code Generierung bekomme ich folgende Fehlermeldung " impfterminservice   [err] [*P3N8 | 68163]   Code kann nicht angefragt werden: {"error":"Geburtsdatum ungueltig oder in der Zukunft"}"

Was ist an der Stelle falsch?

Ich habe beim Leistungsmerkmal L921 eingegeben.

Viele Grüße
cd

**Comment by alexanderrock** [comment]
Duplikat #303

**Comment by sinun98** [comment]
Wird aktuell gefixt.

**Comment by iamnotturner** [comment]
fixed mit #306, bitte v1.1.4 nochmal herunterladen
