### ISSUE TITLE
GUI funktioniert seit v1.1.3 nicht mehr

### ISSUE THREAD

**Issue by juziegle** [iamnotturner/vaccipy#305]
GUI öffnet nach "Termin suchen" ein weißes Fenster, dann geht es wieder zu und der Prozess bricht ab.

**Comment by iamnotturner** [comment]
v1.1.4 kommt gleich, bitte dann nochmal probieren :-)

**Comment by iamnotturner** [comment]
live, bitte probieren und Rückmeldung geben

**Comment by juziegle** [comment]
Der "Fehler" besteht weiterhin. Vielleicht liegt es auch nur an mir ...
