### ISSUE TITLE
Code generation fails. Website writes "Ein unerwarteter Fehler ist aufgetreten"

### ISSUE THREAD

**Issue by noppelmax** [iamnotturner/vaccipy#307]
Hey,

first, thanks for your work!

I failed to generate a code with the current branches: master, beta as well as v1.1.3, v1.1.2, v1.1.1. In all cases the chrome window pops up, "ja" is clicked, some code is entered and than the message "Ein unerwarteter Fehler ist aufgetreten". Any ideas what might go wrong? The console writes that i should move the mouse and click some buttons for 30s, but this does not help.

Kind regards,
Max

**Comment by iamnotturner** [comment]
Try v1.1.4 please

**Comment by sinun98** [comment]
> Ein unerwarteter Fehler ist aufgetreten

= IP Bann. Use VPN or wait some minutes.

**Comment by noppelmax** [comment]
NIce! Thanks @iamnotturner . It worked now! I also managed to get to this error "ungültiges Geburtstagdatum" right now. But now i dont have to figure out how the json must bechanged, s.t. it works. You did it already! Thanks!
