### ISSUE TITLE
Error: SessionNotCreatedException exception raised

### ISSUE THREAD

**Issue by incomingstorm** [iamnotturner/vaccipy#308]
Hallo, 
nach der Auswahl der Generierung des Impf-Codes und Eingabe der Kontaktdaten und Altersgruppe wird das Programm gestartet aber ich bekomme folgende Fehlermeldung: 

![image](https://user-images.githubusercontent.com/41796773/120710589-9a826800-c4be-11eb-9b83-4201a3fd9876.png)

Woran kann das liegen und wie kann ich das beheben? Auf der Hauptseite sehe ich , dass das irgendwas mit dem Chromedriver liegen kann? Aber das habe ich nicht wirklich verstanden. 
Das ganze läuft auf Windows 10

Vielen Dank!

**Comment by iamnotturner** [comment]
Hey, hast du Chrome installiert? Bitte nochmal die neuste Version (v1.1.4) herunterladen, es gab Änderungen auf der Website.

**Comment by incomingstorm** [comment]
Danke, ja ich hatte die den Links auf der Hauptseite gefolgt die vor ca. 1 Stunde wohl noch die Version 1.1.3 hatten. Mit 1.1.4 ging es dann. Danke!
