### ISSUE TITLE
GUI: Terminsuche startet nicht

### ISSUE THREAD

**Issue by schindlboeckLi** [iamnotturner/vaccipy#309]
Hallo Zusammen,

hab grad das neueste Release (gui) runtergeladen, die Terminsuche startet aber nicht mehr.
Es öffnet sich kurz ein Fenster, welches sich sofort wieder schließt und unter laufende Prozesse auf der Oberfläche verschwindet der Prozess.
Chrome Version: 91.0.4472.77
Betriebssystem: Windows 10

**Comment by iamnotturner** [comment]
Danke für die Info. Es funktioniert teilweise, bei manchen nicht. Wir sind dran!

**Comment by iamnotturner** [comment]
könntest du mal schauen ob bei dir der Chromedriver oder ähnliche Prozesse im Task-Manager noch laufen?

**Comment by juziegle** [comment]
> 
> 
> könntest du mal schauen ob bei dir der Chromedriver oder ähnliche Prozesse im Task-Manager noch laufen?

Bei mir sagt das Installationsprogramm, dass der Chromedriver noch läuft, das tut er aber laut Task-Manager nicht. Wenn man dann "ohne Beenden" wählt, wird es installiert, aber es tritt das oben beschriebene Problem auf.

**Comment by Pratikk17** [comment]
Hello, 
I am also facing the same problem. The bot open chrome but it does not accept cookies and hence stops. There is a message on the top "Chrome is being controlled by automated test software".

**Comment by schindlboeckLi** [comment]
> Danke für die Info. Es funktioniert teilweise, bei manchen nicht. Wir sind dran!

**Comment by schindlboeckLi** [comment]
> könntest du mal schauen ob bei dir der Chromedriver oder ähnliche Prozesse im Task-Manager noch laufen?

Sicher,
 Chromedriver läuft nicht. Ähnliche Prozesse?

**Comment by schindlboeckLi** [comment]
> > könntest du mal schauen ob bei dir der Chromedriver oder ähnliche Prozesse im Task-Manager noch laufen?
> 
> Sicher,
> Chromedriver läuft nicht. Ähnliche Prozesse?

**Comment by iamnotturner** [comment]
hey, könntet ihr mal testen ob [dieser Release](https://github.com/iamnotturner/vaccipy/releases/tag/v1.1.5) das Problem fixt? 

Ggf. auch mal einen Neustart probieren.

**Comment by schindlboeckLi** [comment]
hi, Rechner neu gestartet bei mir unverändert

**Comment by juziegle** [comment]
hey, bei mir leider nicht.. danke für das große engagement übrigens! :)

**Comment by iamnotturner** [comment]
Ich kann das Problem aktuell leider nicht nachproduzierten. Könntet ihr mal testen ob die [CLI Version](https://github.com/iamnotturner/vaccipy/releases/latest/download/vaccipy_installer.exe) funktioniert?

[Kommt gerne in unseren Slack :-) ](https://join.slack.com/t/vaccipy/shared_invite/zt-qt5ympiu-j7P86E2U0yM3shqoNSoqyg)

**Comment by schindlboeckLi** [comment]
Edit:
bei mir tuts. hab die Kontaktdaten + Zeitspanne noch einmal neu eingetragen (hatte zuvor die .json vom vorherigen Release)

**Comment by iamnotturner** [comment]
> Edit:
> bei mir tuts. hab die Kontaktdaten + Zeitspanne noch einmal neu eingetragen (hatte zuvor die .json vom vorherigen Release)

@juziegle @Pratikk17 könntet ihr testen, ob das bei euch auch hilft?

**Comment by schindlboeckLi** [comment]
> Ich kann das Problem aktuell leider nicht nachproduzierten. Könntet ihr mal testen ob die [CLI Version](https://github.com/iamnotturner/vaccipy/releases/latest/download/vaccipy_installer.exe) funktioniert?
> 
> [Kommt gerne in unseren Slack :-) ](https://join.slack.com/t/vaccipy/shared_invite/zt-qt5ympiu-j7P86E2U0yM3shqoNSoqyg)

CLI läuft bei mir auch

**Comment by Pratikk17** [comment]
> > Edit: works 
> > for me. I re-entered the contact data + time span (previously had the .json from the previous release)
> 
> @juziegle @ Pratikk17 could you test whether this also helps you?

@iamnotturner  Ich danke Ihnen vielmals. Jetzt funktioniert es auch bei mir

**Comment by andoorius** [comment]
> Edit:
> 
> bei mir tuts. hab die Kontaktdaten + Zeitspanne noch einmal neu eingetragen (hatte zuvor die .json vom vorherigen Release)

Hatte das gleiche Problem. Zeitspanne neubgeschrieben über GUI -> funktioniert (bin mir nicht mehr sicher ob es 1.1.2 oder 1.1.3 war, leider)

**Comment by Sars-Cov-2-Antigen** [comment]
Was mir manchmal passiert, ist dass das Script beim Generieren der Cookies hängen bleibt. Da steht dann, es würde Userverhalten simuliert werden (Mausbewegungen / Klicks), das Chromedriverfenster bleibt offen und es tut sich nichts mehr. 
In diesen Fällen "valdiere" ich den Cookie manuell, indem ich selbst auf Impfterminservice herumklicke. 

Mir ist folgende Zeile unter Headers aufgefallen:

![grafik](https://user-images.githubusercontent.com/84661358/120763478-8a4aa700-c517-11eb-8a69-4fe8a7d46722.png)

Also die zweite (rote Schrift). Man muss so lange auf der Seite surfen, bis diese Zeile verschwindet, dann kann man die Suche neu starten und es funktioniert wieder. Gilt auch für das Generieren der Impfcodes, falls die manuelle Cookieeingabe gefordert wird. Keine Ahnung, ob das jetzt nur Zufall war.

**Comment by Sylwuscha** [comment]
Nachdem ich die Terminsuche gestern irgendwann endlich zum Laufen gebracht habe (Windows, Chrome oder Antivirenprogramm blockt), ging es heute Nacht irgendwann nicht mehr.

Heute will die Terminsuche nicht loslaufen. Bleibt immer stocken bei: "Browser Cookies generieren" 

Was kann ich tun ohne IT-Wissen haben zu müssen?

**Comment by bitwon** [comment]
@iamnotturner Das liegt definitiv an der neuen Struktur des JSON Files für die Zeitspanne. Ich konnte letzte Woche bereits erfolgreich einen Termin für einen Familienmitglied ergattern und heute das Update auf die 1.1.5 gemacht und eben das hier beschriebene Problem gehabt. Wenn man die Strukturen vergleicht, ist es auch klar:

**Alt**
```json
{
    "wochentage": [
        0,
        1,
        2,
        3,
        4,
        5,
        6
    ],
    "startzeit": {
        "h": 0,
        "m": 1
    },
    "endzeit": {
        "h": 23,
        "m": 59
    },
    "einhalten_bei": [
        1,
        2
    ],
    "startdatum": {
        "jahr": 2021,
        "monat": 6,
        "tag": 04
    }
}
```

**Neu**
```json
{
    "von_datum": "04.6.2021",
    "von_uhrzeit": "0:1",
    "bis_uhrzeit": "23:59",
    "wochentage": [
        "Di",
        "Mo",
        "Do",
        "Sa",
        "So",
        "Mi",
        "Fr"
    ],
    "einhalten_bei": "beide"
}
```

CLI ging bei mir ebenfalls, da nicht auf die alte Datei zugegriffen wurde.

**Comment by Sylwuscha** [comment]
Das sagt mir als Laie rein gar nichts

**Comment by iamnotturner** [comment]
da mit der neuen Version des GUI in der Beta schon länger getestet wurde, haben wir ganz vergessen, dass sich die Struktur angepasst hat. Danke nochmal für die Hinweise, ich denke, dass das vielen hilft. Wir bauen da aber nochmal was ein, damit man zukünftig auf solche Änderungen besser hingewiesen wird. Danke!

**Comment by iamnotturner** [comment]
> Das sagt mir als Laie rein gar nichts

Einfach das Programm Neustarten und alle Daten nochmal neu eintragen, dann hast du kein Problem!

**Comment by Sylwuscha** [comment]
Programm starten heißt für mich auf das Symbol der Spritze auf dem Desktop klicken. Hab ich gemacht. Das schwarze Fenster öffenet sich. Alles scheint normal. Ich starte die Terminsuche und gebe noch einmal alle Namens- und Adressdaten neu ein. 
Es bleibt leider weiterhin stehen bei "Browser Cookies generieren"

**Comment by sinun98** [comment]
> Programm starten heißt für mich auf das Symbol der Spritze auf dem Desktop klicken. Hab ich gemacht. Das schwarze Fenster öffenet sich. Alles scheint normal. Ich starte die Terminsuche und gebe noch einmal alle Namens- und Adressdaten neu ein.
> Es bleibt leider weiterhin stehen bei "Browser Cookies generieren"

Bitte einmal die neuste Version downloaden und installieren.

**Comment by Sylwuscha** [comment]
Oh je, das dauert wieder Stunden, weil sich mein PC mit Händen und Füßen dagegen wehrt -- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 04.06.21, 12:13, "Simon Bräuninger" ***@***.***> schrieb:




Programm starten heißt für mich auf das Symbol der Spritze auf dem Desktop klicken. Hab ich gemacht. Das schwarze Fenster öffenet sich. Alles scheint normal. Ich starte die Terminsuche und gebe noch einmal alle Namens- und Adressdaten neu ein.

Es bleibt leider weiterhin stehen bei "Browser Cookies generieren"



Bitte einmal die neuste Version downloaden und installieren.



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/iamnotturner/vaccipy/issues/309#issuecomment-854565737",

"url": "https://github.com/iamnotturner/vaccipy/issues/309#issuecomment-854565737",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Sylwuscha** [comment]
![image](https://user-images.githubusercontent.com/84845174/120790188-e53dc780-c532-11eb-8608-3ada52d0530c.png)
![image](https://user-images.githubusercontent.com/84845174/120790230-f4247a00-c532-11eb-9733-0c7bca35c189.png)
Wo steckt das Programm drin? Ich finde es nicht nach Download und Entzippen

**Comment by schindlboeckLi** [comment]
> ![image](https://user-images.githubusercontent.com/84845174/120790188-e53dc780-c532-11eb-8608-3ada52d0530c.png)
> ![image](https://user-images.githubusercontent.com/84845174/120790230-f4247a00-c532-11eb-9733-0c7bca35c189.png)
> Wo steckt das Programm drin? Ich finde es nicht nach Download und Entzippen

Scheint als hättest du den Sourcecode gedownloadet. Versuche es hier mit -> [https://github.com/iamnotturner/vaccipy/releases/download/v1.1.5/vaccipy-windows-gui.zip](https://github.com/iamnotturner/vaccipy/releases/download/v1.1.5/vaccipy-windows-gui.zip)

**Comment by sinun98** [comment]
Oder das altbekannte schwarze Fenster über: https://github.com/iamnotturner/vaccipy/releases/download/v1.1.5/vaccipy-windows.zip

**Comment by Sylwuscha** [comment]
Danke, jetzt klappt es. Neues weißes Fenster :-)

 
 

Gesendet: Freitag, 04. Juni 2021 um 12:53 Uhr
Von: "Liz" ***@***.***>
An: "iamnotturner/vaccipy" ***@***.***>
Cc: "Sylwuscha" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [iamnotturner/vaccipy] GUI: Terminsuche startet nicht (#309)


 




Wo steckt das Programm drin? Ich finde es nicht nach Download und Entzippen


Scheint als hättest du den Sourcecode gedownloadet. Versuche es hier mit -> https://github.com/iamnotturner/vaccipy/releases/download/v1.1.5/vaccipy-windows-gui.zip
