### ISSUE TITLE
Johnson & Johnson Terminbuchung führt zu Abbruch

### ISSUE THREAD

**Issue by D0mc3k** [iamnotturner/vaccipy#31]
Hallo Zusammen,

bei Johnson & Johnson als Wirkstoff fliegt uns die Zeile 319 um die Ohren, weil es hierbei keinen zweiten Impftermin geben wird. Leider bin ich kein Python Experte und weiß deswegen nicht wie ich das umsetzen kann aber vielleicht hat ein anderer eine Idee.

```
line 319, in termin_buchen
"slots": [self.terminpaar[0].get("slotId"), self.terminpaar[1].get("slotId")],
IndexError: list index out of range←[0m
```

Termine wäre verfügbar gewesen aber er stieg dann aus und hat mir auch die manuelle Terminvereinbarung blockiert.

**Comment by iamnotturner** [comment]
Hey, das ist ärgerlich, Aber danke für den Hinweis. Ich habe die Terminbuchung angepasst, dass es jetzt auch mit nur einem Termin klappen sollte.

Ist jetzt noch nicht im Windows Build. Führst du die .exe oder die py-Datei aus?

#32 einfach den Master nochmal pullen.

**Comment by D0mc3k** [comment]
hab das repo ausgecheckt und die main.py etwas angepasst (timeout verringert auf 2 sek ;)) und lass die laufen.

Danke für den Hotfix :)

**Comment by iamnotturner** [comment]
Gib bitte ein kurzes Update, wenn es (nicht) geklappt hat

**Comment by D0mc3k** [comment]
> Gib bitte ein kurzes Update, wenn es (nicht) geklappt hat

Klar das mache ich. Bisher habe ich aber leider keinen weiteren Impftermin angeboten bekommen

**Comment by D0mc3k** [comment]
Also absolut geniales Script. Vielen herzlichen Dank dafür :). Wir haben heute Abend erfolgreich einen Johnson & Johnson Termin vereinbart bekommen. Das heißt einerseits funktioniert das Script hervorragend, andererseits deine Anpassung von heute Morgen auch:)

`2021-05-09 22:24:40.111   impfterminservice   ←[32m[suc] [*7K9J | XXXXX]   Terminpaar gefunden!←[0m
2021-05-09 22:24:40.111   impfterminservice   ←[32m[suc] [*7K9J | XXXXX]   1. Termin: 10.05.2021 um 10:40 Uhr←[0m
2021-05-09 22:24:40.341   impfterminservice   ←[32m[suc] [*7K9J | XXXXX]   Termin erfolgreich gebucht!←[0m`

**Comment by iamnotturner** [comment]
- und dann auch direkt morgen früh um 10 Uhr! Freut mich sehr, danke für das gute Feedback 🤗
