### ISSUE TITLE
Automatische Buchung nicht möglich

### ISSUE THREAD

**Issue by prinze2021** [iamnotturner/vaccipy#315]
Hallo und DANKE erst einmal für die Mühe hier. Bin ja froh das ich mit NULL Ahnung von PC`s das hinbekommen habe :-) Habe die neue Version installiert, also die ohne GUI, und hatte eben einen freien Termin angezeigt bekommen der aber nicht automatisch gebucht wurde. Habe dann versucht diesen schnell manuell zu buchen, aber der Termin war dann schon vergeben. Mache ich was falsch? Wäre super wenn das wieder automatisch gehen würde da man ja nicht immer am PC sitzt. Ich versuche mal die GUI Version und schaue ob das da auch ist. Danke noch einmal für eure Mühe.

**Comment by iamnotturner** [comment]
Hi, es geht noch immer automatisch. Manchmal kommt es vor, dass ein Termin nicht gebucht werden kann. Dann einfach weiterlaufen lassen und auf einen anderen Termin warten 😊

**Comment by Pratikk17** [comment]
> Hallo und DANKE erst einmal für die Mühe hier. Bin ja froh das ich mit NULL Ahnung von PC`s das hinbekommen habe :-) Habe die neue Version installiert, also die ohne GUI, und hatte eben einen freien Termin angezeigt bekommen der aber nicht automatisch gebucht wurde. Habe dann versucht diesen schnell manuell zu buchen, aber der Termin war dann schon vergeben. Mache ich was falsch? Wäre super wenn das wieder automatisch gehen würde da man ja nicht immer am PC sitzt. Ich versuche mal die GUI Version und schaue ob das da auch ist. Danke noch einmal für eure Mühe.
> ![capture_001_04062021_090635](https://user-images.githubusercontent.com/84878386/120760245-31c5da80-c514-11eb-9737-4cb501d50944.jpg)

Do you have latest version of Chrome installed? Is this error related to web-browser and its version? @iamnotturner
