### ISSUE TITLE
IP Bann

### ISSUE THREAD

**Issue by Qopixe** [iamnotturner/vaccipy#316]
Hallo zusammen,

ich befürchte, dass ich einen Perm Bann kassiert habe. 
Hatte extrem viele fenster von Vaccipy offen und habe es über Stunden laufen lassen. Und in allen Fenstern stand, dass meine IP adresse wegen zu vielen Anfragen gebannt wird. Leider habe ich davon kein Screenshot, hatte es erst für einen Tempban gehalten. Aber heute verbindet der Bot auch nicht...
Er bleibt immer bei Browser-Cookies generieren ohne Fehlermelden stehen.

Kennt das jemand? Hat einer da einen Ausweg gefunden?

Will eig vermeiden ab jetzt mit VPN oÄ zu arbeiten.

Grüße,

Julian

**Comment by pancakeDevelopment** [comment]
Hi,
gestern wurden einige Änderungen seitens Impfterminservice durchgeführt.
Lad dir am besten mal die aller neuste Version herunter, erstelle die Kontaktdaten neu und probiere es erneut.

**Comment by Qopixe** [comment]
Danke, probiere ich!

**Comment by Floskinner** [comment]
Hey,

mal ne Frage, wie viele Fenster hattest du denn offen?
Eigentlich braucht man nicht mehr als 2 oder 3 Fenster für 1 Code um recht schnell einen Termin zu finden. Wir wollen mit dem Bor ja nicht die Server mit Anfragen bombadieren und den Service lahmlegen

**Comment by iamnotturner** [comment]
> Hey,
> 
> 
> 
> mal ne Frage, wie viele Fenster hattest du denn offen?

und mit welchem Retry-Delay hast du sie laufen lassen?

**Comment by Qopixe** [comment]
Hey Floskinner,
ich hatte 20 Tabs offen nachdem ich jetzt nach 1 1/2 Tagen keinen Termin gefunden hatte, aber zeitnah einen brauchte.

**Comment by Qopixe** [comment]
Mit dem GUI läuft es jetzt, danke euch! 
Hatte mit der alten Version auch aus unterschiedlichen Gruppen gesucht.
Thread kann hier geschlossen werden.

**Comment by iamnotturner** [comment]
> ich hatte 20 Tabs offen nachdem ich jetzt nach 1 1/2 Tagen keinen Termin gefunden hatte, aber zeitnah einen brauchte. 

20 Tabs ist absurd und ändert nichts an der Wahrscheinlichkeit, einen Termin zu bekommen. Ich bitte dich vernünftig zu bleiben.

**Comment by Qopixe** [comment]
> > ich hatte 20 Tabs offen nachdem ich jetzt nach 1 1/2 Tagen keinen Termin gefunden hatte, aber zeitnah einen brauchte.
> 
> 20 Tabs ist absurd und ändert nichts an der Wahrscheinlichkeit, einen Termin zu bekommen. Ich bitte dich vernünftig zu bleiben.
Ja, werde ich nun. Danke für eure Aufklärung. Hatte es für normal gehalten, mehrere Tabs geöffnet zu haben.
