### ISSUE TITLE
Geburtsdatum erforderlich für Anforderung des Codes

### ISSUE THREAD

**Issue by ToppAce** [iamnotturner/vaccipy#317]
Bei der Anforderung des SMS codes, erhielt ich immer den folgenden Fehler:
 > Code kann nicht angefragt werden: {"error":"Geburtsdatum ungueltig oder in der Zukunft"}

Scheinbar ist nun ebenfalls die Angabe des Geburtsdatums erforderlich. Die Ergänzung von
`"birthday": "JJJJ-MM-DD"`
bei data in code_anfordern() in der Datei its.py hat das Problem gelöst.

**Comment by iamnotturner** [comment]
Hi, das Problem wurde in Version 1.1.5 bereits behoben :-) einfach neu downloaden

**Comment by ToppAce** [comment]
> 
> 
> Hi, das Problem wurde in Version 1.1.5 bereits behoben :-) einfach neu downloaden

Ah danke, mein Fehler. Ich dachte ich hätte die aktuellste Version, da ich das Repo erst frisch geclont hatte.
