### ISSUE TITLE
Cookies können nicht generiert werden

### ISSUE THREAD

**Issue by StarsKy1990** [iamnotturner/vaccipy#318]
Anscheinend wurde etwas an der Webseite umgestellt und jetzt stimmt der xpath für den Button "Alle cookies bestätigen" nicht mehr. 

Habe es gerade bei mir umgestellt und jetzt läuft es wieder:

`        # Klick auf "Auswahl bestätigen" im Cookies-Banner
        # Warteraum-Support: Timeout auf 1 Stunde
        button_xpath_old = ".//html/body/app-root/div/div/div/div[2]/div[2]/div/div[1]/a"
        button_xpath = "/html/body/app-root/div/div/div/div[3]/div[2]/div/div[2]/a"
`

Die Zeile befindet sich in its.py in "def driver_enter_code"

**Comment by iamnotturner** [comment]
bitte nochmal die neuste Version downloaden, Problem wurde bereits behoben :-)

**Comment by Alexanderstaehle** [comment]
Hey :) kann es sein dass der master branch die updates noch nicht bekommen hat?

**Comment by iamnotturner** [comment]
hey @Alexanderstaehle doch eigentlich schon - gehts bei dir nicht?

**Comment by Alexanderstaehle** [comment]
Ne bekomme leider dauernd timeouts oder SessionNotCreatedExceptions

**Comment by iamnotturner** [comment]
das ist ein bekanntes Problem, hängt mit Chromedrivern zusammen. Kannst du mal schauen, ob bei dir im Task-Manager Chrome-Tasks oder Chromedriver-Tasks offen sind?

**Comment by Alexanderstaehle** [comment]
Ahh ja das hat geholfen :) dankeschön! Allerdings ist für mich das Problem mit der Eingabe des Geburtstags nicht gefixt, im json file ist dafür auch kein extra attribut, ist das so geplant?

**Comment by iamnotturner** [comment]
> Ahh ja das hat geholfen :) dankeschön! Allerdings ist für mich das Problem mit der Eingabe des Geburtstags nicht gefixt, im json file ist dafür auch kein extra attribut, ist das so geplant?

Hey alexander, hat sich das Problem behoben? Master ist jetzr aufm aktuellsten Stand und Release 1.1.8 ist auch raus.

**Comment by Alexanderstaehle** [comment]
Hi sorry dass ich mich erst jetzt melde :) Das hats gefixt dankeschön euch! Spendenaktion ist auch eine richtig nice idee :)
