### ISSUE TITLE
Cookies werden nicht generiert

### ISSUE THREAD

**Issue by Gudwud** [iamnotturner/vaccipy#320]
Das Programm startet nicht mehr. Um genauer zu sein wenn ich es öffne und die Terminsuche startet geht es bis zu dem Punkt wo es die cookies generiert aber von dort aus geht es nicht mehr weiter
![Vaccipy Problem](https://user-images.githubusercontent.com/85011320/120810285-2e9a1100-c54b-11eb-8bac-1e087f9a76cc.png)

**Comment by sinun98** [comment]
Hi, 
verwendest du die neuste Version? https://github.com/iamnotturner/vaccipy/releases/latest/download/vaccipy_installer.exe

**Comment by Gudwud** [comment]
Oh habe nicht bemerkt dass es eine neu Version gibt Sry

**Comment by sinun98** [comment]
Damit sollte es funktionieren. Sonst nochmal melden bitte.
