### ISSUE TITLE
error: Geburtsdatum ungueltig oder in der Zukunft

### ISSUE THREAD

**Issue by braindeath0815** [iamnotturner/vaccipy#322]
Bei der Generierung des Impfcodes kommt es zu folgendem Fehler:

> Leistungsmerkmal: L921
[inf] [*4NI6 | 72072]   Browser-Cookies generieren
[inf] [*4NI6 | 72072]   Code eintragen und Mausbewegung / Klicks simulieren. Dieser Vorgang kann einige Sekunden dauern.
[err] [*4NI6 | 72072]   Code kann nicht angefragt werden: {"error":"Geburtsdatum ungueltig oder in der Zukunft"}

Das Broserfenster öffnet sich. Es wird ein "Ungültiger Vermittlungscode" Vermittlungscode eingegeben (siehe Bild). Nach einer Weile schließt sich das Fenster und auf der Console wird der Fehler ausgegeben.  
Ich vermute dass (neuerdings?) irgendwo ein Geburtsdatum eingegeben werden muss. Ich konnte das allerdings noch nicht verrifizieren da ich es bisher nicht geschafft habe zu dieser Stelle vorzudringen.  

![Screenshot_20210604_161423-1](https://user-images.githubusercontent.com/85354471/120815699-5d66b600-c550-11eb-8ecf-0967e47ef5f3.png)

**Comment by iamnotturner** [comment]
Hey, bitte [neuste Version herunterladen](https://github.com/iamnotturner/vaccipy/releases/tag/v1.1.5)

**Comment by braindeath0815** [comment]
danke! bit der Beta tut es.
