### ISSUE TITLE
"error":"Geburtsdatum ungueltig oder in der Zukunft"

### ISSUE THREAD

**Issue by leo513** [iamnotturner/vaccipy#323]
Hallo Zusammen,

ich bekomme bei der Impf-Code erzeugung folgenden Fehler: "error":"Geburtsdatum ungueltig oder in der Zukunft"
laut der readme wir das Geburtsdatum ja nicht benötigt, ist das neu?

**Comment by iamnotturner** [comment]
Hey, bitte [neuste Version herunterladen](https://github.com/iamnotturner/vaccipy/releases/tag/v1.1.5)
