### ISSUE TITLE
Viruswarnung bei neuesten Builds

### ISSUE THREAD

**Issue by BlackScreen** [iamnotturner/vaccipy#33]
Hallo,
erstmal: vielen Dank für dieses Tool, es hat mir bereits einen Termin "besorgt". :)

Ich wollte gerade die neueste Version runter laden, dann kam direkt vom Windows Defender eine Meldung.
Ich hab die ZIP-Datei vom ganzen Repository mal bei VirusTotal hoch geladen.
https://www.virustotal.com/gui/file/7cd63a7206affeedc8ff598cef54d6d1aec0a597200d38da073b2686a6fa3b8a/detection

Es wäre klasse, wenn die Builds wieder ohne Viruswarnung kämen. :)

**Comment by JuliusJacobitz** [comment]
Hab mich etwas eingelesen und es müsste an einem fehlenden Code-Zertifikat scheitern. Um das zu umgehen wollte ich [fbs](https://build-system.fman.io/) nutzen, was in der kostenlosen Version leider nur Python <= 3.6 unterstützt. (Wir aber dependencies zu 3.9 haben). 
Ich bin unsicher ob der Switch auf 3.6 Lohnt @iamnotturner 
Bin weiterhin auf der Suche nach der richtigen Lösung. 

Wer andere Alternativen oder Methoden kennt, immer gern her damit ! :)

**Comment by BlackScreen** [comment]
Komisch, mit den aktuellsten Builds meckert mein Defender nicht mehr.

Trotzdem gibts bei VirusTotal immer noch einige Warnungen:
https://www.virustotal.com/gui/file/911955398f5e8c86550854ecdc3cfda0d5980082a9b74cccf19e1be1c6b26593/detection

Danke auf alle Fälle für eure Mühe. Das Tool ist wirklich großartige und eine tolle Hilfe!

**Comment by JuliusJacobitz** [comment]
Denke wenn man die Datei einmal zugelassen hat, meldet er sich nicht mehr :)

**Comment by brainbite** [comment]
Also ich habe immer noch eine Virus-Warnung. Was bedeutet das denn? Ist jetzt ein Virus in den Dateien oder nict?

**Comment by iamnotturner** [comment]
Hi & nein, da ist kein Virus in den Dateien 😄

Dein Defender meckert, weil das eine nicht bekannte Anwendung ist mit unbekanntem Code.
@JuliusJacobitz korrigiere mich, aber ich glaube, dass sich daran gerade nicht viel rütteln lässt (außer wie schon erwähnt über ein Codezertifikat?). Vielleicht hat hier jemand eine Expertise und kann uns helfen, von der Virus-Meldung loszukommen.

Alternativ besteht natürlich die Möglichkeit, den Code direkt auszuführen. 
Dadurch dass der Sourcecode offen zugänglich ist, kann man genau nachverfolgen, was das Programm genau macht.
Du benötigst dazu Python3.9 und Pip zur Installation der Module. Wie das genau geht findest du in der README oder im Internet. 

Wir lassen den Thread hier offen. Wenn wir eine Lösung finden, wird es hier ein Update geben.

**Comment by brainbite** [comment]
Super! Dann beachte ich da die Warnung mal nicht weiter und probiere das Tool aus. Vielen Dank für eure tolle Arbeit!

**Comment by iamnotturner** [comment]
Wir haben noch keine Lösung dafür, aber [DASDING haben in ihrem Beitrag](https://www.dasding.de/update/wie-impftermin-einfacher-bekommen-100.html) einen Workaround vorgeschlagen:

"[...] Um das Tool dann zum Laufen zu bringen, könntest du zum Beispiel eine [Ausnahme in den Windows-Sicherheiteinstellungen hinzufügen.](https://support.microsoft.com/de-de/windows/hinzufügen-eines-ausschlusses-zu-windows-sicherheit-811816c0-4dfd-af4a-47e4-c301afe13b26)"

**Comment by JuliusJacobitz** [comment]
Update: Ich habe einen Installer erstellt, mit dem es keine Viruswarnungen mehr geben sollte. Push kommt morgen :)

**Comment by JuliusJacobitz** [comment]
Installers now available on the beta branch!
