### ISSUE TITLE
Code generierung: Geburtsdatum ungueltig oder in der Zukunft

### ISSUE THREAD

**Issue by TheMrPhantom** [iamnotturner/vaccipy#330]
```
2021-06-04 21:04:24.793   impfterminservice   [err] [*OGTM | xxxxx]   Code kann nicht angefragt werden: {"error":"Geburtsdatum ungueltig oder in der Zukunft"}

Die Code-Generierung war leider nicht erfolgreich.
```

**Comment by TheMrPhantom** [comment]
Das Geburtsdatum wird doch gar nicht abgefragt 🤔

**Comment by sinun98** [comment]
Gestern hat sich auf der Seite etwas verändert.
Versuche mal die neuste Version, damit sollte es funktionieren
https://github.com/iamnotturner/vaccipy/releases/tag/v1.1.5

**Comment by TheMrPhantom** [comment]
Ich verwende den master branch auf dem aktuellsten stand

**Comment by sinun98** [comment]
Die ist aktuell noch hinter dem Release 1.1.5

**Comment by TheMrPhantom** [comment]
Hat funktioniert 👍

**Comment by noppelmax** [comment]
Fixed in v1.1.5. Kann geschlossen werden.

**Comment by sinun98** [comment]
> Fixed in v1.1.5. Kann geschlossen werden.

Haben es noch als Info offen für diejenigen, die nicht in die geschlossenen Issues schauen.
