### ISSUE TITLE
Gültigkeit von Impfcode

### ISSUE THREAD

**Issue by chqu1012** [iamnotturner/vaccipy#331]
Hallo zusammen,

weiß zufällig jemand wie lange der Impfcode gültig ist? Ich habe  gestern abend bis heute abend versucht ein Termin zu bekommen aber leider bisher noch nichts bekommen.

Hat da jemand eine Idee?

Viele Grüße

**Comment by sinun98** [comment]
Hallo,
die laufen nicht ab. Einfach solange probieren bis du einen Termin hast. Kann aber durchaus etwas dauern.

**Comment by andoorius** [comment]
> Hallo zusammen,
> 
> 
> 
> weiß zufällig jemand wie lange der Impfcode gültig ist? Ich habe  gestern abend bis heute abend versucht ein Termin zu bekommen aber leider bisher noch nichts bekommen.
> 
> 
> 
> Hat da jemand eine Idee?
> 
> 
> 
> Viele Grüße

Mehrere Wochen (aus eigener Erfahrung). Vermutlich kein "Verfallsdatum" hatte mal auf ner offizielle Seite gelesen, dass bei den ganz alten Codes noch nicht die Impfstoffe ans Alter gekoppelt sind und man neue erstellen soll, um keine "falschen" Impfstoffe angeboten zu bekommen....
Er word einfülltet, wenn Du 2x nen Termin storniert hast.
Das kann durchaus dauern... geht aber teilweise auch in Minuten -  nichts ungewöhnliches.

**Comment by chqu1012** [comment]
> > Hallo zusammen,
> > weiß zufällig jemand wie lange der Impfcode gültig ist? Ich habe  gestern abend bis heute abend versucht ein Termin zu bekommen aber leider bisher noch nichts bekommen.
> > Hat da jemand eine Idee?
> > Viele Grüße
> 
> Mehrere Wochen (aus eigener Erfahrung). Vermutlich kein "Verfallsdatum" hatte mal auf ner offizielle Seite gelesen, dass bei den ganz alten Codes noch nicht die Impfstoffe ans Alter gekoppelt sind und man neue erstellen soll, um keine "falschen" Impfstoffe angeboten zu bekommen....
> Er wird ungültig, wenn Du 2x nen Termin storniert hast.
> Das ganze kann durchaus dauern... geht aber teilweise auch in Minuten - nichts ungewöhnliches.

Sieht man dass es dann ungültig wird, zum Beispiel beim 2x stornieren?

**Comment by sinun98** [comment]
> > > Hallo zusammen,
> > > weiß zufällig jemand wie lange der Impfcode gültig ist? Ich habe  gestern abend bis heute abend versucht ein Termin zu bekommen aber leider bisher noch nichts bekommen.
> > > Hat da jemand eine Idee?
> > > Viele Grüße
> > 
> > 
> > Mehrere Wochen (aus eigener Erfahrung). Vermutlich kein "Verfallsdatum" hatte mal auf ner offizielle Seite gelesen, dass bei den ganz alten Codes noch nicht die Impfstoffe ans Alter gekoppelt sind und man neue erstellen soll, um keine "falschen" Impfstoffe angeboten zu bekommen....
> > Er wird ungültig, wenn Du 2x nen Termin storniert hast.
> > Das ganze kann durchaus dauern... geht aber teilweise auch in Minuten - nichts ungewöhnliches.
> 
> Sieht man dass es dann ungültig wird, zum Beispiel beim 2x stornieren?

Ja da kommt dann "Anspruch abgelaufen"
