### ISSUE TITLE
[Feature/Bug] Suche beenden 'x' macht Fenster zu 

### ISSUE THREAD

**Issue by andoorius** [iamnotturner/vaccipy#332]
Wenn man die Suche beenden möchte, kommt der Hinweise: Ausgabe prüfen!
Will ich das nun tun und klicke statt 'OK' das rote 'x' schließen sich beide Fenster und *zack* es gibt nichts mehr zu prüfen :-)

Idee: Das rote 'x' schließt nur das Hinweisfenster oder 'Abbrechen' Button implementieren.

**Comment by Floskinner** [comment]
Hey
habe es etwas anders gelöst. Wenn man auf "Ok" drückt wird einfach der Hinweis geschlossen :D
Möchte man dann das ganze Ausgabefenster schließen, kann man unten auf "Close" oder auf "x" drücken

**Comment by sinun98** [comment]
Fiexed mit [v1.1.8](https://github.com/iamnotturner/vaccipy/releases/tag/v1.1.8)
