### ISSUE TITLE
[Feature] VersionsNr. bei Downloads und im geöffneten Fenster

### ISSUE THREAD

**Issue by juziegle** [iamnotturner/vaccipy#333]
Hey,
es wäre cool, wenn im "Code"-Tab bei "Downloads" die Versionsnummer stehen würde (z.B. neben dem Windows Logo) und zusätzlich wäre es nicht schlecht, wenn die Nr. auch im geöffneten vaccipy-Fenster stehen würde (also als Fenstername, wo bislang nur "vaccipy" steht oder irgendwo anders).

**Comment by iamnotturner** [comment]
Duplikat zu #255, das Festure kommt am Wochenende. Danke :-)
