### ISSUE TITLE
Terminpaare können nicht geladen werden: 401 Unauthorized

### ISSUE THREAD

**Issue by megaherox** [iamnotturner/vaccipy#334]
Hi erhalte jedes mal mit der neusten Version folgenden Fehler:
![image](https://user-images.githubusercontent.com/30510004/120870713-e2c28880-c599-11eb-928c-c11e4fdd26a6.png)

Was mach ich falsch?

**Comment by megaherox** [comment]
https://001-iz.impfterminservice.de/impftermine/service?plz=68163 vermittlungscode wäre falsch wenn ich die Webseite aufruf.
Sobald ich https://002-iz.impfterminservice.de/impftermine/service?plz=68163 auswähle nimmt er es.... leider aber nicht im script hier kommt immer wieder 401...

**Comment by chqu1012** [comment]
Ich hatte das Problem auch gehabt, dann habe ich pro ImpfKreis ein Vaccipy Instanz gestartet, damit gehts.

**Comment by iamnotturner** [comment]
Hey, wie's aussieht haben sich die Gruppierungen (von `001.` zu `002.`) geändert, deshalb klappt das mit dem Code nicht mehr. Ich update nachher die Liste
