### ISSUE TITLE
Script hängt sich auf "Code eintragen und Mausbewegung / Klicks simulieren."

### ISSUE THREAD

**Issue by Fawkes83** [iamnotturner/vaccipy#335]
Hi, bei der Code-Generierung scheint sich das Script aufzuhängen.

Das geöffnete Chrome Fenster bleibt einfach offen, aber es tut sich nichts.
Schließt man das Fenster manuell kommt folgendes Fehlermeldung:
[err] [renew_cookies_code]   WebDriverException exception raised - retry 2

Chromium Driver habe ich ausgetauscht

<img width="704" alt="error_vaccipy" src="https://user-images.githubusercontent.com/85375260/120872630-86626780-c59f-11eb-88d3-d7f491ef90d9.png">

**Comment by iamnotturner** [comment]
Hey, wie lange bleibt das Fenster offen? Es dauert ein paar Sekunden bis die Cookies generiert werden

**Comment by Fawkes83** [comment]
Hi, unendlich lange.

es kommt auch kein error solange man nicht das geöffnete Chrome Fenster schließt.
Meine Chrome Version ist: 91.0.4472.77
Chrome Driver den ich verwendet habe: https://chromedriver.storage.googleapis.com/index.html?path=91.0.4472.19/
Dies ist die letzte verfügbare Version.

![image](https://user-images.githubusercontent.com/85375260/120884353-0958e180-c5e3-11eb-8f02-4c6f31eebaa0.png)

**Comment by iamnotturner** [comment]
Nutzt du Version 1.1.1?

**Comment by Fawkes83** [comment]
Hi,

ok 1.1.5 funktioniert, allerdings überspringt er den Schritt zu welcher Altersklasse man gehört und fragt direkt nach dem Geburtsdatum. Woran könnte das liegen?

**Comment by sinun98** [comment]
> Hi,
> 
> ok 1.1.5 funktioniert, allerdings überspringt er den Schritt zu welcher Altersklasse man gehört und fragt direkt nach dem Geburtsdatum. Woran könnte das liegen?

Das wird jetzt am Geburtsdatum ermittelt.

**Comment by Fawkes83** [comment]
Unter v1.1.5 läuft es. Super danke!
