### ISSUE TITLE
Readme.md: Rechtschreibfehler

### ISSUE THREAD

**Issue by Perrschy** [iamnotturner/vaccipy#338]
Nur eine Kleinigkeit, die gerne übersehen wird: es kommt ein paar Mal „erhälst“ in der Readme vor, es heißt „erhältst“ (von erhalten). Ansonsten: danke für das tolle Projekt!

**Comment by sinun98** [comment]
Danke für den Hinweis :)

**Comment by iamnotturner** [comment]
behoben in #341
