### ISSUE TITLE
ACHTUNG Windows exe enthält Trojaner Wacatac

### ISSUE THREAD

**Issue by Koseng** [iamnotturner/vaccipy#347]
Seid ihr gehackt worden?
Bei der aktuellen Windows .exe wird mir ein Trojaner gemeldet.

![image](https://user-images.githubusercontent.com/26673978/120916740-8f405f80-c6ab-11eb-9844-ef91b0779fa5.png)

**Comment by iamnotturner** [comment]
Hi, die Virusmeldung ist ein bekanntes Problem, siehe https://github.com/iamnotturner/vaccipy/issues/128
Das liegt daran, dass der Code nicht verifiziert ist und Windows das Programm nicht erkennt.

Um sicher zu gehen raten wir immer dazu, das Programm direkt mit Python auszuführen.
