### ISSUE TITLE
Impf-Code generieren scheitert an Botprotection

### ISSUE THREAD

**Issue by AccidentalCalzone** [iamnotturner/vaccipy#349]
![image](https://user-images.githubusercontent.com/85437998/120922004-046d5e00-c6c7-11eb-87bf-251a2c2880e4.png)

Der Schritt "Browser-Cookies generieren" scheitert an der Botprotection und der Prozess beginnt erneut. Auch manuelles Bewegen/Klicken der Maus ändert daran nichts. Getestet mit Version 1.1.8 auf Windows 10 und Ubuntu 21.04.

**Comment by pancakeDevelopment** [comment]
Also ich hatte eben auch mehrere Anläufe benötigt. Nachdem ich dann mehrere Elemente angeklickt und andere Codes eingegeben hatte funktionierte die Code Generierung.

**Comment by iamnotturner** [comment]
Hey, welche Version verwendest du?

**Comment by iamnotturner** [comment]
Nutzt du vaccipy in einer Desktop-Umgebung? @AccidentalCalzone

**Comment by AccidentalCalzone** [comment]
@iamnotturner GNOME/Ubuntu und Modern UI/Windows

Ich habe jetzt (pancakeDevelopment's Kommentar folgend) durch frenetisches Klicken bzw. die Eingabe zufälliger Zeichenfolgen tatsächlich irgendwann einen Code erhalten. Einfach war das allerdings nicht, da es das Skript nach Eingabe des SMS-Codes für nötig hielt, die Cookies zu erneuern und auch hier wieder die Botprotection griff. Auch dies konnte ich durch Eingabe zufälliger Zeichenfolgen irgendwann umgehen, was allerdings erheblich erschwert wurde durch den Umstand, dass in diesem Schritt kein 30-Sekunden-Zeitfenster vorgesehen ist.

**Comment by alexanderrock** [comment]
@iamnotturner
Wenn es mit Botprotection fehlschlägt klappt es, wenn man einen anderen code verwendet
->es muss ein neuer Vermittlungscode generiert werden

-> VACC-IPY1-2345
-> Schlägt Fehl
-> VACC-IPY2-3456
-> funktioniert wieder

**Comment by iamnotturner** [comment]
> @iamnotturner
> 
> Wenn es mit Botprotection fehlschlägt klappt es, wenn man einen anderen code verwendet
> 
> ->es muss ein neuer Vermittlungscode generiert werden
> 
> 
> 
> -> VACC-IPY1-2345
> 
> -> Schlägt Fehl
> 
> -> VACC-IPY2-3456
> 
> -> funktioniert wieder

Hast du den Code dann manuell im Fenster kurz geändert?

**Comment by alexanderrock** [comment]
@iamnotturner
Sowohl im Fenster geändert als auch dann mal in der kontaktdaten.json probiert, geht beides

**Comment by pancakeDevelopment** [comment]
**Meine Erfahrung war folgende:**

1. Tritt "Es ist ein unbekannter Fehler aufgetreten" nach Eingabe von VACC-IPY1-2345 auf, dann klappts nicht
2. Tritt "Ungültiger Vermittlungscode" auf, dann ging es bei mir

**Comment by lynix** [comment]
Ich erhalte _"Es ist ein unbekannter Fehler aufgetreten"_, egal wie viele Objekte ich anklicke oder was ich in die Textboxen für den temporären Code einschleuse.

Wenn ich das Ganze manuell (Firefox) durchspiele, erhalte ich _"Ungültiger Vermittlungscode"_. Sieht so aus, als hätten die ihre Bot-Protection verbessert...

**Comment by cr1979** [comment]
Bei mir wurde ein Code in der Konsole generiert und wurde im Browser automatisch eingetragen. Bekomme jedoch im Browser ein 423 Too Many Requests. Wenn ich einen anderen Browser öffne und den Code eingebe, bekomme ich "Ungültiger Vermittlungscode". Sind die refreshes nicht ein bisschen zu schnell hintereinander im Warteraum?

**Comment by cr1979** [comment]
Ok noch einmal probiert und den refresh Timer auf 60 Sekunden gestellt, aber jetzt bekomme ich "Anfrage wurde von der Botprotection geblockt. Die Cookies müssen manuell im Browser generiert werden"

**Comment by iamnotturner** [comment]
haben eine Lösung in Aussicht.

**Comment by iamnotturner** [comment]
sollte fixed sein mit #395
