### ISSUE TITLE
Impf-code

### ISSUE THREAD

**Issue by ericzhou571** [iamnotturner/vaccipy#35]
Könnten Sie mir sagen, wo kann impf-code bekommen? Es ist ein ID wie Versicherungsnummer?

**Comment by iamnotturner** [comment]
Hey! Den Impfcode bekommst du hier: 

https://www.impfterminservice.de/impftermine

Du musst erst dein Impfzentrum auswählen, dann wirst du gefragt, ob du schon einen Code hast. Dort klickst du auf Nein und wenn du Glück hast, kannst du auf Anhieb einen Code für dich erstellen.

Es kann sein, dass vorübergehend keine Codes verfügbar sind. Es braucht etwas Gelduld, aber die kommen aber alle paar Tage wieder rein. Für eine Übersicht, wo es gerade Codes gibt, kannst du hier schauen:

https://www.impfterminübersicht.de

**Comment by ericzhou571** [comment]
Vielen Dank!
