### ISSUE TITLE
Browser Cookies können nicht generiert werden

### ISSUE THREAD

**Issue by leoniegit** [iamnotturner/vaccipy#353]
![image](https://user-images.githubusercontent.com/84661575/120932237-4614fd80-c6f5-11eb-9c8b-b33f93a8556a.png)

Ich erhalte immer diesen Fehler beim Versuch Browser Cookies zu generieren.

**Comment by iamnotturner** [comment]
Hi, in deiner Fehlermeldung steht schon die Lösung: du hast Chrome Version 90 installiert, brauchst aber Version 91. Also einfach deinen Chrome-Browser updaten auf Version 91 und es läuft wieder.

**Comment by leoniegit** [comment]
Oh gott, wie doof von mir. Danke für die schnelle Antwort, jetzt funktioniert es natürlich wieder. Ganz großes Lob an dich für diese tolle Tool!
