### ISSUE TITLE
Terminsuche fuer 12-16 Jahre (BW)

### ISSUE THREAD

**Issue by VolkerH** [iamnotturner/vaccipy#355]
Hallo,
ein Bekannter von mir versucht fuer seine Tochter im Alter 12-16 einen Impfcode fuer BW zu generieren.
Er bekommt die Fehlermeldung "ermitteltes Leistungsmerkmal ungueltig".
Ich vermute, dass hier zu `"L920" ... "L923"` noch ein weiterer Code hinzugefuegt werden muss.

**Comment by iamnotturner** [comment]
Hi, die Leistungsmerkmale werden dynamisch von der API geladen. Vermutlich wird der Impfterminservice bald die Leistungsmerkmale anpassen, bzw. Codes auch für U18-Personen anbieten.

**Comment by markusstoll** [comment]
In BW gabs doch einen Rückzieher. 12-16 Jahre nur in medizinischen Ausnahmen, solange die Stiko das nicht explizit freigibt. Ich nehme an, solange wird da nix gehen…

**Comment by VolkerH** [comment]
@markusstoll 
Ok, wusste ich nicht. Auf der BW Impfzentrum FAQ Seite steht davon nichts https://www.baden-wuerttemberg.de/en/service/aktuelle-infos-zu-corona/faq-impfzentren/ 
Momentan steht da noch:

> Ab dem 7. Juni 2021 können alle Personen ab 12 Jahren unabhängig von Alter, Vorerkrankungen und Beruf ohne weitere Voraussetzungen einen Impftermin in einem Impfzentrum vereinbaren.

**Comment by VolkerH** [comment]
@markusstoll 
Ok, Quelle fuer Info von @markusstoll  via SWR https://www.swr.de/swraktuell/baden-wuerttemberg/corona-impfreihenfolge-in-baden-wuerttemberg-faellt-weg-100.html

> Über das bundesweite Online-Portal seien Buchungen für Kinder in Baden-Württemberg erst ab der Freigabe durch die Stiko reservierbar, so ein Ministeriumssprecher gegenüber dem SWR. 

Da wurde wohl am Wochenende die FAQ nicht auf den aktuellen Stand gebracht. Von daher eigentlich kein issue fuer vaccipy mehr, kann  gerrne geschlossen werden.

**Comment by markusstoll** [comment]
Zumindest das Impfzentrum Liederhalle hatte das gestern abend auch schon explizit ausgeführt:

https://www.klinikum-stuttgart.de/aktuell-im-klinikum/presse/zentrales-impfzentrum

**Comment by iamnotturner** [comment]
Issue kann erstmal noch offen bleiben als Information für andere. Danke @markusstoll mark

**Comment by apeltzer** [comment]
Feedback: Bekannter war heute (15 Jahre) in RT, das hat wohl geklappt - ist halt wieder wie bei Schwangeren o.Ä. und direkt vom Gespräch mit dem zuständigen Arzt abhängig und kein "generell freigegeben ab 12".

**Comment by Raus-noett** [comment]
War gestern in Rheinstetten mit 15 jährigen Kind. Code war für 16-18J, also Biontech. Gespräch mit Arzt und geimpft. Hat Ausnahme von STIKO notiert und unterschreiben lassen.
