### ISSUE TITLE
Vermittlungscode ungültig, wenn ich ihn auf 116117 eingebe. Normal?

### ISSUE THREAD

**Issue by typu3yy9** [iamnotturner/vaccipy#356]
Wie der Titel schon sagt, ich habe eine Woche laufen lassen und keinen Termin bekommen. Wollte daraufhin mal manuell testen ob der Code auch wirklich geht un dich bekomme einen Error, dass der Code ungültig ist. Ist das normal?

**Comment by iamnotturner** [comment]
Hey, hast du den Code beim gleichen Impfzentrum wie im Programm getestet? Wenn der Code ungültig wäre, würde auch die Terminsuche in vaccipy nicht mehr funktionieren.
