### ISSUE TITLE
Benötige ich eine GUI?

### ISSUE THREAD

**Issue by marvin-te** [iamnotturner/vaccipy#361]
Moin,
nur eine schnelle Frage, da ich bisher nicht zu 100% aus den READMEs schlau geworden bin:

Benötigt der Bot auf Linux eine GUI (X11), um Chromium zu starten? Oder kann ich den Bot auch auf meinem Headless Server laufen lassen?

Ansonsten kann ich nur sagen: Klasse Sache! Sehr umfangreich und das Erstellen der Codes hat schonmal super funktioniert.

LG

**Comment by sinun98** [comment]
Hi, Headless wird leider nicht unterstützt.

**Comment by aventu90** [comment]
Ich habe es headless auf einem Ubuntu Server laufen lassen und es funktioniert so weit. Ich hatte leider eine Fehlermeldung bei der Terminbuchung. Ob es an der headless Konfiguration lag weiß ich nicht.

**Comment by sinun98** [comment]
Ja die Suche ist headless möglich. Für die Buchung wird aber zwingend die GUI benötigt um valide Cookies zu generieren.

**Comment by marvin-te** [comment]
Danke für die zahlreichen und schnellen Antworten. :)
