### ISSUE TITLE
Possibly blacklisted/improved bot protection?

### ISSUE THREAD

**Issue by DaveDavesen** [iamnotturner/vaccipy#362]
I usually saw a cookie refresh every 2 hours, the last regular one today at 05:30. At 06:57 it found a open spot, but could not book it and did a cookie refresh and then could still not book it. That was the last time it did a cookie refresh until now (18:28). Is this a bug/change in behavior of the website regarding cookies? Or was I just unlucky?
Version is 1.1.8 on Windows 10. I added the logfile here:
[vaccipylogfile.txt](https://github.com/iamnotturner/vaccipy/files/6610616/vaccipylogfile.txt)
(Name and  booking code were removed)

**Comment by sinun98** [comment]
You were just unlucky. There is a error if someone was faster then you. "Der Termin wurde in der Zwischenzeit blockiert und steht nicht mehr zur Verfügung. Bitte wählen Sie einen anderen Termin aus." 
At the moment we dont catch this error.

**Comment by DaveDavesen** [comment]
But why do I not get every two hours an "Timeout exception raised" with new generation of browser-cookies anymore? Should I restart it?
With the other instance on the same PC (another vaccination center group) it still happens at the expected times on the same day.
[vaccipylog2.txt](https://github.com/iamnotturner/vaccipy/files/6610853/vaccipylog2.txt)

**Comment by sinun98** [comment]
Everything looks good. Just let it run.
