### ISSUE TITLE
Aktuell Wartungsarbeiten beim Impfterminservice 

### ISSUE THREAD

**Issue by Teodoru** [iamnotturner/vaccipy#364]
Bei der Code-Generierung erscheint bei mir alle 30 Skunden die folgende Fehlermeldung:

[err] [impfzentren_laden] JSON parsing exception | IP gebannt oder Website down, erneuter Versuch in 30 Sekunden

Ich habe auch schon verschiedene Impfzentren durchprobiert und jedes Mal die selbe Fehlermeldung.

Ist dies nur ein vorübergehendes Problem, da Website temporär down oder mache ich was falsch?

**Comment by sinun98** [comment]
Aktuell sind Wartungsarbeiten einfach etwas warten.

**Comment by orthand** [comment]
Unter https://www.impfterminservice.de wurde auf Wartungsarbeiten hingewiesen, war also serverseitig. Hat sich wohl eben geändert, sind wieder online,
