### ISSUE TITLE
Anfrage wurde von Botprotection geblockt

### ISSUE THREAD

**Issue by Teodoru** [iamnotturner/vaccipy#365]
Kann mir jemand bezgl. der folgenden Fehlermeldung weiterhelfen:

![Fehlermeldung](https://user-images.githubusercontent.com/85516310/121074089-a8dcc680-c7d3-11eb-9270-54462cd051a8.jpg)

**Comment by sinun98** [comment]
Hast du Google chrome installiert?

**Comment by mlsxlist** [comment]
Bei mir ist das passiert, als ich nicht den passenden Chromedriver hatte. Ich verwende Debian und der bei vaccipy mitgelieferte Chromedriver passt nicht zum Chrome 90 aus dem Debian Repository . Seit ich den Pfad, zu einem zu meinem Chrome passenden Chromedriver via Environment Variable setze, tritt der Fehler nicht mehr auf

**Comment by Teodoru** [comment]
Danke für den Hinweis. Funktioniert nun
