### ISSUE TITLE
"Es ist ein Unerwarteter Fehler Aufgetreten" bei manueller Eingabe

### ISSUE THREAD

**Issue by OnlyRealMerlin** [iamnotturner/vaccipy#368]
Vaccipy zeigt mir in der Konsole an, dass Keine Termine Verfügbar sind. Wenn ich probiere meinen Vermittlungscode manuell auf der 116117 Seite einzugeben, dann kommt die obengenannte Nachricht. Vermutlich kann das Programm keine Termine finden weil der Code nicht richtig funktioniert?

Die PLZ auf der ich nach Terminen prüfe ist die gleiche wie die, die ich beim kreieren des Vermittlungscodes benutzt habe.

**Comment by pancakeDevelopment** [comment]
Manchmal tritt ein Fehler beim manuellen Aufrufen des Codes auf. Sollte ein Code fehlerhaft sein, dann bekommst du folgende Rückmeldung:

`Ungültiger Vermittlungscode`

Solange vaccipy beim Suchen "keine Termine in X" ausgibt, dann funktioniert auch alles.

**Comment by OnlyRealMerlin** [comment]
Top, danke für die Nachricht. Tolle Arbeit, die ihr hier leistet!

**Comment by sinun98** [comment]
> Vaccipy zeigt mir in der Konsole an, dass Keine Termine Verfügbar sind. Wenn ich probiere meinen Vermittlungscode manuell auf der 116117 Seite einzugeben, dann kommt die obengenannte Nachricht. Vermutlich kann das Programm keine Termine finden weil der Code nicht richtig funktioniert?
> 
> Die PLZ auf der ich nach Terminen prüfe ist die gleiche wie die, die ich beim kreieren des Vermittlungscodes benutzt habe.

Was bekommst du wenn du auf Termin buchen klickst aus der Mail mit dem Vermittlercode?

**Comment by OnlyRealMerlin** [comment]
Der link aus der Mail hatte mich immer zur Seite geschickt, wo man das Bundesland etc. auswählt.

Ich habe mal mit meinen Erweiterungen rumgespielt. Scheinbar mag Ublock Origin die links nicht. Vllt könnt ihr das auch Mal auf euere Seite testen. Aus meinen ca 8 Erweiterungen hat's nur funktioniert, wenn Ublock Origin ausgeschaltet war. Das sollte aber kein Effekt auf die Funktionstüchtigkeit von Vaccipy haben, oder?

**Comment by sinun98** [comment]
Genau das hat keine Auswirkungen auf vaccipy. Wenn du auf die Startseite weitergeleitet wirst im Browser bedeutet das, dass du von dem Bot Schutz geblockt wurdest. Dafür verantwortlich können unter anderem AddBlocker sein.

**Comment by OnlyRealMerlin** [comment]
Genau so hats sich auch ergeben. Bei Firefox gings dann wieder normal. Dran Schuld war Ublock Origin. Adblock+/Disconnect/Sponsorblock hatten keinen Effekt. Hoffentlich bin ich der einzige, der solche ein einfaches problem hatte. 

Bedeutet das also, das Vaccipy nicht direkt über mein Browser läuft? Ich Frage nur, weil es im Browser nicht funktioniert hatte aber in Vaccipy selbst wohl nichts falsch gemeldet wurde.

**Comment by sinun98** [comment]
> Genau so hats sich auch ergeben. Bei Firefox gings dann wieder normal. Dran Schuld war Ublock Origin. Adblock+/Disconnect/Sponsorblock hatten keinen Effekt. Hoffentlich bin nicht ich der einzige, der solch eine einfache Lösung findet.
> 
> Bedeutet das also, das Vaccipy nicht direkt über mein Browser läuft? Ich Frage nur, weil es im Browser nicht funktioniert hatte aber in Vaccipy selbst wohl nichts falsch gemeldet wurde.

Vaccipy verwendet eine eigene frische Chrome Instanz ohne Extensions.
