### ISSUE TITLE
Button "Termin buchen" konnte nicht gedrückt werden.

### ISSUE THREAD

**Issue by prinze2021** [iamnotturner/vaccipy#371]
Ich hatte einen Termin habe ich in der GUI Version gesehen aber da stand "Button Termin buchen konnte nicht gedrückt werden". Habe die Version 1.1.8. Ist da wieder was geändert worden?

**Comment by iamnotturner** [comment]
Hey, das passiert manchmal. Wenn nicht dransteht "Termin wurde erfolgreich gebucht" musst du es einfach weiterprobieren :-)
