### ISSUE TITLE
[err] [termin_suchen] NameError exception raised

### ISSUE THREAD

**Issue by ba0um** [iamnotturner/vaccipy#374]
Bricht ab nach 10 tries:
```
[err] [termin_suchen]   NameError exception raised - retry 10
2021-06-08 10:29:18.980   impfterminservice   [err] [*DXL2 | 68163, 69124, 70174, 70376, 72072, 74585, 76287, 77656, 79108, 89703]   File "tools\utils.py", line 32, in wrapper
File "tools\its.py", line 633, in termin_suchen
NameError: name 'quit' is not defined
```

**Comment by dominikwalk** [comment]
Wurde soeben im beta-branch behoben. Siehe: Issue: #367 Fix: #373

**Comment by ba0um** [comment]
Danke. Kann ich das bei mir manuell ändern? Finde tools\its.py in meinem Verzeichnis nicht?

**Comment by dominikwalk** [comment]
Wenn du dir das repo gecloned oder runtergeladen hast kannst du die Zeile einfach manuell anpassen und das Programm selbst durch den Aufruf `python3 main.py` starten. Achte dabei darauf, dass du vorher alle nötigen module installiert hast:
 (`pip install -requirements.txt`)
Wenn du mit dem build arbeiten möchtest kannst du sie ebenfalls anpassen, musst danach allerdings die software neu builden. Wie das funktioniert findest du hier: 
https://github.com/iamnotturner/vaccipy/blob/412b3e711ef7df758824c782e319d7f7a1e94157/docs/distribution.md

**Allerdings** tritt der Fehler nur dann auf, wenn du zwei (oder mehr) Impfzentren aus unterschiedlichen Gruppen gleichzeitig verwenden möchtest. Dafür musst du die Suche ohnehin mit zwei **unterschiedlichen** Impf-Codes starten. Den Fehler der hier #373 behoben wird, verhindert also nur den `NameError`. Das Programm soll an dieser Stelle abbrechen, da die Impfcodes nicht kombinierbar sind. Hier ebenfalls beschrieben:  #367

**Comment by ba0um** [comment]
Der Fehler tritt auch auf, wenn ich nur Zentren aus einer Gruppe wähle. Habe Gruppen 2 und 5 getestet und jeweils der gleiche Fehler.

**Comment by dominikwalk** [comment]
> Der Fehler tritt auch auf, wenn ich nur Zentren aus einer Gruppe wähle. Habe Gruppen 2 und 5 getestet und jeweils der gleiche Fehler.
> 
> edit: Gruppe 1 funktioniert

Konnte den Fehler bei mir leider nicht reproduzieren. Eventuell kann hier ein anderer weiterhelfen, sorry.

**Comment by ba0um** [comment]
Ich teste nochmal die Gruppen durch. Ansonsten /closed, der zu  Grunde liegende Fehler wurde ja bereits behoben, vgl. oben.
