### ISSUE TITLE
cannot find Chrome binary

### ISSUE THREAD

**Issue by PerennialNovice** [iamnotturner/vaccipy#376]
Hallo,

wollte mir gerade einen Impf-Code genereieren, das scheiterte aber weil irgendwas mit Chromium fehlt.

Habe dann Chromium von https://download-chromium.appspot.com/ installiert, hat aber keine Änderung gebracht

Fehlermeldung ist:
> [err] [*S77L | xxxxx]   File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

Version ist v1.1.8

**Comment by Pestimist** [comment]
OH, achso, OK

bei den Requirements steht Chrome oder Chromium, da dachte ich ist egal was und welche Version

Ich probiers!

Hab auch eben erst gemerkt dass die closed-issues woanders zu finden sind.... hätte da auch mal suchen können...

**Comment by iamnotturner** [comment]
Macht nix, sag einfach Bescheid wenns noch immer nicht klappt.

**Comment by Pestimist** [comment]
funzt!
Dankeschön :)
