### ISSUE TITLE
Fehler 401 - Terminpaare können nicht geladen werden

### ISSUE THREAD

**Issue by Sylwuscha** [iamnotturner/vaccipy#378]
![grafik](https://user-images.githubusercontent.com/84845174/121200525-1c361500-c874-11eb-9991-303e323ce19d.png)

Warum bekomme ich den Fehler plötzlich? War bei meinen Suchen noch nie da? 

Ich suche mit dem Code ja nur für 1 Impfzentrum?

P.S. Leider musste ich ein neues Problem erstellen, da das alte zu diesem Thema schon geschlossen ist und mir nicht weiterhilft.

**Comment by iamnotturner** [comment]
Hey, bitte neue Version runterladen.

401 bedeutet, dass die PLZ vom Impfzentrum nicht zum Code passt.

**Comment by Sylwuscha** [comment]
Könnte ich bitte einen Link zur neuen Version haben. Gestern lief noch alles normal.-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 08.06.21, 16:14, Tim Reibe ***@***.***> schrieb:

Hey, bitte neue Version runterladen.
401 bedeutet, dass die PLZ vom Impfzentrum nicht zum Code passt.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/iamnotturner/vaccipy/issues/378#issuecomment-856805622",
"url": "https://github.com/iamnotturner/vaccipy/issues/378#issuecomment-856805622",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by iamnotturner** [comment]
https://github.com/iamnotturner/vaccipy/releases/latest/download/vaccipy_installer.exe

Eventuell bist du mit den Codes/PLZ durcheinandergekommen

**Comment by Sylwuscha** [comment]
Nein, da war nichts durcheinanderzubringen. Habe heute Nachmittag 3 Codes für Aalen generiert und alle 3 zeigen den gleichen Fehler. Jetzt werde ich den Link von unten probieren.

 
 

Gesendet: Dienstag, 08. Juni 2021 um 16:19 Uhr
Von: "Tim Reibe" ***@***.***>
An: "iamnotturner/vaccipy" ***@***.***>
Cc: "Sylwuscha" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [iamnotturner/vaccipy] Fehler 401 - Terminpaare können nicht geladen werden (#378)


 

https://github.com/iamnotturner/vaccipy/releases/latest/download/vaccipy_installer.exe

Eventuell bist du mit den Codes/PLZ durcheinandergekommen

**Comment by sinun98** [comment]
> Nein, da war nichts durcheinanderzubringen. Habe heute Nachmittag 3 Codes für Aalen generiert und alle 3 zeigen den gleichen Fehler. Jetzt werde ich den Link von unten probieren.

Hier beschreibst du deinen Fehler selbst. Warum generierst du Codes für Aalen aber suchst in Esslingen?

**Comment by Sylwuscha** [comment]
Ich hab mich verschrieben. Ich wollte natürlich Codes für Esslingen schreiben. Aber vielleicht hab ich tatsächlich für 73430 (Aalen) generiert und nicht für 73730 (Esslingen). Danke für den Tipp-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 08.06.21, 18:14, "Simon Bräuninger" ***@***.***> schrieb:




Nein, da war nichts durcheinanderzubringen. Habe heute Nachmittag 3 Codes für Aalen generiert und alle 3 zeigen den gleichen Fehler. Jetzt werde ich den Link von unten probieren.



Hier beschreibst du deinen Fehler selbst. Warum generierst du Codes für Aalen aber suchst in Esslingen?



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/iamnotturner/vaccipy/issues/378#issuecomment-856906614",

"url": "https://github.com/iamnotturner/vaccipy/issues/378#issuecomment-856906614",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Squelsh** [comment]
Vorschlag: Bitte schreibt das auch noch auf die Haupt-Seite, als Warnung:
Ich habe 18h lang das Script laufen lassen, weil ich dachte, dass der 401er Fehler temporär sei...

Nun habe ich neue Codes generiert und schwupp, ist der Fehler weg

**Comment by iamnotturner** [comment]
> Vorschlag: Bitte schreibt das auch noch auf die Haupt-Seite, als Warnung:
> 
> Ich habe 18h lang das Script laufen lassen, weil ich dachte, dass der 401er Fehler temporär sei...
> 
> 
> 
> Nun habe ich neue Codes generiert und schwupp, ist der Fehler weg

@Squelsh hey, wir haben das in den FAQs stehen https://github.com/iamnotturner/vaccipy/issues/116#issuecomment-848690301

Und theoretisch gibt der Bot seit 1.1.8 auch die passende Fehlermeldung aus, in der steht, dass die PLZ nicht zum Code passt.

**Comment by Squelsh** [comment]
Danke @iamnotturner, in den FAQs hatte ich tatsächlich nicht geschaut.
Kann es sein, dass unter Linux auf der CLI die Erleuterung nicht auftaucht, von wegen "PLZ passt nicht zum Code".

Völlig unabhängig: Sau gute Arbeit!! Danke für das Script. Für meine Frau hatte ich nach 8h einen Termin :)

**Comment by iamnotturner** [comment]
> Kann es sein, dass unter Linux auf der CLI die Erleuterung nicht auftaucht, von wegen "PLZ passt nicht zum Code".

sollte eigentlich schon, nutzt du den aktuellen Master?

> Völlig unabhängig: Sau gute Arbeit!! Danke für das Script. Für meine Frau hatte ich nach 8h einen Termin :)

es freut mich sehr das zu hören :-)
