### ISSUE TITLE
Missing file - version.txt

### ISSUE THREAD

**Issue by xiaoyaooo** [iamnotturner/vaccipy#380]
Hi Dear Authors,

I may have found one small and trivial problem in your released source code. As for mac users, they need to run the software using the source code, it would be great if you could fix this.
The problem is as described in the issue title, the file that should store the current version of the code is missing. 
There should be a version.txt containing "v1.1.8" under the root directory.

Because either the main.py or the gui.py will call tools.utils.get_current_version() before the program runs, if that file is missing, there will be problem for both CLI and GUI version. The CLI version runs still with an error notice, but the GUI won't open.

And btw, thank you very much for creating this great software! I did get my termin using this weeks ago.

**Comment by iamnotturner** [comment]
Just create the version.txt file in the vaccipy directory

**Comment by xiaoyaooo** [comment]
Yep, thank you for your fast reply! Actually, it’s not a problem for me, as I am a windows user.
Just want to let you know, so that maybe it can be added in later releases. 😉
Thanks again anyway!

**Comment by iamnotturner** [comment]
thanks @xiaoyaooo and @stefanogito
