### ISSUE TITLE
Fehler bei der Code Generierung

### ISSUE THREAD

**Issue by riecke99** [iamnotturner/vaccipy#392]
Hallo Miteinander,

beim Code generieren treffe ich auf folgenden Fehler, dieser wird alle 15 Sekunden neu ausgegeben.

![image](https://user-images.githubusercontent.com/85612858/121323620-4210f780-c910-11eb-95b1-fb98d3e0f6bb.png)

Kann mir da jemand eventuell weiterhelfen?

Danke, und auch für das Tool :)

**Comment by iamnotturner** [comment]
Hey, welche Version verwendest du?

**Comment by riecke99** [comment]
In der version.txt steht v1.1.8

**Comment by iamnotturner** [comment]
sehr komisch... wir arbeiten gerade an einem neuen Release, könntest du [den hier](https://github.com/iamnotturner/vaccipy/releases/tag/v1.2.1) mal probieren?

**Comment by riecke99** [comment]
![image](https://user-images.githubusercontent.com/85612858/121325963-5e159880-c912-11eb-8706-dd14f3b7f657.png)
 nun tritt das auf

**Comment by sinun98** [comment]
Nutzt du Windows?

**Comment by riecke99** [comment]
ja, brauch ich ein anderes Betriebssystem?

**Comment by sinun98** [comment]
Nein das sollte eigentlich funktionieren.

**Comment by riecke99** [comment]
bei dem neuen Release den Installer

**Comment by iamnotturner** [comment]
> ![image](https://user-images.githubusercontent.com/85612858/121325963-5e159880-c912-11eb-8706-dd14f3b7f657.png)
> nun tritt das auf

huch, das sieht nach einem Verbindungsfehler aus... führst du das aufm Arbeitsrechner oder so aus?

**Comment by stefanogito** [comment]
wollte auch eben fragen, ob eventuell die ports gesperrt sind, vaccipy nicht durch die (Windows-)Firewall kommt oder ähnliches

**Comment by riecke99** [comment]
Ja, mach ich, dass habe ich gerade auch vermutet, dann muss ich es nochmal auf einen anderen Rechner testen.

**Comment by iamnotturner** [comment]
Der Übersicht wegen schließe ich das Issue mal. Melde dich, wenns weiterhin nicht klappt.
