### ISSUE TITLE
Automatisierte Terminbuchung fehlgeschlagen

### ISSUE THREAD

**Issue by tand0r** [iamnotturner/vaccipy#393]
Hallo zusammen und erstmal vielen Dank für das geniale Tool!

Habe leider in den bereits vorhandenen Issues keine Tipps gefunden, wie man mit diesem Problem umgehen soll.

Code-Generieren und Terminsuche verlaufen problemlos, aber die automatische Terminbuchung schlug bei mir heute Nacht leider drei mal fehl. :(

Gibt es momentan schon eine Möglichkeit diesen Fehler zu umgehen und die Automatisierte Buchung wieder zu ermöglichen?
Oder einfach weiter probieren..

Habe diese zwei verschiedene Fehlermeldungen erhalten: 

![Screenshot 2021-06-09 121837](https://user-images.githubusercontent.com/85617063/121337450-d8e3b100-c91c-11eb-915d-c1bcc4c9f4ba.jpg)

und:

![Screenshot 2021-06-09 122000](https://user-images.githubusercontent.com/85617063/121337675-121c2100-c91d-11eb-9444-6df1f899e161.jpg)

Vielen Dank für euren Support!

**Comment by AllCanor** [comment]
Gleiches Problem auch bei mir. Automatisierte Buchung fehlgeschlagen und da ich zu der Zeit geschlafen habe, natürlich auch keine Möglichkeit zur manuellen Eingabe gehabt.

**Comment by Sars-Cov-2-Antigen** [comment]
Mir ist das irgendwie nie passiert.

Solange hier keine bessere technische Lösung gefunden wird, könnte man vielleicht eine Art Weckerfunktion in Erwägung ziehen, 
so dass das Script in solchen Fällen in bestimmten zeitlichen Abständen ein Tonsignal auslöst über eine Dauer von max. 10 Minuten. Dann besteht zumindest die Chance, dass man geweckt wird, wenn man die Boxen laut aufdreht ;)

Könnte man in der GUI optional anbieten (Häkchen setzen) und über Python vielleicht unter erweiterte Optionen eingliedern.

**Comment by tand0r** [comment]
> Gleiches Problem auch bei mir. Automatisierte Buchung fehlgeschlagen und da ich zu der Zeit geschlafen habe, natürlich auch keine Möglichkeit zur manuellen Eingabe gehabt.

Ja genau, eigentlich wäre die manuelle Buchung auch garkein Problem, aber die Termine kommen leider zu Uhrzeiten rein wo jeder Normalo am schlafen ist ^^

**Comment by AllCanor** [comment]
> Mir ist das irgendwie nie passiert.
> 
> Solange hier keine bessere technische Lösung gefunden wird, könnte man vielleicht eine Art Weckerfunktion in Erwägung ziehen,
> so dass das Script in solchen Fällen in bestimmten zeitlichen Abständen ein Tonsignal auslöst über eine Dauer von max. 10 Minuten. Dann besteht zumindest die Chance, dass man geweckt wird, wenn man die Boxen laut aufdreht ;)
> 
> Könnte man in der GUI optional anbieten (Häkchen setzen) und über Python vielleicht unter erweiterte Optionen eingliedern.

Mit dem nächsten Release kommt wohl eine Benachritigungsoption für Telegram.

**Comment by andoorius** [comment]
> Gleiches Problem auch bei mir. Automatisierte Buchung fehlgeschlagen und da ich zu der Zeit geschlafen habe, natürlich auch keine Möglichkeit zur manuellen Eingabe gehabt.


Kenne das Problem von einem Arbeitskollegen.
Rechnerwechsel hat geholfen - leider haben wir das Problem nicht weiter eingegrenzt bekommen. [Win 10]
Bei mir hat 1x der Windows Virenschutz zugeschlagen (habe jetzt den kompletten Ordner ausgenommen)
Und dann Testbuchungen in Brandenburg gemacht und gleich wieder storniert - sonst sinkt die Laune wenn man morgens die Termine sieht die man hätte buchen können 🤪

**Comment by iamnotturner** [comment]
Also der Erfahrung nach kann man nichts anderes machen als, wer hätte es gedacht, es einfach weiterprobieren 😄

Das ist etwas ernüchternd, aber die Terminbuchung klappt dann meistens nicht, wenn der Termin nicht richtig reserviert und (auch manuell) nicht buchbar ist.

Vielleicht hilft es, das Script mal zu pausieren, auf einem anderen Rechner auszuführen oder neue Codes zu generieren. 

Was nicht zu vergessen ist: wir (und sicher die anderen Impf-Bot's auch) erhalten in den letzten Tagen enormen User-Zuwachs. 

Am Ende bleibt es Glück.
