### ISSUE TITLE
[BUG] Kontakdateneingabe stürzt ab GUI

### ISSUE THREAD

**Issue by andoorius** [iamnotturner/vaccipy#396]
Die GUI lädt beim Start wohl die Kontaktdaten.json ist diese von einer alten Version (beim mir vor 1.2.1) geht das GUI Fenster komplett zu.
Ein löschen der Datei behebt das Problem. Gleiches Verhalten, wenn man eine alte Datei laden möchte.
Vielleicht könnte man das abfangen - habe etwas gebraucht um das Problem zu beheben.
Die Luxusvariante "Teilkonvertierung" lohnt sich vermutlich nicht, da der Versionswechsel und Datenübernahme nicht so häufig vorkommen wird.....

**Comment by iamnotturner** [comment]
@andoorius das Problem ist bekannt, liegt am neuen Feature, dass man nun nicht mehr nur 1 Code, sondern mehrere Codes eintragen kann (das Feld in der `Kontaktdaten.json` heißt jetzt `codes` nicht `code`). Wird noch behoben.

**Comment by JuliusJacobitz** [comment]
Optionales enhancement. On install, delete kontaktdaten.json. 
Würde ich aber mal als nicht so wichtig einstufen. Sollte ja mit einem Löschen der Datei erstmal gehen :) Danke @andoorius 👍
