### ISSUE TITLE
Keine Terminbestätigung per E-Mail erhalten

### ISSUE THREAD

**Issue by Benutzer12345** [iamnotturner/vaccipy#397]
Hallo,

ich konnte vorher einen Termin über vaccipy buchen, allerdings habe ich keine Terminbestätigung per E-Mail erhalten. Ich kann den Termin so leider nicht wahrnehmen

**Comment by iamnotturner** [comment]
Hi, du kannst die Buchung auch online mit deinem Code einsehen, das reicht für das Impfzentrum.

Die Mails schickt der Impfterminservice, da können wir nichts machen. Hast du deine Mail korrekt angegeben?

**Comment by Benutzer12345** [comment]
Hey Tim,

danke für die schnelle Antwort!

Meine E-Mail-Adresse ist korrekt. Hab sie kontrolliert.

Mit dem Code kann ich mich auf der Homepage Impfterminservice unter
"Buchung verwalten" nicht einloggen. Es kommt die Meldung "Keine Buchung
gefunden".

Auf vaccipy wurde mir bestätigt, dass der Termin erfolgreich gebucht wurde.

Kannst du mir da weiterhelfen?

Liebe Grüße
Viktoria


Tim Reibe ***@***.***> schrieb am Mi., 9. Juni 2021, 14:56:

**Comment by iamnotturner** [comment]
Hey Viktoria, das ist komisch, bei welchen Impfzentren hast du überall gesucht und bei welchem wurde der Termin gebucht? Kannst du den Ausschnitt von der Log-Datei senden?

**Comment by Benutzer12345** [comment]
Hi Tim,

anbei die Ausschnitte der Dateien. Es sind zwei Termine, da ich parallel in
verschiedenen Impfzentren gesucht habe. Sie wurden relativ schnell
hintereinander gebucht.

Ich habe in den Impfzentren direkt angerufen, sie kümmern sich darum und
prüfen, ob die Termine überhaupt gebucht wurden.

Liebe Grüße und herzlichen Dank für alles!!
Viktoria

Tim Reibe ***@***.***> schrieb am Mi., 9. Juni 2021, 15:30:
