### ISSUE TITLE
Fehler: "Einloggen mit Code nicht möglich!"

### ISSUE THREAD

**Issue by iamnotturner** [iamnotturner/vaccipy#4]
Hey
Ich bekomme oft folgenden Fehler:  "Einloggen mit Code nicht möglich!"
Woran könnte das liegen?

Und wie gebe ich Frau oder Herr richtig ein?
Habe es aktuell so eingegeben wie in der Frage geschrieben.

Danke schon mal und auch vielen dank für das Tool.

_Originally posted by @domi1210 in https://github.com/iamnotturner/vaccipy/issues/1#issuecomment-829671687_

**Comment by iamnotturner** [comment]
Hi @domi1210, 

das kann verschiedene Gründe haben. Der wahrscheinlichste ist - vorausgesetzt es hat schonmal geklappt (?) - dass du **temporär gebannt** bist. Das kommt einfach von zu vielen Anfragen, dagegen hilft kurz warten (irgendwas zwischen 5 und 30 Minuten). Sollte das immer wieder passieren, solltest du eventuell den `check_delay` von `30` anheben auf `45` oder `60` (in der Datei `main.py`, Zeile 405). Zur Info: Paralleles ausführen des Scripts mit mehreren Codes führt schneller zu einem Ban.

Eine anderer Grund könnte sein, dass der **Code nicht zu der von dir eingetragenen PLZ passt**. Das kannst du aber einfach überprüfen, indem du manuell im Browser versuchst, dich in dem Impfzentrum mit dem Code anzumelden.

Achja, hast du denn **neuste Version** des Tools? 

Probier mal, ob dir das schon hilft. Ansonsten kannst du dich gerne nochmal melden 😄 

GuNa
Tim

**Comment by domi1210** [comment]
Danke für die schnelle Antwort.

Dann scheint es wohl ein Bann zu sein. 
Habe das Tool parallel laufen lassen. 

Ja ich hab die neueste Version.

**Comment by iamnotturner** [comment]
Ja das stimmt, die Login-Funktion wird hat nur einen fixen Retry-Delay von 3 Sekunden. 

Ich habe das Script eben nochmal bei mir getestet und bei mir funktioniert der Login - daher nochmal die Frage: der Login im Browser funktioniert mit deiner PLZ-Code-Kombination? Ist gerade der Warteraum in deinem Impfzentrum aktiviert?

Die Funktion ist eigentlich dafür da, die Qualifikationen abzurufen, die für deinen Code hinterlegt sind (also welche Impfungen dir zustehen). Diese werden bei der Terminbuchung im Body des `POST`-Requests mitgeschickt - sind aber soweit ich weiß nicht zwingend notwendig. Also könnte das als Workaround dienen, vielleicht kannst du irgendwann von deiner Erfahrung berichten.

**Comment by domi1210** [comment]
Ja im Browser funktioniert es mit der PLZ-Code Kombination. Warteraum war vorhin bei einem Test nicht aktiv. 
Aktuell ist der Warteraum aktiviert. 

Wenn ich Neuigkeiten habe melde ich mich.
Denke ich teste das ganze mal Nachts. 
Da sind die Chancen höher das ein Termin verfügbar ist.

**Comment by domi1210** [comment]
Also nach einer Nacht durchgehender Nutzung muss ich sagen das es bei mir nicht funktioniert...
Ich erhalte immer die "Einloggen mit Code nicht möglich!" Meldung. 
Im Browser Fenster sehe ich allerdings wie er sich mit dem Code einloggt und dann auf der Seite zum Termin buchen ist. Allerdings wird das Fenster dann geschlossen. Ich teste es jetzt mal ohne die login Funktion

**Comment by iamnotturner** [comment]
Okay, das ist Mist, bei mir funktioniert es nach wie vor. 
Der Code sollte dieses Format haben: `ABCD-FGHI-JKLM`

Könntest du mir sagen, um welche PLZ es geht?

**Comment by domi1210** [comment]
Hab diese beiden getestet: 76287 und 89073.

**Comment by iamnotturner** [comment]
ich hab eben 76287 getestet: bei mir funktioniert es ohne Probleme.
Sieht deine Config so aus, wie bei mir?

```  
{
    "code": "ABCD-1234-QWER",
    "plz": "76287",
    "kontakt": { ... }
}
```

![Test 76287](https://user-images.githubusercontent.com/38082956/116794574-3b4fc300-aace-11eb-8cd5-909bb72b5128.png)

**Comment by domi1210** [comment]
![image](https://user-images.githubusercontent.com/64898596/116827161-f5f7c800-ab97-11eb-8da4-663e6ecd4394.png)

![image](https://user-images.githubusercontent.com/64898596/116827170-0019c680-ab98-11eb-9d1d-ffc860b65b61.png)

So sieht das bei mir aus. Hab mir eben das Tool auch extra nochmal neu runtergeladen.
Manuell kann ich mich mit dem Code einloggen:
![image](https://user-images.githubusercontent.com/64898596/116827201-23dd0c80-ab98-11eb-8441-1a49a269bf70.png)

**Comment by iamnotturner** [comment]
Mega ärgerlich, aber ich vermute, dass das Problem bei deinem Endgerät liegt. 
Die Fehlermeldung "usb_device_handle_win.cc:1054 Failed ..." hängt mit Selenium zusammen und ich befürchte, dass da irgendwas bei der Cookie-Generierung fehlschlägt ([https://stackoverflow.com/questions/65080685/usb-usb-device-handle-win-cc1020-failed-to-read-descriptor-from-node-connectio](siehe hier)).

Hast du ein anderen PC, an dem du das Script mal mit deinen Konfigurationen testen könntest?

**Comment by domi1210** [comment]
Ich habe es bereits an meinem Laptop und PC getestet. Beide laufen mit Windows. 
Nutzt du Linux oder Mac?

**Comment by domi1210** [comment]
Also mit einer virtuellen Maschine mit Ubuntu sieht es so aus wie bei dir.

**Comment by iamnotturner** [comment]
Ich selbst nutze einen Mac. Aber prinzipiell sollte es auch auf Windows laufen, habe schon mit mehreren Leuten gesprochen, die das Tool unter Windows erfolgreich nutzen. Leider steht mir kein WIndows-Rechner zur Verfügung, kann daher dein Problem leider nicht rekonstruieren. Die Tage sollte noch ein Build als .exe kommen, vielleicht klappt es ja dann damit.

Ist die VM eine vorübergehende Option für Dich?

**Comment by domi1210** [comment]
Ja für mich ist das aktuell ein Lösung.
Hab noch etwas anderes gefunden, was kein Fehler an sich ist, aber man könnte hier was verbessern:
Wenn ich gesperrt werde kommt folgendes:
![image](https://user-images.githubusercontent.com/64898596/116921884-e7231b00-ac54-11eb-94d7-4da4ac4e15ea.png)

Nachdem ich einige Zeit gewartet habe ging es wieder ganz normal.
Eine entsprechenden Fehlermeldung wäre hier sinnvoll. 
So hab ich nämlich erstmal das Problem gegoogelt.

**Comment by iamnotturner** [comment]
das ist ein guter Punkt, hab das ins Errorhandling aufgenommen. Cookies werden erneuert, wenn der Ban bei der Terminsuche auftaucht.

#13 und #14

![image](https://user-images.githubusercontent.com/38082956/116936331-fa8bb180-ac67-11eb-98df-dd6e0a53e481.png)

**Comment by iamnotturner** [comment]
@domi1210 es gibt das Tool jetzt auch als `.exe`, siehe hier: https://github.com/iamnotturner/vaccipy#distributionen

Big Up @JuliusJacobitz #17

**Comment by iamnotturner** [comment]
ich nehme an das hat sich erledigt

**Comment by domi1210** [comment]
Als .exe funktioniert es.  

Danke vielmals!

**Comment by Matze1x** [comment]
Guten Morgen, ich habe unter Ubuntu sowie auch Raspian folgendes problem, unter Mac OSX läuft es super, vielen Dank schonmal

2021-05-15 10:31:19.159   impfterminservice   [err] [cookies_erneuern]   OSError exception raised - retry 9
2021-05-15 10:31:19.160   impfterminservice   [inf] [*MWZV | 72280]   Browser-Cookies generieren
2021-05-15 10:31:19.172   impfterminservice   [err] [cookies_erneuern]   OSError exception raised - retry 10
2021-05-15 10:31:19.177   impfterminservice   [err] [*MWZV | 72280]   File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/ubuntu/vaccipy/tools/chromedriver/chromedriver-linux'

**Comment by JuliusJacobitz** [comment]
@Matze1x  bitte mal mit dem neusten master-stand ausprobieren :)

**Comment by Matze1x** [comment]
> @Matze1x bitte mal mit dem neusten master-stand ausprobieren :)

@JuliusJacobitz merci das teste ich gleich, hab mir eine eben eine Abhilfe geschaffen, allerdings ist diese nicht so Optimal, ich berichte dankeschön

**Comment by Matze1x** [comment]
@JuliusJacobitz  ging leider nicht, hab das laufende Script nun als Pullup angefragt, danke trotzdem für deine Hilfe

**Comment by JuliusJacobitz** [comment]
#43
