### ISSUE TITLE
Nur Johnson & Johnson als möglicher Impfstoff

### ISSUE THREAD

**Issue by repa1030** [iamnotturner/vaccipy#40]
Hallo,

erstmal vielen Dank für dieses tolle Tool!
Beim Laden der möglichen Impfstoffe erhalte ich lediglich Johnson & Johnson, obwohl ich weiß, dass in diesen Impfzentren hauptsächlich andere Impfstoffe verimpft werden (somit bekomme ich natürlich keinen Termin). Warum wird BioNTech und Moderna nicht ebenfalls hinzugefügt? Die Altersgruppe würde passen.

_[L920] Altersgruppe: 16+ (Intervall: 40 Tage) --> ['BioNTech']←[0m
[L921] Altersgruppe: 18+ (Intervall: 40 Tage) --> ['Moderna', 'BioNTech']←[0m
[L922] Altersgruppe: 60+ (Intervall: 40 Tage) --> ['Moderna', 'BioNTech', 'AstraZeneca']←[0m
[L923] Altersgruppe: 18+ (Intervall:  ? Tage) --> ['Johnson&Johnson']←[0m
.
.
.
Mögliche Impfstoffe: ['Johnson&Johnson']←[0m_

**Comment by iamnotturner** [comment]
Hi, das liegt tatsächlich nicht an uns, sondern an der Codevergabe vom Impfterminservice. Bei der Erstellung wird jedem Code eine Qualifizierung (J&J: L923) erteilt, also im Prinzip die möglichen Impfstoffe zugewiesen.

Das ist etwas frustrierend, weil es für J&J so gut wie keine Termine gibt.

**Comment by repa1030** [comment]
ok schade, dann muss ich wohl nach neuen Codes schauen :D Trotzdem danke!

**Comment by robert-scheck** [comment]
Möglicherweise wird (bei der Erzeugung des Vermittlungscodes) die Auswahl "Einzeltermin" oder "Terminpaar" nicht berücksichtigt, die bei *einzelnen* Impfzentren auftaucht. Wird hier "Einzeltermin" gewählt, bekommt man mit diesem Vermittlungscode anschließend ausschließlich Termine für L923 angeboten.
