### ISSUE TITLE
Problem beim Termin und Code generieren

### ISSUE THREAD

**Issue by Schwenki** [iamnotturner/vaccipy#403]
Hallo zusammen, ich habe folgendes Problem. Kann mir jemand helfen?
![image](https://user-images.githubusercontent.com/85638403/121395915-28dd6a80-c953-11eb-8f2d-cbb12a41a6fe.png)

**Comment by iamnotturner** [comment]
es kommt bald eine Optimierung der Cookies-Generierung, evtl müsstest du dich noch etwas gedulden. #395

**Comment by Schwenki** [comment]
Hallo Herr Reibe,

vielen dank für die schnelle Rückmeldung. Ich warte dann einfach noch ab.
Ich hab leider kein großes Fachwissen im Bereich PC und hoffe das dies dann
doch noch irgendwie funktioniert.
Dank aber für das tolle Tool und ich hoffe es klappt bald so über einen
Impftermin.

Gruß
Schwenk

Am Mi., 9. Juni 2021 um 18:55 Uhr schrieb Tim Reibe <
***@***.***>:

**Comment by AllCanor** [comment]
Klickst du auch wirklich manuell Elemente im Chrome Fenster an? Da muss man wirklich sehr viele Elemente anklicken, dann klappt es auch im derzeitigen Zustand.

**Comment by Schwenki** [comment]
Guten Morgen Herr Reibe,

ich habe gemäß der Anleitung vaccipy heruntergeladen und entpackt.
Als erstes habe ich dann über [2] einen Impf-Code generiert. Hierbei kam
gestern immer die Fehlermeldung , siehe Screenshot, der Fehlermeldung von
gestern. Gestern Abend hat es dann doch noch geklappt und ein Fenster in
Windows Edge wurde geöffnet und ein Impf-Code generiert. In dem Fenster war
immer die Anmeldeseite von www.impfterminübersicht.de
<http://www.xn--impfterminbersicht-v6b.de> zu sehen, es gab aber gleich
eine Fehlermeldung, das der Impf-Code nicht stimmt.

Was Sie nun mit "manuell Elemente im Chrome Fenster an" meinen, verstehe
ich leider nicht?

Gruß
Andreas







Am Do., 10. Juni 2021 um 00:23 Uhr schrieb AllCanor <
***@***.***>:

**Comment by bergungsdackel** [comment]
Bei mir auch dasselbe Problem, weiss jemand eine Lösung?

**Comment by iamnotturner** [comment]
bitte neuste Version probieren https://github.com/iamnotturner/vaccipy/releases/tag/v1.2.10

ich schließe diesen Thread, bitte #449 folgen
