### ISSUE TITLE
Code kann nicht angefragt werden: {"error":"Anfragelimit erreicht."}

### ISSUE THREAD

**Issue by Calieston** [iamnotturner/vaccipy#406]
Hallo,

ich erhalte folgende Meldung beim Generieren eines neuen Codes. Ist es ein bekanntes Problem von der Website oder sollte ich es später erneut versuchen? Danke im Voraus.

```2021-06-09 18:50:06.316   impfterminservice   [err] [*xxxx | xxxx]   Code kann nicht angefragt werden: {"error":"Anfragelimit erreicht."}```

Mfg Cali

**Comment by apeltzer** [comment]
Zuviele SMS generiert würde ich mal raten.
