### ISSUE TITLE
frage vermittlungscode

### ISSUE THREAD

**Issue by BurgerKing2k19** [iamnotturner/vaccipy#407]
ist es möglich, die response auch so anzupassen:

{"termineVorhanden":true,"vorhandeneLeistungsmerkmale":["L920", "L921", "L923"]}

und kann man dann mit dem vermittlungscode termine für biontech, moderna und johnson gleichzeitig suchen?

**Comment by sinun98** [comment]
Für was benötigst du das?

**Comment by BurgerKing2k19** [comment]
naja, ich hätte eben gerne einen vermittlungscode, der nach drei impfstoffen gleichzeitig suchen kann. die normalen codes für 18-59 suchen ja, soweit ich weiß, nur nach biontech und moderna...

**Comment by sinun98** [comment]
Achso, wir können da leider auch nichts anderes machen. Das liegt am Impfterminservice und wird von diesem so vorgegeben.
