### ISSUE TITLE
Chromedriver not working on Linux anymore

### ISSUE THREAD

**Issue by plorenz-etes** [iamnotturner/vaccipy#41]
Since the Raspi compatibility, the Chromedriver binary for Linux is 32 bit ARM only and cannot be run on x86_64 anymore.

**Comment by iamnotturner** [comment]
#42 supporting both architectures again, already merged into master

**Comment by JuliusJacobitz** [comment]
#43 @plorenz-etes  pls test

**Comment by philippweinmann** [comment]
![ChromeCookies](https://user-images.githubusercontent.com/38894417/118627425-fe711500-b7cb-11eb-97b5-1453fbfdf588.png)

**Comment by philippweinmann** [comment]
I suppose that is related to the bug, or did I make a mistake? On Ubuntu 20.04

**Comment by JuliusJacobitz** [comment]
> I suppose that is related to the bug, or did I make a mistake? On Ubuntu 20.04
@philippweinmann I changed the driver some minutes ago, pls verify if your master branch is up to date :) If thats the case, we might have to include a download for the linux drivers.

**Comment by plorenz-etes** [comment]
Works fine now, thanks!
The error reported by @philippweinmann was the same I got before.

**Comment by philippweinmann** [comment]
@JuliusJacobitz Works great now! Thanks :)

**Comment by philippweinmann** [comment]
![WebdrError](https://user-images.githubusercontent.com/38894417/118632173-717c8a80-b7d0-11eb-9187-39b629fa0898.png)
