### ISSUE TITLE
[Verbesserung] Terminsuche: Mehrere Vermittlungscodes (mehrere Gruppen) Gleichzeitig prüfen

### ISSUE THREAD

**Issue by neXorianus** [iamnotturner/vaccipy#413]
Hallo in die Runde,

Leider hat Baden-Württemberg seine Impfzentren in 5 verschiedene Gruppen eingeteilt, die geografisch nicht wirklich logisch von einander getrennt sind.

Darum habe ich nun 2 verschiedene Vermittlungscodes, für 2 verschiedene Gruppen.
Anscheinend gibt es aber nicht die Möglichkeit in 2 Gruppen gleichzeitig mit 2 Codes zu suchen (oder habe ich etwas falsch verstanden/gemacht?).

Wäre es möglich ein solches Feature noch mit einzubauen?

Danke für dieses geniale Tool schon jetzt!

**Comment by iamnotturner** [comment]
Kommt mit Version 1.2, in [v1.2.2 (Beta)](https://github.com/iamnotturner/vaccipy/releases/tag/v1.2.2) ist das Feature schon implementiert

**Comment by pancakeDevelopment** [comment]
https://github.com/iamnotturner/vaccipy/releases/tag/v1.2.6
Ist jetzt auch in der GUI drin :)

**Comment by neXorianus** [comment]
super, ich lasse das Ticket noch offen, bis es den sprung von Beta in den release geschafft hat.
die v1.2.2 (WIN10, cli) ist bei mir leider nicht gestartet (ohne error direkt wieder verschwunden)
126 habe ich noch nciht getestet

**Comment by iamnotturner** [comment]
Sind mittlerweile sogar bei 1.2.8, hatten da ein paar Problemchen 😁
