### ISSUE TITLE
SMS-Code kommt nicht an

### ISSUE THREAD

**Issue by D1yt** [iamnotturner/vaccipy#417]
Hey, ich bekomme ab und zu folgende Nachricht in Vaccipy:
```
[err] [*RTN2 | 70174]   Code-Verifikation fehlgeschlagen: {"error":"Pin ungültig"}
> SMS-Code:
```
Jedoch erhalte ich keinen SMS-Code an mein Handy.
Woran kann das liegen?
Was mach ich dann? Einfach Enter und weiter?

**Comment by iamnotturner** [comment]
wenn kein SMS-Code kommt nochmal die Handynummer überprüfen und ggf später nochmal probieren

**Comment by D1yt** [comment]
Also einfach irgendwas eingeben und auf das nächste Mal warten?

**Comment by iamnotturner** [comment]
einfach den Prozess von neuem beginnen, ja :-)
