### ISSUE TITLE
Windows: -f argument wird nicht angenommen

### ISSUE THREAD

**Issue by ecki** [iamnotturner/vaccipy#421]
v1.1.8: Laut Quellcode müsste es möglich sein den Pfad zu den Kontaktdaten mit -f anzugeben, aber das Windows.exe nimmt diese Option nicht an. Oder gibt es eine andere Möglichkeit in mehreren IZ Gruppen zu suchen (PLZ+Code in eigener Kontaktdaten.json).

    usage: windows-terminservice.exe [-h] {search,code} ...
    windows-terminservice.exe: error: unrecognized arguments: --file

**Comment by iamnotturner** [comment]
Update mit Möglichkeit zur Eingabe mehrer Codes/PLZs kommt im neuen Release v1.2 heute oder morgen

**Comment by JuliusJacobitz** [comment]
Sollte gefixed sein mit #434
