### ISSUE TITLE
[IDEE] Den Spendenlink bei erfolgreich gebuchtem Termin anzeigen

### ISSUE THREAD

**Issue by eliasws** [iamnotturner/vaccipy#422]
Finde das Projekt und auch die Idee Spenden zu sammeln super.
Eventuell könnte man den Spendenlink direkt bei erfolgter Buchung noch ausgeben, dann wird er nicht so leicht übersehen.

**Comment by pancakeDevelopment** [comment]
Hey @eliasws,
ich find den Vorschlag klasse, weswegen ich es gerade eben eingefügt habe. 
Siehe #429
