### ISSUE TITLE
[Info] Adressbestätigungslink anclicken nachdem Termin gefunden wurde

### ISSUE THREAD

**Issue by ecki** [iamnotturner/vaccipy#425]
Hallo, vielen Dank für das Script, ich wollte nur kurz Feedback geben.

Bei mir hat die Suche in der Nacht (schpon nach wenigen Stunden Suche in 3 Gruppen) einen Termin bekommen und dies in der Console angezeigt. Es kam eine Mail mit der Bitte die E-Mail Adresse zu bestätigen.

Als ich am Morgen auf diesen Link geclicked habe wurde mir ein Fehler angezeigt "Leider konnten wir Ihre E-Mail-Adresse nicht bestätigen" - ich hatte schon befürchtet die Mail nicht schnell genug gesehen zu haben. Oder hätte ich den Link im Chrome anclicken müssen?

Aber trotz(?) der Fehlermeldung im Browser kam dann doch die Terminbestätigungsmail!

**Comment by iamnotturner** [comment]
Hey @ecki, der Vorschlag kam auch schonmal auf. Es wäre notwendig, dass der Nutzer die Account-Informationen zu seinem Mail-Account einträgt, damit wir diese eine Mail abfangen könnten - und das ist schlicht weg zu komplex.

Und wenn die Mail trotzdem kam, ist das doch eigentlich ganz egal, oder? ;-)

**Comment by ecki** [comment]
Ja ich bin versorgt und hab schon gespendet :) 

Ich glaub es ist gut wenn das nicht automatisch passiert, damit man wenigstens eine Handlung willentlich am Ende machen muss. Wollte nur bescheid sagen dass die Fehlermeldung niemanden stört bzw damit rechnet dass man regelmässig nachschaut. Vielleicht lag die kurze Zeitspanne auch nur daran dass der Termin für Heute eingestellt war.
