### ISSUE TITLE
Cloudscraper installed, yet shows error

### ISSUE THREAD

**Issue by simone-1991** [iamnotturner/vaccipy#427]
I get this error after I choose option 2 (Generate code) and enter the contact details -

Fehler:
name 'cloudscraper' is not defined

**Comment by iamnotturner** [comment]
hey, what version are you using?

**Comment by simone-1991** [comment]
It seems like 1.2.52. 
Running it on python via main.py. 
But I individually installed all the requirements in the file requirements.txt (except PyQt5-Qt5, ERROR: Could not find a version that satisfies the requirement PyQt5-Qt5 (from versions: none)
ERROR: No matching distribution found for PyQt5-Qt5)  - hope that's fine?

**Comment by IAmWebSA** [comment]
which python version are you using?
how have you installed the cloudscraper?

**Comment by simone-1991** [comment]
Python 3/5.2
Cloudscraper 1.2.58 (installed via pip)

**Comment by IAmWebSA** [comment]
python must be at least 3.8.x, please upgrade your python to see if the error persists

**Comment by simone-1991** [comment]
Dear All, Thank you for your help yesterday. 
I tried python 3.9.5. This time it could successfully install all as per requirements.txt (using    pip --user -req. ...)
And it still shows the same error "Fehler: name 'cloudscraper' is not defined '

**Comment by simone-1991** [comment]
Ok, it works now. I changed to version vaccipy 1.2.8. 
But now it gives me separate error which I receive on webpage - (I mention this in a different issue)

Thanks,
