### ISSUE TITLE
Keine Buchung, trotz Termine gefunden 

### ISSUE THREAD

**Issue by Sylwuscha** [iamnotturner/vaccipy#438]
2x Pech gehabt und ich weiß nicht, was passiert ist und ob ich etwas falsch gemacht habe

Und denkt dran, ich bin Laie und verstehe keine IT-Sprache ;-)

**Comment by iamnotturner** [comment]
@Sylwuscha bitte niemals PLZ + Code posten, damit könnte man deine persönlichen Daten einsehen!
