### ISSUE TITLE
Can't generate Browser Cookies Linux

### ISSUE THREAD

**Issue by philippweinmann** [iamnotturner/vaccipy#44]
I am allowing myself to open another issue, after issue #41 was closed since the issue still persists for me. On Commit `commit 55a9f6e084c52f7946660977ebbf4afc75d6671c` I get following error: 
![WebdrError](https://user-images.githubusercontent.com/38894417/118634059-6aef1280-b7d2-11eb-8448-056730c55b66.png)

On Ubuntu 20.04

**Comment by JuliusJacobitz** [comment]
@philippweinmann
1. There might be additional information in your logs: `vaccipy/log/...`
2. We definetaly have to improve error logging, but for now: In wich "state" does your browser crash ?  E.g. after or before inserting the code ?
3. can you give me your system specs via ```$ uname -srm```

**Comment by hpingel** [comment]
Ubuntu 20.04 has Chromium as a snap! 

You could try this in main.py:

        chromedriver = os.path.join(PATH, "/snap/bin/chromium.chromedriver")

**Comment by philippweinmann** [comment]
I'll send you all the requested info when I'm back at the PC

**Comment by philippweinmann** [comment]
@JuliusJacobitz  
1. I'm afraid no traceback, since the program does not crash. If I let it run for a longer time I get this: 
![ImpfLong](https://user-images.githubusercontent.com/38894417/118664875-1fe4f780-b7f2-11eb-8862-7126245d8cc8.png)
2. I found tools/log/impfterminservice.log, I put the file in attachment but there isn't any more information than the output.
[impfterminservice.log](https://github.com/iamnotturner/vaccipy/files/6501886/impfterminservice.log)
3. I just see a blank page nothing more and then the chromium browser closes again.
4. `Linux 5.8.0-53-generic x86_64`

Tell me if I you need more information.

**Comment by philippweinmann** [comment]
@hpingel That worked!!! Thanks yeah I installed chrome as a snap!

**Comment by JuliusJacobitz** [comment]
see #65
