### ISSUE TITLE
Ausgabe in logfile schreiben

### ISSUE THREAD

**Issue by funnym0nk3y** [iamnotturner/vaccipy#440]
Es wäre schön, wenn vaccipy ein logfile schreiben würde, um alles danach analysieren zu können.

**Comment by iamnotturner** [comment]
Hi, gibt doch den Ordner `log` mit Log-Dateien, oder?

**Comment by funnym0nk3y** [comment]
Soweit ich gesehen habe ist der bei mir leer. Muss da eine Option gegeben werden?
