### ISSUE TITLE
[GUI] Terminsuche mit mehreren Codes (Reihenfolge teilweise anders)

### ISSUE THREAD

**Issue by pancakeDevelopment** [iamnotturner/vaccipy#441]
Hey,
habe eben zum ersten Mal die Suche nach Terminen mit mehreren Codes ausprobiert.
**Was mir auffiel:** Warum auch immer werden manchmal manche Codes öfter benutzt als andere, obwohl jede PLZ nur einmal angegeben wurde.

**Screenshot:**

<img width="255" alt="Unbenannt" src="https://user-images.githubusercontent.com/43381667/121750715-33dbfa80-cb0d-11eb-8101-b4b1d1564fec.PNG">

@haslersn war glaub dein PR mit den mehreren Codes, oder?

**Comment by haslersn** [comment]
In jeder Iteration (= alle `check_delay` Sekunden) werden alle Gruppen durchgegangen. So werden die einzelnen Server gleich stark belastet. Innerhalb der Gruppe wird eine zufällige PLZ gewählt.

Prinzipiell könnte man das verbessern, indem man innerhalb jeder Gruppe durch die PLZs rotiert.

**Comment by pancakeDevelopment** [comment]
Ahh alright!
War nur gerade Mobil unterwegs und mir fiel das auf.
Wäre meiner Meinung nach natürlich Sinnvoll, wenn man diese rotiert, sodass jede PLZ gleichermaßen abgefragt wird.

**Comment by haslersn** [comment]
Ist halt dann nicht ganz so einfach lesbarer Code. Ich sehe zwei einfachere Varianten:

- Entweder wir checken in jeder Iteration nur eine PLZ, und rotieren diese durch.
- Oder wir checken in jeder Iteration alle angegebenen PLZs.

In beiden Fällen werden die Server dann halt nicht gleichmäßig belastet. Das ist aber eh nicht so wichtig. Erstere Variante kommt am nächsten an das ran, was wir vorher hatten.

**Comment by pancakeDevelopment** [comment]
> Ist halt dann nicht ganz so einfach lesbarer Code. Ich sehe zwei einfachere Varianten:
> 
> * Entweder wir checken in jeder Iteration nur eine PLZ, und rotieren diese durch.
> * Oder wir checken in jeder Iteration alle angegebenen PLZs.
> 
> In beiden Fällen werden die Server dann halt nicht gleichmäßig belastet. Das ist aber eh nicht so wichtig. Erstere Variante kommt am nächsten an das ran, was wir vorher hatten.

Ich stimme dir da völlig zu. Die erste Variante wäre natürlich von Vorteil. Vaccipy hat ja vorher sowieso auch nur je Iteration eine Anfrage gestellt. Dabei könnte man eigentlich bleiben.
