### ISSUE TITLE
Fehlt da nicht ein f vor dem String?

### ISSUE THREAD

**Issue by batcats** [iamnotturner/vaccipy#445]
Hi. Python ... ne weile her bei mir, aber fehlt in der folgenden Zeile nicht ein f vor dem String?
Sonst wird die plz-Expression nicht ersetzt.
https://github.com/iamnotturner/vaccipy/blob/710be5c8bea5d2ff7f3c60c3f23d20890cfe2e5b/tools/its.py#L735

**Comment by iamnotturner** [comment]
Ist korrekt, danke für den Hinweis!

**Comment by iamnotturner** [comment]
fixed mit #466
