### ISSUE TITLE
Telegram Info in GUI - Erfolgsmeldung erweitern

### ISSUE THREAD

**Issue by andoorius** [iamnotturner/vaccipy#447]
Ist die Implemetierung der Telegraminfo in der GUI geplant?
Könnte man eventuell einen Link zum Termin in die "Telegramerfolgsmeldung" implementieren?

Wie gesagt ich buche viel für Freunde und Bekannte mit weniger IT Kenntnissen und bekommen natürlich die eMail nicht.... [und da muss mal schon mal darauf hinweisen, dass es ne neue eMail mit Termin am xxxx gibt und sicher der Gang zum PC lohnt :-)]

**Comment by marcorombach** [comment]
Hey, im neuesten Pre-Release (1.2.10) kann PushOver und Telegram auch über die GUI konfiguriert werden :)

https://github.com/iamnotturner/vaccipy/releases/tag/v1.2.10

**Comment by burnout2000** [comment]
wann wird man denn via Telegram informiert? Wenn ein Termin gefunden wurde der dem angegebenen Zeitrahmen entspricht oder sobald ein Termin gefunden wurde, egal in welchem Zeitfenster? Die generelle Info wäre sehr hilfreich

**Comment by marcorombach** [comment]
> wann wird man denn via Telegram informiert? Wenn ein Termin gefunden wurde der dem angegebenen Zeitrahmen entspricht oder sobald ein Termin gefunden wurde, egal in welchem Zeitfenster? Die generelle Info wäre sehr hilfreich

Die Telegram/Pushover Benachrichtigung wird gesendet wenn entweder die Buchung eines Termins erfolgreich war, oder es zu einem Fehler bei der Buchung kam. Mit Ausnahme des Fehlers, dass der Termin nicht mehr verfügbar ist (AppointmentGone). Im Fall das der Termin nicht automatisch gebucht werden konnte (BookingError), wird eine Telegram/Pushover Nachricht mit einem Link zur manuellen Buchung gesendet.
Aus diesem Grund bekommt man die Benachrichtigung auch nur für Termine im gewählten Zeitrahmen.
