### ISSUE TITLE
Vermittlungscodes lassen sich nicht mehr generieren (Fehler HTTP 429) 

### ISSUE THREAD

**Issue by lolman2079** [iamnotturner/vaccipy#449]
Ich hab heute versucht via VM und meinem Rechner neue Codes zu bekommen aber jedes mal bekomme ich einen 429 Fehler. VM greift auch über eine andere IP zu. 

Was kann man machen?

**Comment by IAmWebSA** [comment]
Hast du deine VM an einem seperaten Internetanschlluss oder via VPN? 
Weil sonst teilen die sich ja die Provider IP.

429 Too Many Requests  ;)

**Comment by tobi2li** [comment]
Habe seit gestern Abend auch das Problem ausnahmslos in die Bot-Protectiin zu laufen. Gestern Mittag ging es noch, aber jetzt passiert das trotz neuer IP und anderen Daten immer.

**Comment by lolman2079** [comment]
> Hast du deine VM an einem seperaten Internetanschlluss oder via VPN?
> Weil sonst teilen die sich ja die Provider IP.
> 
> 429 Too Many Requests ;)

Speraten Internetanschluss

**Comment by janmoritzmeyer0210** [comment]
Same here, haben die das angepasst dass das nur noch geht wenn auch Termine verfügbar sind?

**Comment by pancakeDevelopment** [comment]
Da wurde vielleicht wieder etwas geändert, wodurch die aktuelle Aktionen durch die Botprotection erkannt werden...

**Comment by intrigus-lgtm** [comment]
Kann das Problem bestätigen, seit mindestens heute 00:01 Uhr laufe ich auch permanent in die Botprotection rein.
Wie wildes rumklicken, Eingabe von verschiedenen Codes usw. bringt leider nichts.

**Comment by stefanogito** [comment]
Wo laufen die VM's denn? Wenn die bei den großen Cloud-Anbietern gehostet werden, könnten auch die AWS, Azure, GCP,... IP-Ranges generell gefiltert werden...

**Comment by lolman2079** [comment]
Die VMs laufen auf einem Privaten Abschluss mit Dual Stack d.h wir haben auch eine IP vom Provider

**Comment by iamnotturner** [comment]
Es bestehen aktuell überall Probleme mit der Cookie-Generierung. Das kam schon öfters vor und behebt sich nicht selten von ganz allein, also würde ich mal den Tag noch abwarten. Ansonsten sind wir dran, die Cookie-Generierung entsprechend anzupassen.

**Comment by IAmWebSA** [comment]
Kann es bestätigen, liegt nicht an der VM, da wurde wohl wieder was geändert bzw. abwarten ob s im Laufe des Tages wieder geht

**Comment by stefanogito** [comment]
Jap, hab es eben auch mit der neuesten Version getestet

**Comment by ogzylmz80** [comment]
Kann bestätigen, dass es (zumindest bei mir) immer noch nicht geht, Bot-Protection schlägt bei mir auch immer zu. Frage ist, ob das für die Terminsuche auch gleich ist.  Vermute ja

**Comment by janmoritzmeyer0210** [comment]
Die Terminsuche geht noch, ob das buchen noch geht weiß ich nicht. Hat gestern Abend fehlgeschlagen (Fehler Botprotection & so), kann aber auch sein dass das der "normale" Bug war dass der Termin doppelt reserviert und weggebucht war.

**Comment by JonasMock** [comment]
Habe mal einen PR erstellt. Das sollte die Chancen auf 429 verringern.
Dafür geht die Cookie Generierung / Eingabe von v-codes 15-30 Sekunden länger.
https://github.com/iamnotturner/vaccipy/pull/453

**Comment by Sylwuscha** [comment]
Da ja gerade keine Code-Generierung funktioniert, habe ich eine Frage: Kann ich unverbrauchte Codes für andere Personen im gleichen Ort in der gleichen Altersspanne nutzen? Eigentlich sollte das ja egal sein. Früher, wo man nur das Alter - nicht das gesamte Geburtsdatum - eingeben musste, war es auch egal und eine Buchung hat geklappt. Was meint ihr?

**Comment by janmoritzmeyer0210** [comment]
Müsste klappen, das Geburtsdatum muss man bei der Buchung ja eh nochmal eingeben afaik

**Comment by andoorius** [comment]
> Müsste klappen, das Geburtsdatum muss man bei der Buchung ja eh nochmal eingeben afaik

Buchung klappt auf jeden Fall ... ob im Impfzentrum abgelehnt wird oder nicht kommt auf die Laune der MA an.
Eine Eingabe des Geburtsdatums bei Buchung ist in BaWü (zumindest bis gestern nicht möglich gewesen)
Bauchgefühl sagt, solange Altersgruppe passt dürfte es kein Problem sein - aber nur ein Gefühl...

**Comment by pancakeDevelopment** [comment]
> Da ja gerade keine Code-Generierung funktioniert, habe ich eine Frage: Kann ich unverbrauchte Codes für andere Personen im gleichen Ort in der gleichen Altersspanne nutzen? Eigentlich sollte das ja egal sein. Früher, wo man nur das Alter - nicht das gesamte Geburtsdatum - eingeben musste, war es auch egal und eine Buchung hat geklappt. Was meint ihr?

Soweit ich weiß sind die Vermittlungscodes unabhängig von der eigentlichen Buchung. So sollte die Buchung + Wahrnehmung des Termins klappen, solange die Qualifikation stimmt. (Gleiche Altersgruppe)
Hatte das öfters hier in meiner Region gemacht und es gab nie Probleme.

**Comment by prinze2021** [comment]
Ja das kann man machen. Hatte ein paar übrig von Leuten denen ich helfen wollte die aber selbst einen Termin beim Arzt gefunden haben. Solange die Altergruppe stimmt gibt bzw. gab es noch nie Probleme. Hat also alles perfekt geklappt. Hoffe man kann bald wieder Vermittlungscodes erstellen. Schönen Sonntag noch.

**Comment by DokuKaefer** [comment]
Buchen von Terminen geht leider auch nicht mehr. Vaccipy läuft nun schon seit 2 Tagen bei mir, habe erst heute Morgen bemerkt das mehrere Termine zur Verfügung standen, aber leider kein einziger gebucht wurde.

Hier ein Beispiel
![2021-06-14 08_35_33-vaccipy - Terminsuche](https://user-images.githubusercontent.com/11537653/121849656-e4075a00-cceb-11eb-91a6-332e106ab7db.png)

**Comment by iamnotturner** [comment]
you can try our new beta version, code generation is with selenium now - and it works! special thanks to @JonasMock 

https://github.com/iamnotturner/vaccipy/releases/tag/v1.2.10

please let us know if this works for you, so we can publish it to everybody asap

**Comment by marnet0815** [comment]
Leider bekomme ich immer noch die Nachricht, dass der Code wegen BotProtection nicht generiert werden kann.

Mache ich hier irgendwas falsch?

![image](https://user-images.githubusercontent.com/85927287/122011986-fb624800-cdbc-11eb-9e0f-f0e35e714679.png)

**Comment by nagel86** [comment]
> Leider bekomme ich immer noch die Nachricht, dass der Code wegen BotProtection nicht generiert werden kann.
> 
> Mache ich hier irgendwas falsch?
> 
> ![image](https://user-images.githubusercontent.com/85927287/122011986-fb624800-cdbc-11eb-9e0f-f0e35e714679.png)

Habe/hatte das gleiche Problem. Die SMS wurde verschickt, aber wenn ich den Code dann eingegeben habe, bin ich auch in die Bot Protection gerannt. Habe dann einfach in der `its.py` in Zeile 1276 `driver.close()` rausgenommen. Dadurch bleibt nach dem SMS Versand der Browser offen, wenn ich dort dann den Code eingebe funktioniert es. Ich vermute dass durch das schließen des Fensters evtl. noch eine Nachricht an den Server geschickt wird, welcher das Cookie ungültig macht. Dieser Workaround funktioniert natürlich nur wenn man den Code verwendet, nicht die kompilierte Version.

**Comment by JonasMock** [comment]
@nagel86 Hast du zuvor in kurzer Zeit viele Anfragen mit der vorherigen Version versandt ? 

Wenn das häufiger der Fall sein sollte, dass bei der SMS-Code Bestätigung ein 429 Auftritt, kann man natürlich auch diesen via Selenium auf der Webseite eingeben lassen. Das habe ich erstmal nicht eingebaut.

**Comment by nagel86** [comment]
@JonasMock nope, habe heute nur die aktuelle Version verwendet. Ich muss dazu sagen: die ersten beiden Code für Gruppe 4 und 5 konnte ich problemlos erzeugen, bei Gruppe 1 bis 3 trat dann das Problem auf. Parallel zum Erzeugen der Codes für Gruppe 1 bis 3 lief schon die Suche für Gruppe 4 und 5. Da das ja aber andere Server sind, gehe ich davon aus, dass das nicht das Problem sein sollte.

**Comment by ogzylmz80** [comment]
Hi all,

worked for the first Vermittlungscode (Gruppe 3), afterwards (some 1.5h later) I did second try with Gruppe 4 and then it did not work. Same reason as last days -> Botprotection

<img width="643" alt="Bildschirmfoto 2021-06-15 um 10 11 47" src="https://user-images.githubusercontent.com/71979693/122018002-c22cd680-cdc2-11eb-97c2-113a9329ca22.png">

**Comment by nagel86** [comment]
@ogzylmz80 workaround: as I have mentioned a few posts above (in German), remove `driver.close()` (line 1276) from `tools/its.py` and then enter the code in the browser and not in the terminal

**Comment by ogzylmz80** [comment]
@nagel86 yes, you're right with the edit comment. Deleting/commenting out `driver.close()` does not solve the problem.

**Comment by lolman2079** [comment]
Also ich kann auch bestätigen, dass die Code-Generierung mit der Version 1.2.10 noch nicht funktioniert. Mit der GUI komme ich nicht mal bis zur Eingabe der E-Mail und der Telefonnummer. Mit der CMD geht's aber dann bekomme ich wieder einen 429 Error. 

Mit der V1.2.9 ging auch die Terminbuchung wieder.

**Comment by JonasMock** [comment]
@lolman2079 Die GUI ruft noch die vorherige Version der Code Anforderung auf. Das muss noch angepasst werden.

**Comment by lolman2079** [comment]
![Screenshot 2021-06-15 113915](https://user-images.githubusercontent.com/25888484/122030805-5fd9d300-cdce-11eb-941e-664ac1632ec4.png)

Ab hier bekomme ich den Fehler. Sobald der SMS-Code angefragt werden soll.

**Comment by lolman2079** [comment]
Zudem ist mir aufgefallen, dass man die Kontaktdaten in der GUI ab Version 1.2.10 nicht mehr bearbeiten kann. Die Software crasht dann direkt.

**Comment by pancakeDevelopment** [comment]
> ![Screenshot 2021-06-15 113915](https://user-images.githubusercontent.com/25888484/122030805-5fd9d300-cdce-11eb-941e-664ac1632ec4.png)
> 
> Ab hier bekomme ich den Fehler. Sobald der SMS-Code angefragt werden soll.

Ich habe mehrfach auf Anfordern geklickt, dann gings tatsächlich. Hast du das mal ausprobiert?

**Comment by JonasMock** [comment]
@pancakeDevelopment Das habe ich auch schon mal bemerkt. Bei der enter_code Funktion habe ich das eingebaut, dass noch ein zweites Mal geklickt werden soll wenn "Ein unerwarteter Fehler ist aufgetreten" erscheint. Werde ich hier auch hinzufügen, danke. 👍🏻

**Comment by marnet0815** [comment]
Leider komme ich nicht mal soweit, dass ich den SMS Code eingeben kann :-(

**Comment by JonasMock** [comment]
@prinze2021 Wenn du kurz Zeit hast, kannst du es ja mal damit testen: https://github.com/iamnotturner/vaccipy/pull/480

**Comment by prinze2021** [comment]
Ach du Gott das bekomme ich nicht hin. Bin froh wenn ich den Knopf zum Hochfahren des PC`s finde. Ist das schwer was da beschrieben wird?

**Comment by nagel86** [comment]
@JonasMock habe es mal schnell getestet, funktioniert zwar, aber Programm bricht mit folgendem Error ab:
```
Traceback (most recent call last):
  File "D:\Repos\vaccipy\main.py", line 615, in <module>
    main()
  File "D:\Repos\vaccipy\main.py", line 517, in main
    subcommand_code(args)
  File "D:\Repos\vaccipy\main.py", line 426, in subcommand_code
    gen_code_interactive(args.file)
  File "D:\Repos\vaccipy\main.py", line 346, in gen_code_interactive
    return gen_code(kontaktdaten)
  File "D:\Repos\vaccipy\main.py", line 384, in gen_code
    token, cookies = its.selenium_code_anfordern(
  File "D:\Repos\vaccipy\tools\its.py", line 1198, in selenium_code_anfordern
    driver.execute_script(f"arguments[0].innerText='Vaccipy! - Bitte SMS-Code im Browser eingeben. Noch {max_sms_code_eingabe_sekunden} Sekunden verbleibend.'", sms_verifizierung_h1)
  File "C:\Users\snage\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "C:\Users\snage\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\snage\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=91.0.4472.101)
```

**Comment by JonasMock** [comment]
@nagel86 Danke. habe ich auch gerade gemerkt. Da muss ich mal schauen wie ich das lösen

**Comment by nagel86** [comment]
@JonasMock du musst ja eigentlich nur vorab überprüfen ob da Element (`check_h1`) noch existiert

**Comment by JonasMock** [comment]
@nagel86 Das habe ich schon gelöst. Aber danach kommt er auch nicht mit der Überprüfung der Status codes klar: Fehler:
'NoneType' object has no attribute 'status_code'

Muss ich kurz ein bisschen testen..

**Comment by prinze2021** [comment]
Das bekomme ich echt nicht hin. Wie sagt man? Ich bin ein Dummie :-) Die GUI Version ist für mich gemacht. Anklicken, eingeben, fertig. Aber das mit der Programmiersprache und das irgendwo eingeben ist nichts für mich. Mir wird da nur Schwindelig bei den ganzen Befehlen und was es alles gibt.

**Comment by Sylwuscha** [comment]
Du sprichst mir aus der Seele. 😁-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 15.06.21, 21:08, prinze2021 ***@***.***> schrieb:


Das bekomme ich echt nicht hin. Wie sagt man? Ich bin ein Dummie :-) Die GUI Version ist für mich gemacht. Anklicken, eingeben, fertig. Aber das mit der Programmiersprache und das irgendwo eingeben ist nichts für mich. Mir wird da nur Schwindelig bei den ganzen Befehlen und was es alles gibt.



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/iamnotturner/vaccipy/issues/449#issuecomment-861760872",

"url": "https://github.com/iamnotturner/vaccipy/issues/449#issuecomment-861760872",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by JonasMock** [comment]
@prinze2021 Danke für den hinweise. Die GUI arbeitet noch mit einer vorherigen Version. Da weiß ich jedoch nicht wie ich das aktualisieren kann, dass muss jemand anders Übernehmen.

Eventuell reicht es als workaround die Zeile anzupassen ?

https://github.com/iamnotturner/vaccipy/blob/312923a590cd78b1626b6f7f3ff346a43f88bd12/tools/gui/qtcodegen.py#L130

**Comment by prinze2021** [comment]
Selbst das wüsste ich nicht wie ich das machen sollte. Da werde ich wohl warten müssen bis die aktualisierte GUI Version kommt.

**Comment by nagel86** [comment]
> Möchte da nicht einfach abbrechen. Will noch den status 200 verarbeiten, um in der console anzuzeigen, dass die Anfrage erfolgreich versandt wurde

@JonasMock Du sollst ja auch nicht abbrechen. Einfach überspringen wenn das Element nicht mehr existiert...danach responses auslesen, fertig. Klappt bei mir wunderbar

**Comment by JonasMock** [comment]
@nagel86 Ja dass ist im neusten commit drin

**Comment by prinze2021** [comment]
Was auslesen? Ich sage doch ich bin ein Dummie :-) Das müsste mir mal einer zeigen und dann kapier ich es vielleicht, aber auch nur vielleicht. Muss ich da Phython installiert haben?

**Comment by nagel86** [comment]
Ah ok, ging an mir vorbei. Bezüglich NoneType, tritt bei mir nicht auf. Evtl. passiert das bei einem unglücklichen timing? In dem Fall einfach auf NoneType prüfen und noch ein weiteres mal (mit pause) iterieren?!

**Comment by JonasMock** [comment]
@nagel86 Ja, das hört sich gut an. Oder ich überprüfe zu Beginn ob ich auf der Seite gelandet bin auf die man weitergeleitet wird. 

```
# Prüfen ob SMS-Code an Server versandt wurde
                # TODO Überprüfung verbessern, vielleicht success banner auslesen
                if driver.current_url == f"{url}impftermine/{plz_impfzentrum}":
                    driver.close() 
                    raise RuntimeError("SMS-Code erfolgreich übermittelt. Bitte Prüfen Sie Ihre E-Mails.")
```

**Comment by JonasMock** [comment]
@nagel86 Ja das ist ein unschöner workaround. selenium_code_anfordern() hängt in der main.py noch in einem anderen Prozess drin, der eigentlich anschließend die code_bestaetigen() Funktion aufrufen möchte:
https://github.com/iamnotturner/vaccipy/blob/312923a590cd78b1626b6f7f3ff346a43f88bd12/main.py#L349

Das muss man dann noch anpassen.

**Comment by nagel86** [comment]
@JonasMock wäre auch ne Möglichkeit, aber ich weiß nicht ob man, daraus direkt auf eine erfolgreiche Übermittlung schließen kann, das würde ich schon über den Status Code machen...in dem Response ist übrigens dann auch der SMS-PIN enthalten

**Comment by prinze2021** [comment]
Ich bin raus. Ich kapier nichts mehr. Ich warte auf die neue GUI wo es hoffentlich wieder geht. Glaube wenn mir jemand per PC Fernsteuerung helfen  würde, würde ich nichts kapieren.

**Comment by JonasMock** [comment]
@nagel86 sollte jetzt laufen. Fällt dir sonst noch irgendetwas auf ?

**Comment by prinze2021** [comment]
Die GUI Code generierung?

**Comment by nagel86** [comment]
@JonasMock habe nur mal einen Blick drauf geworfen, aber nicht getestet. Sieht soweit gut aus.

@prinze2021 du musst dich noch etwas gedulden, der Code von Jonas muss noch gemerged werden und evtl. sind noch (kleinere) Anpassung für die GUI nötig.

**Comment by prinze2021** [comment]
Alles klar. Tausend Dank für die Info. Dann warte ich mal auf das neue Release. DANKE

**Comment by iamnotturner** [comment]
bitte testen: [v1.2.12](https://github.com/iamnotturner/vaccipy/releases/tag/v1.2.12)
GUI ist noch nicht angepasst, aber CLI-Version!

**Comment by prinze2021** [comment]
![capture_001_16062021_005016](https://user-images.githubusercontent.com/84878386/122133420-ee853900-ce3c-11eb-9699-d7b02da92a16.jpg)

**Comment by nagel86** [comment]
@prinze2021 siehe #467

**Comment by prinze2021** [comment]
Guten Morgen. Ich konnte komischerweise gerade zwei neue Codes erstellen mit der Version 2.11. Mal gespannt ob das heute Abend auch noch geht wenn ich wieder zuhause bin.

**Comment by andoorius** [comment]
Habe heute Morgen um kurz vor 8Uhr mit dem GUI und 1.2.12 auch codes erstellt ohne Probleme. Zweimal falsche eMail deshalb kam nie was an :-S und einmal alles super funktioniert.
SMS Abfrage kam 3x 

Gestern Abend mit der 1.2.12 Bot Protection ohne was zu verändern über Nacht.

Ich denke das liegt am Impfterminservice Bzw an der Auslastung…

Am 16.06.2021 um 10:07 schrieb prinze2021 ***@***.***>:

﻿
Guten Morgen. Ich konnte komischerweise gerade zwei neue Codes erstellen mit der Version 2.11. Mal gespannt ob das heute Abend auch noch geht wenn ich wieder zuhause bin.

**Comment by iamnotturner** [comment]
> Guten Morgen. Ich konnte komischerweise gerade zwei neue Codes erstellen mit der Version 2.11. Mal gespannt ob das heute Abend auch noch geht wenn ich wieder zuhause bin.

@prinze2021 hast du dazu das Zertifikat manuell hinzugefügt?

**Comment by prinze2021** [comment]
Ich habe nichts gemacht. Ich habe ganz normal die Version 2.11
runtergeladen und das war es.

Tim Reibe ***@***.***> schrieb am Mi., 16. Juni 2021, 11:04:

**Comment by iamnotturner** [comment]
eventuell liegt es wirklich am Impfterminservice, solltet ihr immer noch scheitern bitte den neusten Release probieren: 

https://github.com/iamnotturner/vaccipy/releases/tag/v1.2.13 

ich schließe das issue und öffne ggf. wieder

**Comment by marnet0815** [comment]
Ich habe mit 1.2.13 z.B. keine Chance, er bricht in der "Nicht-Gui-Version" sofort ab und sucht nicht nach Terminen... Codes generieren hat den selben Effekt... zumindest Abends kein Erfolg mit 1.2.13 und 1.2.12

**Comment by iamnotturner** [comment]
> Ich habe mit 1.2.13 z.B. keine Chance, er bricht in der "Nicht-Gui-Version" sofort ab und sucht nicht nach Terminen... Codes generieren hat den selben Effekt... zumindest Abends kein Erfolg mit 1.2.13 und 1.2.12

funktioniert 1.2.13? Und bzgl. Code-Generierung: vermutlich sind die Schlupflöcher bald gepatcht

**Comment by marnet0815** [comment]
Ja, 1.2.13. funktioniert - keine Ahnung wieso es plötzlich wieder geht. 

Code Generierung hingegen nicht (mehr)

**Comment by andoorius** [comment]
Habe heute mit der GUI V1.2.13 erfolgreich gebucht nur Telegram kam nicht an … muss ich mir anschauen, wenn ich zu Hause bin.

Codegenerierung heute morgen um 8 4x ohne Probleme (Console) - m.E. abhängig von der Auslastung (SW Änderung nach Tageszeit schließe ich im Portal mal aus…)

Am 17.06.2021 um 12:29 schrieb marnet0815 ***@***.***>:

﻿
Ja, 1.2.13. funktioniert - keine Ahnung wieso es plötzlich wieder geht.

Code Generierung hingegen nicht (mehr)

**Comment by marnet0815** [comment]
Ok scheint so. Hatte heute versucht auch gegen 8 in Gruppe 3 Codes zu generieren, dass hat bei mir nicht funktioniert.

Dann scheint es wirklich gruppenabhängig oder an der Auslastung zu liegen... es bleibt also spannend.

**Comment by JonasMock** [comment]
@marnet0815 Das gute ist, wenn man die Methode die der Bot anwendet manuell unabhängig von Vaccipy im Browser ausführt, kann man in fast 100% der Fälle einen Code generieren. Wurde bei mir noch nie geblockt. Unabhängig von der Uhrzeit oder Auslastung. 

-> lediglich die automatische Anwendung der Methode wird von den Betreibern als Bot erkannt und geblockt. Daher muss man herausfinden warum die Automatisierung als Bot erkannt wird.
