### ISSUE TITLE
Error regarding cookie and botprotection, followed by error on Impfterminservice webpage

### ISSUE THREAD

**Issue by simone-1991** [iamnotturner/vaccipy#451]
![Capture](https://user-images.githubusercontent.com/85735938/121772996-64597e00-cb79-11eb-9b3e-a66b68a27eed.JPG)

Dear All,
Can you please help me understand these two errors attached above?

Because it keeps running with these 2 errors, and then shows error on Impfterminservice webpage - "Es ist ein unerwarteter Fehler aufgetreten"

Thanks

**Comment by simone-1991** [comment]
Python -v 3.9
vaccipy 1.2.8

**Comment by pancakeDevelopment** [comment]
Probably the cookie generation is currently detected, which is why no valid cookie can be created

**Comment by simone-1991** [comment]
I allowed all cookies on Chrome. The error still remains the same.

**Comment by simone-1991** [comment]
Is there soemthing else I shoudl do?

**Comment by iamnotturner** [comment]
no, we're encountering issues with our cookies generation. as soon as we've fixed this we'll post an update

**Comment by simone-1991** [comment]
I see. Alright. Then I will wait, thanks.
Is this related to this version, or will changing the version help?

**Comment by iamnotturner** [comment]
> Is this related to this version, or will changing the version help?

no, Impfterminservice changed their system, so using an old version won't fix this, unfortunately

**Comment by deeenes** [comment]
The code generation with this other script works like a charm: https://github.com/alfonsrv/impf-botpy
Maybe it can help to find out how to fix it here. Once I generated the code, I was able to search for appointments with both scripts.

**Comment by pancakeDevelopment** [comment]
> The code generation with this other script works like a charm: https://github.com/alfonsrv/impf-botpy
> Maybe it can help to find out how to fix it here. Once I generated the code, I was able to search for appointments with both scripts.

Does this script allow instant code generation? As far as I know: No
Am I right?

**Comment by simone-1991** [comment]
I need impf code generation.
Does the impf-botpy really work?

**Comment by janmoritzmeyer0210** [comment]
The script only generates codes if there are appointments available

**Comment by andoorius** [comment]
> I need impf code generation.
> 
> Does the impf-botpy really work? it would be great if it does.

You can Twitter me under the same Nick - I got some not used ones for BaWü. Ages 18-59....

**Comment by janmoritzmeyer0210** [comment]
impf-botpy worked for code generation for hamburg, needed about half an hour for me

**Comment by deeenes** [comment]
@pancakeDevelopment Yes it does instant code generation (with the `--code` switch), I've just generated 2 codes in BaWü. Not clear how it addresses the cookie issue, it does a combination of redundant pointer movements and sleeps. But as far as I see you are doing something similar in #453

**Comment by pooyashahidi** [comment]
maybe I'm doing something wrong but I still cannot generate any codes
![image](https://user-images.githubusercontent.com/5418119/121826253-164a9480-ccb7-11eb-8388-190930e15801.png)

**Comment by andoorius** [comment]
V1.2.9 also working here with the first cookie. (Win 10, Console) - Thx for the Update!

**Comment by simone-1991** [comment]
umm somehow the impf-bot doesn't like my python environment i think 
![image](https://user-images.githubusercontent.com/85735938/121864150-defed680-ccfc-11eb-9c6e-a4cf1dca8759.png)

I am trying to generate code for hamburg, it should not be an issue because of region though? I mean I called the centers and they say they are still prioritizing people with medical conditions and educators now.

**Comment by simone-1991** [comment]
Windows versions of both codes show Trojan for me, so instead I am trying to run via python

**Comment by iamnotturner** [comment]
There is a new way of code generation as PR right now, which will be implemented tonight: https://github.com/iamnotturner/vaccipy/pull/459

**Comment by simone-1991** [comment]
It was my fault that impf-botpy showed errors, I missed the part of downloading 'Selenium for Chrome' , basically the chromedriver exe file. 
Thanks @deeenes for the suggestion. I could generate the code using impf-botpy. But I don't know why it still hasn't managed to get an appointment since the past 3-4hrs- it somehow didn't confirm me available slots, despite few empty slots popping up on the Impftermin Ubersicht app. 
Thanks to the team vaccipy as well and @iamnotturner  - looking forward to the team's new development of the code and will wait to use it, it would be great if it works again!

**Comment by pancakeDevelopment** [comment]
> It was my fault that impf-botpy showed errors, I missed the part of downloading 'Selenium for Chrome' , basically the chromedriver exe file.
> Thanks @deeenes for the suggestion. I could generate the code using impf-botpy. But I don't know why it still hasn't managed to get an appointment since the past 3-4hrs- it somehow didn't confirm me available slots, despite few empty slots popping up on the Impftermin Ubersicht app.
> Thanks to the team vaccipy as well and @iamnotturner - looking forward to the team's new development of the code and will wait to use it, it would be great if it works again!

Hi Simone,
Whether you get an appointment is not up to vaccipy. Vaccipy only takes care of the requests (as if you were constantly sitting in front of the PC and reloading the page). The "Impftermin-Übersicht" page will show appointments as soon as a "Vermittlungscode" can be created. This is the case when appointments are available. Neither we nor the "Impftermin-Übersicht" can see how many there are. This can be one, five or even twenty appointments. Since you are not the only one who uses such sites or bots, this appointment may have already been booked in the meantime.

Therefore, I recommend: Just let vaccipy run. As soon as you get an appointment reserved, vaccipy books it completely automatically. Sometimes it takes 2 hours, but sometimes it takes several days. Of course, this depends on availability

**Comment by simone-1991** [comment]
yea, you are right. I should be patient.  let's see how it goes. Thanks !!!

**Comment by iamnotturner** [comment]
you can try our new beta version, code generation is with selenium now - and it works! special thanks to @JonasMock 

https://github.com/iamnotturner/vaccipy/releases/tag/v1.2.10

please let us know if this works for you, so we can publish it to everybody asap

**Comment by simone-1991** [comment]
ok. I made few attempts 
It showed 'Request limit reached' once, and after that it is repeating the error (screenshot below)
![image](https://user-images.githubusercontent.com/85735938/122012256-41b7a700-cdbd-11eb-90f5-64de9b29a2ba.png)
It could be the website traffic, maybe I will try again in half an hour and updated you again.

**Comment by simone-1991** [comment]
but with an exiting code, I can definitely search for appointment using this new version.
thanks to @JonasMock too for your help
!!

**Comment by simone-1991** [comment]
It just automatically works now, after I restarted in 4-5 times (i don't know why or how, I didn't change anything). It could successfully generate a code now with the newest version! 
Thanks guys, for your constant help!

**Comment by Seb202020** [comment]
Hi,
I've recieved an bot protection error after entering the sms code (version 1.2.10 on mac ). I've tried it three times.
Best regards

**Comment by JonasMock** [comment]
@Seb202020 Thanks. As this seems to happen more often then I thought, we should probably also implement a selenium version of code_bestaetigen()

**Comment by alemaoJulian** [comment]
Hi,
I am still receiving the bot protecting error with 1.2.10 on windows. Am I missing something?
I hope I'm not wasting anyone's time and it's just an error on my end.
![Vaccipy](https://user-images.githubusercontent.com/3777982/122024784-091dca80-cdc9-11eb-8b83-5ef3718c289b.jpg)

**Comment by JonasMock** [comment]
@alemaoJulian Seems like the GUI calls code_anfordern() and not selenium_code_anfordern(). I don't know how the GUI works, could someone please update this.

**Comment by JonasMock** [comment]
@alemaoJulian Could you try it again with the console version ?

**Comment by alemaoJulian** [comment]
The console version says that \\vaccipy\\seleniumwire\\ca.crt is missing

**Comment by alemaoJulian** [comment]
![vaccipy](https://user-images.githubusercontent.com/3777982/122027534-7cc0d700-cdcb-11eb-870b-cadcfbec4b94.jpg)

**Comment by iamnotturner** [comment]
@alemaoJulian we're on it #467

**Comment by alemaoJulian** [comment]
Thanks for the quick response, but even with the correct seleniumwire folder I'm running into the botprotection error. But vaccipy was able to enter my mail address and phone number.

**Comment by JonasMock** [comment]
@alemaoJulian Where does 429 occur ? After you entered the SMS-Code ?

The SMS-Code confirmation works like in the previous version, this probably needs also an Update to a selenium version (enter the sms code automatically in browser and don't send request directly to REST endpoint)

**Comment by alemaoJulian** [comment]
The error occurs before I even get the sms code. It worked once but then I entered the sms code in the console window and then it seems like it could not continue.

**Comment by Seb202020** [comment]
> @iamnotturner @Seb202020 Thanks. As this seems to happen more often then I thought, we should probably also implement a selenium version of code_bestaetigen() ? Or should the user just enter the sms code in the browser window ? What do you think ?

For a fast (if it's really a fast option?) workarround I think it's OK to enter the SMS code in the browser window. Actually the browser window is closed at this moment For the usability I think it's easier to enter the sms code in the console

**Comment by iamnotturner** [comment]
please try our latest release: https://github.com/iamnotturner/vaccipy/releases/tag/v1.2.13
