### ISSUE TITLE
Idee/Feature request: Mehr Zufall

### ISSUE THREAD

**Issue by prok42** [iamnotturner/vaccipy#461]
Hallo zusammen,

bei der Impfcode-Erzeugung wird ja zuerst ein Pseudo-Vermittlungscode namens VACC-IPY[5 Random Zeichen] eingetragen. Wäre ich Betreiber des impfterminservice, würde ich irgendwann anfangen, auf diesen Code zu prüfen und IPs temporär zu sperren ;-)
Hier wäre ein komplett zufälliger Pseudo-Code vermutlich (irgendwann) sinnvoll.

Weiterhin könnte man die Regelmäßigkeit der Retries ebenfalls via Randomisierung "verwässern" (bspw.: Retry-Sec als Mindest-Wartezeit zwischen Retries nutzen und noch eine Zusatz-Wartezeit random.randint(0, retry_sec) einführen, sodass die echte Retry-Zeit im Intervall "retry-sec" bis 2*retry-sec wäre.)

**Comment by Genmutant** [comment]
Hi, das habe ich gestern schonmal angefangen in #457 zu implementieren. Da gibts auch eine Diskussion bzgl VACC-IPY

**Comment by prok42** [comment]
--> Siehe #457
