### ISSUE TITLE
GUI Installation in Windows 10

### ISSUE THREAD

**Issue by rynaldi95** [iamnotturner/vaccipy#464]
Hallo,

ich habe eine kurze Frage: ich habe eine Windows 10 Maschine und ich habe schon das GUI Version heruntergeladen. Mit dem GUI braucht man eigentlich nichts mehr zu installieren, oder? Ich meine, muss man immer noch diese Code` pip3 install -r requirements.txt` durchführen?

**Comment by TRojaner2013** [comment]
Hey,
sofern du die .exe-Datei heruntergeladen hast, musst du dich um nichts weiter zu kümmern. EInfach die Datei ausführen und Vaccipy installieren. Nach abgeschlossener Installation kannst du sofort mi der Terminsuche beginnen.

**Comment by rynaldi95** [comment]
alles klar! danke dir! @TRojaner2013
