### ISSUE TITLE
DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by RedStylzZ** [iamnotturner/vaccipy#465]
Ich bekomme auf über die CLI auf Ubuntu diese Fehlermeldung beim suchen von Impfterminen:
Chromium ist installiert und der chrome-driver hat Execute-Rechte.
![image](https://user-images.githubusercontent.com/19490975/121966427-ee1e6c80-cd6e-11eb-8729-9c47fc963b64.png)

**Comment by iamnotturner** [comment]
fixed mit #466, kommt bald in executable
