### ISSUE TITLE
Booking an appointment does not work automatically

### ISSUE THREAD

**Issue by Spenhouet** [iamnotturner/vaccipy#469]
I now had this multiple times and I always missed it...
![image](https://user-images.githubusercontent.com/7819068/122011584-8b53c200-cdbc-11eb-8d36-946e223647a4.png)

It seems that it is unable to automatically book an appointment. I would need to do it manually.

Was there an UI change which the vaccipy does not yet consider and therefore can not handle?

**Comment by iamnotturner** [comment]
Hi, which version are you using?

**Comment by Spenhouet** [comment]
The newest commit on master.

**Comment by SebastianVol** [comment]
Same issue here, with the same center. Also using the newest version on mac via console.

**Comment by Spenhouet** [comment]
I also had it with different centers. I'm on windows.

**Comment by SebastianVol** [comment]
Did you also try to write your data manually? Because for me there was also the issue, that it closed the browser automatically after I typed my info. manually.

**Comment by Spenhouet** [comment]
> Did you also try to write your data manually? Because for me there was also the issue, that it closed the browser automatically after I typed my info. manually.

I had the selenium/Chrome window open up once (the other times I completely missed due to being in meetings).
I could have continued manually but I did not have time on the chosen date.
Nonetheless, yes, the window closed on its own again. I did not know how to continue manually. I assume you would somehow need to inject the current session cookie into a browser session to continue where vaccipy left. But no clue how to access that.

**Comment by pancakeDevelopment** [comment]
Hi,
you should remove the screenshot or censor the "Vermittlungscode". I also had the problem, but then it was due to the Impfterminservice, because the appointment was no longer available.

**Comment by axxelia-freiburg** [comment]
I had the same issue but manage to use the link and open the browser manually myself. That helps me to get the appointment.

**Comment by Spenhouet** [comment]
> I had the same issue but manage to use the link and open the browser manually myself. That helps me to get the appointment.

This does not seem to work for me. Every time I open a new browser window I get a new session.
Or does this work while in the 10 min. timeframe?

At least if I open different browser the Impfterminservice page shows independent count downs.

**Comment by PWNDA** [comment]
V1.2.10 Windows GUI worked for me today, for the same center. On 2nd try, but I was also able to open it manually and enter my data, but the bot was faster then

**Comment by T0XiiC27** [comment]
Im on the most recent version of the vaccipy GUI for Windows. Bot found an appointment in the morning at like 5am, but couldnt book it automatically, same thing as in ur screenshot (Different Center tho). Wasnt on my pc at that time so I couldnt try it manually.

**Comment by simone-1991** [comment]
yes, I get the same error too, doesn't book the appointment automatically.

**Comment by jaydkay** [comment]
Same thing here as well, current commit on the master branch on Mac:
```
2021-06-14 09:38:27.982   impfterminservice   [suc] [70376]   Termin gefunden!
2021-06-14 09:38:27.984   impfterminservice   [suc] [70376]   'Impfzentrum am Robert-Bosch-Krankenhaus' in 70376 Stuttgart
2021-06-14 09:38:27.984   impfterminservice   [suc] [70376]   1. Termin: 03.07.2021 um 08:35 Uhr
2021-06-14 09:38:27.984   impfterminservice   [suc] [70376]   2. Termin: 14.08.2021 um 18:40 Uhr
2021-06-14 09:38:27.984   impfterminservice   [suc] [70376]   Link: https://001-iz.impfterminservice.de/impftermine/suche/****-****-****/70376
2021-06-14 09:38:27.985   impfterminservice   [inf] [70376]   Browser-Cookies generieren
2021-06-14 09:38:30.158   impfterminservice   [inf] [70376]   Vermittlungscode eintragen und Mausbewegung / Klicks simulieren. Dieser Vorgang kann einige Sekunden dauern.
2021-06-14 09:38:45.248   impfterminservice   [inf] [70376]   Browser-Cookie generiert: *glzA==
2021-06-14 09:38:45.404   impfterminservice   [err] [70376]   Termin konnte nicht gebucht werden: 429 {}
2021-06-14 09:38:45.404   impfterminservice   [inf] [70376]   Starte zweiten Versuch über Selenium ...
2021-06-14 09:38:45.404   impfterminservice   [inf] [70376]   Termin über Selenium buchen
2021-06-14 09:38:47.399   impfterminservice   [inf] [70376]   Vermittlungscode eintragen und Mausbewegung / Klicks simulieren. Dieser Vorgang kann einige Sekunden dauern.
2021-06-14 09:39:01.122   impfterminservice   [err] [70376]   Termine können nicht gesucht werden
2021-06-14 09:39:05.408   impfterminservice   [err] [70376]   Termine können nicht ausgewählt werden
2021-06-14 09:39:06.657   impfterminservice   [err] [70376]   Termine können nicht ausgewählt werden (Button)
2021-06-14 09:39:07.677   impfterminservice   [err] [70376]   1. Daten können nicht erfasst werden
2021-06-14 09:39:08.695   impfterminservice   [err] [70376]   Kontaktdaten können nicht eingegeben werden
2021-06-14 09:39:09.936   impfterminservice   [err] [70376]   Button ÜBERNEHMEN kann nicht gedrückt werden
2021-06-14 09:39:10.960   impfterminservice   [err] [70376]   Button Termin buchen kann nicht gedrückt werden
2021-06-14 09:39:13.966   impfterminservice   [err] [70376]   Automatisierte Terminbuchung fehlgeschlagen
2021-06-14 09:39:13.966   impfterminservice   [err] [70376]   Termin manuell im Fenster oder im Browser buchen.
2021-06-14 09:39:13.967   impfterminservice   [err] [70376]   Link: https://001-iz.impfterminservice.de/impftermine/suche/****-****-****/70376
2021-06-14 09:49:14.047   impfterminservice   [err] [70376]   Termin konnte nicht gebucht werden.
```

**Comment by plorenz-etes** [comment]
I also had the same issue - booking it manually does work however (keep the browser window open and enter the code and contact information by hand).

**Comment by ankeknicker** [comment]
I had this problem today already two times. the first time I tried to enter the data manually, but wasnt able to book. The second time I totally missed it...

**Comment by rynaldi95** [comment]
I also had the same problem, but then I open a new Chome browser and just go to the designated Impfzentrum, enter the Vermittlungscode and the slot was still available for me. Then, I enter my contact details manually and got the appointment booked! I had it exactly just now.

**Comment by Spenhouet** [comment]
Any idea on how to resolve this? @iamnotturner What would you need as info?

**Comment by simone-1991** [comment]
Adding information manually works for booking. Once it detects an available appointment, it seems to reserve the date for few mins, which is enough to enter personal information manually I think.

**Comment by Spenhouet** [comment]
I had the same thing again. This time I was at the computer and entered everything manually in a second Chrome window but the appointment was already taken when I tried to book it...


> 2021-06-16 07:39:20.124   impfterminservice   [suc] [70376]   Termin gefunden!
> 2021-06-16 07:39:20.125   impfterminservice   [suc] [70376]   'Impfzentrum am Robert-Bosch-Krankenhaus' in 70376 Stuttgart
> 2021-06-16 07:39:20.125   impfterminservice   [suc] [70376]   1. Termin: 26.06.2021 um 08:05 Uhr
> 2021-06-16 07:39:20.126   impfterminservice   [suc] [70376]   2. Termin: 07.08.2021 um 11:15 Uhr
> 2021-06-16 07:39:20.127   impfterminservice   [suc] [70376]   Link: https://001-iz.impfterminservice.de/impftermine/suche/XXXX-XXXX-XXXX/70376
> 2021-06-16 07:39:20.127   impfterminservice   [inf] [70376]   Browser-Cookies generieren
> 2021-06-16 07:39:21.238   impfterminservice   [inf] [70376]   Vermittlungscode eintragen und Mausbewegung / Klicks simulieren. Dieser Vorgang kann einige Sekunden dauern.
> 2021-06-16 07:39:37.875   impfterminservice   [inf] [70376]   Browser-Cookie generiert: *lAMA==
> 2021-06-16 07:39:40.091   impfterminservice   [err] [70376]   **Termin konnte nicht gebucht werden: 429 {}**
> 2021-06-16 07:39:40.092   impfterminservice   [inf] [70376]   Starte zweiten Versuch über Selenium ...
> 2021-06-16 07:39:40.093   impfterminservice   [inf] [70376]   Termin über Selenium buchen
> 2021-06-16 07:39:41.196   impfterminservice   [inf] [70376]   Vermittlungscode eintragen und Mausbewegung / Klicks simulieren. Dieser Vorgang kann einige Sekunden dauern.
> 2021-06-16 07:39:57.393   impfterminservice   [err] [70376]   **Termine können nicht gesucht werden**
> 2021-06-16 07:40:01.497   impfterminservice   [err] [70376]   **Termine können nicht ausgewählt werden**
> 2021-06-16 07:40:02.616   impfterminservice   [err] [70376]   **Termine können nicht ausgewählt werden (Button)**
> 2021-06-16 07:40:03.654   impfterminservice   [err] [70376]   **1. Daten können nicht erfasst werden**
> 2021-06-16 07:40:04.692   impfterminservice   [err] [70376]   **Kontaktdaten können nicht eingegeben werden**
> 2021-06-16 07:40:05.804   impfterminservice   [err] [70376]   **Button ÜBERNEHMEN kann nicht gedrückt werden**
> 2021-06-16 07:40:06.845   impfterminservice   [err] [70376]   **Button Termin buchen kann nicht gedrückt werden**
> 2021-06-16 07:40:09.853   impfterminservice   [err] [70376]   Automatisierte Terminbuchung fehlgeschlagen
> 2021-06-16 07:40:09.853   impfterminservice   [err] [70376]   Termin manuell im Fenster oder im Browser buchen.
> 2021-06-16 07:40:09.854   impfterminservice   [err] [70376]   Link: https://001-iz.impfterminservice.de/impftermine/suche/XXXX-XXXX-XXXX/70376
> 2021-06-16 07:50:12.051   impfterminservice   [err] [70376]   Termin konnte nicht gebucht werden.

To address this issue I tried to record all html UI elements.

We start with selecting an appointment by pressing "Termine suchen":

```html
<div _ngcontent-nfa-c126="" class="its-search-step-content"><button _ngcontent-nfa-c126="" data-toggle="modal"
        class="btn btn-magenta kv-btn kv-btn-round search-filter-button" data-target="#itsSearchAppointmentsModal">
        Termine suchen
    </button></div>
```

The appointment form dialog shows up:
![select_appointment](https://user-images.githubusercontent.com/7819068/122165248-38d7db80-ce78-11eb-99fd-f66e603e731e.PNG)

Here we find the following form:

```html
<form _ngcontent-nfa-c125="" novalidate="" class="ng-untouched ng-dirty ng-valid">
    <!---->
    <!---->
    <div _ngcontent-nfa-c125=""
        class="d-flex flex-column its-slot-pair-search-info pr-3 pl-3">
        <div _ngcontent-nfa-c125="" class="mb-3"><span
                _ngcontent-nfa-c125=""><strong
                    _ngcontent-nfa-c125="">Impfzentrum am
                    Robert-Bosch-Krankenhaus - 0</strong></span><span
                _ngcontent-nfa-c125="" class="d-block"> Auerbachstr. 110,
                70376 Stuttgart </span></div>
        <div _ngcontent-nfa-c125="" class="form-group d-flex flex-column">
            <!---->
            <div _ngcontent-nfa-c125=""
                class="d-none d-lg-flex its-slot-pair-search-title">
                <div _ngcontent-nfa-c125=""
                    class="d-flex its-slot-pair-search-slot-wrapper"><span
                        _ngcontent-nfa-c125="" class="flex-fill"><strong
                            _ngcontent-nfa-c125="">1.
                            Impftermin</strong></span><span
                        _ngcontent-nfa-c125=""
                        class="its-slot-pair-search-slot-sep"></span><span
                        _ngcontent-nfa-c125="" class="flex-fill"><strong
                            _ngcontent-nfa-c125="">2.
                            Impftermin</strong></span></div>
                <div _ngcontent-nfa-c125=""
                    class="its-slot-pair-search-radio-wrapper"></div>
            </div>
            <!----><label _ngcontent-nfa-c125=""
                class="d-flex flex-nowrap its-slot-pair-search-item"><input
                    _ngcontent-nfa-c125="" type="radio"
                    formcontrolname="slotPair"
                    class="ng-untouched ng-dirty ng-valid">
                <div _ngcontent-nfa-c125=""
                    class="d-flex flex-lg-row flex-column its-slot-pair-search-slot-wrapper">
                    <div _ngcontent-nfa-c125=""
                        class="its-slot-pair-search-slot"><span
                            _ngcontent-nfa-c125="">Sa., 26.06.2021 -
                        </span><span _ngcontent-nfa-c125=""
                            class="text-nowrap">08:05 Uhr</span></div>
                    <div _ngcontent-nfa-c125=""
                        class="text-center its-slot-pair-search-slot-sep">
                        <span _ngcontent-nfa-c125=""
                            class="d-lg-inline-block d-none text-blue">-</span>
                    </div>
                    <div _ngcontent-nfa-c125=""
                        class="its-slot-pair-search-slot"><span
                            _ngcontent-nfa-c125="">Sa., 07.08.2021 -
                        </span><span _ngcontent-nfa-c125=""
                            class="text-nowrap">11:15 Uhr</span></div>
                    <!---->
                    <!---->
                </div>
                <div _ngcontent-nfa-c125=""
                    class="its-slot-pair-search-radio-wrapper">
                    <div _ngcontent-nfa-c125=""
                        class="its-slot-pair-search-radio-btn"></div>
                </div>
            </label>
            <!---->
            <!---->
        </div>
    </div>
    <!---->
    <!---->
    <!---->
    <!---->
    <div _ngcontent-nfa-c125="" class="form-group"><button
            _ngcontent-nfa-c125="" type="submit"
            class="btn kv-btn btn-magenta text-center d-inline-block">
            AUSWÄHLEN </button><button _ngcontent-nfa-c125="" type="button"
            data-dismiss="modal"
            class="btn kv-btn kv-btn-hollow btn-magenta text-center d-inline-block">
            Abbrechen </button></div>
</form>
```

Here the round radio button at the right needs to be selected first.

```html
<div _ngcontent-nfa-c125="" class="its-slot-pair-search-radio-wrapper">
    <div _ngcontent-nfa-c125="" class="its-slot-pair-search-radio-btn"></div>
</div>
```

Then the form can be submitted with the "AUSWÄHLEN" submit button.

```html
<div _ngcontent-nfa-c125="" class="form-group"><button _ngcontent-nfa-c125="" type="submit"
        class="btn kv-btn btn-magenta text-center d-inline-block">
        AUSWÄHLEN </button><button _ngcontent-nfa-c125="" type="button" data-dismiss="modal"
        class="btn kv-btn kv-btn-hollow btn-magenta text-center d-inline-block">
        Abbrechen </button></div>
```

After selecting an appointment the data needs to be entered:
![enter_data](https://user-images.githubusercontent.com/7819068/122165782-fc58af80-ce78-11eb-985f-f967ea3f58c3.PNG)

This is done via the "Daten erfassen" button:

```html
<button _ngcontent-nfa-c126="" data-toggle="modal" class="btn btn-magenta kv-btn kv-btn-round search-filter-button"
    data-target="#itsSearchContactModal"> Daten erfassen </button>
```

This will open up the following form dialog:
![enter_data_form](https://user-images.githubusercontent.com/7819068/122165979-48a3ef80-ce79-11eb-8e10-0f93ae81f981.PNG)

The html form:

```html
<form novalidate="" class="ets-booking-content ng-touched ng-dirty ng-invalid">
    <div class="form-group">
        <app-booking-contact-form formcontrolname="contact" _nghost-nfa-c78="" class="ng-touched ng-dirty ng-invalid">
            <div _ngcontent-nfa-c78="" class="row no-gutters">
                <div _ngcontent-nfa-c78="" class="col-12">
                    <div _ngcontent-nfa-c78="" class="form-group">
                        <p _ngcontent-nfa-c78="">Anrede*</p>
                        <div _ngcontent-nfa-c78="" class="ets-radio-wrapper full"><label _ngcontent-nfa-c78=""
                                class="ets-radio-control"><input _ngcontent-nfa-c78="" type="radio" name="salutation"
                                    value="Herr" required="" formcontrolname="salutation"
                                    class="form-check-input ng-untouched ng-dirty ng-valid"><span
                                    _ngcontent-nfa-c78="">Herr</span></label><label _ngcontent-nfa-c78=""
                                class="ets-radio-control"><input _ngcontent-nfa-c78="" type="radio" name="salutation"
                                    value="Frau" required="" formcontrolname="salutation"
                                    class="form-check-input ng-untouched ng-dirty ng-valid"><span
                                    _ngcontent-nfa-c78="">Frau</span></label><label _ngcontent-nfa-c78=""
                                class="ets-radio-control"><input _ngcontent-nfa-c78="" type="radio" name="salutation"
                                    value="Divers" required="" formcontrolname="salutation"
                                    class="form-check-input ng-untouched ng-dirty ng-valid"><span
                                    _ngcontent-nfa-c78="">Divers</span></label><label _ngcontent-nfa-c78=""
                                class="ets-radio-control"><input _ngcontent-nfa-c78="" type="radio" name="salutation"
                                    value="Kind" required="" formcontrolname="salutation"
                                    class="form-check-input ng-untouched ng-dirty ng-valid"><span
                                    _ngcontent-nfa-c78="">Kind</span></label></div>
                        <!---->
                    </div>
                </div>
            </div>
            <div _ngcontent-nfa-c78="" class="row no-gutters">
                <div _ngcontent-nfa-c78="" class="col-12 col-md-5">
                    <div _ngcontent-nfa-c78="" class="form-group"><label _ngcontent-nfa-c78=""><span
                                _ngcontent-nfa-c78="" class="d-none d-md-block">Vorname*</span><input
                                _ngcontent-nfa-c78="" name="firstname" formcontrolname="firstname" required=""
                                type="text" class="form-control ng-dirty ng-touched ng-invalid"
                                placeholder="z.B. Maximilian"></label>
                    </div>
                </div>
                <div _ngcontent-nfa-c78="" class="col-12 col-md-5 offset-md-1">
                    <div _ngcontent-nfa-c78="" class="form-group"><label _ngcontent-nfa-c78=""><span
                                _ngcontent-nfa-c78="" class="d-none d-md-block">Nachname*</span><input
                                _ngcontent-nfa-c78="" name="lastname" formcontrolname="lastname" required="" type="text"
                                class="form-control ng-dirty ng-touched ng-invalid"
                                placeholder="z.B. Mustermann"></label>
                    </div>
                </div>
            </div>
            <div _ngcontent-nfa-c78="" class="row no-gutters">
                <div _ngcontent-nfa-c78="" class="col-12 col-md-5">
                    <div _ngcontent-nfa-c78="" class="form-group"><label _ngcontent-nfa-c78=""><span
                                _ngcontent-nfa-c78="" class="d-none d-md-block">PLZ*</span><input _ngcontent-nfa-c78=""
                                name="plz" formcontrolname="zip" required="" type="tel" minlength="5" maxlength="5"
                                class="form-control ng-dirty ng-touched ng-invalid" placeholder="z.B. 12345"></label>
                    </div>
                </div>
                <div _ngcontent-nfa-c78="" class="col-12 col-md-5 offset-md-1">
                    <div _ngcontent-nfa-c78="" class="form-group"><label _ngcontent-nfa-c78=""><span
                                _ngcontent-nfa-c78="" class="d-none d-md-block">Ort*</span><input _ngcontent-nfa-c78=""
                                name="city" formcontrolname="city" required="" type="text"
                                class="form-control ng-dirty ng-touched ng-invalid"
                                placeholder="z.B. Musterort"></label>
                    </div>
                </div>
            </div>
            <div _ngcontent-nfa-c78="" class="row no-gutters">
                <div _ngcontent-nfa-c78="" class="col-7">
                    <div _ngcontent-nfa-c78="" class="form-group"><label _ngcontent-nfa-c78=""><span
                                _ngcontent-nfa-c78="" class="d-none d-md-block">Straße*</span><input
                                _ngcontent-nfa-c78="" name="street" formcontrolname="street" required="" type="text"
                                placeholder="z.B. Musterstraße" class="ng-dirty ng-touched ng-invalid"></label>
                    </div>
                </div>
                <div _ngcontent-nfa-c78="" class="col-4 col-md-3 offset-1">
                    <div _ngcontent-nfa-c78="" class="form-group"><label _ngcontent-nfa-c78=""><span
                                _ngcontent-nfa-c78="" class="d-none d-md-block">Hausnummer</span><input
                                _ngcontent-nfa-c78="" name="street" formcontrolname="housenumber" type="text"
                                placeholder="z.B. 123" class="ng-valid ng-dirty ng-touched"></label>
                        <!---->
                    </div>
                </div>
                <div _ngcontent-nfa-c78="" class="col-12 col-md-11">
                    <div _ngcontent-nfa-c78="" class="form-group"><label _ngcontent-nfa-c78=""><span
                                _ngcontent-nfa-c78="" class="d-none d-md-block">Rückrufnummer*</span>
                            <div _ngcontent-nfa-c78="" class="input-group">
                                <div _ngcontent-nfa-c78="" class="input-group-prepend"><span _ngcontent-nfa-c78=""
                                        class="input-group-text">+49 </span></div><input _ngcontent-nfa-c78=""
                                    name="phone" formcontrolname="phone" required="" type="tel" minlength="2"
                                    class="form-control ng-dirty ng-touched ng-invalid" placeholder="z.B. 160 1234567">
                            </div>
                            <!---->
                            <!---->
                        </label>
                    </div>
                </div>
            </div>
            <div _ngcontent-nfa-c78="" class="form-group">
                <!---->
                <div _ngcontent-nfa-c78="" class="row no-gutters">
                    <div _ngcontent-nfa-c78="" class="col-12"><label _ngcontent-nfa-c78=""><span _ngcontent-nfa-c78=""
                                class="d-none d-md-block">E-Mail zur
                                Terminbenachrichtigung*</span><input _ngcontent-nfa-c78="" name="notificationReceiver"
                                formcontrolname="notificationReceiver" type="text" placeholder="z.B. max@muster.de"
                                class="ng-dirty ng-touched ng-invalid"></label>
                    </div>
                </div>
            </div>
            <!---->
            <div _ngcontent-nfa-c78="" class="form-group">
                <div _ngcontent-nfa-c78="" class="row no-gutters">
                    <div _ngcontent-nfa-c78="" class="col-12"><small _ngcontent-nfa-c78="">* Pflichtfelder</small>
                    </div>
                </div>
            </div>
            <!---->
        </app-booking-contact-form>
    </div>
    <div class="form-group"><button type="submit" class="btn kv-btn btn-magenta text-center d-inline-block" disabled="">
            Übernehmen </button><button type="button" data-dismiss="modal"
            class="btn kv-btn kv-btn-hollow btn-magenta text-center d-inline-block"> Abbrechen </button></div>
</form>
```

There all data needs to be entered / selected and then submitted via the submit button "Übernehmen".

The final step is to press "VERBINDLICH BUCHEN":

```html
<button _ngcontent-nfa-c126="" class="btn btn-magenta kv-btn kv-btn-round search-filter-button"> VERBINDLICH BUCHEN
</button>
```

The first issue is probably that it already fails at this step:

> Termin konnte nicht gebucht werden: 429 {}

But then it tries to book via UI and here it already fails at:

> Termine können nicht gesucht werden

Suggesting to me that it already is not able to handle the appointment form dialog.
I hope the html snippets above help to fix this issue.

**Comment by AmadeusL** [comment]
I have exactly the same issue (Error 429) but with Ubuntu 21.04 and vaccipy version 1.2.8.
Booking manually works because the appointment is reserved. But that means to look at the computer every 10 minutes or so.

**Comment by iamnotturner** [comment]
> The first issue is probably that it already fails at this step:
> 
> > Termin konnte nicht gebucht werden: 429 {}
> 
> But then it tries to book via UI and here it already fails at:
> 
> > Termine können nicht gesucht werden
> 
> Suggesting to me that it already is not able to handle the appointment form dialog.
> I hope the html snippets above help to fix this issue.

Its a bit weird since the automated booking works for some and for some not. Both, requests or selenium.
I think the main issue is the 429, where when you're temporary banned, selenium won't be able to book the appointment aswell. @Spenhouet have you tried to pause the search for a few hours and started again? Thanks a lot for the code snippets, they might help a lot!

@AmadeusL could you please try v1.2.12?

**Comment by Spenhouet** [comment]
> when you're temporary banned, selenium won't be able to book the appointment aswell

That would make sense but why am I not getting a 429 when I'm continuing manually (opening up a new browser window)?

> @Spenhouet have you tried to pause the search for a few hours and started again?

No. Are you thinking about a shadow bann of my IP?

I am running multiple instances of vaccipy for different centers but they all use different API URLs so I would not expect this to be a problem.

**Comment by iamnotturner** [comment]
> That would make sense but why am I not getting a 429 when I'm continuing manually (opening up a new browser window)?

there is a difference between Selenium and your "regular" browser. I'm not too deep into network stuff, but they definitely can detect what kind of browser you're using.

> No. Are you thinking about a shadow bann of my IP?

actually yes, even if you're running on different subdomains its possible that your IP is temporarily banned due to too many requests. I had the same issues, for me it was code generation - and after not using vaccipy for 2-3 days I instantly was able to generate a code and to book an appointment with requests.

**Comment by Spenhouet** [comment]
> but they definitely can detect what kind of browser you're using.

I can confirm that. I just now had the same again and checked. In selenium I get a 429 and in another Chrome window I don't but the appointment was gone already again...

>  its possible that your IP is temporarily banned

I somewhat doubt that since I occasionally find an appointments and am not constantly getting 429 returns.
Currently I get about 2 appointments per day... so going the pause 2-3 days route would just not be fast enough to get an appointment. I'm not taking the chances.

If this is not fixable via the automation then I will to hope that I'm fast enough entering everything manually and getting an appoint via that when vaccipy reserved one automatically.

**Comment by Genmutant** [comment]
Yes, there are some possibilities for the webpage (I guess mainly using JS) to check for selenium. See [here](https://stackoverflow.com/questions/33225947/can-a-website-detect-when-you-are-using-selenium-with-chromedriver/):
For example:

> Basically, the way the Selenium detection works, is that they test for predefined JavaScript variables which appear when running with Selenium. The bot detection scripts usually look anything containing word "selenium" / "webdriver" in any of the variables (on window object), and also document variables called $cdc_ and $wdc_.

Would be interessting to debug the running JS that sends the data (the one on-click maybe?) to see what data is being collected.

**Comment by T0XiiC27** [comment]
Bot found an appointment today and it wasnt able to book it automatically. Had to book it myself, which worked flawlessly.

**Comment by HoliGHOST** [comment]
I'm not very deep into this whole stuff but what I see on impfterminservice.de, if I want to insert my Vermittlungscode this works only if I type the characters manually.
Using copy & paste leads to the problem, that the first field of the Vermittlungscode is always overwritten with the characters I want to paste.

For example, instead of this

![codeerr1](https://user-images.githubusercontent.com/85995763/122205838-f8408800-cea0-11eb-9097-c2ccaafb4401.png)

I get 

![image](https://user-images.githubusercontent.com/85995763/122205981-2625cc80-cea1-11eb-9267-5c2701b5f9d4.png)

Maybe this happens also when vaccipy tries to write the code and thus, is not able to login...

**Comment by Spenhouet** [comment]
I now had it again. I did instantly go to the manual booking but again the appointment was already taken.

@HoliGHOST No, that's not it.

@iamnotturner I did watch the selenium window and it tried to enter the code but got a 429 back:

> Request URL: https://002-iz.impfterminservice.de/rest/login?plz=70174
> Request Method: GET
> Status Code: 429 Too Many Requests

I did open up another Chrome window and tried manually:

![image](https://user-images.githubusercontent.com/7819068/122218144-69d30300-ceae-11eb-8737-9436cecfa1cf.png)

As you can see in the timing I did not take long.

The response here was:

> Request URL: https://002-iz.impfterminservice.de/rest/buchung
> Request Method: POST
> Status Code: 400 Bad Request

```
{
    "errors": [
        {
            "code": "WP011",
            "text": "Der ausgewählte Termin ist nicht mehr verfügbar. Bitte wählen Sie einen anderen Termin aus"
        }
    ]
}
```

**Comment by HoliGHOST** [comment]
Exactly the same here,

appointment can still be selected but after inserting data manually and clicking on booking button I get same message. Appointment not available anymore, although  it should have been reserved for 10 minutes.

**Comment by JonasMock** [comment]
@Spenhouet @HoliGHOST Which vaccipy release version do you use for the booking ?

**Comment by HoliGHOST** [comment]
v1.2.8 CLI
Happend also with previous version, so I updated, but didn't help

**Comment by Spenhouet** [comment]
> @Spenhouet @HoliGHOST Which vaccipy release version do you use for the booking ?

As I wrote before, I'm using the latest commit on master.

**Comment by JonasMock** [comment]
@Spenhouet Could you try latest commit on beta branch ? Would be interesting to know if this solves your problem.

**Comment by Spenhouet** [comment]
> @Spenhouet Could you try latest commit on beta branch ? Would be interesting to know if this solves your booking problem. / Reduces the chance of 429.

Sure, will do.
For anyone else going on the beta branch: You need to install the selenium-wire dependency.

I will report back as soon as it finds a new appointment. From the past days I do not expect any more free appointments today.

**Comment by Spenhouet** [comment]
Nice, this worked.

The new mouse movement simulation and slow entering of the vcode did help!

```
2021-06-16 15:44:31.535   impfterminservice   [suc] [XXXXX]   Termin gefunden!
2021-06-16 15:44:31.535   impfterminservice   [suc] [XXXXX]   XXXXXXXXXXXX
2021-06-16 15:44:31.536   impfterminservice   [suc] [XXXXX]   1. Termin: XX.XX.2021 um XX:XX Uhr
2021-06-16 15:44:31.537   impfterminservice   [suc] [XXXXX]   2. Termin: XX.XX.2021 um XX:XX Uhr
2021-06-16 15:44:31.537   impfterminservice   [suc] [XXXXX]   Link: https://003-iz.impfterminservice.de/impftermine/suche/XXXX-XXXX-XXXX/XXXXX
2021-06-16 15:44:31.545   impfterminservice   [inf] [XXXXX]   Browser-Cookies generieren
2021-06-16 15:44:32.546   impfterminservice   [inf] [XXXXX]   Vermittlungscode eintragen und Mausbewegung / Klicks simulieren. Dieser Vorgang kann einige Sekunden dauern.
2021-06-16 15:44:33.317   impfterminservice   [inf] [XXXXX]   Simulation der Mausbewegungen gestartet. Von: (0, 0) nach (264, 566)
2021-06-16 15:44:43.351   impfterminservice   [inf] [XXXXX]   Simulation der Mausbewegungen gestartet. Von: (264.0, 566.0) nach (387, 792)
2021-06-16 15:44:48.568   impfterminservice   [inf] [XXXXX]   Simulation der Mausbewegungen gestartet. Von: (387.0, 792.0) nach (260, 268)
2021-06-16 15:44:57.936   impfterminservice   [inf] [XXXXX]   Simulation der Mausbewegungen gestartet. Von: (260.0, 268.0) nach (167, 405)
2021-06-16 15:45:14.233   impfterminservice   [inf] [XXXXX]   Simulation der Mausbewegungen gestartet. Von: (167.0, 405.0) nach (359, 470)
2021-06-16 15:45:19.196   impfterminservice   [inf] [XXXXX]   Browser-Cookie generiert: *XXXX==
2021-06-16 15:45:21.602   impfterminservice   [suc] [XXXXX]   Termin erfolgreich gebucht!
```

Thanks!
I guess when this is merged it should work for all.
