### ISSUE TITLE
Kurze Frage zur Code generierung in der neuen GUI Version 

### ISSUE THREAD

**Issue by prinze2021** [iamnotturner/vaccipy#470]
Muss man eine Adresse plus einen selbst Erfunden Code eingeben um dann den neuen Code mit Geburtsdatum erstellen zu können? Zugesendet wird einem ja dann ein, ich sage mal, echter Code für das entsprechende Impfzentrum.

**Comment by iamnotturner** [comment]
Hey, du gibst immer die richtigen Daten an und erhälst anschließend auch einen korrekten Code 😎

**Comment by prinze2021** [comment]
Sorry für die Störung noch einmal. Ich gebe ja die komplett korrekten Daten
ein mit Adresse Name und so weiter aber wenn ich dann einen Code generieren
möchte zeigt er mir an das ein Code fehlt. Also gebe ich irgendein erst
einmal ein und bekomme dann einen korrekten. Das ist doch richtig so oder?

Tim Reibe ***@***.***> schrieb am Di., 15. Juni 2021, 09:54:

**Comment by TRojaner2013** [comment]
@prinze2021 
Sofern du die Kontaktdaten das erste Mal eingbist, nachdem du auf "Vermittlungscode generieren"geklickt hast, sollte sich folgendes Fenster öffnen:
![image](https://user-images.githubusercontent.com/10894083/122021806-53ea1300-cdc6-11eb-83f2-4780829ef7b6.png)

Hier ist ein Platzhalter XXXX-XXXX-XXX (gelb markiert) eingegeben.
Wenn du die Kontaktdaten über das Feld "Kontaktdaten bearbeiten" öffnest, ist dieser Platzhalter nicht ausgewählt.
In dem Fall kannst du selber eine belibgen Code eingeben (z. B. XXXX-XXXX-XXXX).
Solltes du noch weitere Fragen haben, schreib einfach hier.

**Comment by prinze2021** [comment]
Tausend Dank für die schnelle und freundliche Antwort. Werde das heute
abend mal versuchen wenn ich wieder zu Hause bin. Danke danke danke

Alex ***@***.***> schrieb am Di., 15. Juni 2021, 10:45:
