### ISSUE TITLE
Überspringe Code XXXX* für PLZ

### ISSUE THREAD

**Issue by JaDerBobby** [iamnotturner/vaccipy#473]
Ist es möglich die Codes den richtigen Impfzentren zuzuordnen?

![image](https://user-images.githubusercontent.com/85932693/122042249-33c44f00-cdda-11eb-9c9e-3e85ff34db4b.png)

**Comment by RedStylzZ** [comment]
Das passiert glaube ich wenn der Impfcode für eine andere Gruppe generiert wurde als die die hier angegeben sind. Zumindest war das bei mir mal so

**Comment by RedStylzZ** [comment]
Du musst hier Impfcodes aus ein und der selben Gruppe verwenden: https://github.com/iamnotturner/vaccipy/wiki/Ein-Code-fuer-mehrere-Impfzentren

Möchtest du aber auch in anderen Zentren suchen, musst du mehrere Codes generieren

**Comment by JaDerBobby** [comment]
Ich habe für jedes der 5 Zentren einen Code generiert und alle 5 Codes/Zentren in die .json eingetragen. Funktioniert das trotzdem?

**Comment by RedStylzZ** [comment]
Das kann ich dir leider nicht sagen, habe selber noch nicht mit mehreren Vermittlungscodes gearbeitet

**Comment by RedStylzZ** [comment]
Es ist aber auch möglich dass es einfach so programmiert wurde, denn teilweiße prüft der bot ja auf Codes die er davor übersprungen hat

**Comment by JuliusJacobitz** [comment]
> https://github.com/iamnotturner/vaccipy/wiki/Ein-Code-fuer-mehrere-Impfzentren

Es wird jede Kombination aus Impfzentrum und code geprüft, die du eingibst. Wenn Impfzentrums-Gruppe und Code-Gruppe nicht übereinstimmen, wird diese Kombination übersprungen.
