### ISSUE TITLE
[1.2.11] Vermittlungscode generieren: Fehler nach einem Versuch, SMS Eingabe via Bot funktioniert oft nicht

### ISSUE THREAD

**Issue by prok42** [iamnotturner/vaccipy#475]
Hallo zusammen,

zwei kleine Fehler, die mir in 1.2.10/1.2.11 aufgefallen sind (nutze das Windows-Zip):
1.) Wenn die Code Generierung wg. 429 fehlschlägt, schreibt der Bot zwar "Erneuter Versuch in 30 Sekunden", liefert dann jedoch "Fehler: Message: invalid session id" und befördert einen ins Hauptmenü. 

2.) Heute konnte ich mit 1.2.10/1.2.11 schon zwei Codes generieren, aber nur dann, wenn ich extrem schnell war und die SMS TAN in das Browserfenster *manuell* eingegeben habe. Jedesmal (zweimal versucht), wenn ich gewartet habe, das Browserfenster verschwand und der Bot die SMS TAN abgefragt hat, schlug die Code-Erzeugung fehl. (-> hier vlt. einfach das Browserfenster offen lassen?)

**Comment by JonasMock** [comment]
@prok42 Beides sollte in PR: https://github.com/iamnotturner/vaccipy/pull/480 behoben sein.

**Comment by iamnotturner** [comment]
bitte testen: [v1.2.12](https://github.com/iamnotturner/vaccipy/releases/tag/v1.2.12)
issue mache ich wieder auf, wenn das problem weiterhin besteht.
