### ISSUE TITLE
DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by sicherist** [iamnotturner/vaccipy#483]
Hallo, danke fürs Entwickeln von vaccipy!

Ich habe mit der Version 1.2.12 folgendes Problem beim Vermittlungscode generieren (Kubuntu 21.04, CLI):

Nach der Eingabe des Geburtsdatums öffnet sich ein Chromium-Fenster. In der Adressleiste des Browserfensters steht nur "data:," und nach einiger Zeit schließt sich das Fenster.
```
Fehler:
Message: unknown error: DevToolsActivePort file doesn't exist
```

**Comment by iamnotturner** [comment]
humm... ich dachte das wäre behoben mit https://github.com/iamnotturner/vaccipy/blob/995824b5e21aeb92c42e5ad097f8b6b4ef15219c/tools/its.py#L281 ... hattest du das Problem auch schon mit vorherigen Versionen (v1.2.8)?

**Comment by meteore** [comment]
Hallo, Ubuntu 21.04, CLI hier - gleiche Meldung sowohl bei Ubuntu CLI version (1.2.8) wie auch mit aktuellem Quellcode aus GH.

**Comment by JonasMock** [comment]
@iamnotturner Vielleicht müssen bei selenium_code_anfordern() dieselben Args beim driver init angegeben werden. Habe da keine Args übergeben.

https://github.com/iamnotturner/vaccipy/blob/995824b5e21aeb92c42e5ad097f8b6b4ef15219c/tools/its.py#L1023

**Comment by JonasMock** [comment]
Kann das heute Nachmittag einbauen, dass der Driver auch über get_chrome_driver() geholt wird und mit den gleichen Optionen gestartet wird.

**Comment by iamnotturner** [comment]
@JonasMock done #485

**Comment by iamnotturner** [comment]
habe die Chrome-Options hinzugefügt, bitte mal probieren: https://github.com/iamnotturner/vaccipy/releases/tag/v1.2.13

**Comment by Sylwuscha** [comment]
"Die Code-Generierung war leider nicht erfolgreich:
Vermittlungscode kann derzeit nicht angefragt werden. Versuchen Sie es später erneut."

Bei mir klappt weder das weiße Fenster noch das schwarze. Immer erscheint obiger Fehler

**Comment by Sylwuscha** [comment]
Ich meine die neue 13er Version

"Die Code-Generierung war leider nicht erfolgreich:
Vermittlungscode kann derzeit nicht angefragt werden. Versuchen Sie es später erneut."

Bei mir klappt weder das weiße Fenster noch das schwarze. Immer erscheint obiger Fehler

**Comment by JonasMock** [comment]
@Sylwuscha Ja. Jetzt wo die meisten Fehler behoben sind, erkennen die Betreiber natürlich jedes Mal den Bot. :(

**Comment by iamnotturner** [comment]
> "Die Code-Generierung war leider nicht erfolgreich:
> Vermittlungscode kann derzeit nicht angefragt werden. Versuchen Sie es später erneut."

> Bei mir klappt weder das weiße Fenster noch das schwarze. Immer erscheint obiger Fehler

@Sylwuscha dein Problem hat hier an dieser Stelle nichts zu suchen, hier geht es um etwas anderes. 

Ich habe dir schonmal gesagt, dass du bitte ein eigenes Issue aufmachen und nicht irgendwo dazwischen kommentieren sollst. Sonst geht die Ordnung verloren. Bitte das nächste mal dran denken.

**Comment by prinze2021** [comment]
![capture_001_16062021_195621](https://user-images.githubusercontent.com/84878386/122268974-014f4a80-cedd-11eb-9b17-8d3bec7019d4.jpg)

Guten Abend. Heute morgen ging es noch mit der 2.12 Version 2x einen VCode zu generieren und jetzt nicht mehr. Habe die Version 2.12 dann deinstalliert und die Version 2.13 installiert und nun bekomme ich auch diesen Hinweis angezeigt. Vielleicht greifen wieder zu viele drauf zu. Keine Ahnung. Bin ja ein Dummie. Also wieder warten :-)

**Comment by iamnotturner** [comment]
> Guten Abend. Heute morgen ging es noch mit der 2.12 Version 2x einen VCode zu generieren und jetzt nicht mehr. Habe die Version 2.12 dann deinstalliert und die Version 2.13 installiert und nun bekomme ich auch diesen Hinweis angezeigt. Vielleicht greifen wieder zu viele drauf zu. Keine Ahnung. Bin ja ein Dummie. Also wieder warten :-)

Hey, das gleiche gilt für dich, was ich auch schon zu Sylwuscha gesagt habe

> Sylwuscha dein Problem hat hier an dieser Stelle nichts zu suchen, hier geht es um etwas anderes.
> 
> Ich habe dir schonmal gesagt, dass du bitte ein eigenes Issue aufmachen und nicht irgendwo dazwischen kommentieren sollst. Sonst geht die Ordnung verloren. Bitte das nächste mal dran denken.

Bitte dafür ein eigenes Issue aufmachen, dann sprechen wir darüber

**Comment by Sylwuscha** [comment]
Verstehe ich nicht! Du hast oben aufgefordert, man soll die neue Version 2.13 testen. Das habe ich getan und direkt unter deinem Post dazu geantwortet. Sorry, dann bin ich zu blöd, denn für mich war es nur hier logisch. Vielleicht sollte ich lieber schweigen :-(

**Comment by sicherist** [comment]
> habe die Chrome-Options hinzugefügt, bitte mal probieren: https://github.com/iamnotturner/vaccipy/releases/tag/v1.2.13

Ja, danke, jetzt funktionierts. Es kam dann zwar "Die Code-Generierung war leider nicht erfolgreich:
Vermittlungscode kann derzeit nicht angefragt werden. Versuchen Sie es später erneut." Aber das ist ja ein anderes Thema ;)
