### ISSUE TITLE
'Vermittlungscode'  kann nicht gneriert werden

### ISSUE THREAD

**Issue by chimii1** [iamnotturner/vaccipy#488]
Hallo,

Lieder funktioniert (auch?) mit der neuen Version  v1.2.13 die Code-Generierung nicht. Es wird alles eingetippt geprüft und dann kommt folgende Fehlermelung:

"Die Code-Generierung war leider nicht erfolgreich:
Vermittlungscode kann derzeit nicht angefragt werden. Versuchen Sie es später erneut."

Bei der vorherigen Version ging es ab und zu noch aber dann musste man den SMS-Code manuell auf der website eingeben und hatte dafür auch nur 2-3 sekunden Zeit, bis sich dann die Seite wieder automatisch schließte. Auch das geht mittlerweile nicht mehr.
lG

**Comment by JonasMock** [comment]
@chimii1 Ja, die Betreiber der Webseite lernen auch dazu. Die Methode an sich funktioniert weiterhin. Nur wenn der Bot sie ausführt nicht, weil er als Bot erkannt und blockiert wird.

**Comment by chimii1** [comment]
@JonasMock Danke für deine Antwort.
Ich weiß, dass ich keinen SMS-Code eingeben kann, weil es eben nicht so weit kommt, dass eine SMS gesendet wird.
Aber so wie sich das anhört, scheint es bei dir zu funktionieren, daher die Frage woran das liegen kann, dass ich nicht mehr so weit komme, dass ich eine SMS bekomme bzw. ob ich da was tun kann?

**Comment by marnet0815** [comment]
Ist denn mit 1.2.13 nochmal was geändert worden? Im Grunde ging es ja heute schon mit 1.2.11 und 1.2.12 - allerdings morgens.

Kann es sein, dass es Abends schwieriger wird?

**Comment by ogzylmz80** [comment]
Bei mir hat es wieder nicht funktioniert. HAbe mir aber damit beholfen -> [LINK](https://github.com/alfonsrv/impf-botpy) <- zumindest habe ich jetzt die Vermittlungscodes und nutze aber weiterhin `vaccipy`

**Comment by iamnotturner** [comment]
> Ist denn mit 1.2.13 nochmal was geändert worden? Im Grunde ging es ja heute schon mit 1.2.11 und 1.2.12 - allerdings morgens.

Ein paar kleine Fixes, aber nichts wirklich an der Code-Generierung


> Btw. Mit 1.2.13 kann ich aktuell keine Termine mehr suchen. Ich habe wieder auf 1.2.12 "gedowngraded" (Nicht-GUI Version)

wieso nicht? welche Fehlermeldung erhält du?

**Comment by JonasMock** [comment]
@chimii1 Die Methode die der Bot anwendet funktioniert, wenn ich sie manuell unabhängig von Vaccipy im Browser durchführe. So war das gemeint.

@marnet0815 Die Methode hat sich nicht geändert nur die Darstellung im Browser wurde angepasst. Das was sich geändert hat, ist die Fähigkeit der Botprotection diesen Ansatz jetzt ebenfalls bei fast jedem Versuch zu erkennen.

Kann man bestimmt wieder irgendwie umgehen, das muss dann jemand anderes versuchen. Bin erstmal raus die nächsten Tage.

**Comment by marnet0815** [comment]
Ok, haltet mich jetzt für völlig blöd, nach dem Downgrade auf 1.2.12. und anschließendem Upgrade auf 1.2.13. läuft es wieder völlig normal. Habe sonst nichts angepasst und ich habe die Fehlermeldung leider zuvor nicht gespeichert. Wie gesagt, es läuft wieder, sorry... die Code Generierung geht Stand eben aber immer noch nicht.

**Comment by marnet0815** [comment]
> 
> 
> @chimii1 Die Methode die der Bot anwendet funktioniert, wenn ich sie manuell unabhängig von Vaccipy im Browser durchführe. So war das gemeint.
> 
> @marnet0815 Die Methode hat sich nicht geändert nur die Darstellung im Browser wurde angepasst. Das was sich geändert hat, ist die Fähigkeit der Botprotection diesen Ansatz jetzt ebenfalls bei fast jedem Versuch zu erkennen.
> 
> Kann man bestimmt wieder irgendwie umgehen, das muss dann jemand anderes versuchen. Bin erstmal raus die nächsten Tage.

Ahh, dann ist man da mittlerweile sehr schnell unterwegs.

**Comment by AllCanor** [comment]
Bei der Generierung eines Vermittlungscodes bekomme ich die Meldung `'NoneType' object is not subscriptable"`. Woran kann das liegen?

**Comment by Sylwuscha** [comment]
Nachdem ich es seit 1 Woche zu allen möglichen Tageszeiten nicht schaffe einen Vermittlungscode zu generieren, muss ich heute nachfragen, mit welchem Link es zur Zeit funktioniert. Ich habe die 11er, 12er, 13er und 14er Version durchprobiert - normal und die GUI-Version. Es will aber einfach nicht klappen. In den neueren Versionen mit der Simulation wie von Geisterhand erscheint nach wie vor die Fehlermeldung: 
"Die Code-Generierung war leider nicht erfolgreich: Vermittlungscode kann derzeit nicht angefragt werden. Versuchen Sie es später erneut."
Hängt die Codegenerierung mit der Verfügbarkeit zusammen? In dem Ort wo ich hauptsächlich suche, wurden nämlich seit ca. 1 Monat keine neuen Termine eingestellt!
(Die Terminbuchung dagegen klappt - manchmal automatisch und manchmal mit der manuellen Buchung)

Wer hat einen Tipp für mich?

**Comment by JonasMock** [comment]
@Sylwuscha Es wird an einem möglichen Fix gearbeitet. 

Du kannst keinen Vermittlungscode generieren, weil die aktuellen Versionen fast zu 100% von der Botprotection erkannt werden. Es liegt nicht an der Tageszeit oder dem Impfzentrum. Die Methode die der Bit verwendet funktioniert weiterhin. Wir müssen nur eine neue Möglichkeit finden wie sie automatisch durch den bot ausgeführt werden kann ohne erkannt zu werden.

 https://github.com/iamnotturner/vaccipy/pull/497 Hier wird an einer Lösung gearbeitet, die das Problem möglicherweise behebt.

**Comment by milagorecki** [comment]
Lässt sich diese Überprüfung auch manuell überspringen? 
Ich habe leider das gleiche Problem, dass ich keine Vermittlungscode generieren kann, da die Bot-Protection das spätestens beim zweiten Versuch blockiert. Habe mal einen Screenshot von der Fehlermeldung angehängt. 
<img width="1097" alt="Bildschirmfoto 2021-06-17 um 18 05 37" src="https://user-images.githubusercontent.com/28266295/122593451-fd026900-d065-11eb-97a1-504bbdfb94d5.png">

**Comment by JonasMock** [comment]
@milagorecki Ja, man kann die Methode die der Bot anwendet auch manuell ausführen. In Slack habe ich da beschrieben.

Btw. du scheinst nicht die aktuellste Version zu verwenden.

**Comment by milagorecki** [comment]
> Btw. du scheinst nicht die aktuellste Version zu verwenden.

Das wundert mich, ich direkt davor gestern den Source Code von Version 1.2.14 runtergeladen und lasse es (weil Mac) übers Terminal laufen.

**Comment by Gr33ndev** [comment]
Eben mit 1.3.1 getestet, da funktioniert es

**Comment by iamnotturner** [comment]
Wir haben eine neue Methode der Cookies-Generierung. Bitte mal die [BETA v1.3.1](https://github.com/iamnotturner/vaccipy/releases/tag/v1.3.1) testen und Rückmeldung geben :-)

**Comment by milagorecki** [comment]
Ja, sieht gut aus. Damit hat die Code-Generierung für mich jetzt problemlos funktioniert. Danke!

**Comment by fabianlandwehr1** [comment]
Das kann ich bestätigen. Bei uns hat es mit dem Update auch funktioniert. Vielen Dank!

**Comment by iamnotturner** [comment]
Hey, zur Info: neuer Release [BETA v1.3.2](https://github.com/iamnotturner/vaccipy/releases/tag/v1.3.2)
