### ISSUE TITLE
Geburtsdatum wird nicht gespeichert

### ISSUE THREAD

**Issue by sicherist** [iamnotturner/vaccipy#489]
v1.2.13
ubuntu, CLI

Bin mir nicht sicher, ob das ein Bg ist oder gewollt. Ich muss mein Geburtsdatum jedes mal neu eintippen, wenn ich einen Vermittlungscode generieren möchte, obwohl ich mit "y" bestätigt habe, dass die Daten aus 'kontaktdaten.json' geladen werden sollen.

**Comment by marcorombach** [comment]
Hey, das liegt daran, dass das Geburtsdatum in der kontaktdaten.json nicht enthalten ist.
