### ISSUE TITLE
Code generieren mit einer ausländischen Vorwahl

### ISSUE THREAD

**Issue by Norde** [iamnotturner/vaccipy#495]
Hallo,

zunächst einmal vielen Dank für dieses tolle Tool.

Es stellt sich heraus, dass es unmöglich ist, eine ausländische Nummer (mit einer anderen Vorwahl als +49) zu verwenden.
Ist dies eine Einschränkung von vaccipy oder von impfterminservice?

**Comment by iamnotturner** [comment]
Musste grad selbst nochmal nachschauen, aber die Einschränkung kommt vom Impfterminservice

![image](https://user-images.githubusercontent.com/38082956/122395963-cfd78d00-cf77-11eb-8320-61f72113167d.png)

**Comment by Norde** [comment]
Vielen Dank für Ihre schnelle Antwort.

Ich werde warten müssen, um eine deutsche Nummer zu bekommen, bevor ich einen Termin bekommen kann!
