### ISSUE TITLE
fehler v 1.3.1

### ISSUE THREAD

**Issue by Jar01** [iamnotturner/vaccipy#503]
Fehler:
expected str, bytes or os.PathLike object, not NoneType

**Comment by iamnotturner** [comment]
ups, das ist noch die Beta :-) danke für den Hinweis

**Comment by Jar01** [comment]
sehr gerne!  :-)

**Comment by 0llifreak** [comment]
Der Fehler kommt bei mir auch.
Hier der Auschnitt aus dem Debugger, falls das beim Fixen hilft ;-)

![grafik](https://user-images.githubusercontent.com/74310296/122669061-cfc7cf00-d1bb-11eb-9bb0-55eaa1554255.png)

**Comment by iamnotturner** [comment]
kommt der Fehler bei euch direkt oder erst nach dem Start von Terminsuche/Code-Generierung?

**Comment by iamnotturner** [comment]
habt ihr Google Chrome installiert? Wenn nein: könntet ihr mal testen, ob der Fehler behoben wird, wenn Chrome installiert ist?

**Comment by 0llifreak** [comment]
Der Fehler kam nach dem Start der Code-Generierung.
Die "richtige" Installation von Chrome hat bei mir den Fehler behoben. 
Das bedeutet dann aber, dass die lokale Installation über vaccipy (Option 3 im CLI) aktuell nicht funktioniert.

**Comment by andoorius** [comment]
> 
> 
> habt ihr Google Chrome installiert? Wenn nein: könntet ihr mal testen, ob der Fehler behoben wird, wenn Chrome installiert ist?

Hatte Chrome schon installiert - läuft wunderbar! 3 Codes sofort generiert.  [Windows 10, Console]

**Comment by iamnotturner** [comment]
@0llifreak und @Jar01 könntet ihr mal den PR #509 testen und prüfen, ob das bei euch den Fehler behebt? Man hat nun 3 Optionen, Chromium und Chromedriver zu verwenden. Option 1 und 2 habe ich erfolgreich getestet.

**Comment by Jar01** [comment]
@iamnotturner 
Umgebung: Windows 10 x64, Sandboxie, portable Python, vaccipy-local-chromium

Option 1:  keinen Fehler
Option 2:  Unbekannter TypeError:
'WindowsPath' object is not subscriptable

Exception ignored in: <function Chrome.__del__ at 0x000002162B6F0280>
Traceback (most recent call last):
  File "C:\Portable Python-3.9.4 x64\App\Python\lib\site-packages\undetected_chromedriver\v2.py", line 590, in __del__
    self.quit()
  File "C:\Portable Python-3.9.4 x64\App\Python\lib\site-packages\undetected_chromedriver\v2.py", line 573, in quit
    if not self.keep_user_data_dir or self.keep_user_data_dir is False:
AttributeError: 'Chrome' object has no attribute 'keep_user_data_dir'

der Fehler war nicht in vaccipy-master

Option 3: no test

**Comment by iamnotturner** [comment]
[BETA v1.3.2](https://github.com/iamnotturner/vaccipy/releases/tag/v1.3.2) behebt diesen Fehler, daher closed
