### ISSUE TITLE
Code Generierung / Chrome bestätigen ? V1.3.1

### ISSUE THREAD

**Issue by Martomeister** [iamnotturner/vaccipy#505]
Nachdem ich einen Code generieren möchte, gehen plötzlich drei verschiedene Fenster in Windows auf? Hat das möglicherweise mit der Cookies Generierung zutun? Bei den vorherigen Versionen hatte ich keinerlei Probleme?
![image](https://user-images.githubusercontent.com/85500462/122804714-8618da80-d2c8-11eb-89e9-d39ce7959163.png)

**Comment by pancakeDevelopment** [comment]
Durch diesen PR (https://github.com/iamnotturner/vaccipy/pull/497) wird der Chromedriver automatisch geladen und gepatcht. (Seit der Nutzung vom `undetected Chromedriver`)
Gut möglich, dass das dann der Download ist. Aber um ehrlich zu sein: Bei mir kam das nicht

**Comment by Martomeister** [comment]
Nachdem ich auf akzeptieren geklickt habe hat sich die Seite normal geöffnet. Code Generierung hat nun funktioniert 👍
