### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:43432 from chrome not reachable

### ISSUE THREAD

**Issue by RedStylzZ** [iamnotturner/vaccipy#506]
Die Code-Generierung auf Linux funktioniert mit der Version 1.3.1 wohl nicht, es kommt diese Fehlermeldung:
![image](https://user-images.githubusercontent.com/19490975/122807007-55867000-d2cb-11eb-979f-ba50e72b3566.png)

**Comment by iamnotturner** [comment]
Hey, theoretisch sollte er Chromium von selbst finden. Hast du Google Chrome installiert? Wenn nein, könntest du mal testen obs dann geht?

**Comment by RedStylzZ** [comment]
Auf dem Server ist chromium installiert, oder geht es nur mit Google Chrome direkt?

**Comment by iamnotturner** [comment]
hey, könntest dus nochmal mit [BETA v1.3.2](https://github.com/iamnotturner/vaccipy/releases/tag/v1.3.2) probieren?

**Comment by RedStylzZ** [comment]
Habe es jetzt sowohl mit der eigenen Google Chrome Instanz als auch mit der lokal installierten im vaccipy Ordner getestet, beides war nicht möglich. Habe es an meinem Windows PC getestet, dort muss jedoch der SMS-Code z.B. manuell eingegeben werden. Gibt es vielleicht ein Problem mit der Eingabe der Daten?

**Comment by iamnotturner** [comment]
Läuft dein Linux-Server mit einer Desktop-Umgebung? Wenn nicht wird's daran liegen, headless wird aktuell (soweit ich weiß) wegen der Cookie-Generierung nicht mehr unterstützt.

Den Code ins Browserfenster eingeben ist Absicht, das hatte auch was mit den Cookies zu tun.

**Comment by RedStylzZ** [comment]
Ach so okay, mein Server läuft nur über die Kommandozeile. Vielen Dank für die Hilfe :)
