### ISSUE TITLE
Frage: Muss das Geburtsdatum des Vermittlungscodes zur geimpften Person passen?

### ISSUE THREAD

**Issue by sicherist** [iamnotturner/vaccipy#510]
Ich habe für meine Frau einen Termin gebucht und bin mir aber nicht sicher, ob ich beim Generieren des Vermittlungscodes mein Geburtsdatum oder ihres eingegeben habe. Spielt das eine Rolle?

**Comment by sinun98** [comment]
Da spielt keine Rolle. Der Termin ist gültig.
