### ISSUE TITLE
Wichtiger Hinweis bzgl.  Bundesland

### ISSUE THREAD

**Issue by aschetelig** [iamnotturner/vaccipy#513]
Hallo, könnt Ihr bitte irgendwo in der Beschreibung deutlich die Info hinterlegen, dass man sich nur im eigenen Bundesland impfen lassen kann? Nach 10 Tagen Laufzeit des Rechners wurde jetzt endlich ein Termin gefunden, und er ist nicht nutzbar, weil Baden-Württemberg keine Menschen aus Hessen impft.

**Comment by iamnotturner** [comment]
Hey, ganz oben in der README steht

> Ebenso stellt ein Termin keine Berechtigung zur Impfung dar. Bitte die aktuellen Impfbestimmungen beachten.

**Comment by nagel86** [comment]
Kann ich so übrigens nicht bestätigen. Ich habe für zwei Personen (eine aus Hessen und eine aus Bayern) Termine in BW (Mannheim und Wolpertshausen) gebucht und beide wurden geimpft. In Mannheim haben sie nicht mal nachgefragt und in Wolpertshausen wurde die Person zwar darauf angesprochen, aber dann trotzdem geimpft.

Es ist wohl nicht angedacht, dass man sich in einem anderen Bundesland impfen lassen kann/soll, aber es ist auch nicht grundsätzlich "verboten".
