### ISSUE TITLE
Vaccipy generates Vermittlungscode for only one Impfzentrum group despite inputting several postal codes from differnet groups

### ISSUE THREAD

**Issue by AlyMoh** [iamnotturner/vaccipy#518]
### Premise
When generating a Vermittlungscode for more than one vaccination center (Impfzentrum) from different groups as per [this list](https://github.com/iamnotturner/vaccipy/wiki/Ein-Code-fuer-mehrere-Impfzentren), one is presented with the option of providing the postal codes (PLZs) of the desired vaccination centers. Upon entering the one-time code sent by SMS, I received a Vermittlungscode, presumably valid for all the groups I use.

### Problem description
However, when `vaccipy` attempts to use the Vermittlungscode, it turns out it's only valid for one group of the vaccination centers. In particular it seems to be that `vaccipy` only generates a Vermittlungscode for the group corresponding to the first input PLZ.

### Steps to reproduce (under Linux):
1. Run `vaccipy` in a shell
2. Choose option 1, i.e., generate a Vermittlungscode
3. Input several Impfzentren-PLZs; at least two where each corresponds to a different group.
4. Proceed with `vaccipy` until a Vermittlungscode is sent by E-Mail
5. Search for vaccination dates (option 1) and input the Vermittlungscode sent in step 4

`vaccipy` will now search in the previously input PLZs whether a vaccination slot is open (assuming the user reuses the information stored in `kontaktdaten.json`). However, because of the problem discussed previously, `vaccipy` will display a warning to the tune of "Kein gültiger Vermittlungscode vorhanden für PLZ XXXXX", where XXXXX corresponds to an Impfzentrum belonging to a group for which the Vermittlungscode generated in step 4 is not valid.

### Possible solutions:
I know that a Vermittlungscode is only valid for the group to which it was designated, but `vaccipy` does not make this clear either in the step-by-step instructions in the CLI version or the repository README. Perhaps either of the following can serve as a solution:

1. **Modify the prompt message to make it clear that PLZs to be input should belong to the same group.** This would be the approach for when vaccipy behaviour is correct, but the prompt message is ambiguous.
2. **Fix the problem associated with generating a Vermittlungscode for only one group despite inputting several PLZs from various groups.** This would be the approach if this indeed is the intended behaviour and this is just a bug.

For solution 2, rerunning the Vermittlungscode generation i.e. option 2 for each PLZ or PLZs belonging to the same group seems to me like the more straightforward approach, but I'm not knowledgeable of the code base and thus would leave it to someone more experienced to asses the feasibility of this solution.

### Similar issues
I've looked through the already existing issues but could not find any regarding this particular problem. If there exists one, however, I'd appreciate a link to the issue and marking this as a duplicate.

If any additional information, clarifications, or perhaps screenshots are needed, I'd be happy to submit any.

**Comment by JuliusJacobitz** [comment]
Hi @AlyMoh,
thank you for your submission! As far as I know, there is no need to use vaccipy at the moment. So to get your vaccination appointment, just use the default solution: [impterminservice.de](https://www.impfterminservice.de/impftermine)
