### ISSUE TITLE
Stürtzt ab nachdem es die Impfterminseite öffnet.

### ISSUE THREAD

**Issue by D-ctrl** [iamnotturner/vaccipy#519]
Das Programm wirft mir nach dem eingeben des Geburtstages und dem öffnen von Chrome folgende Fehler: 
Unable to locate element: {"method":"xpath","selector"://app-its-check-success//p"} 
(Session info: chrome=91.0.4469.0)

Fehler tritt auch mit anderen Versionen von Chrome, sowie der eigenen Chromium Instanz im Vaccipy Ordner auf.
Fehler ist auch auf Windows aufgetreten.

PS: 
Ich würde gerne Termine für ein paar Freunde buchen.
Habe das Programm benutzt um meine beiden Impftermine zu buchen. Danke fürs Entwickeln!

**Comment by iamnotturner** [comment]
Hey @D-ctrl, vaccipy wird seit Mitte Juni nicht mehr gewartet, weil es keine Notwendigkeit mehr gab. Eine lange Zeit waren durchgehend Termine verfügbar ohne Wartezeiten - wie ist die Lage aktuell, hat sich die Lage wieder geändert und ist es wieder schwer an Termine zu kommen? VG

**Comment by D-ctrl** [comment]
Okay alles klar. Ich wollte vaccipy benutzen um automatisiert Termine zu einem bestimmten Zeitpunkt zu buchen aber dann müssen sich meine Kollegen wohl selber darum kümmern. Keine große Sache. 
Danke für die Antwort!
Mit freundlichem Gruß
