### ISSUE TITLE
"Einloggen mit Code nicht möglich"

### ISSUE THREAD

**Issue by plorenz-etes** [iamnotturner/vaccipy#54]
Since a few hours I receive this error with every start of the script:

`2021-05-19 16:02:14.090   impfterminservice   [war] [*XXXX | XXXXX]   Einloggen mit Code nicht möglich`

The script however continues to run.
Will this affect whether a free appointment can be booked?

**Comment by iamnotturner** [comment]
No, since this is most-likely a temporary ban for your IP you can ignore it.
The login gets a few more informations about your code, but is not required.

You can pause your script for an hour or so and it will work again as usual.

**Comment by plorenz-etes** [comment]
Thank you for the clarification.
I have waited all night before running Vaccipy again, but unfortunately, it still gives me this message (on different servers, too).

**Comment by iamnotturner** [comment]
this issue is affecting a few more users now and we're working on a solution.
If you want to, you can pull our Improvements-Branch and execute it with Python (Windows-Exe is not updated yet).

let us know once you've tested.

#15

**Comment by n0ci** [comment]
Just pulled the improvement branch. Running it seems to work fine now.
For some reason installing cloudscraper didnt work properly, fixed it by removing the version in requirements.txt.

![image](https://user-images.githubusercontent.com/36604445/118947931-1d041700-b958-11eb-951b-ef170ec1f1f0.png)

tyvm!

**Comment by sinun98** [comment]
@moritzuehling which plz did you try?

**Comment by moritzuehling** [comment]
> @moritzuehling which plz did you try?

69123 (Heidelberg), to get a code for Group 2. I tried using the code manually, but not in the tool

**Comment by sinun98** [comment]
@aliahari  "Ungültiger Vermittlungscode" for code "AAAA-AAAA-AAAA" is expacted. Its a Dummy code to gen the cookies and solve akamai. 

Do you have any issues with requesting a code with the improvement branch?

**Comment by aliahari** [comment]
Good to know :) I was not able to get a code even with the improvement branch :(

**Comment by sinun98** [comment]
Can you provide the log?

**Comment by aliahari** [comment]
2021-05-20 13:08:56.599   impfterminservice   [inf] [*AAAA | 74360]   Browser-Cookies generieren
2021-05-20 13:09:02.312   impfterminservice   [inf] [*AAAA | 74360]   Browser-Cookie generiert: *4O4g==
2021-05-20 13:09:04.566   impfterminservice   [err] [{} ]   Code kann nicht angefragt werden

Maybe it is because of the mismatch between my chrome version and the driver?

**Comment by sinun98** [comment]
You still use the old version. Please Donwload https://github.com/iamnotturner/vaccipy/tree/improvements and execute with python. 
![image](https://user-images.githubusercontent.com/48892674/118969938-f5b84480-b96d-11eb-8360-319c0315aa72.png)

1. Python 3.9 installieren (https://www.python.org/downloads/release/python-395/)
2. pip installieren (https://phoenixnap.com/kb/install-pip-windows)
3. https://github.com/iamnotturner/vaccipy/tree/improvements => downloaden
4. in der Konsole in den Ordner navigieren
5. pip install -r requirements.txt => in der Konsole ausführen
6. python main.py => in der Konsole ausführen

 The Windows exe isnt updatet yet.

**Comment by igmuhlmann** [comment]
With the improvement-branch, the "get code" still does not work here; upon insertion of "AAAA-AAAA-AAAA" into the browser window, the "Ungültiger Code" appears, vaccipy then displays "Anfrage wurde geblockt". Tested for PLZ 88045 and 88212.
Maybe impfterminservice changed their code?

**Comment by plorenz-etes** [comment]
I just had the same issue: "Anfrage wurde geblockt".
Using another phone number and email address solved this issue for me.

**Comment by sinun98** [comment]
"Es ist ein unerwartet Fehler auftretreten" means your ip is banned. Wait a few minutes, change your ip or use a vpn. If you receive "Ungültiger Vermittlungscode" for code "AAAA-AAAA-AAAA" then your ip isnt banned and its a bot issue.

**Comment by igmuhlmann** [comment]
> 
> 
> I just had the same issue: "Anfrage wurde geblockt".
> Using another phone number and email address solved this issue for me.

Thanks, it now worked.
Let's head for the next step of finding a date... :)

**Comment by iamnotturner** [comment]
> I just had the same issue: "Anfrage wurde geblockt".
> 
> Using another phone number and email address solved this issue for me.

Important information, thanks for sharing!

In retrospect it is obvious that they might ban some phone numbers or mail adresses.

**Comment by webdev-pw** [comment]
Über das Tool kommt bei mir am Anfang bei der Termin-Suche auch immer "Einloggen mit Code nicht möglich" auf der WSL2 Ubuntu Maschine genau wie am Windows PC. Habe es bei Ubuntu auch schon mit dem improvement Branch probiert selbes Problem.
Funktioniert es dann trotzdem?
Das Script läuft ja dann einfach weiter und sucht nach freien Terminen.

**Comment by McLP2** [comment]
The improvements branch from this morning just got me an appointment successfully, just to let you know. Also generated a code for a friend w/o problems.

**Comment by fflai** [comment]
I'm gonna be vaccinated now, too. It's really relieving that (for me) this whole thing will be over soon. I wish the best of luck to everyone else in getting their appointment, so this can be over for everything.

I know you guys cannot help that more people get vaccinated (as all the vaccine is being used up either way), but you certainly helped me severely reduce my stress when trying to get one. 

The frustration I felt after calling the hotline 50+ times, and refreshing 100s of times was most certainly not good for my mental health.

I wish there were waitlists - with (for example) a random draw or something. The current system isn't particularly fair or good.

**Comment by iamnotturner** [comment]
Probleme sollten mit #69 behoben sein. Aktuellen Master pullen bzw. die EXE neu downloaden. 
Ich schließe das Issue und öffne es wieder, sollte das Problem wieder auftauchen.

**Comment by jhelgert** [comment]
Ich befürchte, dass auch das Problem weiterhin/wieder auftritt (der neuste master branch). Ich konnte es zumindest soeben mit unterschiedlichen IP Adressen, Vermittlungscodes und Impfzentren reproduzieren. Normales Einloggen über den Browser funktioniert dagegen. Gib bitte Bescheid, falls ich irgendwie durch weitere Tests oder Logfiles helfen kann! :)

**Comment by om-hb** [comment]
> 
> 
> Ich befürchte, dass auch das Problem weiterhin/wieder auftritt (der neuste master branch). Ich konnte es zumindest soeben mit unterschiedlichen IP Adressen, Vermittlungscodes und Impfzentren reproduzieren. Normales Einloggen über den Browser funktioniert dagegen. Gib bitte Bescheid, falls ich irgendwie durch weitere Tests oder Logfiles helfen kann! :)

Same problem here! 😬
