### ISSUE TITLE
Impf-Code Generierung

### ISSUE THREAD

**Issue by webdev-pw** [iamnotturner/vaccipy#55]
Hey,

erstmal vielen Dank für die Entwicklung des Tools!
Ist eine super Idee!

Ich habe gerade die Windows Version gestartet und wollte einen Impf-Code generieren allerdings kommt immer der Fehler "Code kann nicht angefragt werden".
Liegt das an mir oder haben die beim impfterminservice evtl. etwas geändert?

Gruß Philipp

**Comment by iamnotturner** [comment]
Hey, danke für das nette Feedback! 😄 
Ich habe es eben nochmal getestet und konnte einen Code generieren.

Was steht denn nach der Meldung "Code kann nicht angefragt werden" ? 
Und für welches Impfzentrum probierst du es?

**Comment by webdev-pw** [comment]
Hey, das ging ja schnell :)
Ich hab es mit 88212 und 88045 probiert,
Danach kommt nur "Die Code-Generierung war leider nicht erfolgreich. Der Prozess wird neugestartet."

**Comment by sinun98** [comment]
Hi, 
falls der Error folgend aussieht:
[err] [{} ]   Code kann nicht angefragt werden

 {}  bedeutet temporär gebannt. Dann einfach später nochmal probieren.

**Comment by iamnotturner** [comment]
Wie gibst du deine Daten denn ein? Achte drauf, dass keine Leerzeichen am Ende deiner Eingaben sind.

![image](https://user-images.githubusercontent.com/38082956/118846811-5e9bb000-b8cd-11eb-9a47-6b15c9ee8d8d.png)

**Comment by webdev-pw** [comment]
@sinun98 ja genau das ist der Fehler.
Okay hatte es gerade direkt beim ersten mal daher dacht ich nicht an einen Bann :D 

@iamnotturner Leerzeichen hat ich aufjedenfall nicht drin

**Comment by mrTag** [comment]
Ich hatte das gleiche problem, also hab ich mir in der log zeile einfach mal den http status_code der response mit ausgegeben: `self.log.error("Code kann nicht angefragt werden, resultcode: "+str(res.status_code), res.text)` und dabei kam der http code 429 raus ("Too Many Requests"). Scheint für mich so als ob die Impfzentren gerade überlastet sind (vielleicht wegen Feierabend?).

Vielleicht wäre es auch sinnvoll für den 429er eine gesonderte Fehlermeldung auszugeben? Bei dem termin_buchen gab es bei mir übrigens dann auch ein einfaches "Termin konnte nicht gebucht werden: {}" und mit zusätzlicher Ausgabe des status_code kam auch ein 429 rum...

**Comment by webdev-pw** [comment]
@iamnotturner 
gerade gesehen bei dir hat es mit 88212 funktioniert das ist echt komisch.
Ich geb die Daten eigentlich ganz normal ein E-Mail und Handynummer ohne 0 am Anfang. Hab es gerade noch mit einer anderen E-Mail probiert leider der selbe Fehler.

**Comment by 4kills** [comment]
Ich hatte den selben Fehler **auf Windows 10** mit **Python 3.9.5*. 
Als ich meine **Linux VM** (Ubuntu 20, **Python 3.8.5**, aber libraries auf 3.9) gebootet hab und es dort versucht habe, ging es allerdings **ohne Probleme.** Die public IP, Impfzentrum und sonstige Daten waren die selben. Auch nach Löschen der Cookies auf Windows-Chrome wurde der Fehler nicht behoben. Auf Windows habe ich es mit cmd und git bash probiert, Fehler bleibt. 

Ich hatte auch einen Kumpel bei dem der Fehler eben wie bei mir beschrieben, auch aufgetreten ist, wobei Linux das Problem auch gelöst hat.

**Comment by kscjuli2408** [comment]
Auch von mir vielen Dank für das Tool! :) 
Habe bei der Generierung des Impfcodes jedoch das gleiche Problem wie webdev-pw. Und hatte es auch direkt beim ersten mal, also unwahrscheinlich, dass es durch einen Bann dazu kam 

![grafik](https://user-images.githubusercontent.com/84475759/118881138-037cb400-b8f3-11eb-951d-74d35e5f9954.png)

**Comment by webdev-pw** [comment]
Ich hab hier ja noch mit WSL2 Ubuntu 20.04 und hab da ein GUI installiert, Chrome installiert und versucht das Script auszuführen und gehofft das es dann funktioniert.
Leider das selbe Problem.

@4kills Du hast eine komplett eigene VM dafür aufgesetzt oder?

**Comment by 4kills** [comment]
> Ich hatte den selben Fehler **auf Windows 10** mit **Python 3.9.5**.
> Als ich meine **Linux VM** (Ubuntu 20, **Python 3.8.5**, aber libraries auf 3.9) gebootet hab und es dort versucht habe, ging es allerdings **ohne Probleme.** Die public IP, Impfzentrum und sonstige Daten waren die selben. Auch nach Löschen der Cookies auf Windows-Chrome wurde der Fehler nicht behoben. Auf Windows habe ich es mit cmd und git bash probiert, Fehler bleibt.
> 
> Ich hatte auch einen Kumpel bei dem der Fehler eben wie bei mir beschrieben, auch aufgetreten ist, wobei Linux das Problem auch gelöst hat.

Ich hab es jetzt noch einmal mit Python 3.8.5 auf Windows getestet (der Version mit der es auf Ubuntu funktioniert), aber nach wie vor scheint es auf Windows nicht zu funktionieren.

**Comment by 4kills** [comment]
@webdev-pw Jap, [ VM Ware Workstation Player ](https://www.vmware.com/products/workstation-player/workstation-player-evaluation.html) mit [Ubunutu Deskop](https://ubuntu.com/download/desktop/thank-you?version=20.04.2.0&architecture=amd64) frisch installiert, dann auf Ubuntu git installiert, python 3.8.5 (per apt) installiert, mit pip die python module installiert, dann Chrome graphisch installiert ([siehe hier](https://itsfoss.com/install-chrome-ubuntu/#install-chrome-gui)). Schließlich noch einmal impfterminservice.de manuell geöffnet, cookies akzeptiert, chrome geschlossen, dann main.py ausgeführt und es hat wiederholt funktioniert (hab auch ein paar Codes für Freunde generiert).

**Comment by sinun98** [comment]
Hatte ab ca. 15 Uhr das selbe Problem auf Mac und Windows. Response 429 ist grundsätzlich das die Anfrage von Akamai geblockt wurde. 

Seit gerade geht es bei Windows wieder. Auf meinem Mac bekomme ich immer noch 429.

**Comment by JeffJeffrey12** [comment]
[https://gyazo.com/85d3701c8444574c4ddc65c337d5c08d](url)

Vielen Dank erstmal für dieses Tool.
Ich hab lediglich das Problem, dass sich öfter diese Seite öffnet und dann das Tool nicht weiterläuft, außer ich schließe das Fenster immer wieder manuell.

Gibt es hierfür nen Workaround?

**Comment by iamnotturner** [comment]
Schnelle Workarounds:
- ein anderes Impfzentrum [aus der jeweiligen Gruppe](https://github.com/iamnotturner/vaccipy/wiki/Ein-Code-fuer-mehrere-Impfzentren) (Gruppe 1) wählen und dafür den Code generieren
- einfach kurz warten, bis die Warteschlange durch ist (das dauert meist weniger als 5 Minuten)

**Comment by kscjuli2408** [comment]
noch ein kleiner Nachtrag:

habe es gerade einfach mal für 21075 Hamburg (Nur Personen 70+) probiert, wo man auch so locker über die Webseite einen Code generieren kann. Hier läuft es ohne Probleme. Bei den anderen Impfzentren jedoch immer noch erfolglos.

**Comment by sinun98** [comment]
@kscjuli2408 hast du es nachdem es in Hamburg ging nochmal versucht in einem anderen Zentrum? 
Ich habe aktuell 2 Szenarien:
1. Windows geht bei allen Zentren.
2. Mac geht bei keinen Zentren, auch nicht Hamburg.

**Comment by webdev-pw** [comment]
Ich hab es jetzt gerade am Laptop per Mobilem Hotspot versucht und es hat tatsächlich einmal funktioniert und ich habe per SMS die PIN bekommen allerdings ist dann die Verifikation der PIN fehlgeschlagen^^

**Comment by kscjuli2408** [comment]
@sinun98 ja habe es direkt davor und danach bei anderen Impfzentren versucht (über Windows), jedoch immer erfolglos. Fehlermeldung siehe Screenshot oben.

**Comment by 4kills** [comment]
@webdev-pw Laptop mit Windows 10 ?

**Comment by webdev-pw** [comment]
@4kills ja genau

**Comment by webdev-pw** [comment]
Okay liegt wohl echt an der Überlastung, jetzt ging es zweimal an meinem Win10 PC ohne Probleme ;-)

**Comment by kscjuli2408** [comment]
@webdev-pw kann ich bestätigen! :)

**Comment by sinun98** [comment]
#54 ist ein fix beschrieben.

**Comment by meikehagemann** [comment]
Hallo, bei bei mir erscheint leider auch ständig eine Fehlermeldung. Wisst ihr an was es liegen könnte?... 
![image](https://user-images.githubusercontent.com/84515375/118992390-e395d080-b984-11eb-97b4-a90d698d8ca8.png)

**Comment by sinun98** [comment]
@meikehagemann hast du Google Chrome installiert?

**Comment by meikehagemann** [comment]
@sinun98 nein habe ich nicht... mache ich mal :) danke! :D

**Comment by meikehagemann** [comment]
@sinun98 es funktioniert! vielen Dank!!

**Comment by Naeaeaeaeae** [comment]
Bei mir ging es bei Karlsruhe  76137 nicht. Ebenso Rheinstetten.

**Comment by BlackScreen** [comment]
Ich hatte es schon in #59 erwähnt, aber ich habe es gerade nochmal verifiziert:
Wenn man mit frischen Daten, ohne aktiven Warteraum versucht, kriegt man den Vermittlungscode direkt.
Es scheint echt so zu sein, dass man direkt geblockt wird, wenn man es einmal versucht, wenn der Warteraum aktiv ist.

**Comment by meikehagemann** [comment]
![image](https://user-images.githubusercontent.com/84515375/119029275-b9560a00-b9a8-11eb-9f4e-01d037ea682c.png)
Was hat das denn für eine Bedeutung?...

**Comment by sinun98** [comment]
Aktuell sind Wartungsarbeiten beim Impfterminservice.

**Comment by iamnotturner** [comment]
kleines Update: wir haben nun einen BETA-Branch, in den Änderungen schon vorzeitig zum testen gepusht werden. Das Backup zur Terminbuchung mit Selenium und Verbesserung der Codegenerierung sind drin, die EXE ist auch geupdated (Hinweis: für die BETA-EXE muss der `dist/`-Ordner manuell heruntergeladen werden).
**Eine stabile Version befindet sich stets im Master, BETA kann auch mal crashen!**

https://github.com/iamnotturner/vaccipy/tree/beta

**Comment by webdev-pw** [comment]
@iamnotturner 
Hab die Beta gerade runtergeladen und die .exe getestet.
Wenn ich die bei der Terminsuche die Daten eingebe crasht er direkt nach der E-Mail eingabe (also sobald alles eingegeben wurde)

**Comment by iamnotturner** [comment]
@webdev-pw auch die Terminsuche?

**Comment by webdev-pw** [comment]
@iamnotturner 
ja ich starte die .exe geh auf 1 für Terminsuche gebe alle Daten ein und am Ende crasht es direkt

**Comment by iamnotturner** [comment]
ach mist, meinte Code-Generierung

**Comment by BrotFisch** [comment]
Hey,

bekomme auch den Fehler "[err] [{} ]   Code kann nicht angefragt werden"

Habe das Chrome-Fester beobachtet. Es gibt einen Fehler "Ungültiger Vermittlungscode".

![screenshot](https://user-images.githubusercontent.com/84567895/119114823-c9acca00-ba26-11eb-882e-2d25f2c8e835.jpg)

Mache ich etwas falsch?

**Comment by JuliusJacobitz** [comment]
> Hi,
> falls der Error folgend aussieht:
> [err] [{} ] Code kann nicht angefragt werden
> 
> {} bedeutet temporär gebannt. Dann einfach später nochmal probieren.

@BrotFisch Wir haben grade auf dem Master ein update gepushed mit es besser funktionieren könnte. Gerne testen :)

**Comment by JuliusJacobitz** [comment]
> @iamnotturner
> Hab die Beta gerade runtergeladen und die .exe getestet.
> Wenn ich bei der Terminsuche die Daten eingebe crasht er direkt nach der E-Mail eingabe (also sobald alles eingegeben wurde)

@iamnotturner  @webdev-pw fixed with: #69

**Comment by webdev-pw** [comment]
@JuliusJacobitz 
super hab es gerade getestet und es funktioniert
"Erfolgreich mit Code eingeloggt" ;-)

**Comment by riecke99** [comment]
![image](https://user-images.githubusercontent.com/85612858/121322867-a1bad300-c90f-11eb-97aa-4542fa6b04f0.png)

Hallo Miteinander,

kann mir jemand bei meinem Fehler weiterhelfen? Dieser tritt auf bei der Funktion: "Code generieren".

Danke. ;)
