### ISSUE TITLE
non GUI Linux environment (chrome is no longer running)

### ISSUE THREAD

**Issue by fluffyfirefly** [iamnotturner/vaccipy#56]
I'm trying to run vaccipy on Ubuntu server 20.04 without desktop environment. 
Due to #44 chromedriver is set to    `chromedriver = os.path.join(PATH, "/snap/bin/chromium.chromedriver")`
But I still get the following error: 
```
(unknown error: DevToolsActivePort file doesn't exist)
(The process started from chrome location /snap/chromium/1589/usr/lib/chromium-browser/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```
![image](https://user-images.githubusercontent.com/69301522/118877798-260cce00-b8ef-11eb-8186-62410c9c3e50.png)

I'm currently avoiding this issue by installing Ubuntu desktop via tasksel and starting it in a GUI seassion. Is it possible to somehow run it without a desktop environment via ssh session?

**Comment by iamnotturner** [comment]
unfortunately it is not possible to run it without a desktop yet.
this depends on the cookie creation, which does not support headless selenium

**Comment by fluffyfirefly** [comment]
Alright, I guessed as much but figured it couldn't hurt to ask.
Thank you very much for the quick reply and this very helpful application.
