### ISSUE TITLE
Terminbuchung von Hand ging, während bot nix gefunden hat.

### ISSUE THREAD

**Issue by MatzeDevloft** [iamnotturner/vaccipy#57]
Servus, erstmal richtig cooles Projekt !
Ich bin heute aber von Hand an meinen Termin gekommen während der Bot lief.
Bissel ausführlicher:
Ich hab versucht über den Bot an einen Impftermin zu kommen. Der Bot lief fast 12 Stunden rund, aber ohne Ergebnis.
Auch der Impfradar hat keine Termine angezeigt, daher hab ich mir keine Gedanken gemacht. Ich habs dann aber doch mal von Hand probiert, habt direkt einen neuen Code und auch sofort einen Termin bekommen während der Bot mit meinem alten Code noch fröhlich vor sich her suchte.
Zwei Möglichkeiten:
Entweder ich hatte extremes Glück, oder der Bot tut nicht das was er soll, bzw sie haben irgendeine Möglichkeit um Bots zu blacklisten oder irgendwas in der Art.
Ich wollte euch das mal als Feedback geben und vielleicht haben andere sowas ähnliches erlebt.

**Comment by iamnotturner** [comment]
Hi Matze, danke für dein Feedback!

Die Erfahrung habe ich auch schon gemacht. Heute ähnlich: habe zwei Instanzen auf die selben Impfzentren laufen lassen und trotz gleichzeitiger Abfrage hat nur eine Instanz einen Termin bekommen.

Ich nehme an, dass das an dem Reservierungssystem liegt und die Impftermine zufällig unter allen Anfragen verteilt werden. So oder so ähnlich muss es ja laufen, damit es fair bleibt. Man bekommt einen Termin vorgeschlagen und bucht ihn, oder er wird an den nächsten weitergereicht.

Mir ist auch schon aufgefallen, dass ich schon öfters direkt nach der Cookie-Generierung einen Termin bekommen habe. Vielleicht sollte man die öfters aktualisieren für bessere Chancen.

Ich bin gespannt, was andere erzählen.

**Comment by Floskinner** [comment]
Hey zusammen,

erstmal echt cooler Bot!

Ich habe so ein ähnlichen Bot wie euren Programmiert, mit dem unterschied, dass die Suche komplett über Selenium / Chrome funktioniert (und der Termin nicht automatisch gebucht wird). 
Es wird bei jeder Anfrage ein neues Chrome Fenster mit neuen Cookies erzeugt und letztens hat es bei mir auch 3 Tage gedauert bis ein Termin gefunden worden ist. Wobei andere gleichzeitig manuell einen Termin auf das gleichen Impfzentrum gesucht und bekommen haben.

Glaube daher nicht, dass es an der Cookie-Generierung liegt bzw. das öftere Cookie-Generierung helfen könnte :/

**Comment by iamnotturner** [comment]
Hey Flo, danke für die Rückmeldung. Deine Erfahrung spricht auch für die Verteilung seitens Impfterminservice, die wahrscheinlich zufällig passiert. Um etwas aufzuräumen schließe den Thread mal, für weiteres Feedback gerne #1 nutzen oder ein neues Issue aufmachen.
