### ISSUE TITLE
Vermittlungscode von Rottweil funktioniert nicht in Sinsheim

### ISSUE THREAD

**Issue by robert-scheck** [iamnotturner/vaccipy#58]
Im Gegensatz zu https://github.com/iamnotturner/vaccipy/blob/master/impfzentren_gruppiert.md funktioniert jedoch faktisch ein Vermittlungscode von [Rottweil](https://001-iz.impfterminservice.de/impftermine/service?plz=78628) (PLZ: 78628) leider nicht in [Sinsheim](https://001-iz.impfterminservice.de/impftermine/service?plz=74889) (PLZ: 74889). Fehlermeldung auf impfterminservice.de dazu lautet "Es ist ein unerwarteter Fehler aufgetreten". Die Problematik ist für mich mit verschiedenen Vermittlungscodes (alle 0-10 Tage alt) seit Tagen durchweg reproduzierbar.

Lustig: Der Vermittlungscode aus Sinsheim funktioniert in Rottweil.

**Comment by iamnotturner** [comment]
Das ist schräg, aber liegt nicht in unserer Hand - leider.
Allgemein sollte die Regel weiterhin gelten, dass ein Code für alle Impfzentren der Gruppe verwendet werden kann.

**Comment by robert-scheck** [comment]
Das ist mir bewusst, aber es wäre zumindest für Benutzer vermutlich hilfreich, wenn die Dokumentation diesbezüglich vielleicht um einen Hinweis erweitert werden könnte (zumal es übrigens mehr als diese eine Problemkonstellation gibt).

**Comment by iamnotturner** [comment]
👍 [da hast du recht, habe hier einen Hinweis hinterlassen.](https://github.com/iamnotturner/vaccipy/wiki/Ein-Code-fuer-mehrere-Impfzentren)
