### ISSUE TITLE
Kontaktdaten zu Beginn abfragen und dann für Code-Generierung oder Termin-Buchung nutzen

### ISSUE THREAD

**Issue by BlackScreen** [iamnotturner/vaccipy#59]
Hallo zusammen,
ich habe noch eine kleine Verbesserung:
Aktuell ist es ja so, dass man bei der Code-Generierung die Kontaktdaten immer wieder eingeben muss.
Das könnte man doch etwas komfortabler gestalten, denke ich.
Vielleicht sollte man direkt zu Beginn die Kontaktdaten abfragen - wie bei der Termin-Buchung - und diese dann auch für die Code-Generierung nutzen?
Das wäre wirklich sehr hilfreich. Aktuell muss man so für die Code-Generierung die Daten ständig neu eingeben. :/

**Comment by iamnotturner** [comment]
Hi, da die Anzahl der Codes, die eine Person benötigt, eigentlich recht überschaubar ist, haben wir von einer Speicherung der Daten abgesehen. Selbst wenn man aufgrund der Gruppierung der Impfzentren mal mehr als einen Code benötigt, ist der Aufwand jetzt nicht riesig - oder?

**Comment by BlackScreen** [comment]
Da würde ich dir prinzipiell Recht geben, leider kommt aktuell immer dieser Fehler, weshalb das Tool dann wieder von vorne beginnt...
`2021-05-20 11:42:58.440   impfterminservice   [err] [{} ]   Code kann nicht angefragt werden`

**Comment by iamnotturner** [comment]
Ach klar, I see - passen wir im Laufe des Tages an.

**Comment by BlackScreen** [comment]
> Ach klar, I see - passen wir im Laufe des Tages an.

Sehr cool, vielen Dank!

**Comment by moritzuehling** [comment]
Ich hatte den gleichen fehler - auf der `improvements` branch klappt das code holen aber zuverlässig.

**Comment by BlackScreen** [comment]
> Ich hatte den gleichen fehler - auf der `improvements` branch klappt das code holen aber zuverlässig.

Ja, bin bisher noch unfähig das Tool ohne die EXE laufen zu kriegen. Bin für eine kurze Anleitung dankbar, dann probier ich es auch damit. :D

**Comment by sinun98** [comment]
1. Python 3.9 installieren
2. pip installieren (https://phoenixnap.com/kb/install-pip-windows)
3. https://github.com/iamnotturner/vaccipy/tree/improvements  => downloaden 
4. in der Konsole in den Ordner navigieren
5. pip install -r requirements.txt    => in der Konsole ausführen
6. python main.py    => in der Konsole ausführen 

Sollte das nicht klappen aufs Update warten :)

**Comment by sinun98** [comment]
Das ist auf jeden Fall die richtige Version. Hast du es mal mit einer anderen Email und Telefonnummer versucht.

**Comment by BlackScreen** [comment]
> Das ist auf jeden Fall die richtige Version. Hast du es mal mit einer anderen Email und Telefonnummer versucht.

Habe ich noch nicht. Aber blocken die ernsthaft Mail-Adressen und Telefonnummern permanent? Wie beschissen ist das denn bitte?! Wissen wir das sicher oder ist das nur eine Vermutung?

**Comment by sinun98** [comment]
Ist keine Vermutung. Ist aber auch nur temporär nach spätestens 24 Stunden sollte es wieder gehen.

**Comment by BlackScreen** [comment]
> Ist keine Vermutung. Ist aber auch nur temporär nach spätestens 24 Stunden sollte es wieder gehen.

Ok, verstehe. Aber ab wann (also wie viele Versuche, Anfragen, wie auch immer) da geblockt wird weiß man nicht oder?

**Comment by sinun98** [comment]
Aus Erfahrung ca. zwischen 2-3

**Comment by BlackScreen** [comment]
> Aus Erfahrung ca. zwischen 2-3

Beim gleichen Impfzentrum innerhalb von x Minuten?

**Comment by sinun98** [comment]
Auch wenn man innerhalb einer halben Stunde 2-3 anfragt ist danach meistens Schluss. Der temporäre Block gilt nicht nur für das gleichen Impfzentrum sondern für die gesamte Gruppe. Siehe dazu: https://github.com/iamnotturner/vaccipy/blob/master/impfzentren_gruppiert.md

**Comment by BlackScreen** [comment]
Du hast Recht. Ich hatte es teilweise auch versucht, wenn der Warteraum aktiv war. Einmal, mit neuer IP und neuen Daten - direkt geblockt.
Dann mit neuen Daten, neuer IP versucht ohne Warteraum - direkt den Code gekriegt.
