### ISSUE TITLE
Virusmeldung unter Windows

### ISSUE THREAD

**Issue by StealthyGherkin** [iamnotturner/vaccipy#61]
Ich habe das Programm über die Schaltfläche "Download for WIndows" heruntergeladen, es wird mir jedoch als "Trojan:Win32/Wacatac.B!ml" angezeigt, jedoch nur auf meinem Surface Tablet, auf meinem normalen Rechner erscheint diese Meldung nicht.

**Comment by iamnotturner** [comment]
#33 dazu gibts schon ein Issue. In diesem Thread werden wir auch Updates posten.

Wir wissen davon, können aber aktuell nichts dagegen tun. **Grundsätzlich ist richtig und wichtig, dass Windows vor der Ausführung von unbekannten Programmen warnt.** 

Es ist definitiv kein Virus drin - um sicher zu gehen kannst du dir den Quellcode anschauen und auch direkt ausführen mit Python.
