### ISSUE TITLE
Vermittlungscode/SMS-Code funktionieren nicht

### ISSUE THREAD

**Issue by aesz13** [iamnotturner/vaccipy#70]
Hallo, 
erstmal vielen Dank und Respekt für die Entwicklung dieses Tools, die Idee ist wirklich super! Ich versuche es nun schon seit drei Tagen und konnte noch immer keinen Termin ergattern. Ich habe hier schon einige der Probleme von anderen verfolgt und bei mir klappt es trotz dem letzten Update nicht. Ich schaffe es nicht, mir einen Vermittlungscode zu generieren. Gestern hat es nicht funktioniert, weil ich den gleichen Fehler bekommen habe, den hier viele hatten, heute funktioniert die SMS-Verfikation nicht. Eine Anfrage mit jeder meiner E-Mails und meiner Telefonnummer wird nun geblockt, mit der E-Mail und der Telefonnummer einer anderen Person hat es dann funktioniert und sie hat einen SMS-Code erhalten, aber die Eingabe hat den SMS-Code letztlich nicht angenommen. Nun sind neben meinen Daten auch die Daten der anderen Person geblockt und langsam gehen mir die Daten aus. 
Wenn das hilft: Ich suche in Hamburg und dort gibt es nur ein Impfzentrum, das auch unter 70jährige impft.

Ich weiß nicht genau, wo das Problem liegt, aber ich versuche es erst einmal weiter.

**Comment by JuliusJacobitz** [comment]
Hi @aesz13. Hab ich dich richtig verstanden, dass du mit den aktuellen builds von heute arbeitest ?

**Comment by aesz13** [comment]
Hi, genau habe den kompletten Master vor ein paar Stunden noch einmal heruntergeladen.

**Comment by bonxz** [comment]
Kann man dich irgendwo kontaktieren?

**Comment by JuliusJacobitz** [comment]
@bonxz wer ist gemeint :D

**Comment by vesperbrot** [comment]
Habe ein ähnliches Problem: "Anfrage wurde geblockt. Bitte später erneut versuchen" 

Habe das jetzt seit einigen Stunden.

**Comment by aesz13** [comment]
Ich bin auf Discord erreichbar: eszett#7064 Mittlerweile habe ich einen Termin bei einem anderen Impfzentrum, allerdings über den Browser.

**Comment by wolfmarcel** [comment]
Wie habt ihr das Problem "Anfrage wurde geblockt. Bitte später erneut versuchen" gelöst ?

**Comment by sinun98** [comment]
Potenzieller Fix im Branch sms-code-fix https://github.com/iamnotturner/vaccipy/tree/sms-code-fix

Anleitung für die manuelle Cookie Eingabe:  

1. Skript läuft in Botprotecion Fehler:
![image](https://user-images.githubusercontent.com/48892674/119194323-30f86780-ba83-11eb-8c9f-3ba709036752.png)
2.  Impterminservice im Browser (Chrome) öffnen beispielsweise: https://www.impfterminservice.de/impftermine 
3. Chrome Entwickler-Konsole öffnen über F12 
4. In den Tab Network gehen und Seite neu laden, sodass Requests zu sehen sind:
![image](https://user-images.githubusercontent.com/48892674/119194687-c09e1600-ba83-11eb-88d6-a7c440de8bdd.png)
5. Erster Request auswählen und unter Request Headers den Wert Cookie kopieren. (Ohne "Cookie:" lediglich den Wert nach ":")
![image](https://user-images.githubusercontent.com/48892674/119194979-2e4a4200-ba84-11eb-8391-bfa52aaa74d6.png)
6. Wert in die Konsole kopieren und mit Enter bestätigen
![image](https://user-images.githubusercontent.com/48892674/119195129-6c476600-ba84-11eb-9c03-21cd6b8d06a7.png)

ACHTUNG!!!
Cookies sind nur valide wenn der Impfterminservice mindestens eine halbe Stunde oder länger im Browser geöffnet ist und ein normales Verhalten (Klicks, Seitenaufrufe, Eingaben) ausgeführt wurde. Nachdem Cookies gelöscht wurden oder wenn der Impfterminservice das erste Mal im Browser geöffnet wird muss abgewartet werden bis die Cookies valide sind und im Skript funktionieren:

![image](https://user-images.githubusercontent.com/48892674/119195883-9ea59300-ba85-11eb-982d-e00eb55de313.png)

**Comment by ProLoDs** [comment]
@sinun98 Danke! das hat für mich funktioniert!

**Comment by sinun98** [comment]
@ProLoDs Mit welcher PLZ hast du es versucht? Bei mir funktioniert es Problemlos.

**Comment by ProLoDs** [comment]
@sinun98 Ja der Gedanke hatte ich auch schon. Ich hab es allerdings richtig eingegeben und doppelt geprüft. ich habe es mit 77656 versucht.

**Comment by sinun98** [comment]
@ProLoDs Habe es aktuell getestet und funktioniert bei mir. Die SMS kommt unmittelbar. Hast du es schon mit einer anderen Email/ Nummer getestet?

**Comment by ProLoDs** [comment]
@sinun98 Ich habe eine andere Telefonnummer versucht, damit hat es sofort funktioniert. Vll war meine gebannt. Danke hat funktioniert, jetzt auf der suche nach einem Termin. Danke!

**Comment by arneg82** [comment]
also bei mir ist es egal bei welchem zentrum oder mail oder rufnummer, alle anfragen werden geblockt.
lustigerweise konnte ich direkt gestern auf der website mal nen schritt weiter kommen, aber selbst die haben es nicht geschafft die daten an die mailadresse zu schicken..

**Comment by colfes** [comment]
Soweit ich weiß kann man pro Handynummer nur 5 SMS-Codes generieren. Vielleicht lag es daran - bei mir ging es nach 5 Codes auch nicht, mit einer anderen Handynummer dann aber schon wieder.

**Comment by devsbr** [comment]
> Soweit ich weiß kann man pro Handynummer nur 5 SMS-Codes generieren. Vielleicht lag es daran - bei mir ging es nach 5 Codes auch nicht, mit einer anderen Handynummer dann aber schon wieder.

Das kann nicht stimmen. Habe über meine Telefonnummer und E-Mail Adresse über 20 Codes erstellt :)

**Comment by Sars-Cov-2-Antigen** [comment]
Für mich funktioniert das nicht. Nicht wegen der Handynummer, sondern weil ich wohl keinen validen Cookie erzeugen kann. Die Bot-Protection verhindert die Abfrage.

**Comment by sinun98** [comment]
@arneg82 Ich kann nur mal empfehlen, es in Impfzentren manuell zu probieren einen Code anzufordern. Bei den Impfzentren in Hamburg, die Ü70 Termine vergeben, ist dies oftmals möglich.

**Comment by arneg82** [comment]
hab das nun mal mit der beta probiert und siehe da da funktioniert es, code erstellen lassen, sms nachricht etc.. nun lass ich mal die terminsuche laufen

**Comment by Floskinner** [comment]
Bei mir das gleiche, Beta hat geholfen 👍 
Zentrum: Hamburg 20259

> hab das nun mal mit der beta probiert und siehe da da funktioniert es, code erstellen lassen, sms nachricht etc.. nun lass ich mal die terminsuche laufen

**Comment by Sars-Cov-2-Antigen** [comment]
Kann ich inzwischen bestätigen. Habe es mit der Beta versucht und es hat sofort funktioniert.
