### ISSUE TITLE
Abfragefehler

### ISSUE THREAD

**Issue by arneg82** [iamnotturner/vaccipy#72]
Hi

hab grad das Tool geladen (neueste Version) und aktuell rumgetestet mit mehren Zentren. 
Bei alle erscheint dieser Fehler? Was fehlt da evtl. auf meinem Rechner oder generell ein Fehler?

Das ganze kommt im endeffekt nach der Abfrage zu Code generieren bzw. Suche halt und entsprechend wenn die Daten eingetragen sind und die Abfrage startet. (Egal ob Zentren mit Warteraum oder ohne)
![1](https://user-images.githubusercontent.com/39674305/119145052-8e6fc280-ba49-11eb-99ec-3df8f0d00119.PNG)

**Comment by iamnotturner** [comment]
Hi, hast du Chrome installiert?

**Comment by arneg82** [comment]
den hab ich grad schnell noch installiert, damit ging es zumindest bis zum nächsten Hop (Anfrage wurde blockiert) aber das fenster ging grad auf etc.. 
nutze sonst edge chromium..

**Comment by iamnotturner** [comment]
Okay - es bestehen grad wieder Probleme bei der Cookie-Generierung. Die beheben sich entweder von selbst oder wir finden eine andere Lösung. Halten dich auf dem Laufenden.

**Comment by Koecherli** [comment]
Habe den gleichen Fehler
![image](https://user-images.githubusercontent.com/84581773/119154762-c4657480-ba52-11eb-9e0e-40a8fe74e8c6.png)

**Comment by Fijo** [comment]
Dito - Will nur einen Code generieren. Habe um das ganze nachzuvollziehen den Prozess aufgenommen und die Fehlermeldung, die im Browser erscheint erwischt. Nicht sicher warum der überhaupt versucht einen Termin zu suchen, wenn ich doch nur Code generieren gewählt habe.
https://puu.sh/HIxii/d1e6221d62.png

**Comment by iamnotturner** [comment]
@Fijo das Verhalten ist gewünscht - er gibt einen fiktiven Code ein, um (eigentlich) einen validen Cookie zu generieren. Kann ignoriert werden.

**Comment by Fijo** [comment]
Passt. War nur ein versuch der Fehlermeldung, dass die Abfrage geblockt wird auf den Grund zu gehen.
Ich war gestern auf der Seite und sie war eine Weile down. Ich denke die haben evtl. ein Update eingespielt, was erklären könnte, warum der Workflow gerade nicht mehr funktioniert.

**Comment by Koecherli** [comment]
Bei mir hat sich das Problem von selbst behoben, funktioniert alles.
Top Programm habt ihr da geschrieben!!

**Comment by sinun98** [comment]
Potenzieller Fix in #70 beschrieben.
