### ISSUE TITLE
New Feature: Datum eingrenzen bei der Terminwahl - Unittests verfügbar?

### ISSUE THREAD

**Issue by Floskinner** [iamnotturner/vaccipy#74]
Hey zusammen,

ich bin gerade dabei dem User die Möglichkeit zu bieten, dass er die Termine welche er buchen möchte, auf Wochentage und einem Zeitraum begrenzen kann.
Leider tu ich mir mit dem Testen etwas schwer. Daher hätte ich die Frage, wie ihr das Programm testet. Speziell die `termin_suchen()`, da ich aktuell dort die Abfrage eingebaut habe, ob ein Termin in dem angegebenen Zeitraum ist.

Ich kopiere nun meinen eigenen Code in eine extra Datei und deklariere davor alle benötigten Variablen. Leider kennt mans, dass die Variablen nicht immer das beinhalten was man denkt... ^^
Daher die Frage meinerseits, gibt es automatisierte Tests / Unittests, die unter anderem den Response vom Server simulieren, wenn Terminpaare zur Verfügung stehen?
Oder könnt ihr mir Tipps geben wie ihr Änderungen testet?

Zudem stimmt es das die JSON, welche der Server zurück gibt so ausschaut?
```
{
    "termine": [
        [
            {
                "slotId": "slot-56817da7-3f46-4f97-9868-30a6ddabcdef",
                "begin": 1616999901000,
                "bsnr": "005221080"
            },
            {
                "slotId": "slot-d29f5c22-384c-4928-922a-30a6ddabcdef",
                "begin": 1623999901000,
                "bsnr": "005221080"
            }
        ],
        [
            {
                "slotId": "slot-56817da7-3f46-4f97-9868-30a6ddabcdef",
                "begin": 1615999901000,
                "bsnr": "005221080"
            },
            {
                "slotId": "slot-d29f5c22-384c-4928-922a-30a6ddabcdef",
                "begin": 1723999901000,
                "bsnr": "005221080"
            }
        ]
    ]
}
```

Ach ja und das ist das erste mal das ich in GitHub bei einem anderem Projekt mitarbeite, von daher gebt mir gerne Rückmeldung wie man so eine Zusammenarbeit am effektivsten bewerkstelligt :)

**Comment by iamnotturner** [comment]
Hey Flo, zunächst mega cool, dass du das Feature adden willst. Und keine Sorge bzgl. der Mitarbeit - für mich ist das bspw. auch das erste öffentliche Projekt. Ich denke, wir können hier alle viel dran lernen, also go for it!

Ich bin gerade nur am Handy unterwegs, aber ich meine, dass die Antwort so aussieht. Zumindest gibt es eine Liste, in der die Terminpaare aufgezählt werden.

Unit-Tests haben wir nicht, wäre aber sicher auch mal gut. Am besten testest dus bei Impfzentren, die oft Termine haben (Hamburg Ü70). 

Meiner Meinung nach wäre dieses Feature optional cool, aber es sollte (vielleicht als default) ein zufälliger Termin gewählt werden. Wie ich das mitbekommen habe waren die meisten Leute froh, überhaupt einen bekommen zu haben. 

Wenn du so weit bist können wir hier gern einen separaten Branch einführen oder in die Beta packen.

Falls du Discord hast: @turner#0069

LG

**Comment by Floskinner** [comment]
Cool danke für den Hinweis mit Hamburg!

An sich hab ich schon mal in einem [Fork](https://github.com/Floskinner/vaccipy/tree/zeitbegrenzer) heute angefangen, da es mich einfach interessiert hat, wie man das umsetzten könnte 😄 

Daher hier mal ein Statusbericht :) 

Die einzugrenzende Tage / Uhrzeit wird wie die Kontaktdaten in einer .json gespeichert.
Dadurch kommt direkt nach der `Sollen die vorhandene Daten aus 'kontaktdaten.json' geladen werden (y/n)?:` eine zweite Abfrage `Soll die vorhandene Zeitspanne aus "zeitspann.json" geladen werden (y/n)?:`

Möchte man diese anpassen / startet man den Bot zum ersten mal kommt folgendes Fenster:
![vaccipy](https://user-images.githubusercontent.com/58706771/119198245-4a041700-ba89-11eb-9d40-a1a7d63d7b3c.png)

Dadurch das Standardmäßig alles im grünen Bereich ist, ist das Feature so zu sagen "optional"

Bisher hab ich es für Sinnvoll erfunden nur gewisse Wochentage und die Uhrzeit einzugrenzen. Spezifische Kalendertage könnte man später noch hinzufügen. 
Man kann noch auswählen ob die Begrenzung nur für den 1., 2. oder beide Termine gelten soll. Habe ich deswegen so implementiert, da der 1. Termin in meiner Gegend doch schon 1-3 Tage nach der Buchung ist und der zweite erst in 6 Wochen ansteht. Der 1. Termin könnte daher öfters ungelegener kommen als der 2., bei dem man noch Planen / Termine verschieben kann. Dann sagt man einfach, ok ich hab diese Woche immer Frühschicht oder an dem Tag ein Meeting, dann Starte ich den Bot solange einfach mit dem Parameter, dass der 1. Termin nicht auf die Tage oder Uhrzeit fallen sollen.

Aktuell hab ich noch folgende TODOS vor:

- [ ] Wenn das Fenster geschlossen wird soll was passieren...? -> Speichern oder Programm komplett beenden
- [ ] Fenstergröße sollte man nicht verändern können
- [ ] Fenster beim Start in den Vordergrund bringen
- [ ] Docstrings hinzufügen
- [ ] .icon adden ( evtl. das von meinem eigenen Bot ) -> [.ico](https://github.com/Floskinner/impftermin_finder/blob/main/data/spritze.ico)
- [ ] (Rückmeldung bei erfolgreichem Speicher)
- [ ] **Testen**

Realisiert wird das ganze mit [PyQt5](https://pypi.org/project/PyQt5/). 
Der [Fork / Code](https://github.com/Floskinner/vaccipy/tree/zeitbegrenzer)

Grüße
Flo

**Comment by JuliusJacobitz** [comment]
Hi @Floskinner , mir sind noch ein paar Dinge aufgefalle: 
1. Wir müssen sicherstellen, dass pyqt5 auch im pyinstaller build und auf den verschiedenen Plattformen noch läuft.

2. Wenn das gegeben ist, könnte man sich noch überlegen, ob es hilfreich ist, alles andere auch in die pyqt5 Gui zu schieben. 

Vielen Dank für deine Unterstützung! :)

**Comment by Floskinner** [comment]
Hey @JuliusJacobitz,

also ich konnte erfolgreich mit Ubuntu 18.04 und Windows 10 den pyinstaller build ausführen und auch das Programm entsprechend starten 👍 
Ich würde daher jetzt einfach mal davon ausgehen, dass es mit Mac auch funktionieren wird.

An sich könnte man den Rest auch in die GUI ziehen ( Eingabe der Kontaktdaten / Impf-Code )

Btw. Tests laufen aktuell noch...

--------------------------------------

Jedoch mal ne kurze Frage, wollt ihr mein [Icon](https://github.com/Floskinner/impftermin_finder/blob/main/data/spritze.ico) verwenden?
Aktuell hat die Anwendung ja keins und beim starten ist nur dieses Typische Standard Symbol
![vaccypi_icon](https://user-images.githubusercontent.com/58706771/119273135-c3c30e80-bc09-11eb-9ef7-2e953cd03658.png)

Für mein [alten Bot](https://github.com/Floskinner/impftermin_finder) hab ich damals dieses [Icon](https://github.com/Floskinner/impftermin_finder/blob/main/data/spritze.ico) erstellt. Wenn ihr daran Interesse hättet, dürft ihr das gerne verwenden :)
Bzw gebt mir bescheid und ich pass euer pyinstaller build an
![vaccypi_icon2](https://user-images.githubusercontent.com/58706771/119273324-ae9aaf80-bc0a-11eb-9ea0-8ea5dee344c8.png)

**Comment by JuliusJacobitz** [comment]
@iamnotturner @Floskinner ich find das Icon gut :)

**Comment by Floskinner** [comment]
Sooo, also an sich würde bei mir alles funktionieren. Seit dem letzten "großem" update auf dem Beta Branch mit den ganzen arg parser, hab ich leider etwas den Überblick verloren und hab mal so gut wies geht an den richtigen Stellen den Code verändert / hinzugefügt. 
Jedoch weiß ich selber, das des aktuell noch nicht so wirklich nice ist und würde da auch um die Hilfe vom @haslersn bitten :)

Jetzt weiß ich nur nicht so recht, wie man das am besten macht. Soll ich jetzt einfach mal ein PR erstellen oder erst dann, wenn alles richtig integriert ist?
Hier wäre mein entsprechender Branch -> [link](https://github.com/Floskinner/vaccipy/tree/zeitbegrenzung_beta)

Aussehen würde das ganze dann jetzt so:
![2021-05-25 18_34_19-vaccipy](https://user-images.githubusercontent.com/58706771/119535244-17f3fd00-bd88-11eb-8642-743ba12b8435.png)

**Comment by haslersn** [comment]
Hallo @Floskinner . Ich hab gesehen, dass du GUI-Code in die `main.py` gepackt hast. Das ist für mich persönlich aber unerwünscht: Die `main.py` ist der Einstiegspunkt für die Konsolenanwendung. Ich als Konsolennutzer möchte nicht, dass da plötzlich eine GUI aufploppt.

Du kannst natürlich gerne eine GUI für den Impfterminservice schreiben, aber das sollte dann ein separat ausführbare Python-Datei sein.

**Comment by haslersn** [comment]
PS: Falls Code aus der `main.py` auch in der GUI-Anwendung wiederverwendet werden soll, kann man den Code natürlich nach `tools/...` auslagern. Aber es sollte keine Aufrufe in die umgekehrte Richtung geben; das wäre sonst eine zyklische Abhänigkeit.

**Comment by Floskinner** [comment]
Hey @haslersn also an sich ist die GUI nur für den Part, wo man einstellen kann, ob man die Suche auf irgendwelche Tage / Uhrzeit einschränken möchte, da ich die Eingabe über Konsole als schwer / nicht schön empfunden hätte.

An sich ist kein "GUI code" in der `main.py` sondern nur der Code, wo die GUI für diese eine Eingabe startet und anschließend eine `zeitspanne.json` erstellt. Also so ähnlich wie `kontaktdaten.json`. Wenn bereits eine `zeitspanne.json` existiert, muss keine GUI aufgerufen werden (außer man möchte es entsprechend anpassen). Die wirkliche GUI befindet sich bereits unter `tools/qttimer.py`

Mein Gedanke war dann, das man ja dann auch theoretisch weitere Parameter mit übergeben kann, so wie für das Einstellen der `kontaktdaten.json` (eigene Namen, nur Konfigurieren, etc.)

Hier sonst mal ein kleiner Ablauf, wenn man den Bot zum 1. mal startet:
![start0](https://user-images.githubusercontent.com/58706771/119541081-74f2b180-bd8e-11eb-89a9-e02913325eb9.png)

Oder wenn schon eine Konfig vorliegt:
![start1](https://user-images.githubusercontent.com/58706771/119541184-9bb0e800-bd8e-11eb-91b7-58c80f9d65aa.png)

**Comment by haslersn** [comment]
Wieso ist das eigentlich in einer Extra-Datei? Man könnte es, denke ich, einfach als neues Feld in die `kontaktdaten.json` packen, oder?

Nachdem du für die Zeitspanne ein GUI hast, dürfte es ja recht einfach sein, alles per GUI einzugeben, oder? Dann könnte man 

- ein Programm machen, bei dem alles per Konsole eingegeben wird (ggf. ist dort Zeitspanne einfach nicht unterstützt, bis es jemand implementiert) und
- ein Programm machen, bei dem alles per GUI eingegeben wird.

**Comment by haslersn** [comment]
@chilischarf1 stimmt. Das ist eigentlich das allerwichtigste Feature. Wochentag und Uhrzeit ist eigentlich den meisten egal, meiner Erfahrung nach.

**Comment by Floskinner** [comment]
Hey @chilischarf1, das sollte sogar recht einfach gehen und ist ne gute Idee :D
Hoffe bekomme das noch rechtzeitig hin ^^

**Comment by Floskinner** [comment]
@haslersn 
Stimmt, keine Ahnung warum ich das nicht in Kontaktdaten gespeichert hab xD

Aber wie genau meinst du das mit 2 Programme?
Wüsste jetzt nicht, wie ich das hier machen soll. Macht man dann einfach ein neuen Branch wo das GUI Programm ist oder wie soll ich das ganze angehen. Ist hier mein erstes mal, dass ich an einem öffentlichem Projekt mitmache. Privat hat man solche Probleme nicht :D
> Wieso ist das eigentlich in einer Extra-Datei? Man könnte es, denke ich, einfach als neues Feld in die kontaktdaten.json packen, oder?
> 
> Nachdem du für die Zeitspanne ein GUI hast, dürfte es ja recht einfach sein, alles per GUI einzugeben, oder? Dann könnte man
> 
> ein Programm machen, bei dem alles per Konsole eingegeben wird (ggf. ist dort Zeitspanne einfach nicht unterstützt, bis es jemand implementiert) und
> ein Programm machen, bei dem alles per GUI eingegeben wird.

**Comment by haslersn** [comment]
Ne, kein extra Branch. Einfach eine neue Datei. Die Konsolenanwendung heißt ja bekanntlich aktuell `main.py`. Die GUI-Anwendung könnte man z. B. `gui.py` nennen.

**Comment by 4kills** [comment]
@Floskinner 
Ich finde super dass du dich engagierst, neue features und eine GUI hinzufügen willst! Das wird definitiv den Leuten helfen, die mit Konsolenanwendungen nicht vertraut sind! 

Jetzt zu dem Grund meines Comments: Du meintest ja du bist neu in der Open-Source-Community und hast ja nach Tipps gefragt, also hab ich ein paar für dich :P.  
Du solltest in Zukunft für jedes Thema einen separaten issue erstellen:  
`New Feature: Datum eingrenzen bei der Teminwahl - Unittests verfügbar?` sollte aufgeteilt werden in
| _ > `New Feature: Datum eingrenzen bei der Terminwahl`
| _ > `Testing: Unittests vorhanden / wie testen?`
| _ > `New Feature: GUI hinzufügen`

Die Unit-Test Frage hat sich ja schon erledigt, aber ich würde das GUI jetzt trotzdem noch in einen neuen Issue auslagern, weil das einfach zwei unterschiedliche Themen sind.

**Comment by 4kills** [comment]
> Jetzt weiß ich nur nicht so recht, wie man das am besten macht. Soll ich jetzt einfach mal ein PR erstellen oder erst dann, wenn alles richtig integriert ist?
> Hier wäre mein entsprechender Branch -> [link](https://github.com/Floskinner/vaccipy/tree/zeitbegrenzung_beta)

@Floskinner Hey das ist ne gute Idee! Erstell die PR und markiere sie als **DRAFT**, dann ist klar dass noch was geadded werden muss, aber es ist einfacher Kommentare und Feedback zu geben und auch an deinem Code mitzuarbeiten/anzuschauen. [Hier ist wie du eine PR als DRAFT erstellst](https://github.blog/2019-02-14-introducing-draft-pull-requests/). Im Prinzip einfach beim Erstellen statt "Create Pull Request" "Create Draft Pull Request" auswählen im letzten Schritt. Du kannst PRs auch noch nachträglich zu einem [draft umwandeln](https://github.blog/changelog/2020-04-08-convert-pull-request-to-draft/).

**Comment by Floskinner** [comment]
Hey @4kills. danke für die Tipps / best practice! :)

Den DRAFT PR hab ich direkt mal erstellt -> #152

----

> Wäre es auch möglich für die Terminbuchung einen Zeitraum "ab Datum" einzustellen? Ich spiele da auf den 07. Juni 2021
> an. Der Tag, ab dem die Impfpriosierung aufgehoben wird. :-)

@chilischarf1 die Idee mit dem "starten ab", hab ich in dem DRAFT implementiert. Nochmals danke für den Hinweis! :)
Das GUI Feature wurde ja bereits separat geöffnet in #143 und werde daran arbeiten.

----

Da noch eine kleine Frage, ob ich es nun verstanden habe wie DRAFT PRs funktionieren. 
Wäre es dann Sinnvoll meinen GUI Branch bereits auch als DRAFT PR an #143 anzuhängen, damit andere sehen an was ich arbeite 🤔 ?

... Würde dann im Anschluss auch mal diesen "Kuddelmuddel Issue" schließen, da es ja zu den einzelnen Themen ein getrenntes Issue gibt.
Danke an alle für das Feedback! ❤️

**Comment by 4kills** [comment]
![image](https://user-images.githubusercontent.com/30271713/119665109-534c0580-be34-11eb-91f1-9fcde6ce5650.png)
@Floskinner Dadurch dass du den Issue in der PR gementioned hast, ist auch die PR in dem Issue verlinkt, ich denke das sollte so reichen :) Vielen Dank noch mal für deine Contribution in dem Bereich !
