### ISSUE TITLE
"Einloggen mit Code nicht möglich"

### ISSUE THREAD

**Issue by heja99** [iamnotturner/vaccipy#75]
Hallo!

Erstmal danke für dieses geniale Tool, super Idee!
Ich habe eine  Frage zu folgender Meldung:
![image](https://user-images.githubusercontent.com/62422524/119203923-80935f00-ba94-11eb-94ce-fb97d0665dbc.png)
Wie man sieht kommt die Meldung "Einloggen mit Code nicht möglich", obwohl man erkennt wie das Skript den Code im Browser eingibt und keine Fehlermeldung auftaucht. Die Schleife wird scheinbar auch gestartet, aber ich bin nicht sicher ob das so passt, weil davor eben diese Meldung kommt.

Vielleicht kannst du mir ja weiter helfen :) Danke!

EDIT: Ich habe gesehen dass ich nicht der einzige mit dieser Frage bin. Sorry für den redundanten Post.

**Comment by JuliusJacobitz** [comment]
Hi @heja99, das einloggen mit dem Code ist optional. Wie du siehst wird weiterhin die Terminabfrage durchgeführt. Alles in Ordnung 👍

 @iamnotturner korrigiere mich bitte wenn ich falsch liege.

**Comment by heja99** [comment]
> Hi @heja99, das einloggen mit dem Code ist optional. Wie du siehst wird weiterhin die Terminabfrage durchgeführt. Alles in Ordnung 👍
> 
> @iamnotturner korrigiere mich bitte wenn ich falsch liege.

Perfekt, danke dir! :)
