### ISSUE TITLE
[err] [*TER1 | XXXXX]   Kein Impfzentrum zu eingetragenen PLZ's verfügbar.

### ISSUE THREAD

**Issue by gorfreed** [iamnotturner/vaccipy#79]
Ich habe das Tool sowohl in Windows als auch in Ubuntu 20 installiert und bei beiden wird mir bei der Generierung des Impf-Codes folgender Fehler ausgegeben:

![image](https://user-images.githubusercontent.com/6634117/119233079-8ab26d80-bb27-11eb-9fe4-62ffea040f6f.png)

Dabei spielt es keine Rolle, welche PLZ verwendet wird. Das Ergebnis ist immer das gleiche. Da dieser Bug von niemandem reported wurde, übersehe ich entweder etwas offensichtliches oder er ist neu.

**Comment by iamnotturner** [comment]
Hi, welche PLZ hast du denn eingetragen? Hier siehst du nochmal alle möglichen PLZ's:

https://github.com/iamnotturner/vaccipy/wiki/Ein-Code-fuer-mehrere-Impfzentren

**Comment by gorfreed** [comment]
Oh! Wusste nicht, dass das Script nur ein paar der Bundesländer abdeckt. Ich hatte die PLZ eines Berliner Impfzentrums eingegeben. Das könnte man allerdings durchaus in der Beschreibung erwähnen.
Gibt es Pläne für weitere Bundesländer?

**Comment by iamnotturner** [comment]
Also wir bieten ein Tool, das die Buchung beim [Impfterminservice](https://www.impfterminservice.de/impftermine) übernimmt. Leider sind nicht alle Bundesländer dabei, daran können wir leider nichts ändern.
