### ISSUE TITLE
"Virtueller Warteraum" support

### ISSUE THREAD

**Issue by ThiefMaster** [iamnotturner/vaccipy#8]
Right now you get a Chrome window popping up every few seconds in case the host used by a particular vaccination center - this is quite annoying when running the script on your main desktop.

Maybe it would be possible to keep the Chrome window open until the waiting period is over, and only then get the Cookies etc? I'm not sure how the waiting thing is implemented (probably on the akamai level), but it looks really crappy - a few weeks ago when booking the appointment for my dad I sometimes was thrown back into the waiting queue after a few minutes when simply reloading the page (and sometimes even the API requests in a normal browser got the waiting queue response again instead of the expected JSON)

**Comment by iamnotturner** [comment]
Hi Adrian, the Chrome window was popping up every few seconds because I set the waiting-for-element-delay in Selenium to 1 Second (🤦). I just pushed an update and set the first waiting to 1 hour - from now, it will stay 1 hour in the queue. Once the queue is passed, the script continues almost immediately. 

Update is pushed.

**Comment by ThiefMaster** [comment]
Oh perfekt, ich war gerade dabei mir sowas reinzuhacken und zu hoffen dass das klappt, aber der längere Wait ist deutlich schöner ;)

```python
            while 'Virtueller Warteraum des Impfterminservice' in driver.page_source:
                print('Waiting room :(')
                time.sleep(10)
```

**Comment by iamnotturner** [comment]
Gib gerne eine Rückmeldung, obs nun klappt :-)

**Comment by ThiefMaster** [comment]
Ich war grad AFK und hatte da nochmal diesen retry-loop im Log:

```
2021-05-02 21:04:10.562   impfterminservice   [inf] [*KLV7]   Browser-Cookie generiert: XXX
2021-05-02 21:04:12.990   impfterminservice   [err] [login]   JSONDecodeError exception raised - retry 1
2021-05-02 21:04:13.110   impfterminservice   [err] [login]   JSONDecodeError exception raised - retry 2
2021-05-02 21:04:13.232   impfterminservice   [err] [login]   JSONDecodeError exception raised - retry 3
2021-05-02 21:04:13.379   impfterminservice   [err] [login]   JSONDecodeError exception raised - retry 4
2021-05-02 21:04:13.554   impfterminservice   [err] [login]   JSONDecodeError exception raised - retry 5
2021-05-02 21:04:13.665   impfterminservice   [err] [*KLV7]   Keine qualifizierten Impfstoffe verfügbar!
2021-05-02 21:04:43.674   impfterminservice   [inf] [*KLV7]   Browser-Cookies generieren
```

Aber ich glaub das zeigt mal wieder was für ein unglaublicher Murks dieser Warteraum ist. Es sei denn, der Useragent o.ä. zählt da auch mit rein.

Hab mir jetzt mal testweise noch das hier bei der Terminsuche reingemacht:

```python
            if 'Virtueller Warteraum des Impfterminservice' in res.text:
                print('Waiting room... retrying in a bit')
                time.sleep(10)
                raise Exception('retry')  # yeah, i was too lazy to do it in a cleaner way :P
```

Aber natürlich war genau dann der Warteraum wieder weg... q.q

**Comment by ThiefMaster** [comment]
Oh, und kaum habe ich das geschreiben kam nach 2 Terminchecks wieder der Warteraum... und nachdem es ja nur max 10 retries gibt versuch ichs jetzt damit:

```python
        while True:
            res = self.s.get(self.domain + path, timeout=15)
            if not res.ok or 'Virtueller Warteraum des Impfterminservice' not in res.text:
                break
            print('Waiting room... retrying in a bit')
            time.sleep(10)
```

**Comment by iamnotturner** [comment]
Warteraum nun supported, daher closed.
