### ISSUE TITLE
Skip bogus appointments

### ISSUE THREAD

**Issue by ThiefMaster** [iamnotturner/vaccipy#9]
Yesterday and today I had a few cases where I got a pair of appointments suggested but they were already gone when trying to book them - both using this tool and manually on the site. This is clearly a bug on their side since they shouldn't be offering appointments to more than one people at the same time (or appointments that aren't actually available for some other reason).

My fix for that was this change in `termin_buchen`:

```python
        else:
            data = res.json()
            if 'nicht mehr verfügbar' in data.get('errors', {}).get('status', ''):
                self.log.error(f"Termin konnte nicht gebucht werden [BUG]: {data}")
                return False
            self.log.error(f"Termin konnte nicht gebucht werden: {data}")
            return False
```

combined with a loop around the appointment logic in `run()` to wait for the bad suggestion to expire and then keep trying

```python
        while True:
            termin_gefunden = False
            while not termin_gefunden:
                termin_gefunden, status_code = its.terminsuche()
                if status_code >= 400:
                    its.cookies_erneuern()
                elif not termin_gefunden:
                    time.sleep(random.randint(check_delay - 2, check_delay + 15))

            if its.termin_buchen():
                break
            time.sleep(300)
```

**Comment by iamnotturner** [comment]
Hey, das Problem hatte ich auch schon im Browser! Konnte ihn dann aber nicht mehr im Script nachkonstruierten - super, dass du dafür direkt ein Errorhandling gebaut hast. Willst du dazu einen Pull-Request aufmachen? Dann nehmen wir das gleich auf :-)
