### ISSUE TITLE
 Einloggen mit Code nicht möglich

### ISSUE THREAD

**Issue by devsbr** [iamnotturner/vaccipy#92]
Ich erhalte beim Start des Skripts folgende Fehlermeldung:
"Einloggen mit Code nicht möglich"

Danach läuft das Skript aber ganz normal (und sucht nach Terminen).

Muss ich mir Sorgen machen oder funktioniert das trotzdem?

<img width="606" alt="test" src="https://user-images.githubusercontent.com/40228042/119242756-f533cf80-bb60-11eb-9604-d05f05f83a26.PNG">

Fehler tritt wohl bei der Prüfung der qualifizierten Impfstoffe auf

**Comment by iamnotturner** [comment]
Hi, das sorgte nun schon mehrmals für Verwirrung. Kann ignoriert werden! Die Terminsuche und Buchung werden davon nicht beeinflusst.
