### ISSUE TITLE
NO Sachsen? 

### ISSUE THREAD

**Issue by PSYOLOT** [iamnotturner/vaccipy#96]
hi, wieso fehlen so viel?
speziell sachsen/ Leipzig/ Dresden
???
wäre voll wichtig!!??

**Comment by Sars-Cov-2-Antigen** [comment]
Hi Psyolot,

dieses Tool soll das sonst viel zu aufwändige, unnötig kompliziert strukturierte Terminevergabeverfahren des Portals impfterminservice.de vereinfachen. Nur einige Bundesländer nutzen diesen Service und Sachsen gehört nicht dazu.

Sachsen hat ein eigenes Portal (https://sachsen.impfterminvergabe.de/), das mir auf dem ersten Blick viel intelligenter scheint und keine Bot-Hilfe benötigt (ist wohl ähnlich wie Bayern und Schleswig-Holstein, die 2 Bundesländer, die es meiner Meinung nach am besten gelöst haben).

**Comment by JuliusJacobitz** [comment]
Absolut korrekt @Sars-Cov-2-Antigen.

**Comment by PSYOLOT** [comment]
danke für dein feedback, habe mir die anderen b-länder lösungen au gleich mal angesehen und schein bar fällt schon mal der schritt mit: ein code/anfrage weg°°! ha, leider funzt die Umsetzung nur sehr sehr dünne bei uns. aber ich sehe schon, dass ein tool die lage nur noch Prekärer machen würde. 
aber hey THX 4 u codeing
